### ISSUE TITLE
Elastic Agent seems to be stuck when using FLEET_TOKEN_POLICY_NAME

### ISSUE THREAD

**Issue by david-kow** [elastic/beats#27128] opened 2021-07-29 10:02 UTC
Elastic Agent doesn't start Beats when `FLEET_TOKEN_POLICY_NAME` env var is specified. Logs stop at:
```
Policy selected for enrollment:  abc
The Elastic Agent is currently in BETA and should not be used in production

2021-07-29T09:50:49.576Z        WARN    cmd/enroll_cmd.go:371   Remote server is not ready to accept connections, will retry in a moment.
2021-07-29T09:51:49.576Z        INFO    cmd/enroll_cmd.go:378   Retrying to enroll...
2021-07-29T09:51:50.381Z        INFO    cmd/enroll_cmd.go:201   Elastic Agent might not be running; unable to trigger restart
2021-07-29T09:51:50.381Z        INFO    cmd/enroll_cmd.go:203   Successfully triggered restart on running Elastic Agent.
Successfully enrolled the Elastic Agent.
2021-07-29T09:51:50.488Z        INFO    warn/warn.go:18 The Elastic Agent is currently in BETA and should not be used in production
2021-07-29T09:51:50.488Z        INFO    application/application.go:68   Detecting execution mode
2021-07-29T09:51:50.489Z        INFO    application/application.go:93   Agent is managed by Fleet
2021-07-29T09:51:50.489Z        INFO    capabilities/capabilities.go:59 capabilities file not found in /usr/share/elastic-agent/capabilities.yml
2021-07-29T09:51:51.256Z        INFO    [composable]    composable/controller.go:46     EXPERIMENTAL - Inputs with variables are currently experimental and should not be used in production
I0729 09:51:51.461652      13 leaderelection.go:243] attempting to acquire leader lease  default/elastic-agent-cluster-leader...
2021-07-29T09:51:51.463Z        INFO    [composable.providers.docker]   docker/docker.go:43     Docker provider skipped, unable to connect: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
2021-07-29T09:51:51.464Z        INFO    [composable.providers.kubernetes]       kubernetes/kubernetes.go:64     Kubernetes provider started with node scope
2021-07-29T09:51:51.464Z        INFO    [composable.providers.kubernetes]       kubernetes/util.go:114  kubernetes: Using pod name elastic-agent-agent-c9fc6 and namespace default to discover kubernetes node
2021-07-29T09:51:51.551Z        INFO    [composable.providers.kubernetes]       kubernetes/util.go:120  kubernetes: Using node gke-dkowalski-dev-cluste-default-pool-f1bc5417-wtjn discovered by in cluster pod node query
2021-07-29T09:51:51.653Z        INFO    [api]   api/server.go:62        Starting stats endpoint
2021-07-29T09:51:51.653Z        INFO    application/managed_mode.go:291 Agent is starting
2021-07-29T09:51:51.653Z        INFO    [api]   api/server.go:64        Metrics endpoint listening on: /usr/share/elastic-agent/state/data/tmp/elastic-agent.sock (configured: unix:///usr/share/elastic-agent/state/data/tmp/elastic-agent.sock)
2021-07-29T09:51:51.754Z        WARN    application/managed_mode.go:304 failed to ack update open /usr/share/elastic-agent/state/data/.update-marker: no such file or directory
```

As soon as any change is made in the UI (eg. changing unenrollment time or integration description) the Agent gets unstuck and continues to work:

```
2021-07-29T09:51:51.754Z        WARN    application/managed_mode.go:304 failed to ack update open /usr/share/elastic-agent/state/data/.update-marker: no such file or directory
2021-07-29T09:58:29.461Z        INFO    stateresolver/stateresolver.go:48       New State ID is nlinCt4-
2021-07-29T09:58:29.462Z        INFO    stateresolver/stateresolver.go:49       Converging state requires execution of 3 step(s)
2021-07-29T09:58:40.360Z        INFO    log/reporter.go:40      2021-07-29T09:58:40Z - message: Application: filebeat--7.14.0-SNAPSHOT[ee83ba66-7981-4257-9665-bb5bf244a653]: State changed to STARTING: Starting - type: 'STATE' - sub_type: 'STARTING'
2021-07-29T09:58:44.051Z        INFO    log/reporter.go:40      2021-07-29T09:58:44Z - message: Application: filebeat--7.14.0-SNAPSHOT[ee83ba66-7981-4257-9665-bb5bf244a653]: State changed to RUNNING: Running - type: 'STATE' - sub_type: 'RUNNING'
...
```

The policy is defined in kibana config as:
```yaml
    xpack.fleet.agentPolicies:
    - name: Elastic Agent on ECK policy
      id: abc 
      unenroll_timeout: 900
      package_policies:
      - package:
          name: system
        name: system-1
      - package:
          name: kubernetes
        name: kubernetes-1
```

It seems that this only happens for non-default policies. If I set `is_default` to `true` in the policy above and remove `FLEET_TOKEN_POLICY_NAME` Agent works correctly.

- Version: `7.14.0-SNAPSHOT`
- Operating System: centos

**Comment by jlind23** [comment] 2023-06-09 13:49
Closing this for now as it was related to 7.14 and not reproducible since then.

**Closed by jlind23** 2023-06-09 13:49 UTC
Labels: bug, Stalled, Team:Elastic-Agent, Team:Elastic-Agent-Control-Plane, 8.5-candidate
