### ISSUE TITLE
Provide an option to have WinlogBeat automatically reload config changes

### ISSUE THREAD

**Issue by aagupta1** [elastic/beats#9618] opened 2018-12-18 11:51 UTC
**Describe the enhancement:**
Provide an option to have WinlogBeat automatically reload config changes

**Describe a specific use case for the enhancement or feature:**
I want to avoid having to restart WinlogBeats everytime I make config changes.  Config changes should be picked up automatically if I provide the option to do so.

**Comment by urso** [comment] 2020-01-13 12:15
@jsoriano @andrewkroh This looks like a duplicate of #8281. Can we close this issue?

**Comment by jsoriano** [comment] 2020-01-13 12:20
@urso you are right, it looks like a duplicate, closing this, thanks!

**Closed by jsoriano** 2020-01-13 12:20 UTC
Labels: Winlogbeat, enhancement
