### ISSUE TITLE
Metricbeat - does not collect metrics on network drives in Windows

### ISSUE THREAD

**Issue by Yelliny** [elastic/beats#10664] opened 2019-02-11 10:18 UTC
Hi,
After working with Metricbeat for a while I have noticed that it does not collect metrics on network drives (NFS) in Windows (in Linux it does). 
It would be great if they were.

Thanks!

**Comment by narph** [comment] 2019-04-24 07:39
hi @Yelliny, what are the exact operating systems you are transferring files between using the NFS protocol?
Also, what is the metricbeat configuration you are testing with at the moment (modules/metricsets etc), it will help us narrow down any issues here.

**Comment by qwinkler** [comment] 2020-10-20 06:10
Hi there! Looks like it wasn't fixed. I also faced this problem.

- Version: 7.6.1
- Operating System: Windows
- Discuss Forum URL (also more details here): https://discuss.elastic.co/t/metricbeat-filesystem-metrics-does-not-include-remote-network-drives/252346
- Steps to Reproduce:
Attach any(I guess any, like NFS or something else, but I used S3 bucket with TntDrive(https://tntdrive.com/)) network device and run **metricbeat** > 6.3.0 with the following configuration file:
```yml
metricbeat.modules:
- module: system
  enabled: true
  period: 60s
  processes: ['.*']
  filesystem.ignore_types: []
  metricsets:
    - process
    - filesystem # is required
  processors:
    - drop_event.when.regexp.mount_point: '^/(sys|cgroup|proc|dev|etc|host)($|/)'
```

Metricbeat will only collect the data from local drives, not the remote ones.

**Comment by mkotha-clgx** [comment] 2020-10-21 13:56
This is my understanding. The GoLang program behind the FileSystem is not capturing the NFS/Network Shared drives. I added a Network share and ran the go program, it only lists the c: drive.

`package main

import (
	"fmt"
	"os"

	gosigar "github.com/elastic/gosigar"
)

const output_format = "%-15s %4s %4s %5s %4s %-15s\n"

func main() {
	fslist := gosigar.FileSystemList{}
	err := fslist.Get()
	if err != nil {
		fmt.Printf("Failed to get list of filesystems: %v", err)
		os.Exit(-1)
	}

	fmt.Fprintf(os.Stdout, output_format,
		"Filesystem", "Size", "Used", "Avail", "Use%", "Mounted on")

	for _, fs := range fslist.List {
		dir_name := fs.DirName

		usage := gosigar.FileSystemUsage{}

		usage.Get(dir_name)

		fmt.Fprintf(os.Stdout, output_format,
			fs.DevName,
			gosigar.FormatSize(usage.Total),
			gosigar.FormatSize(usage.Used),
			gosigar.FormatSize(usage.Avail),
			gosigar.FormatPercent(usage.UsePercent()),
			dir_name)
	}
}`

**Comment by SpartanB** [comment] 2021-06-09 11:29
Hi,

Is there any update on fixing this issue? Not able to see network drives on Windows with Metricbeat 7.13.1

**Closed** 2022-12-06 12:15 UTC
Labels: enhancement, module, :Windows, Metricbeat, Team:Integrations, Stalled
