### ISSUE TITLE
Collect pipeline stats from logstash

### ISSUE THREAD

**Issue by robin13** [elastic/beats#26519] opened 2021-06-28 10:12 UTC
**Describe the enhancement:**

Currently the metricbeat logstash module collects only the Event Stats under the `node_stats` metric. It would be useful for analysing logstash pipeline performance to also collect the pipeline stats:
https://www.elastic.co/guide/en/logstash/current/node-stats-api.html#pipeline-stats

**Comment by ChrsMark** [comment] 2021-07-26 08:21
cc: @sayden

**Comment by sayden** [comment] 2021-08-05 21:25
Hi @robin13 :slightly_smiling_face:  I'm coming a bit late here but the `node_stats` metricset queries `_node/stats` which includes the data from the `/pipelines` that is mention on the link. This should be under any doc fetched with Metricbeat under the path `logstash_stats.pipelines.[].*` where you can see events, reloads, etc.

So I'm assuming I'm understanding something wrong so you can tell me one single metric you are looking for from the response so I double check? It might also be the case that what you mean is that it's visible in the Stack Monitoring UI perhaps?

**Comment by businessbean** [comment] 2021-11-11 13:13
Currently we have to use the Logstash [http_poller](https://www.elastic.co/guide/en/logstash/current/plugins-inputs-http_poller.html) plugin to collect the node stats.
```bash
input {
  http_poller {
    id => "http_poller_${HOSTNAME}"
    urls => {
      logstash => {
        method => get
        url => "http://localhost:9600/_node/stats/pipelines?pretty"
        headers => {
          Accept => "application/json"
        }
     }
    }
    request_timeout => 60
    schedule => { cron => "* * * * * UTC"}
    codec => "json"
    metadata_target => "http_poller_metadata"
    tags => [ "metric", "http_poller" ]
  }
}
```
This is quite a hack and it doesn't follow the Elastic Common Schema. In general it would help if the Beats components out of the box would support all Elastic products. 

@richardgilm fyi...

**Comment by businessbean** [comment] 2021-11-11 16:01
The [fields](https://github.com/elastic/beats/blob/master/metricbeat/module/logstash/fields.go#L35) definition in the master branch contains that: 
```yaml
- key: logstash
  title: "Logstash"
  description: >
    Logstash module
  release: ga
  settings: ["ssl", "http"]
  short_config: false
  fields:
    - name: logstash_stats
      type: group
      fields:
        - name: timestamp
          type: alias
          path: "@timestamp"
        - name: jvm
          type: group
          fields:
            - name: mem
              type: group
              fields:
                - name: heap_used_in_bytes
                  type: alias
                  path: logstash.node.stats.jvm.mem.heap_used_in_bytes
                - name: heap_max_in_bytes
                  type: alias
                  path: logstash.node.stats.jvm.mem.heap_max_in_bytes
            - name: uptime_in_millis
              type: alias
              path: logstash.node.stats.jvm.uptime_in_millis
        - name: events
          type: group
          fields:
            - name: in
              type: alias
              path: logstash.node.stats.events.in
            - name: out
              type: alias
              path: logstash.node.stats.events.out
            - name: duration_in_millis
              type: alias
              path: logstash.node.stats.events.duration_in_millis
        - name: logstash
          type: group
          fields:
            - name: uuid
              type: alias
              path: logstash.node.stats.logstash.uuid
            - name: version
              type: alias
              path: logstash.node.stats.logstash.version
        - name: pipelines
          type: nested
        - name: os
          type: group
          fields:
            - name: cpu
              type: group
              fields:
                - name: stat
                  type: group
                  fields:
                    - name: number_of_elapsed_periods
                      type: alias
                      path: logstash.node.stats.os.cgroup.cpu.stat.number_of_elapsed_periods
                    - name: time_throttled_nanos
                      type: alias
                      path: logstash.node.stats.os.cgroup.cpu.stat.time_throttled_nanos
                    - name: number_of_times_throttled
                      type: alias
                      path: logstash.node.stats.os.cgroup.cpu.stat.number_of_times_throttled
                - name: load_average
                  type: group
                  fields:
                    - name: 15m
                      type: alias
                      path: logstash.node.stats.os.cpu.load_average.15m
                    - name: 1m
                      type: alias
                      path: logstash.node.stats.os.cpu.load_average.1m
                    - name: 5m
                      type: alias
                      path: logstash.node.stats.os.cpu.load_average.5m
            - name: cgroup
              type: group
              fields:
                - name: cpuacct.usage_nanos
                  type: alias
                  path: logstash.node.stats.os.cgroup.cpuacct.usage_nanos
        - name: process.cpu.percent
          type: alias
          path: logstash.node.stats.process.cpu.percent
        - name: queue.events_count
          type: alias
          path: logstash.node.stats.queue.events_count
    - name: logstash_state
      type: group
      fields:
        - name: pipeline.id
          type: alias
          path: logstash.node.state.pipeline.id
        - name: pipeline.hash
          type: alias
          path: logstash.node.state.pipeline.hash
    - name: logstash
      type: group
      fields:
        - name: node
          type: group
          description: >
            node
          release: ga
          fields:
        - name: node
          type: group
          description: >
            node_stats metrics.
          release: ga
          fields:
            - name: state.pipeline
              type: group
              fields:
                - name: id
                  type: keyword
                - name: hash
                  type: keyword
            - name: host
              type: alias
              path: host.hostname
              migration: true
              description: >
                Host name
            - name: version
              type: alias
              path: service.version
              migration: true
              description: >
                Logstash Version
            - name: jvm
              type: group
              description: >
                JVM Info
              fields:
                - name: version
                  type: keyword
                  description: >
                    Version
                - name: pid
                  type: alias
                  path: process.pid
                  migration: true
                  description: >
                    Process ID
            - name: stats
              type: group
              fields:
                - name: jvm
                  type: group
                  fields:
                    - name: uptime_in_millis
                      type: long
                    - name: mem
                      type: group
                      fields:
                        - name: heap_used_in_bytes
                          type: long
                        - name: heap_max_in_bytes
                          type: long
                - name: events
                  type: group
                  description: >
                    Events stats
                  fields:
                    - name: in
                      type: long
                      description: >
                        Incoming events counter.
                    - name: out
                      type: long
                      description: >
                        Outgoing events counter.
                    - name: filtered
                      type: long
                      description: >
                        Filtered events counter.
                    - name: duration_in_millis
                      type: long
                - name: logstash
                  type: group
                  fields:
                    - name: uuid
                      type: keyword
                    - name: version
                      type: keyword
                - name: os
                  type: group
                  fields:
                    - name: cpu
                      type: group
                      fields:
                        - name: load_average
                          type: group
                          fields:
                            - name: 15m
                              type: long
                            - name: 1m
                              type: long
                            - name: 5m
                              type: long
                    - name: cgroup
                      type: group
                      fields:
                        - name: cpuacct.usage_nanos
                          type: long
                        - name: cpu
                          type: group
                          fields:
                            - name: stat
                              type: group
                              fields:
                                - name: number_of_elapsed_periods
                                  type: long
                                - name: time_throttled_nanos
                                  type: long
                                - name: number_of_times_throttled
                                  type: long
                - name: process.cpu.percent
                  type: double
                - name: pipelines
                  type: nested
                  fields:
                    - name: id
                      type: keyword
                    - name: hash
                      type: keyword
                    - name: queue
                      type: group
                      fields:
                        - name: events_count
                          type: long
                        - name: type
                          type: keyword
                        - name: queue_size_in_bytes
                          type: long
                        - name: max_queue_size_in_bytes
                          type: long
                    - name: events
                      type: group
                      fields:
                        - name: out
                          type: long
                        - name: duration_in_millis
                          type: long
                    - name: vertices
                      type: group
                      fields:
                        - name: duration_in_millis
                          type: long
                        - name: events_in
                          type: long
                        - name: pipeline_ephemeral_id
                          type: keyword
                          description: pipeline_ephemeral_id
                        - name: events_out
                          type: long
                          description: events_out
                        - name: id
                          type: keyword
                          description: id
                        - name: queue_push_duration_in_millis
                          type: float
                          description: queue_push_duration_in_millis
                - name: queue.events_count
                  type: long
```

The `- name: pipelines` section looks promising, but with metricbeat 7.14.2 no pipeline metrics are available
<img width="2764" alt="image" src="https://user-images.githubusercontent.com/43000876/141328789-01d925e7-c198-4ed2-a55c-b3e161e6b8c5.png">

It seems that only a few steps are missing...

**Comment by dforste** [comment] 2022-01-03 16:34
I recently moved from in cluster monitoring to metricbeat based monitoring by the advice of elastic support. Now I can't view logstash pipeline statistics at all in kibana. It would be nice to have parity with native logstash monitoring.

**Comment by ravikesarwani** [comment] 2022-01-18 15:46
@robin13 Do you have some description of the problem as to what we are are trying to solve by this extra data? 
How can this extra data be displayed to solve a specific problem with logstatsh?

Hey @robbavey(please include anyone appropriate from the logstash team) and @elastic/stack-monitoring team, does someone have a little more background in terms of what exactly we collect via metricbeat w.r.t to the logstash module (xpack.enabled: true)? I know we collect and show pipeline details like this and looks like its based of off events data.
<img width="277" alt="Screen Shot 2022-01-18 at 10 30 48 AM" src="https://user-images.githubusercontent.com/64450378/149967439-61c8bbc3-e1f3-4bba-9a4c-80174ce76ce2.png">

The ER is asking to also collect pipeline stats **that seems like contains events data as well** but also other things like filter stats & reload success/failure etc. 


cc: @alexander-marquardt

**Comment by robbavey** [comment] 2022-01-19 15:13
@ravikesarwani @robin13 We should be collecting all the event/pipeline data - and the values sent by metricbeat should be the same as those sent by internal collection/logstash shipping. There is a long standing [issue](https://github.com/elastic/kibana/issues/28153) in stack monitoring where pipeline stats are not shown until ~30 minutes after collection begins, which may be a source of confusion here.

Running some tests with a rudimentary pipeline, using metricbeat monitoring, after a wait, we can see the pipeline definition showing stats:

<img width="449" alt="Screen Shot 2022-01-19 at 9 48 14 AM" src="https://user-images.githubusercontent.com/4061337/150158205-b1d485c4-64c6-40da-bda5-fff89dad627d.png">

With the drill down showing latency and emitted rate for specific plugins:

<img width="420" alt="Screen Shot 2022-01-19 at 9 56 32 AM" src="https://user-images.githubusercontent.com/4061337/150158174-90cddcdd-9451-4240-8cd5-fecdda55aee1.png">

This may be a _presentation_ issue with stack monitoring in Kibana, rather than collection in beats - I believe all the necessary information is already collected by the beat, including reloads, pipeline queue sizes, events in/out on pipelines and individual plugins are already collected.

**Comment by ravikesarwani** [comment] 2022-01-19 19:09
Thanks @robbavey.

Looks like this enhancement as its written should be closed as the data is being collected.

In terms of the UI improvement I reviewed the [issue](https://github.com/elastic/kibana/issues/28153) but not sure if the issue was confirmed or any root cause for that issue was identified. As such I am not sure if this issue can be somehow linked to that one. Feels like a new bug needs to be opened up, if appropriate, so that the potential UI issue can be researched. It's somehow hard to believe that the data is there in Elasticsearch from the get go but the UI is just having delays (of 30 minutes) in displaying it.

**Comment by robbavey** [comment] 2022-01-19 22:06
@robin13 Does [this](https://github.com/elastic/beats/issues/26519#issuecomment-1016565540) answer your question, or is there a specific need that you wish to have addressed, or shown in logstash stack monitoring, that is currently not being shown?

@ravikesarwani It's a strange one for sure - I think @chrisronline *may* have seen this issue and have more context as to why this is happening, but I could be off base

**Comment by chrisronline** [comment] 2022-01-31 17:31
@robbavey I'm honestly not sure. If the data is indeed there and the UI isn't showing it, this sounds like a bug. I can't recall this happening while I worked on stack monitoring so it might be a new bug

**Comment by alah64** [comment] 2022-02-27 10:01
This is a problem on the nerves :), in the past, which was shown as a pipeline tree, this problem did not exist.

**Closed** 2023-08-26 11:04 UTC
Labels: Team:Integrations, Stalled
