### ISSUE TITLE
Broken ML tests in Filebeat (Dashboard loading?)

### ISSUE THREAD

**Issue by urso** [elastic/beats#9938] opened 2019-01-07 23:27 UTC
## Flaky Test

* **Test Name:** test_ml.Test.test_ml_setup_0, test_ml.Test.test_ml_setup_1
* **Link:** 
* **Branch:** master
* **Artifact Link:** [test_ml.Test.test_ml_setup_0.zip](https://github.com/elastic/beats/files/2734642/test_ml.Test.test_ml_setup_0.zip), [test_ml.Test.test_ml_setup_1.zip](https://github.com/elastic/beats/files/2734643/test_ml.Test.test_ml_setup_1.zip)
* **Notes:** Tests fail when checking for the avilabilty of a job via `/_xpack/ml/anomaly_detectors/` API. Maybe related to `_xpack` removal?

### Stack Trace

```
======================================================================
ERROR: Test ML are installed in all possible ways [with setup_flag=True, modules_flag=False]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/go/src/github.com/elastic/beats/filebeat/build/python-env/local/lib/python2.7/site-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/go/src/github.com/elastic/beats/filebeat/tests/system/test_ml.py", line 46, in test_ml_setup
    self._run_ml_test(setup_flag, modules_flag)
  File "/go/src/github.com/elastic/beats/filebeat/tests/system/test_ml.py", line 120, in _run_ml_test
    max_timeout=60)
  File "/go/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 346, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'cond' to be true. Waited 60 seconds.
-------------------- >> begin captured stdout << ---------------------
Using elasticsearch: http://elasticsearch:9200
Test setup_flag: True, modules_flag: False

--------------------- >> end captured stdout << ----------------------

======================================================================
ERROR: Test ML are installed in all possible ways [with setup_flag=True, modules_flag=True]
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/go/src/github.com/elastic/beats/filebeat/build/python-env/local/lib/python2.7/site-packages/parameterized/parameterized.py", line 392, in standalone_func
    return func(*(a + p.args), **p.kwargs)
  File "/go/src/github.com/elastic/beats/filebeat/tests/system/test_ml.py", line 46, in test_ml_setup
    self._run_ml_test(setup_flag, modules_flag)
  File "/go/src/github.com/elastic/beats/filebeat/tests/system/test_ml.py", line 120, in _run_ml_test
    max_timeout=60)
  File "/go/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 346, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'cond' to be true. Waited 60 seconds.
-------------------- >> begin captured stdout << ---------------------
Using elasticsearch: http://elasticsearch:9200
License already enabled
Test setup_flag: True, modules_flag: True

--------------------- >> end captured stdout << ----------------------
```

setup0 error message:
```
2019-01-07T21:17:14.748Z	ERROR	instance/beat.go:907	Exiting: Error importing Kibana dashboards: fail to import the dashboards in Kibana: Error importing directory /go/src/github.com/elastic/beats/filebeat/_meta/kibana.generated: No directory /go/src/github.com/elastic/beats/filebeat/_meta/kibana.generated/6
Exiting: Error importing Kibana dashboards: fail to import the dashboards in Kibana: Error importing directory /go/src/github.com/elastic/beats/filebeat/_meta/kibana.generated: No directory /go/src/github.com/elastic/beats/filebeat/_meta/kibana.generated/6
```

setup1 error message:
```
2019-01-07T21:18:14.845Z	ERROR	instance/beat.go:907	Exiting: Error importing Kibana dashboards: fail to import the dashboards in Kibana: Error importing directory /go/src/github.com/elastic/beats/filebeat/_meta/kibana.generated: No directory /go/src/github.com/elastic/beats/filebeat/_meta/kibana.generated/6
Exiting: Error importing Kibana dashboards: fail to import the dashboards in Kibana: Error importing directory /go/src/github.com/elastic/beats/filebeat/_meta/kibana.generated: No directory /go/src/github.com/elastic/beats/filebeat/_meta/kibana.generated/6
/go/src/github.com/elastic/beats/filebeat/filebeat.test -systemTest -e -d * -c /go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_ml.Test.test_ml_setup_1/filebeat.yml -E setup.dashboards.enabled=false --setup --modules=nginx
```

**Comment by ruflin** [comment] 2019-01-08 08:46
The failure is caused by this PR here: https://github.com/elastic/beats/pull/9892

The error message is:

```
2019-01-07T15:30:04.349Z	ERROR	instance/beat.go:907	Exiting: Error importing Kibana dashboards: fail to import the dashboards in Kibana: Error importing directory /go/src/github.com/elastic/beats/filebeat/_meta/kibana.generated: No directory /go/src/github.com/elastic/beats/filebeat/_meta/kibana.generated/6
```

**Comment by ycombinator** [comment] 2019-04-03 13:38
This failure seems to have come back: e.g. https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-linux/6702/beat=filebeat,label=linux-immutable/consoleFull and https://travis-ci.org/elastic/beats/jobs/515167199.

**Comment by ycombinator** [comment] 2019-04-03 13:48
This might be specific to my PR: https://github.com/elastic/beats/pull/9260. So closing the issue again for now. Sorry for the noise.

**Comment by urso** [comment] 2019-04-03 13:48
error message reported by filebeat:

```
2019-04-03T13:18:24.834Z	ERROR	instance/beat.go:856	Exiting: 2 errors: Error setting up ML for apache_ecs: cannot set up ML with prefix: filebeat-apache_ecs-access-; Error setting up ML for nginx_ecs: cannot set up ML with prefix: filebeat-nginx_ecs-access-
Exiting: 2 errors: Error setting up ML for apache_ecs: cannot set up ML with prefix: filebeat-apache_ecs-access-; Error setting up ML for nginx_ecs: cannot set up ML with prefix: filebeat-nginx_ecs-access-
```

**Closed by ycombinator** 2019-04-03 13:48 UTC
Labels: Filebeat, blocker, bug, flaky-test, v7.0.0-beta1
