### ISSUE TITLE
Packetbeat setup error 

### ISSUE THREAD

**Issue by liza-mae** [elastic/beats#15512] opened 2020-01-13 20:05 UTC
- Version: master latest
- Operating System: Linux
- Steps to Reproduce: 
./packetbeat setup
Overwriting ILM policy is disabled. Set `setup.ilm.overwrite:true` for enabling.

Index setup finished.
Loading dashboards (Kibana must be running and reachable)
Exiting: error generating index pattern: field <tls.version> is duplicated, remove it or set 'overwrite: true', {Name:version Type:keyword Description:The version of the TLS protocol used.
 Format: Fields:[] MultiFields:[] Enabled:<nil> Analyzer: SearchAnalyzer: Norms:false Dynamic:{Value:<nil>} Index:<nil> DocValues:<nil> CopyTo: IgnoreAbove:0 AliasPath: MigrationAlias:false Dimension:<nil> ObjectType: ObjectTypeMappingType: ScalingFactor:0 ObjectTypeParams:[] Analyzed:<nil> Count:0 Searchable:<nil> Aggregatable:<nil> Script: Pattern: InputFormat: OutputFormat: OutputPrecision:<nil> LabelTemplate: UrlTemplate:[] OpenLinkInCurrentTab:<nil> Overwrite:false DefaultField:<nil> Path:tls.version}, {"aggregatable":true,"analyzed":false,"count":0,"doc_values":true,"indexed":true,"name":"tls.version","scripted":false,"searchable":true,"type":"string"}

I am getting the above error running packetbeat setup, not sure what it means, can someone help?
It was not doing this before, so not sure if it is a bug or change in behavior.

**Comment by liza-mae** [comment] 2020-01-14 00:11
This is happening on oss and default packages -

[packetbeat.yml.txt](https://github.com/elastic/beats/files/4056675/packetbeat.yml.txt)

**./packetbeat version**
packetbeat version 8.0.0 (amd64), libbeat 8.0.0 [6c75f403281068623185fb330a166a09cc9df977 built 2020-01-13 14:27:12 +0000 UTC]

**Snapshot version:** 
8.0.0-ae74a27c

**Kibana version:** 
BUILD 29871 COMMIT 14df4c09

**Elasticsearch version:** 
number: "8.0.0-SNAPSHOT",
build_flavor: "oss",
build_type: "tar",
build_hash: "a0513217dba5d964bf176c8f409baccfbd25359b",
build_date: "2020-01-13T15:44:08.340307Z",

cc: @ycombinator

**Comment by ycombinator** [comment] 2020-01-14 21:05
I can confirm that this is indeed a bug. I'm able to reproduce it on `master` with the following minimal steps:

1. Build `packetbeat`.

   ```
   cd $GOPATH/src/github.com/elastic/beats/packetbeat
   mage clean update build
   ```

2. Try to export the index pattern.
   ```
   ./packetbeat export index-pattern
   ```

**Comment by ycombinator** [comment] 2020-01-14 21:09
Looking at the Packetbeat commit history for the past few days, I wonder if this bug was introduced by either https://github.com/elastic/beats/pull/14844 or https://github.com/elastic/beats/pull/15497. @adriansr WDYT?

**Comment by ycombinator** [comment] 2020-01-14 21:13
Yes, doing a git bisect, it looks like the bug was introduced in https://github.com/elastic/beats/pull/14844.

**Comment by adriansr** [comment] 2020-01-14 21:52
It looks like this was broken during the period of time between #14844 and #15497 was merged, which makes sense, because the first adds a new `tls.version` and the second removes the old field from packetbeat.

It shouldn't happen anymore since #15497 was merged, and indeed it doesn't fail for me. @ycombinator can you confirm with an updated master branch?

I will add a system-tests that invokes `beat export index-pattern` to make sure this doesn't happen again.

**Comment by ycombinator** [comment] 2020-01-14 23:48
Yes, pulled down `master` again and built Packetbeat. I can **no longer** cause this bug. Thanks @adriansr!

**Closed by ycombinator** 2020-01-14 23:48 UTC
Labels: Packetbeat, Team:Beats, [zube]: Ready, bug

**Comment by liza-mae** [comment] 2020-01-15 01:31
Thanks @ycombinator @adriansr -- so next master snapshot should pass for me too.  Also please note this fix needs to be backported to 7.x.
