### ISSUE TITLE
Process name is limitated to 15 chars in Linux

### ISSUE THREAD

**Issue by abraxxa** [elastic/beats#428] opened 2015-12-02 16:47 UTC
See https://discuss.elastic.co/t/proc-name-limited-to-15-chars/36034.

Thanks!

**Comment by UserNotFound** [comment] 2016-02-08 23:26
/proc/[pid]/cmdline also contains the information I was wanting to see logged with topbeat.  Everything I am interested in logging is "qemu-kvm" or "python" and of very little value without the full command.


```
[root@ftp00 ~]# cat /proc/15469/stat
15469 (python) S 15466 15469 15469 0 -1 4202752 29048 1939 96 0 1418 161 1 1 20 0 1 0 871492921 678961152 9479 18446744073709551615 4194304 4196532 140733742263776 140733742257984 139951301103955 0 0 20451328 16386 18446744071580752109 0 0 17 0 0 0 294 0 0
```
```
[root@ftp00 ~]# cat /proc/15469/cmdline 
../virtualenv/bin/pythonmanage.pysftpd--bind=16--uid=555--gid=555--key=/etc/ssh/site.com.key--realm=testrealm2--proxy
```

**Comment by andrewkroh** [comment] 2016-02-08 23:29
@UserNotFound  See https://github.com/elastic/beats/issues/533

**Comment by UserNotFound** [comment] 2016-02-08 23:41
Ah, I was able to track down that this was committed and merged before 1.1.0 was released, but was not included in the release. Thanks @andrewkroh !

**Comment by ruflin** [comment] 2016-09-16 14:31
Closing this issue as problem was solved.

**Comment by monicasarbu** [comment] 2017-04-04 09:57
I am still able to reproduce the issue in Metricbeat 5.3. The `system.process.name` is limited to 15 characters, so I am reopening the issue.

**Comment by abraxxa** [comment] 2017-04-04 10:07
Thanks Monica!

**Comment by sundarv85** [comment] 2018-08-17 19:52
+1 - as noted, it seems to be a problem only in linux. In OSX it works correctly.

**Comment by jsoriano** [comment] 2018-10-26 16:13
As mentioned in the original discuss thread, this is caused by a limitation in the operating systems, the `comm` value, used for process names in Linux, is limited to 16 bytes including the termination null, so I think there is little we can do against that. Other POSIX systems as OSX have probably similar limitations too.

As a workaround, users may use other fields to identify processes, as ` system.process.cmdline` or `system.process.cgroup.id`. This can work well for specific use cases as the mentioned before in this issue, but I don't think they can be used to obtain a name in a generic way.

I'm closing this, but I am happy to reopen it if someone has another proposal to collect process names.

**Closed by jsoriano** 2018-10-26 16:13 UTC
Labels: Metricbeat, enhancement, help wanted, module
