### ISSUE TITLE
Beats - reduce deprecation warning logs from Elasticsearch

### ISSUE THREAD

**Issue by jlind23** [elastic/beats#29348] opened 2021-12-08 15:26 UTC

**Comment by cmacknz** [comment] 2021-12-15 22:16
I've been modifying the beat system tests to capture the elasticsearch logs. I've been working with filebeat so far to minimize the amount of tests I need to run locally. I've found a single warning from the filebeat system tests so far:

```json
{
  "@timestamp": "2021-12-15T21:56:11.458Z",
  "log.level": "WARN",
  "data_stream.dataset": "deprecation.elasticsearch",
  "data_stream.namespace": "default",
  "data_stream.type": "logs",
  "elasticsearch.event.category": "api",
  "elasticsearch.http.request.x_opaque_id": "unknownId",
  "event.code": "get_license_accept_enterprise",
  "message": "Including [accept_enterprise] in get license requests is deprecated. The parameter will be removed in the next major version",
  "ecs.version": "1.2.0",
  "service.name": "ES_ECS",
  "event.dataset": "deprecation.elasticsearch",
  "process.thread.name": "elasticsearch[93b7f10eb91b][transport_worker][T#4]",
  "log.logger": "org.elasticsearch.deprecation.xpack.core.rest.action.RestXPackInfoAction",
  "trace.id": "559f9fa5cf5090e3fd4f05e4c340abf3",
  "elasticsearch.cluster.uuid": "6mWjbnURSEebFB8AsXddnA",
  "elasticsearch.node.id": "XOOFKCI1QgiYe2yqNUg-sA",
  "elasticsearch.node.name": "93b7f10eb91b",
  "elasticsearch.cluster.name": "docker-cluster"
}
```

We won't know the full set of deprecation warnings that exist until we run the entire test suite.

**Comment by cmacknz** [comment] 2021-12-23 18:32
There is consistently a single deprecation warning in the libbeat integration tests when they run on Jenkins, but I am unable to reproduce it locally. 

Any deprecation warnings found when running beats as part of the stack are not caused by beats, agent, or fleet. Marking as closed.

**Closed by cmacknz** 2021-12-23 18:32 UTC
Labels: v8.0.0, Team:Elastic-Agent-Control-Plane
