### ISSUE TITLE
[metricbeat] beats xpack module creates a single datastream per service monitored

### ISSUE THREAD

**Issue by stuartnelson3** [elastic/beats#29657] opened 2021-12-31 09:21 UTC
When configured with a beat module and `xpack.enabled: true` (https://github.com/elastic/beats/blob/master/metricbeat/modules.d/beat-xpack.yml.disabled), recent builds of metricbeat from the 8.0 branch create daily datastreams, eg. `.monitoring-beats-8-mb-2021.12.29` and then `.monitoring-beats-8-mb-2021.12.30`.

Can metricbeat be updated to only write to a single datastream per thing monitored, ie., the naming would change to `.monitoring-beats-8-mb`?

**Comment by jlind23** [comment] 2022-01-04 13:44
ping @nimarezainia @cmacknz for awareness and feedback

**Comment by kvch** [comment] 2022-01-04 18:22
I have investigated the issue. Metricbeat correctly selects the data stream name it is supposed to send to. However, it does not seem to match any index template patterns set up by the Beat.

The fix is probably changing the index patterns of the template, so Elasticsearch can create the appropriate data stream for the monitoring data. I will submit a PR tomorrow.

**Comment by matschaffer** [comment] 2022-01-05 03:30
@klacabane has been working on the templates for these, see https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/resources/monitoring-es-mb.json for an example.

**Comment by kvch** [comment] 2022-01-05 13:01
The issue is handed over to @sayden

**Comment by sayden** [comment] 2022-01-05 13:13
Thanks for the heads up @kvch

**Comment by matschaffer** [comment] 2022-01-06 02:28
I met with @ravikesarwani @jasonrhodes and @klacabane yesterday and we discussed that another option here might be falling back to simple dated indices for the monitoring-mb data.

I've opened https://github.com/elastic/elasticsearch/pull/82301 incase we want to go that route.

**Comment by sayden** [comment] 2022-01-06 10:22
Hi @stuartnelson3 please can you try with master and see if you get the expected result? I think this was merged late in the pipeline and you can't found it in `8.0`

I think it should work as expected there.

**Comment by sayden** [comment] 2022-01-06 10:34
This is why I think it should work, btw https://github.com/elastic/elasticsearch/pull/81838

**Comment by klacabane** [comment] 2022-01-06 12:05
debugging (on latest `master`) shows [this function](https://github.com/elastic/beats/blob/master/libbeat/idxmgmt/std.go#L318-L319) is responsible for appending the date to the index name. We're not hitting that path when writing to metricbeat indice (`xpack.enabled: false`)

**Comment by stuartnelson3** [comment] 2022-01-10 10:04
Sounds like once that logic is removed, that should fix the issue?

**Comment by kvch** [comment] 2022-01-10 11:50
@klacabane Unfortunately, I do not think that will solve the issue. We should remove it regardless, I have several things that need clean up in index management in Beats.

When you test with the Beat, you can see that the index is set correctly in the event to `.monitoring-beats-8-mb`. However, when the event lands in Elasticsearch, it gets inserted into a different index. That's why I think the problem is with the template in Elasticsearch. On master the template seems OK: https://github.com/elastic/elasticsearch/blob/master/x-pack/plugin/core/src/main/resources/monitoring-es-mb.json#L3298
Is is backported to 8.0?

**Comment by kvch** [comment] 2022-01-10 12:33
I opened a PR, this will probably fix the problem: https://github.com/elastic/beats/pull/29775

**Closed** 2022-01-11 08:13 UTC
Labels: bug, enhancement, Metricbeat, question, Stack monitoring, v8.0.0, needs_team
