### ISSUE TITLE
Kubernetes POD metrics should expose kube_pod_status_reason 

### ISSUE THREAD

**Issue by StephanErb** [elastic/beats#38946] opened 2024-04-15 14:13 UTC
**Describe the enhancement:**

Please expose the metric [`kube_pod_status_reason`](https://github.com/kubernetes/kube-state-metrics/blob/main/docs/metrics/workload/pod-metrics.md) from kube-state-metrics as part of the `state_pod` metricset. It encodes pod termination reasons like `Evicted`, `NodeAffinity`, `NodeLost`, `Shutdown`, or `UnexpectedAdmissionError`.

I know that the metric is marked as experimental but it has been available for several years and should be safe to use.

**Describe a specific use case for the enhancement or feature:**

Users want to troubleshoot why their POD was terminated without having to look at low-level Kubernetes Events.

**Comment by tetianakravchenko** [comment] 2024-06-06 13:51
duplicate of https://github.com/elastic/integrations/issues/9752, `kubernetes.pod.status_reason` was added

**Closed by tetianakravchenko** 2024-06-06 13:51 UTC
Labels: needs_team
