### ISSUE TITLE
Discard packets issued by load balancer

### ISSUE THREAD

**Issue by bqk-** [elastic/beats#499] opened 2015-12-10 14:00 UTC
Hello,

I am using PacketBeats to monitor the traffic on our application, I use the "RealIp" feature since it is situated behind a load balancer.
However, the load balancer issues a request every second pretty much to ping the servers.

Could an option like "Ignore packets without real ip" or "blacklist ips" be useful ?

**Comment by ruflin** [comment] 2015-12-10 16:41
We are working on a filtering concept which can be found here: https://github.com/elastic/beats/issues/462 This could help with this.

**Comment by bqk-** [comment] 2015-12-11 08:01
Great news, thanks!

**Comment by tsg** [comment] 2015-12-16 10:46
Closing as duplicate of #462.

**Closed by tsg** 2015-12-16 10:46 UTC
Labels: duplicate
