### ISSUE TITLE
Packetbeat segmentation fault on Linux x86_64

### ISSUE THREAD

**Issue by LeeDr** [elastic/beats#4174] opened 2017-05-02 19:10 UTC
For confirmed bugs, please report:
- Version: master
- Operating System: Ubuntu 14.04
- Steps to Reproduce: .deb package installed and started as a service

My packetbeat.yml (same as I currently use on 5.4 and 5.x branches);
```
root@packer-virtualbox-iso-1492351135:~# grep -v "^\s*#"  /etc/packetbeat/packetbeat.yml | grep .
packetbeat.interfaces.device: any
packetbeat.flows:
  timeout: 30s
  period: 10s
packetbeat.protocols:
- type: icmp
- type: amqp
  ports: [5672]
- type: cassandra
  ports: [9042]
- type: dns
  ports: [53]
  include_authorities: true
  include_additionals: true
- type: http
  ports: [80, 8080, 8000, 5000, 8002]
- type: memcache
  ports: [11211]
- type: mysql
  ports: [3306]
- type: pgsql
  ports: [5432]
- type: redis
  ports: [6379]
- type: thrift
  ports: [9090]
- type: mongodb
  ports: [27017]
- type: nfs
  ports: [2049]
output.elasticsearch:
  hosts: ["localhost:9200"]
  protocol: https
  username: "beats_internal"
  password: "changeme"
  ssl.enabled: true
  ssl.certificate_authorities: [/etc/elasticsearch/sslconfig/ca.crt]
  ssl.certificate: /etc/elasticsearch/sslconfig/elasticsearch.crt
  ssl.key: /etc/elasticsearch/sslconfig/elasticsearch.key
  ssl.enabled: true
  ssl.certificate_authorities: [/etc/elasticsearch/sslconfig/ca.crt]
  ssl.certificate: /etc/elasticsearch/sslconfig/elasticsearch.crt
  ssl.key: /etc/elasticsearch/sslconfig/elasticsearch.key
  username: "beats_internal"
  password: "changeme"
  ssl.enabled: true
  ssl.certificate_authorities: [/etc/elasticsearch/sslconfig/ca.crt]
  ssl.certificate: /etc/elasticsearch/sslconfig/elasticsearch.crt
  ssl.key: /etc/elasticsearch/sslconfig/elasticsearch.key
  password: "changeme"
  ssl.enabled: true
  ssl.certificate_authorities: [/etc/elasticsearch/sslconfig/ca.crt]
  ssl.certificate: /etc/elasticsearch/sslconfig/elasticsearch.crt
  ssl.key: /etc/elasticsearch/sslconfig/elasticsearch.key
logging.to_files: true
logging.files:
```

The output;
```
/usr/share/packetbeat/bin/packetbeat: Symbol `stderr' causes overflow in R_X86_64_PC32 relocation
/usr/share/packetbeat/bin/packetbeat: Symbol `stderr' causes overflow in R_X86_64_PC32 relocation
/usr/share/packetbeat/bin/packetbeat: Symbol `stderr' causes overflow in R_X86_64_PC32 relocation
/usr/share/packetbeat/bin/packetbeat: Symbol `stderr' causes overflow in R_X86_64_PC32 relocation
/usr/share/packetbeat/bin/packetbeat: Symbol `stderr' causes overflow in R_X86_64_PC32 relocation
/usr/share/packetbeat/bin/packetbeat: Symbol `stderr' causes overflow in R_X86_64_PC32 relocation
/usr/share/packetbeat/bin/packetbeat: Symbol `stderr' causes overflow in R_X86_64_PC32 relocation
/usr/share/packetbeat/bin/packetbeat: Symbol `stdin' causes overflow in R_X86_64_PC32 relocation
/usr/share/packetbeat/bin/packetbeat: Symbol `stdin' causes overflow in R_X86_64_PC32 relocation
/usr/share/packetbeat/bin/packetbeat: Symbol `stdin' causes overflow in R_X86_64_PC32 relocation
/usr/share/packetbeat/bin/packetbeat: Symbol `stdin' causes overflow in R_X86_64_PC32 relocation
/usr/share/packetbeat/bin/packetbeat: Symbol `stdout' causes overflow in R_X86_64_PC32 relocation
/usr/share/packetbeat/bin/packetbeat: Symbol `stdout' causes overflow in R_X86_64_PC32 relocation
/usr/share/packetbeat/bin/packetbeat: Symbol `stdout' causes overflow in R_X86_64_PC32 relocation
2017/05/02 18:56:39.382249 beat.go:327: INFO Home path: [/usr/share/packetbeat] Config path: [/etc/packetbeat] Data path: [/var/lib/packetbeat] Logs path: [/var/log/packetbeat]
2017/05/02 18:56:39.382285 beat.go:352: INFO Beat metadata path: /var/lib/packetbeat/meta.json
2017/05/02 18:56:39.382374 beat.go:334: INFO Beat UUID: c385fafa-6947-47cd-bdb3-c7c9dba2cdd0
2017/05/02 18:56:39.382383 beat.go:212: INFO Setup Beat: packetbeat; Version: 6.0.0-alpha1
2017/05/02 18:56:39.382512 metrics.go:23: INFO Metrics logging every 30s
2017/05/02 18:56:39.383095 client.go:131: INFO Elasticsearch url: https://localhost:9200
2017/05/02 18:56:39.383128 outputs.go:107: INFO Activated elasticsearch as output plugin.
2017/05/02 18:56:39.383164 publish.go:191: INFO Publisher name: packer-virtualbox-iso-1492351135
2017/05/02 18:56:39.383262 async.go:63: INFO Flush Interval set to: 1s
2017/05/02 18:56:39.383267 async.go:64: INFO Max Bulk Size set to: 50
2017/05/02 18:56:39.383404 procs.go:79: INFO Process matching disabled
2017/05/02 18:56:39.383473 protos.go:99: INFO registered protocol plugin: dns
2017/05/02 18:56:39.383478 protos.go:99: INFO registered protocol plugin: mongodb
2017/05/02 18:56:39.383480 protos.go:99: INFO registered protocol plugin: nfs
2017/05/02 18:56:39.383482 protos.go:99: INFO registered protocol plugin: thrift
2017/05/02 18:56:39.383485 protos.go:99: INFO registered protocol plugin: amqp
2017/05/02 18:56:39.383487 protos.go:99: INFO registered protocol plugin: cassandra
2017/05/02 18:56:39.383518 protos.go:99: INFO registered protocol plugin: http
2017/05/02 18:56:39.383522 protos.go:99: INFO registered protocol plugin: memcache
2017/05/02 18:56:39.383524 protos.go:99: INFO registered protocol plugin: mysql
2017/05/02 18:56:39.383528 protos.go:99: INFO registered protocol plugin: pgsql
2017/05/02 18:56:39.383530 protos.go:99: INFO registered protocol plugin: redis
fatal error:
unexpected signal during runtime execution
[signal
SIGSEGV: segmentation violation
 code=
0x1
 addr=
0xffffffffaba21878
 pc=
0x139f08e
]
==> default:
runtime stack:
runtime.throw
(
0x15ec52f
,
0x2a
)
==> default:
/usr/local/go/src/runtime/panic.go
:
596
 +
0x95
runtime.sigpanic
(
)
==> default:
/usr/local/go/src/runtime/signal_unix.go
:
274
 +
0x2db
goroutine
1
 [
syscall
, locked to thread
]:
runtime.cgocall
(
0x1388480
,
0xc4212b7540
,
0x15eab07
)
==> default:
/usr/local/go/src/runtime/cgocall.go
:
131
 +
0xe2
 fp=
0xc4212b7500
 sp=
0xc4212b74c0
github.com/elastic/beats/vendor/github.com/tsg/gopacket/pcap._Cfunc_pcap_compile
(
0x42d3640
, 0xc4213070d0, 0x42d3010, 0x1, 0x0)
   github.com/elastic/beats/vendor/github.com/tsg/gopacket/pcap/_obj/_cgo_gotypes.go:293 +0x4d fp=0xc4212b7540 sp=0xc4212b7500
github.com/elastic/beats/vendor/github.com/tsg/gopacket/pcap.(*Handle).SetBPFFilter.func4(0x42d3640, 0xc4213070d0, 0x42d3010, 0x1, 0x0)
   /go/src/github.com/elastic/beats/vendor/github.com/tsg/gopacket/pcap/pcap.go:440 +0x116 fp=0xc4212b7588 sp=0xc4212b7540
github.com/elastic/beats/vendor/github.com/tsg/gopacket/pcap.(*Handle).SetBPFFilter(0xc4212bb100, 0x0, 0x0, 0x0, 0x0)
   /go/src/github.com/elastic/beats/vendor/github.com/tsg/gopacket/pcap/pcap.go:440 +0x179 fp=0xc4212b75f0 sp=0xc4212b7588
github.com/elastic/beats/packetbeat/sniffer.(*SnifferSetup).setFromConfig(0xc42129d200, 0xc420181b80, 0x15d203a, 0x10)
   /go/src/github.com/elastic/beats/packetbeat/sniffer/sniffer.go:174 +0x415 fp=0xc4212b7760 sp=0xc4212b75f0
github.com/elastic/beats/packetbeat/sniffer.(*SnifferSetup).Init(0xc42129d200, 0xc42129d200, 0x0, 0x0, 0xc4212b7858, 0xc420181b80, 0x15b95ff, 0x4)
   /go/src/github.com/elastic/beats/packetbeat/sniffer/sniffer.go:271 +0x3a5 fp=0xc4212b7800 sp=0xc4212b7760
github.com/elastic/beats/packetbeat/beater.(*packetbeat).setupSniffer(0xc420181b80, 0x4, 0x15d69e3)
   /go/src/github.com/elastic/beats/packetbeat/beater/packetbeat.go:207 +0x12c fp=0xc4212b7878 sp=0xc4212b7800
github.com/elastic/beats/packetbeat/beater.(*packetbeat).init(0xc420181b80, 0xc421276000, 0xc4212cc0f0, 0x0)
   /go/src/github.com/elastic/beats/packetbeat/beater/packetbeat.go:117 +0x432 fp=0xc4212b7928 sp=0xc4212b7878
github.com/elastic/beats/packetbeat/beater.New(0xc421276000, 0xc421297500, 0x15c9273, 0xc, 0xc421274040, 0x20)
   /go/src/github.com/elastic/beats/packetbeat/beater/packetbeat.go:84 +0x2fb fp=0xc4212b7c70 sp=0xc4212b7928
github.com/elastic/beats/libbeat/beat.(*Beat).launch(0xc421276000, 0x16142a8, 0x0, 0x0)
   /go/src/github.com/elastic/beats/libbeat/beat/beat.go:229 +0x4ff fp=0xc4212b7eb0 sp=0xc4212b7c70
github.com/elastic/beats/libbeat/beat.Run.func1(0x15c6008, 0xa, 0x0, 0x0, 0x16142a8, 0x0, 0x0)
   /go/src/github.com/elastic/beats/libbeat/beat/beat.go:157 +0x88 fp=0xc4212b7ef8 sp=0xc4212b7eb0
github.com/elastic/beats/libbeat/beat.Run(0x15c6008, 0xa, 0x0, 0x0, 0x16142a8, 0xc4200001a0, 0xc4200001a0)
   /go/src/github.com/elastic/beats/libbeat/beat/beat.go:158 +0x53 fp=0xc4212b7f40 sp=0xc4212b7ef8
main.main()
   /go/src/github.com/elastic/beats/packetbeat/main.go:17 +0x57 fp=0xc4212b7f88 sp=0xc4212b7f40
runtime.main()
   /usr/local/go/src/runtime/proc.go:185 +0x20a fp=0xc4212b7fe0 sp=0xc4212b7f88
runtime.goexit()
   /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc4212b7fe8 sp=0xc4212b7fe0
==> default:
goroutine 17 [syscall, locked to thread]:
runtime.goexit()
   /usr/local/go/src/runtime/asm_amd64.s:2197 +0x1
==> default:
goroutine 24 [syscall]:
os/signal.signal_recv(0x0)
   /usr/local/go/src/runtime/sigqueue.go:116 +0x104
os/signal.loop()
   /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.1
   /usr/local/go/src/os/signal/signal_unix.go:28 +0x41
==> default:
goroutine 60 [chan receive]:
github.com/elastic/beats/libbeat/logp.logMetrics(0xc4212760f8)
   /go/src/github.com/elastic/beats/libbeat/logp/metrics.go:28 +0x240
created by github.com/elastic/beats/libbeat/logp.Init
   /go/src/github.com/elastic/beats/libbeat/logp/logp.go:161 +0x2f1
==> default:
goroutine 62 [select]:
github.com/elastic/beats/libbeat/publisher.(*messageWorker).run(0xc420165540)
   /go/src/github.com/elastic/beats/libbeat/publisher/worker.go:63 +0x2a6
created by github.com/elastic/beats/libbeat/publisher.(*messageWorker).init
   /go/src/github.com/elastic/beats/libbeat/publisher/worker.go:57 +0x107
==> default:
goroutine 63 [select]:
github.com/elastic/beats/libbeat/publisher.(*bulkWorker).run(0xc4200ec850)
   /go/src/github.com/elastic/beats/libbeat/publisher/bulk.go:54 +0x34b
created by github.com/elastic/beats/libbeat/publisher.newBulkWorker
   /go/src/github.com/elastic/beats/libbeat/publisher/bulk.go:42 +0x21c
==> default:
goroutine 64 [select]:
github.com/elastic/beats/libbeat/common.(*Cache).StartJanitor.func1(0xc4212baac0, 0xc4212baa80)
   /go/src/github.com/elastic/beats/libbeat/common/cache.go:219 +0x123
created by github.com/elastic/beats/libbeat/common.(*Cache).StartJanitor
   /go/src/github.com/elastic/beats/libbeat/common/cache.go:227 +0x97
==> default:
goroutine 65 [select]:
github.com/elastic/beats/libbeat/common.(*Cache).StartJanitor.func1(0xc4212bab80, 0xc4212bab40)
   /go/src/github.com/elastic/beats/libbeat/common/cache.go:219 +0x123
created by github.com/elastic/beats/libbeat/common.(*Cache).StartJanitor
   /go/src/github.com/elastic/beats/libbeat/common/cache.go:227 +0x97
==> default:
goroutine 66 [select]:
github.com/elastic/beats/libbeat/common.(*Cache).StartJanitor.func1(0xc4212bacc0, 0xc4212bac80)
   /go/src/github.com/elastic/beats/libbeat/common/cache.go:219 +0x123
created by github.com/elastic/beats/libbeat/common.(*Cache).StartJanitor
   /go/src/github.com/elastic/beats/libbeat/common/cache.go:227 +0x97
==> default:
goroutine 67 [select]:
github.com/elastic/beats/libbeat/common.(*Cache).StartJanitor.func1(0xc4212badc0, 0xc4212bad80)
   /go/src/github.com/elastic/beats/libbeat/common/cache.go:219 +0x123
created by github.com/elastic/beats/libbeat/common.(*Cache).StartJanitor
   /go/src/github.com/elastic/beats/libbeat/common/cache.go:227 +0x97
==> default:
goroutine 68 [select]:
github.com/elastic/beats/libbeat/common.(*Cache).StartJanitor.func1(0xc4212bae80, 0xc4212bae40)
   /go/src/github.com/elastic/beats/libbeat/common/cache.go:219 +0x123
created by github.com/elastic/beats/libbeat/common.(*Cache).StartJanitor
   /go/src/github.com/elastic/beats/libbeat/common/cache.go:227 +0x97
==> default:
goroutine 69 [chan receive]:
github.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).publishTransactions(0xc4200ec930)
   /go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:1082 +0x71
created by github.com/elastic/beats/packetbeat/protos/thrift.(*thriftPlugin).init
   /go/src/github.com/elastic/beats/packetbeat/protos/thrift/thrift.go:205 +0x20f
==> default:
goroutine 70 [select]:
github.com/elastic/beats/libbeat/common.(*Cache).StartJanitor.func1(0xc4212baf80, 0xc4212baf40)
   /go/src/github.com/elastic/beats/libbeat/common/cache.go:219 +0x123
created by github.com/elastic/beats/libbeat/common.(*Cache).StartJanitor
   /go/src/github.com/elastic/beats/libbeat/common/cache.go:227 +0x97
==> default:
goroutine 71 [select]:
github.com/elastic/beats/libbeat/common.(*Cache).StartJanitor.func1(0xc4212bb000, 0xc4212bafc0)
   /go/src/github.com/elastic/beats/libbeat/common/cache.go:219 +0x123
created by github.com/elastic/beats/libbeat/common.(*Cache).StartJanitor
   /go/src/github.com/elastic/beats/libbeat/common/cache.go:227 +0x97
==> default:
goroutine 72 [select]:
github.com/elastic/beats/libbeat/common.(*Cache).StartJanitor.func1(0xc4212bb0c0, 0xc4212bb080)
   /go/src/github.com/elastic/beats/libbeat/common/cache.go:219 +0x123
created by github.com/elastic/beats/libbeat/common.(*Cache).StartJanitor
   /go/src/github.com/elastic/beats/libbeat/common/cache.go:227 +0x97
   ...fail!
```

**Comment by tsg** [comment] 2017-05-02 21:13
Thanks for reporting. Just to confirmed, you used the snapshot builds, right?

**Comment by LeeDr** [comment] 2017-05-02 21:16
yes, I used packetbeat-6.0.0-alpha1-SNAPSHOT-amd64.deb

**Comment by andrewkroh** [comment] 2017-05-02 21:20
This looks related: https://github.com/google/gopacket/issues/258#issuecomment-263343898
Possibly we need an update to gopacket?

**Comment by tsg** [comment] 2017-05-04 09:04
This seems to affect the 6.0.0-alpha1 build candidate as well. Interestingly, the package I build on my computer doesn't seem to have this issue.

**Comment by tsg** [comment] 2017-05-04 09:56
Correction to the above, it the 32 bits builds work well (even on amd64), but the 64 bits are broken. Looking into it now.

**Comment by tsg** [comment] 2017-05-04 10:33
Seems that the issue happens when compiling against `libpcap.a`, looks to me like some sort of Go 1.8 regression. One possible solution would be to compile against the `.so` file, and instead ask Go to create a fully static binary.

I was worried that the static binaries would be larger, but actually they are slightly smaller. The other worry that I have, is around DNS resolution, I'm not sure if the `resolv.conf` is treated the same way.

**Comment by tsg** [comment] 2017-05-04 12:42
#4203 seems to fix this. Thanks again @LeeDr for catching this.

**Comment by tsg** [comment] 2017-05-04 19:09
Looks like statically compiling is still not a valid solution, it crashes Metricbeat during DNS resolving:

```
goroutine 48 [syscall, locked to thread]:
runtime.cgocall(0x11cd000, 0xc420203250, 0x1750498)
	/usr/local/go/src/runtime/cgocall.go:131 +0xe2 fp=0xc420203210 sp=0xc4202031d0
net._C2func_getaddrinfo(0x3345f60, 0x0, 0xc42046ea50, 0xc4201f9190, 0x0, 0x0, 0x0)
	net/_obj/_cgo_gotypes.go:86 +0x68 fp=0xc420203250 sp=0xc420203210
net.cgoLookupIPCNAME.func2(0x3345f60, 0x0, 0xc42046ea50, 0xc4201f9190, 0x0, 0x5b0424, 0x2457a20)
	/usr/local/go/src/net/cgo_unix.go:151 +0x171 fp=0xc4202032b0 sp=0xc420203250
net.cgoLookupIPCNAME(0xc4204370f0, 0x9, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/net/cgo_unix.go:151 +0x1bd fp=0xc4202033b0 sp=0xc4202032b0
net.cgoLookupIP(0x24579e0, 0xc4200144a0, 0xc4204370f0, 0x9, 0xc42033c701, 0xc42033c618, 0x57f1c7, 0xc4204370f0, 0x9, 0x170d901)
	/usr/local/go/src/net/cgo_unix.go:209 +0x3a1 fp=0xc420203518 sp=0xc4202033b0
net.cgoLookupHost(0x24579e0, 0xc4200144a0, 0xc4204370f0, 0x9, 0x30, 0x30, 0x169f820, 0x0, 0x0, 0x30)
	/usr/local/go/src/net/cgo_unix.go:53 +0x6a fp=0xc420203628 sp=0xc420203518
net.(*Resolver).lookupHost(0x24b723e, 0x24579e0, 0xc4200144a0, 0xc4204370f0, 0x9, 0x0, 0xc4201f21a8, 0x16710a0, 0x0, 0xc42033c700)
	/usr/local/go/src/net/lookup_unix.go:54 +0x113 fp=0xc420203688 sp=0xc420203628
net.(*Resolver).LookupHost(0x24b723e, 0x24579e0, 0xc4200144a0, 0xc4204370f0, 0x9, 0xc42033c898, 0x0, 0x9, 0x9, 0xc4204370f0)
	/usr/local/go/src/net/lookup.go:121 +0x241 fp=0xc420203708 sp=0xc420203688
net.LookupHost(0xc4204370f0, 0x9, 0xc4204370f0, 0x9, 0xc4204370fa, 0x4, 0x0)
	/usr/local/go/src/net/lookup.go:107 +0x5d fp=0xc420203768 sp=0xc420203708
github.com/elastic/beats/libbeat/outputs/transport.NetDialer.func1(0x1704f18, 0x3, 0xc4204370f0, 0xe, 0x2000107, 0x0, 0xffffffffffffffff, 0xc42033caf0)
	/go/src/github.com/elastic/beats/libbeat/outputs/transport/tcp.go:24 +0xf8 fp=0xc420203898 sp=0xc420203768
github.com/elastic/beats/libbeat/outputs/transport.DialerFunc.Dial(0xc4202bc170, 0x1704f18, 0x3, 0xc4204370f0, 0xe, 0x0, 0x0, 0x0, 0xc42033c9c8)
	/go/src/github.com/elastic/beats/libbeat/outputs/transport/transport.go:23 +0x4e fp=0xc4202038e8 sp=0xc420203898
github.com/elastic/beats/libbeat/outputs/transport.ConnWrapper.func1(0x1704f18, 0x3, 0xc4204370f0, 0xe, 0x10, 0x40fc72, 0x0, 0x60)
	/go/src/github.com/elastic/beats/libbeat/outputs/transport/wrap.go:7 +0x64 fp=0xc420203948 sp=0xc4202038e8
github.com/elastic/beats/libbeat/outputs/transport.DialerFunc.Dial(0xc4202aeee0, 0x1704f18, 0x3, 0xc4204370f0, 0xe, 0x410ffc, 0x24b7500, 0xc42033ca58, 0x0)
	/go/src/github.com/elastic/beats/libbeat/outputs/transport/transport.go:23 +0x4e fp=0xc420203998 sp=0xc420203948
github.com/elastic/beats/libbeat/outputs/transport.(Dialer).Dial-fm(0x1704f18, 0x3, 0xc4204370f0, 0xe, 0xc42033ca58, 0x24b7500, 0xc42033ca60, 0x635c9d)
	/go/src/github.com/elastic/beats/libbeat/outputs/elasticsearch/client.go:178 +0x5b fp=0xc4202039f0 sp=0xc420203998
net/http.(*Transport).dial(0xc4202c8000, 0x24579e0, 0xc4200144a0, 0x1704f18, 0x3, 0xc4204370f0, 0xe, 0xc42033cc08, 0xc4201f43f0, 0x0, ...)
	/usr/local/go/src/net/http/transport.go:852 +0x7b fp=0xc420203a70 sp=0xc4202039f0
net/http.(*Transport).dialConn(0xc4202c8000, 0x24579e0, 0xc4200144a0, 0x0, 0xc4202aeec0, 0x4, 0xc4204370f0, 0xe, 0xc4202b3da0, 0x5be5b3, ...)
	/usr/local/go/src/net/http/transport.go:1008 +0x1c4c fp=0xc420203f38 sp=0xc420203a70
net/http.(*Transport).getConn.func4(0xc4202c8000, 0x24579e0, 0xc4200144a0, 0xc42046e9c0, 0xc42019e0c0)
	/usr/local/go/src/net/http/transport.go:908 +0x78 fp=0xc420203fb8 sp=0xc420203f38
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:2197 +0x1 fp=0xc420203fc0 sp=0xc420203fb8
created by net/http.(*Transport).getConn
	/usr/local/go/src/net/http/transport.go:910 +0x3a3
```

**Closed** 2017-05-04 22:25 UTC
Labels: blocker, bug, Packetbeat
