### ISSUE TITLE
beats/libbeat/scripts/generate_template.py doesn't recognize 'ip' as a valid type

### ISSUE THREAD

**Issue by blacktop** [elastic/beats#3257] opened 2016-12-29 22:42 UTC
For confirmed bugs, please report:
- Version:  master
- Operating System: OSX
- Steps to Reproduce: 

`make update` on a beat where one of the fields.yml types is `ip`

**Comment by andrewkroh** [comment] 2016-12-29 22:45
I have an open PR that contains an enhancement to add `ip`. See https://github.com/elastic/beats/pull/3246/files#diff-f718dc33941d9c75d94b3d9a7243d9c4

**Comment by blacktop** [comment] 2016-12-29 23:06
Awesome thank you, it worked !!!

@andrewkroh I can't figure out how to add other `_types` to the `/etc/fields.yml` can you please help?

**Comment by andrewkroh** [comment] 2016-12-29 23:24
Please use Discuss for general questions. https://discuss.elastic.co/c/beats

**Comment by blacktop** [comment] 2016-12-29 23:43
Will do! Thanks - https://discuss.elastic.co/t/how-to-add-other--types-to-the-etc-fields-yml-in-beats/70241

**Comment by breml** [comment] 2017-01-02 12:26
Support for `ip` fields as well as numeric fields other than `long` would help me as well.

**Comment by ruflin** [comment] 2017-01-03 09:26
@breml `ip` should now be supported in master. Which missing numeric fields are you looking for?

Closing this as the title of the issue is about `ip`.

**Closed by ruflin** 2017-01-03 09:26 UTC
Labels: enhancement
