### ISSUE TITLE
Broken Metricbeat dashboards

### ISSUE THREAD

**Issue by inqueue** [elastic/beats#4777] opened 2017-07-27 20:20 UTC
Metricbeat 6.0.0-beta1 BC2

The `Metricbeat host overview` and `Metricbeat system overview` dashboards are showing error "The request for this panel failed." for several visualizations. The same visualizations load correctly when launched individually or placed in a new dashboard. The issue appears to be something specific to the dashboards.

Dashboards were installed with:
```
./metricbeat setup --dashboards
```

### Host Overview
![screen shot 2017-07-27 at 4 17 54 pm](https://user-images.githubusercontent.com/6099128/28690434-2fc8518c-72e7-11e7-8a48-5a89a3904c8d.png)

### System Overview
![screen shot 2017-07-27 at 4 18 29 pm](https://user-images.githubusercontent.com/6099128/28690454-4789203a-72e7-11e7-9c95-d03be4eab84c.png)

### Custom
![screen shot 2017-07-27 at 4 10 35 pm](https://user-images.githubusercontent.com/6099128/28690422-21b97774-72e7-11e7-88a1-010d3a852d34.png)

**Comment by exekias** [comment] 2017-07-28 11:20
I've reproduced this issue

**Comment by exekias** [comment] 2017-07-28 11:33
![system dashboard 1](https://user-images.githubusercontent.com/299804/28715665-51d2429e-7399-11e7-80b7-83bef0c41a59.gif)

Graph seems to work while editing, it just fails in the dashboard, where I see this error message in the developer console

```
commons.bundle.js?v=15762:38 Error: [ngRepeat:dupes] Duplicates in a repeater are not allowed. Use 'track by' expression to specify unique keys. Repeater: legendData in labels track by legendData.label, Duplicate key: 100% - 100%, Duplicate value: {"label":"100% - 100%"}
http://errors.angularjs.org/1.4.7/ngRepeat/dupes?p0=legendData%20in%20label…el&p1=100%25%20-%20100%25&p2=%7B%22label%22%3A%22100%25%20-%20100%25%22%7D
    at commons.bundle.js?v=15762:35
    at commons.bundle.js?v=15762:43
    at Object.$watchCollectionAction [as fn] (commons.bundle.js?v=15762:39)
    at Scope.$digest (commons.bundle.js?v=15762:39)
    at Scope.$apply (commons.bundle.js?v=15762:39)
    at kibana.bundle.js?v=15762:126
    at complete (commons.bundle.js?v=15762:2)
    at delayed (commons.bundle.js?v=15762:2)
```
Still researching, but this may be a kibana issue

**Comment by tsg** [comment] 2017-07-28 12:39
Looks like this can be workedaround by simply entering the empty string (just press enter), or `*` in the search box.

**Comment by tsg** [comment] 2017-07-28 12:42
I think what happened was that Kibana changed the format in which the query string is saved. This is in the imported dashboards:

```
{
  "filter": [
    {
      "query": {
        "query_string": {
          "analyze_wildcard": true,
          "query": "*"
        }
      }
    }
  ]
}
```

And this is how it looks in a newly created dashboard:

```
{
  "query": {
    "language": "lucene",
    "query": ""
  },
  "filter": [],
  "highlightAll": true,
  "version": true
}
```

**Comment by tsg** [comment] 2017-07-28 14:05
Closing in favor of https://github.com/elastic/kibana/issues/13181.

**Closed by tsg** 2017-07-28 14:05 UTC
Labels: :Dashboards, blocker, bug, v6.0.0-beta1
