### ISSUE TITLE
[Filebeat] Journald causes Filebeat to crash

### ISSUE THREAD

**Issue by Aqualie** [elastic/beats#34077] opened 2022-12-20 00:39 UTC
- Version: 8.5.3
- Operating System: 6.0.12-arch1-1
- Steps to Reproduce: Enable the IPTables (input: journald) plugin in the elastic-agent wait a few minutes and it crashes
Crash logs: [filebeat.log](https://github.com/elastic/beats/files/10263769/filebeat.log)

**Comment by dlouzan** [comment] 2023-02-10 12:19
Bump the issue for hopefully a reaction of the maintainers, or a quick assessment, this is literally crashing dozens of times per day on busy hosts 🙇 

I did not find a policy for tagging / mentioning, could you perhaps help @ph with assessment?

Thanks in advance for any input!

**Comment by utilitynerd** [comment] 2023-09-20 23:28
I'm seeing the same issue on Debian 12 (not technically supported yet) and Filebeat 8.10.1.

**Comment by dlouzan** [comment] 2023-11-17 11:36
Checking upstream, in theory https://github.com/systemd/systemd/pull/29456 is solving this, but I do not even see it added to systemd v255 rc2, so it will probably be a while until we can verify this or whether they'll backport it to previous releases.

It'd be great if somebody that runs a cutting edge setup could confirm 😇

**Comment by belimawr** [comment] 2024-03-25 11:03
I've been trying to reproduce this issue today and I can't get it to happen.

Following the linked issues, I ended up using https://github.com/systemd/systemd/issues/24320#issuecomment-1543429107 to try reproducing it. 

I've tried two distros so far:
* Archlinux, journald/systemd 255 (255.4-2-arch)
*  Ubunutu 2004, journald/systemd 245 (245.4-4ubuntu3.23)

I'll look more into it, probably trying with Fedora as well.

**Comment by dlouzan** [comment] 2024-03-25 11:28
@belimawr We get the crashes regularly (verified our logs just now again) on fedora 38 & amazon linux 2023 hosts. We only see it on busy hosts, which makes sense as this is some kind of race condition.

**Comment by belimawr** [comment] 2024-03-25 14:07
Thanks for the quick reply @dlouzan ! I'll try those distros and see if I can reproduce it.

Do you have any idea of the throughput of messages in the journald logs? Currently I'm working with about 20k ~ 30k events per minute on the systems I mentioned before.

**Comment by dlouzan** [comment] 2024-03-25 14:40
@belimawr Both kinds of hosts are using latest stable dnf packages `8.12.2-1`; at the time of the last crash that I can see, the node was delivering ~10k events from 11 log files every 30s. Not much of a difference on the delivered stats after the restart following the crash:

```json
{
    "message": "Non-zero metrics in the last 30s",
    "service.name": "filebeat",
    "monitoring": {
        "metrics": {
            "beat": {
                "cgroup": {
                    "memory": {
                        "mem": {
                            "usage": {
                                "bytes": 91836416
                            }
                        }
                    }
                },
...
                "handles": {
                    "limit": {
                        "hard": 65535,
                        "soft": 65535
                    },
                    "open": 116
                },
                "info": {
                    "ephemeral_id": "1fe23dc6-4d58-47c3-8c77-fdfdaaa8c143",
                    "uptime": {
                        "ms": 6810097
                    },
                    "version": "8.12.2"
                },
...
            },
            "filebeat": {
                "events": {
                    "active": 775,
                    "added": 10007,
                    "done": 9601
                },
                "harvester": {
                    "open_files": 11,
                    "running": 11
                }
            },
            "libbeat": {
...
                "output": {
                    "events": {
                        "acked": 9600,
                        "active": 0,
                        "batches": 6,
                        "total": 9600
                    },
                    "read": {
                        "bytes": 440
                    },
                    "write": {
                        "bytes": 1841900
                    }
                },
                "pipeline": {
                    "clients": 17,
                    "events": {
                        "active": 775,
                        "filtered": 1,
                        "published": 10006,
                        "total": 10007
                    },
                    "queue": {
                        "acked": 9600
                    }
                }
            },
            "registrar": {
                "states": {
                    "current": 20,
                    "update": 8524
                },
                "writes": {
                    "success": 6,
                    "total": 6
                }
            },
            "system": {
                "load": {
                    "1": 5.98,
                    "15": 5.45,
                    "5": 5.33,
                    "norm": {
                        "1": 0.3738,
                        "15": 0.3406,
                        "5": 0.3331
                    }
                }
            }
        },
        "ecs.version": "1.6.0"
    }
}
```

**Comment by belimawr** [comment] 2024-03-25 14:45
Thanks!

**Comment by belimawr** [comment] 2024-03-25 16:26
I can confirm I can reproduce the crash and the time I noticed it happening was when the journald was rotating its logs.

Interestingly enough, `journalctl --rotate` does not trigger it. There might be something else than just a rotation playing a role there.

Vesrions (IP redacted):
```
[root@ip-42.42.42.42 ec2-user]# filebeat  version
filebeat version 8.12.2 (amd64), libbeat 8.12.2 [0b71acf2d6b4cb6617bff980ed6caf0477905efa built 2024-02-15 13:39:15 +0000 UTC]
[root@ip-42.42.42.42 ec2-user]# uname -a
Linux ip-42.42.42.42.eu-central-1.compute.internal 6.1.79-99.167.amzn2023.x86_64 #1 SMP PREEMPT_DYNAMIC Tue Mar 12 18:15:55 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
[root@ip-42.42.42.42 ec2-user]# journalctl --version
systemd 252 (252.16-1.amzn2023.0.2)
+PAM +AUDIT +SELINUX -APPARMOR +IMA +SMACK +SECCOMP -GCRYPT -GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN -IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 -BZIP2 -LZ4 +XZ -ZLIB -ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=unified
[root@ip-42.42.42.42 ec2-user]# 
```

# How to reproduce
1. Get an Amazon 2023 Linux host
2. Install Filebeat using [yum as described in our documentation](https://www.elastic.co/guide/en/beats/filebeat/8.12/setup-repositories.html#_yum)
3. Use the following configuration (`/etc/filebeat/filebeat.yml`)
    <details><summary>/etc/filebeat/filebeat.yml</summary>
    <p>

    ```yaml
    filebeat.inputs:
    - type: journald
      id: journald-input
    
    output.elasticsearch:
      hosts:
        - https://my-awesome-deployment.elastic-cloud.com:443
      username: elastic
      password: a-very-secret-password
    ```

    </p>
    </details> 
4. Start the service: `systemctl enable --now filebeat`
5. Start watching Filebeat logs `journalctl -fu filebeat`
6. Generate a high load of logs sent to journald so rotation is triggered often. The following script is from https://github.com/systemd/systemd/issues/24320#issuecomment-1543429107. I ran it as root.
    <details><summary>crash.py</summary>
    <p>

    ```python
    #!/usr/bin/env python3
    
    import logging
    import logging.handlers
    import random
    import string
    
    my_logger = logging.getLogger('MyLogger')
    my_logger.setLevel(logging.DEBUG)
    
    handler = logging.handlers.SysLogHandler(address = '/dev/log')
    
    my_logger.addHandler(handler)
    
    animals = ["cat", "dog", "crab"]
    padding = ''.join(random.choices(string.ascii_lowercase, k=1024))
    
    while True:
        for animal in animals:
            my_logger.critical(f"Rubbish - {animal} food is running short. Rubbish: " + padding)
    ```

    </p>
    </details> 
7. Wait until the crash happens. On my tests it seemed to only happen after the maximum number of rotated files was reaches. Once that was reached, every rotation triggered the crash.

**Comment by belimawr** [comment] 2024-03-27 15:51
I've also tried to reproduce it in a VM running Archlinux and the crash does not reproduce, it uses a newer version of Journald/Systemd (255):
```
systemd 255 (255.4-2-arch)
+PAM +AUDIT -SELINUX -APPARMOR -IMA +SMACK +SECCOMP +GCRYPT +GNUTLS +OPENSSL +ACL +BLKID +CURL +ELFUTILS +FIDO2 +IDN2 -IDN +IPTC +KMOD +LIBCRYPTSETUP +LIBFDISK +PCRE2 +PWQUALITY +P11KIT +QRENCODE +TPM2 +BZIP2 +LZ4 +XZ +ZLIB +ZSTD +BPF_FRAMEWORK +XKBCOMMON +UTMP -SYSVINIT default-hierarchy=unified
```

It really looks like the crash is not caused by Filebeat, but by Journald/go-systemd.

**Comment by dlouzan** [comment] 2024-03-28 16:49
@belimawr Perhaps the efforts should go into supporting the backport of the supposed fix into systemd v252, which is the stable version in multiple distributions: https://github.com/systemd/systemd-stable/issues/356 🙇

**Comment by belimawr** [comment] 2024-05-01 21:58
I was looking at this issue again in a more structured way, and this time I can confirm that the crash is not related to Filebeat, even a Filebeat build with a newer version of Journald still experiences the same crash.

I also experienced the crashes described by:
 - https://github.com/elastic/beats/issues/32782
 - https://github.com/elastic/beats/issues/39352

They happen intermittently with the SIGBUS error. All while flooding Journald with logs, thus forcing a quick log rotation.

**Comment by belimawr** [comment] 2024-05-06 19:56
I've tried backporting https://github.com/systemd/systemd-stable/issues/356 to `v252`, but just the patch from the original [PR](https://github.com/systemd/systemd/pull/29456) is not enough because other parts of the code have diverged. I tried to fix some obvious ones, but my C is pretty rusty and my knowledge of the systemd codebase is zero :/

Anyway, here is my attempt: https://github.com/belimawr/systemd-stable/tree/v252-stable

**Comment by belimawr** [comment] 2024-05-06 20:01
The AmazonLinux issue about it also seems pretty stale. I added a comment here but I don't have high hopes. https://github.com/amazonlinux/amazon-linux-2023/issues/608#issuecomment-2096806006

**Comment by belimawr** [comment] 2024-05-10 14:29
I did some investigation tying to recover from the panic caused by systemd and, unfortunately, it's not possible to recover from it :/

When a SIGBUS is sent due to an error in program execution the Go runtime converts it into a run-time panic that we cannot recover from on our code.

From the [Go docs](https://pkg.go.dev/os/signal#hdr-Types_of_signals):
> Synchronous signals are signals triggered by errors in program execution: SIGBUS, SIGFPE, and SIGSEGV. These are only considered synchronous when caused by program execution, not when sent using [os.Process.Kill](https://pkg.go.dev/os#Process.Kill) or the kill program or some similar mechanism. In general, except as discussed below, Go programs will convert a synchronous signal into a run-time panic.

**Comment by jlind23** [comment] 2024-05-13 13:47
@belimawr I am fine closing it with a "won't fix" status then.

**Comment by belimawr** [comment] 2024-05-13 19:53
> Can we detect the systemd version at runtime and refuse to run with a detailed error if it is the version with this bug? That seems preferable to letting us be killed by SIGBUS.

I'll look into that. Worst case scenario we can `exec.Command("journalctl", "--version")` and parse the output.

**Comment by belimawr** [comment] 2024-05-16 19:34
PR adding validation to the Systemd version to prevent Filebeat from crashing: https://github.com/elastic/beats/pull/39605

**Comment by belimawr** [comment] 2024-06-04 13:11
I performed 3 tests reproducing this crash to better understand if there is data loss due to the crash itself. Out of 3 runs, 2 ingested all data and 1 duplicated some events, about 3.2% of duplication.

**Closed as completed** 2024-08-09 12:35 UTC
Labels: bug, Team:Elastic-Agent, Team:Elastic-Agent-Data-Plane
