### ISSUE TITLE
[RabbitMQ] support https management interface

### ISSUE THREAD

**Issue by abraxxa** [elastic/beats#5667] opened 2017-11-21 12:17 UTC
Version: 6.0.0
Operating System: Debian 8
Steps to Reproduce:
- enable the rabbitmq metricbeat module on a host running RabbitMQ with the management plugin enabled and configured for https
- configure `hosts: ["localhost:15671"]` or `hosts: ["https://localhost:15671"]` in /etc/metricbeat/modules.d/rabbitmq.yml
- restart metricbeat
- no data is shown in the Metricbeat RabbitMQ dashboard
- no errors or other logs in /var/log/metricbeat/metricbeat
- no logs in /var/log/rabbitmq/rabbit@hostname.log

**Comment by ruflin** [comment] 2017-11-22 03:31
@abraxxa Could you share your full config file and the debug logs if possible?

**Comment by ruflin** [comment] 2017-11-28 03:41
@abraxxa Does in your case the RabbitMQ monitoring work without the management plugin?

**Comment by abraxxa** [comment] 2017-11-28 08:29
@ruflin sorry for taking so long to answer!

The metricbeat rabbitmq module config file is almost what gets installed by the deb package:

```
- module: rabbitmq
  metricsets: ["node"]
  period: 10s
  hosts: ["localhost:15672"]

  username: guest
  password: guest
```

And here is /etc/rabbitmq/rabbitmq.config
```

[
  {ssl, [{versions, ['tlsv1.2']}]},
  {rabbit, [
      {reverse_dns_lookups, true},
      {hipe_compile, true},
      {ssl_listeners, [5671]},
      {ssl_options, [
        {cacertfile, "/etc/rabbitmq/ca-chain.pem"},
        {certfile,   "/etc/rabbitmq/amqp-prod.example.tld.pem"},
        {keyfile,    "/etc/rabbitmq/amqp-prod.example.tld.key"},
        {versions, ['tlsv1.2']}
      ]}
    ]
  },
  {rabbitmq_management, [
    {listener, [
      {port, 15671},
      {ssl,  true},
      {ssl_opts, [
        {cacertfile, "/etc/rabbitmq/ca-chain.pem"},
        {certfile,   "/etc/rabbitmq/amqp-prod.example.tld.pem"},
        {keyfile,    "/etc/rabbitmq/amqp-prod.example.tld.key"},
        {versions, ['tlsv1.2']}
      ]}
    ]}
  ]}
].
```

**Comment by ruflin** [comment] 2017-12-04 03:17
You are of course right about the management plugin.

I tested rabbitmq with SSL manually and that seems to work as expected. So I assume the problem is either related to the version of RabbitMQ or SSL (more likely). Can you confirm that it works without SSL configured?

What do you get if you access `https://localhost:15671/api/nodes`? Do you see any certifcate errors?

Could you enable debug logging and share the log output?

**Comment by abraxxa** [comment] 2018-02-17 14:08
Sorry for the long delay!
It seems you have to specify hosts with a leading `https://` even when you specify ssl.enabled: true.

This doesn't work and tcpdump shows that it's still sending a plaintext http request:
```
hosts: ["localhost:15671"]
ssl.enabled: true
```

This works:
```
hosts: ["https://localhost:15671"]
```

Please make the first example work too to match the docs.

Thanks!

**Comment by jsoriano** [comment] 2018-04-28 11:26
In principle `ssl.enabled` is only used for outputs ([doc](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-ssl.html)). Is it referenced somewhere else to configure modules?

I'm closing it by now as the main issue seems to be working as expected, please reopen, or open a new issue, if there is any additional problem with the doc.

**Closed by jsoriano** 2018-04-28 11:26 UTC
Labels: Metricbeat, bug, module

**Comment by bramu-rythmos** [comment] 2019-07-02 08:48
Hey I want to try this with non-ssl. Is it possible?

**Comment by jsoriano** [comment] 2019-07-02 08:58
@bramu-rythmos yes, RabbitMQ module should work both with http and with https. Please use https://discuss.elastic.co if you have questions about configuration.

**Comment by bramu-rythmos** [comment] 2019-07-02 09:00
when we make the URL with "http": The error::error.message:error making http request: Get http://mq1.rcx-sei.lmvi.net:15671/api/connections: EOF.

While we try to make the request with "Https": The error is::error making http request: Get https://mq1.rcx-sei.lmvi.net:15671/api/queues: x509: certificate signed by unknown authority.

Can you suggest on this?



Thanks & Regards,
Basaveswar Rao Ramu,
Associate Consultant,
Rythmos India Private Limited.
________________________________

**Comment by jsoriano** [comment] 2019-07-02 09:02
@bramu-rythmos could you please post your question in https://discuss.elastic.co/ ?
