### ISSUE TITLE
Support for verification_mode: certificate

### ISSUE THREAD

**Issue by jguay** [elastic/beats#9486] opened 2018-12-11 15:00 UTC
**Describe the enhancement:**
Beats [supports](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-ssl.html) verification_mode with values full or none but not certificate like is supported with [elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/current/security-settings.html#ssl-tls-settings)
**Describe a specific use case for the enhancement or feature:**
Request for ability to use : 
```
verification_mode: certificate
```
This would allow to check the certificate is issued by a trusted authority without performing any hostname verification

**Comment by arenard** [comment] 2018-12-19 15:13
It seems to be a duplicate of https://github.com/elastic/beats/issues/8164

**Comment by ph** [comment] 2018-12-19 15:21
indeed it is I will close this one.

**Closed by ph** 2018-12-19 15:21 UTC
Labels: enhancement, libbeat
