### ISSUE TITLE
[Auditbeat] flaky file_integrity.test_recursive test

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#8103] opened 2018-08-27 13:20 UTC
Error
```
10:03:53 ======================================================================
10:03:53 ERROR: file_integrity monitors watched directories (recursive).
10:03:53 ----------------------------------------------------------------------
10:03:53 Traceback (most recent call last):
10:03:53   File "/go/src/github.com/elastic/beats/auditbeat/tests/system/test_file_integrity.py", line 167, in test_recursive
10:03:53     self.wait_log_contains("\"path\": \"{0}\"".format(escape_path(file2)), ignore_case=True)
10:03:53   File "/go/src/github.com/elastic/beats/auditbeat/tests/system/../../../metricbeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 348, in wait_log_contains
10:03:53     name=name)
10:03:53   File "/go/src/github.com/elastic/beats/auditbeat/tests/system/../../../metricbeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 325, in wait_until
10:03:53     "Waited {} seconds.".format(max_timeout))
10:03:53 TimeoutError: Timeout waiting for 'log_contains' to be true. Waited 10 seconds.
```

Log
```
2018-08-27T10:03:31.002Z	INFO	instance/beat.go:545	Home path: [/go/src/github.com/elastic/beats/auditbeat/build/system-tests/run/test_file_integrity.Test.test_recursive] Config path: [/go/src/github.com/elastic/beats/auditbeat/build/system-tests/run/test_file_integrity.Test.test_recursive] Data path: [/go/src/github.com/elastic/beats/auditbeat/build/system-tests/run/test_file_integrity.Test.test_recursive/data] Logs path: [/go/src/github.com/elastic/beats/auditbeat/build/system-tests/run/test_file_integrity.Test.test_recursive/logs]
2018-08-27T10:03:31.002Z	DEBUG	[beat]	instance/beat.go:572	Beat metadata path: /go/src/github.com/elastic/beats/auditbeat/build/system-tests/run/test_file_integrity.Test.test_recursive/data/meta.json
2018-08-27T10:03:31.004Z	INFO	instance/beat.go:552	Beat UUID: dab05ae8-a750-4320-90e4-141ef92ac976
2018-08-27T10:03:31.004Z	DEBUG	[seccomp]	seccomp/seccomp.go:109	Loading syscall filter	{"seccomp_filter": {"no_new_privs":true,"flag":"tsync","policy":{"default_action":"errno","syscalls":[{"names":["accept","accept4","access","arch_prctl","bind","brk","clock_gettime","clone","close","connect","dup","dup2","epoll_create","epoll_create1","epoll_ctl","epoll_pwait","epoll_wait","exit","exit_group","fchdir","fchmod","fchown","fcntl","fdatasync","flock","fstat","fsync","ftruncate","futex","getcwd","getdents","getdents64","geteuid","getgid","getpeername","getpid","getppid","getrandom","getrusage","getsockname","getsockopt","gettid","gettimeofday","getuid","inotify_add_watch","inotify_init1","inotify_rm_watch","ioctl","kill","listen","lseek","lstat","madvise","mincore","mkdirat","mmap","mprotect","munmap","nanosleep","newfstatat","open","openat","pipe","pipe2","poll","pread64","pselect6","pwrite64","read","readlink","readlinkat","recvfrom","recvmmsg","recvmsg","rename","renameat","rt_sigaction","rt_sigprocmask","rt_sigreturn","sched_getaffinity","sched_yield","sendfile","sendmmsg","sendmsg","sendto","set_robust_list","setitimer","setsockopt","shutdown","sigaltstack","socket","stat","statfs","sysinfo","tgkill","time","tkill","uname","unlink","unlinkat","wait4","waitid","write","writev"],"action":"allow"}]}}}
2018-08-27T10:03:31.004Z	INFO	[seccomp]	seccomp/seccomp.go:116	Syscall filter successfully installed
2018-08-27T10:03:31.004Z	INFO	[beat]	instance/beat.go:768	Beat info	{"system_info": {"beat": {"path": {"config": "/go/src/github.com/elastic/beats/auditbeat/build/system-tests/run/test_file_integrity.Test.test_recursive", "data": "/go/src/github.com/elastic/beats/auditbeat/build/system-tests/run/test_file_integrity.Test.test_recursive/data", "home": "/go/src/github.com/elastic/beats/auditbeat/build/system-tests/run/test_file_integrity.Test.test_recursive", "logs": "/go/src/github.com/elastic/beats/auditbeat/build/system-tests/run/test_file_integrity.Test.test_recursive/logs"}, "type": "auditbeat", "uuid": "dab05ae8-a750-4320-90e4-141ef92ac976"}}}
2018-08-27T10:03:31.004Z	INFO	[beat]	instance/beat.go:777	Build info	{"system_info": {"build": {"commit": "unknown", "libbeat": "7.0.0-alpha1", "time": "1754-08-30T22:43:41.128Z", "version": "7.0.0-alpha1"}}}
2018-08-27T10:03:31.004Z	INFO	[beat]	instance/beat.go:780	Go runtime info	{"system_info": {"go": {"os":"linux","arch":"amd64","max_procs":4,"version":"go1.10.3"}}}
2018-08-27T10:03:31.005Z	INFO	[beat]	instance/beat.go:784	Host info	{"system_info": {"host": {"architecture":"x86_64","boot_time":"2018-08-21T06:23:17Z","containerized":false,"hostname":"9199ec4ac46e","ips":["127.0.0.1/8","172.18.0.5/16"],"kernel_version":"4.4.0-1065-aws","mac_addresses":["02:42:ac:12:00:05"],"os":{"family":"debian","platform":"debian","name":"Debian GNU/Linux","version":"9 (stretch)","major":9,"minor":0,"patch":0,"codename":"stretch"},"timezone":"UTC","timezone_offset_sec":0,"id":"3e608929fbd39b959f388bf468c9f0b1"}}}
2018-08-27T10:03:31.005Z	INFO	[beat]	instance/beat.go:813	Process info	{"system_info": {"process": {"capabilities": {"inheritable":["chown","dac_override","dac_read_search","fowner","fsetid","kill","setgid","setuid","setpcap","linux_immutable","net_bind_service","net_broadcast","net_admin","net_raw","ipc_lock","ipc_owner","sys_module","sys_rawio","sys_chroot","sys_ptrace","sys_pacct","sys_admin","sys_boot","sys_nice","sys_resource","sys_time","sys_tty_config","mknod","lease","audit_write","audit_control","setfcap","mac_override","mac_admin","syslog","wake_alarm","block_suspend","audit_read"],"permitted":["chown","dac_override","dac_read_search","fowner","fsetid","kill","setgid","setuid","setpcap","linux_immutable","net_bind_service","net_broadcast","net_admin","net_raw","ipc_lock","ipc_owner","sys_module","sys_rawio","sys_chroot","sys_ptrace","sys_pacct","sys_admin","sys_boot","sys_nice","sys_resource","sys_time","sys_tty_config","mknod","lease","audit_write","audit_control","setfcap","mac_override","mac_admin","syslog","wake_alarm","block_suspend","audit_read"],"effective":["chown","dac_override","dac_read_search","fowner","fsetid","kill","setgid","setuid","setpcap","linux_immutable","net_bind_service","net_broadcast","net_admin","net_raw","ipc_lock","ipc_owner","sys_module","sys_rawio","sys_chroot","sys_ptrace","sys_pacct","sys_admin","sys_boot","sys_nice","sys_resource","sys_time","sys_tty_config","mknod","lease","audit_write","audit_control","setfcap","mac_override","mac_admin","syslog","wake_alarm","block_suspend","audit_read"],"bounding":["chown","dac_override","dac_read_search","fowner","fsetid","kill","setgid","setuid","setpcap","linux_immutable","net_bind_service","net_broadcast","net_admin","net_raw","ipc_lock","ipc_owner","sys_module","sys_rawio","sys_chroot","sys_ptrace","sys_pacct","sys_admin","sys_boot","sys_nice","sys_resource","sys_time","sys_tty_config","mknod","lease","audit_write","audit_control","setfcap","mac_override","mac_admin","syslog","wake_alarm","block_suspend","audit_read"],"ambient":null}, "cwd": "/go/src/github.com/elastic/beats/auditbeat", "exe": "/go/src/github.com/elastic/beats/auditbeat/auditbeat.test", "name": "auditbeat.test", "pid": 32255, "ppid": 31955, "seccomp": {"mode":"filter"}, "start_time": "2018-08-27T10:03:30.459Z"}}}
2018-08-27T10:03:31.005Z	INFO	instance/beat.go:274	Setup Beat: auditbeat; Version: 7.0.0-alpha1
2018-08-27T10:03:31.005Z	DEBUG	[beat]	instance/beat.go:291	Initializing output plugins
2018-08-27T10:03:31.005Z	DEBUG	[processors]	processors/processor.go:66	Processors: 
2018-08-27T10:03:31.006Z	DEBUG	[rotator]	file/rotator.go:135	Initialized file rotator	{"rotator": {"filename": "/go/src/github.com/elastic/beats/auditbeat/build/system-tests/run/test_file_integrity.Test.test_recursive/output/auditbeat", "max_size_bytes": 1024000, "max_backups": 7, "permissions": "-rw-------"}}
2018-08-27T10:03:31.006Z	INFO	fileout/file.go:97	Initialized file output. path=/go/src/github.com/elastic/beats/auditbeat/build/system-tests/run/test_file_integrity.Test.test_recursive/output/auditbeat max_size_bytes=1024000 max_backups=7 permissions=-rw-------
2018-08-27T10:03:31.006Z	DEBUG	[publish]	pipeline/consumer.go:137	start pipeline event consumer
2018-08-27T10:03:31.006Z	INFO	pipeline/module.go:98	Beat name: 9199ec4ac46e
2018-08-27T10:03:31.006Z	DEBUG	[modules]	beater/metricbeat.go:98	Register [ModuleFactory:[], MetricSetFactory:[auditd/auditd, file_integrity/file]]
2018-08-27T10:03:31.006Z	DEBUG	[processors]	processors/processor.go:66	Processors: 
2018-08-27T10:03:31.006Z	DEBUG	[file_integrity]	file_integrity/metricset.go:97	Initialized the file event reader. Running as euid=0
2018-08-27T10:03:31.006Z	INFO	instance/beat.go:368	auditbeat start running.
2018-08-27T10:03:31.006Z	INFO	[monitoring]	log/log.go:114	Starting metrics logging every 30s
2018-08-27T10:03:31.006Z	DEBUG	[module]	module/wrapper.go:117	Starting Wrapper[name=file_integrity, len(metricSetWrappers)=1]
2018-08-27T10:03:31.006Z	DEBUG	[module]	module/wrapper.go:171	file_integrity/file will start after 3.18060193s
2018-08-27T10:03:34.187Z	DEBUG	[module]	module/wrapper.go:179	Starting metricSetWrapper[module=file_integrity, name=file, host=]
2018-08-27T10:03:34.194Z	INFO	[file_integrity]	file_integrity/eventreader_fsnotify.go:95	Started fsnotify watcher	{"file_path": ["/tmp/tmpQxnEGoauditbeat_test"], "recursive": true}
2018-08-27T10:03:34.198Z	DEBUG	[file_integrity]	file_integrity/eventreader_fsnotify.go:136	Received fsnotify event	{"file_path": "/tmp/tmpQxnEGoauditbeat_test/subdir", "event_flags": "CREATE"}
2018-08-27T10:03:34.199Z	DEBUG	[file_integrity]	file_integrity/eventreader_fsnotify.go:136	Received fsnotify event	{"file_path": "/tmp/tmpQxnEGoauditbeat_test/subdir/file.txt", "event_flags": "CREATE"}
2018-08-27T10:03:34.199Z	DEBUG	[file_integrity]	file_integrity/metricset.go:252	File changed since it was last seen	{"file_path": "/tmp/tmpQxnEGoauditbeat_test/subdir", "took": 461133, "event": {"old": null, "new": {"timestamp":"2018-08-27T10:03:34.198732133Z","path":"/tmp/tmpQxnEGoauditbeat_test/subdir","info":{"inode":89604202,"uid":0,"gid":0,"sid":"","owner":"root","group":"root","size":4096,"mtime":"2018-08-27T10:03:34.194946251Z","ctime":"2018-08-27T10:03:34.194946251Z","type":"dir","mode":493,"setuid":false,"setgid":false,"origin":null},"source":"fsnotify","action":"created"}}}
2018-08-27T10:03:34.199Z	DEBUG	[publish]	pipeline/processor.go:308	Publish event: {
  "@timestamp": "2018-08-27T10:03:34.198Z",
  "@metadata": {
    "beat": "auditbeat",
    "type": "doc",
    "version": "7.0.0-alpha1"
  },
  "event": {
    "module": "file_integrity",
    "action": [
      "created"
    ]
  },
  "file": {
    "uid": 0,
    "owner": "root",
    "path": "/tmp/tmpQxnEGoauditbeat_test/subdir",
    "group": "root",
    "mtime": "2018-08-27T10:03:34.194Z",
    "ctime": "2018-08-27T10:03:34.194Z",
    "gid": 0,
    "mode": "0755",
    "inode": "89604202",
    "type": "dir"
  },
  "beat": {
    "version": "7.0.0-alpha1",
    "name": "9199ec4ac46e",
    "hostname": "9199ec4ac46e"
  },
  "host": {
    "name": "9199ec4ac46e"
  }
}
2018-08-27T10:03:34.200Z	DEBUG	[file_integrity]	file_integrity/metricset.go:252	File changed since it was last seen	{"file_path": "/tmp/tmpQxnEGoauditbeat_test/subdir/file.txt", "took": 86080, "event": {"old": null, "new": {"timestamp":"2018-08-27T10:03:34.199239384Z","path":"/tmp/tmpQxnEGoauditbeat_test/subdir/file.txt","info":{"inode":89604204,"uid":0,"gid":0,"sid":"","owner":"root","group":"root","size":12,"mtime":"2018-08-27T10:03:34.194946251Z","ctime":"2018-08-27T10:03:34.194946251Z","type":"file","mode":420,"setuid":false,"setgid":false,"origin":null},"source":"fsnotify","action":"created","hash":{"sha1":"430ce34d020724ed75a196dfc2ad67c77772d169"}}}}
2018-08-27T10:03:34.201Z	DEBUG	[publish]	pipeline/processor.go:308	Publish event: {
  "@timestamp": "2018-08-27T10:03:34.199Z",
  "@metadata": {
    "beat": "auditbeat",
    "type": "doc",
    "version": "7.0.0-alpha1"
  },
  "event": {
    "action": [
      "created"
    ],
    "module": "file_integrity"
  },
  "hash": {
    "sha1": "430ce34d020724ed75a196dfc2ad67c77772d169"
  },
  "file": {
    "owner": "root",
    "size": 12,
    "gid": 0,
    "ctime": "2018-08-27T10:03:34.194Z",
    "uid": 0,
    "mode": "0644",
    "inode": "89604204",
    "type": "file",
    "group": "root",
    "path": "/tmp/tmpQxnEGoauditbeat_test/subdir/file.txt",
    "mtime": "2018-08-27T10:03:34.194Z"
  },
  "beat": {
    "name": "9199ec4ac46e",
    "hostname": "9199ec4ac46e",
    "version": "7.0.0-alpha1"
  },
  "host": {
    "name": "9199ec4ac46e"
  }
}
2018-08-27T10:03:34.300Z	DEBUG	[memqueue]	memqueue/ackloop.go:160	ackloop: receive ack [0: 0, 2]
2018-08-27T10:03:34.300Z	DEBUG	[memqueue]	memqueue/eventloop.go:535	broker ACK events: count=2, start-seq=1, end-seq=2

2018-08-27T10:03:34.300Z	DEBUG	[memqueue]	memqueue/ackloop.go:128	ackloop: return ack to broker loop:2
2018-08-27T10:03:34.300Z	DEBUG	[memqueue]	memqueue/ackloop.go:131	ackloop:  done send ack
2018-08-27T10:03:44.237Z	DEBUG	[file_integrity]	file_integrity/eventreader_fsnotify.go:136	Received fsnotify event	{"file_path": "/tmp/tmpQxnEGoauditbeat_test/subdir/file.txt", "event_flags": "REMOVE"}
2018-08-27T10:03:44.237Z	DEBUG	[file_integrity]	file_integrity/eventreader_fsnotify.go:136	Received fsnotify event	{"file_path": "/tmp/tmpQxnEGoauditbeat_test/subdir", "event_flags": "REMOVE"}
2018-08-27T10:03:44.237Z	DEBUG	[file_integrity]	file_integrity/metricset.go:252	File changed since it was last seen	{"file_path": "/tmp/tmpQxnEGoauditbeat_test/subdir/file.txt", "took": 25326, "event": {"old": {"timestamp":"2018-08-27T10:03:34.199239384Z","path":"/tmp/tmpQxnEGoauditbeat_test/subdir/file.txt","info":{"inode":89604204,"uid":0,"gid":0,"sid":"","owner":"","group":"","size":12,"mtime":"2018-08-27T10:03:34.194946251Z","ctime":"2018-08-27T10:03:34.194946251Z","type":"file","mode":420,"setuid":false,"setgid":false,"origin":null},"source":"fsnotify","action":"created","hash":{"sha1":"430ce34d020724ed75a196dfc2ad67c77772d169"}}, "new": {"timestamp":"2018-08-27T10:03:44.237762994Z","path":"/tmp/tmpQxnEGoauditbeat_test/subdir/file.txt","info":null,"source":"fsnotify","action":"deleted"}}}
2018-08-27T10:03:44.238Z	DEBUG	[publish]	pipeline/processor.go:308	Publish event: {
  "@timestamp": "2018-08-27T10:03:44.237Z",
  "@metadata": {
    "beat": "auditbeat",
    "type": "doc",
    "version": "7.0.0-alpha1"
  },
  "host": {
    "name": "9199ec4ac46e"
  },
  "event": {
    "module": "file_integrity",
    "action": [
      "deleted"
    ]
  },
  "file": {
    "path": "/tmp/tmpQxnEGoauditbeat_test/subdir/file.txt"
  },
  "beat": {
    "name": "9199ec4ac46e",
    "hostname": "9199ec4ac46e",
    "version": "7.0.0-alpha1"
  }
}
2018-08-27T10:03:44.239Z	DEBUG	[file_integrity]	file_integrity/metricset.go:252	File changed since it was last seen	{"file_path": "/tmp/tmpQxnEGoauditbeat_test/subdir", "took": 6697, "event": {"old": {"timestamp":"2018-08-27T10:03:34.198732133Z","path":"/tmp/tmpQxnEGoauditbeat_test/subdir","info":{"inode":89604202,"uid":0,"gid":0,"sid":"","owner":"","group":"","size":0,"mtime":"1970-01-01T00:00:00Z","ctime":"1970-01-01T00:00:00Z","type":"dir","mode":493,"setuid":false,"setgid":false,"origin":null},"source":"fsnotify","action":"created"}, "new": {"timestamp":"2018-08-27T10:03:44.237815106Z","path":"/tmp/tmpQxnEGoauditbeat_test/subdir","info":null,"source":"fsnotify","action":"deleted"}}}
2018-08-27T10:03:44.239Z	DEBUG	[publish]	pipeline/processor.go:308	Publish event: {
  "@timestamp": "2018-08-27T10:03:44.237Z",
  "@metadata": {
    "beat": "auditbeat",
    "type": "doc",
    "version": "7.0.0-alpha1"
  },
  "event": {
    "module": "file_integrity",
    "action": [
      "deleted"
    ]
  },
  "file": {
    "path": "/tmp/tmpQxnEGoauditbeat_test/subdir"
  },
  "beat": {
    "version": "7.0.0-alpha1",
    "name": "9199ec4ac46e",
    "hostname": "9199ec4ac46e"
  },
  "host": {
    "name": "9199ec4ac46e"
  }
}
```

**Comment by andrewkroh** [comment] 2018-08-27 18:34
This looks like a duplicate of #7731.

**Closed by andrewkroh** 2018-08-27 18:34 UTC
Labels: :Testing, Auditbeat, flaky-test, review

**Comment by ruflin** [comment] 2018-08-27 19:27
it is. I searched for the title and couldn't find one. I should improve the title of the other one.
