### ISSUE TITLE
add_kubernetes_metadata processor is skipping records

### ISSUE THREAD

**Issue by felipejfc** [elastic/beats#6042] opened 2018-01-10 22:58 UTC
- Version: 6.1.1
- Operating System: minikube
- Steps to Reproduce: deploy filebeat into minikube with the following config:
```
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: kube-system
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
data:
  filebeat.yml: |-
    filebeat.config:
      prospectors:
        path: ${path.config}/prospectors.d/*.yml
        reload.enabled: false
      modules:
        path: ${path.config}/modules.d/*.yml
        reload.enabled: false
    setup.template:
      name: "template-stash-filebeat"
      pattern: "kstash-*"
    output.elasticsearch:
      index: "kstash-%{[kubernetes.namespace]}-%{+yyyy.MM.dd}"
      hosts: ['${ELASTICSEARCH_HOST:elasticsearch}:${ELASTICSEARCH_PORT:9200}']
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-prospectors
  namespace: kube-system
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
data:
  kubernetes.yml: |-
    - type: docker
      containers.ids:
      - "*"
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
---
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    k8s-app: filebeat
    kubernetes.io/cluster-service: "true"
spec:
  template:
    metadata:
      labels:
        k8s-app: filebeat
        kubernetes.io/cluster-service: "true"
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:6.1.1
        args: [
          "-c", "/etc/filebeat.yml",
          "-d", "publish",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: elasticsearch-stag.xxxxx.com
        - name: ELASTICSEARCH_PORT
          value: "9200"
        securityContext:
          runAsUser: 0
        resources: {}
        #  limits:
        #    memory: 200Mi
        #  requests:
        #    cpu: 100m
        #    memory: 100Mi
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: prospectors
          mountPath: /usr/share/filebeat/prospectors.d
          readOnly: true
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: filebeat-config
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: prospectors
        configMap:
          defaultMode: 0600
          name: filebeat-prospectors
      - name: data
        emptyDir: {}
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: filebeat
subjects:
- kind: ServiceAccount
  name: filebeat
  namespace: kube-system
roleRef:
  kind: ClusterRole
  name: filebeat
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: filebeat
  labels:
    k8s-app: filebeat
rules:
- apiGroups: [""] # "" indicates the core API group
  resources:
  - namespaces
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filebeat
  namespace: kube-system
  labels:
    k8s-app: filebeat
---
```

I'm trying filebeat in minikube and hit this problem, it seems that docker prospector/kubernetes_add_metadata is not adding the metadata to some records:

```
filebeat-4q2x2 filebeat 2018/01/09 22:33:22.608847 processor.go:275: DBG [publish] Publish event: {
filebeat-4q2x2 filebeat   "@timestamp": "2017-12-18T20:27:56.029Z",
filebeat-4q2x2 filebeat   "@metadata": {
filebeat-4q2x2 filebeat     "beat": "filebeat",
filebeat-4q2x2 filebeat     "type": "doc",
filebeat-4q2x2 filebeat     "version": "6.1.1"
filebeat-4q2x2 filebeat   },
filebeat-4q2x2 filebeat   "beat": {
filebeat-4q2x2 filebeat     "name": "filebeat-4q2x2",
filebeat-4q2x2 filebeat     "hostname": "filebeat-4q2x2",
filebeat-4q2x2 filebeat     "version": "6.1.1"
filebeat-4q2x2 filebeat   },
filebeat-4q2x2 filebeat   "offset": 49589,
filebeat-4q2x2 filebeat   "stream": "stdout",
filebeat-4q2x2 filebeat   "message": "2017/12/18 20:27:56 Metric client health check failed: the server could not find the requested resource (get services heapster). Retrying in 30 seconds.",
filebeat-4q2x2 filebeat   "source": "/var/lib/docker/containers/7874a93a424f7358babb07dfe1b412041fbc8bdc42aa0a4927330bca52d22e18/7874a93a424f7358babb07dfe1b412041fbc8bdc42aa0a4927330bca52d22e18-json.log",
filebeat-4q2x2 filebeat   "prospector": {
filebeat-4q2x2 filebeat     "type": "docker"
filebeat-4q2x2 filebeat   }
```

this logs comes from a container that is running inside kubernetes and I have docker prospector with the following config:
```
    - type: docker
      containers.ids:
      - "*"
      processors:
        - add_kubernetes_metadata:
            in_cluster: true
```

some other events are being updated with kubernetes metadata:

```
filebeat-4q2x2 filebeat 2018/01/09 22:33:22.608682 processor.go:275: DBG [publish] Publish event: {
filebeat-4q2x2 filebeat   "@timestamp": "2018-01-08T19:23:09.797Z",
filebeat-4q2x2 filebeat   "@metadata": {
filebeat-4q2x2 filebeat     "beat": "filebeat",
filebeat-4q2x2 filebeat     "type": "doc",
filebeat-4q2x2 filebeat     "version": "6.1.1"
filebeat-4q2x2 filebeat   },
filebeat-4q2x2 filebeat   "beat": {
filebeat-4q2x2 filebeat     "version": "6.1.1",
filebeat-4q2x2 filebeat     "name": "filebeat-4q2x2",
filebeat-4q2x2 filebeat     "hostname": "filebeat-4q2x2"
filebeat-4q2x2 filebeat   },
filebeat-4q2x2 filebeat   "offset": 31227,
filebeat-4q2x2 filebeat   "stream": "stdout",
filebeat-4q2x2 filebeat   "message": "INFO: == Kubernetes addon reconcile completed at 2018-01-08T19:23:09+0000 ==",
filebeat-4q2x2 filebeat   "source": "/var/lib/docker/containers/c7abd804756ada3a1c9e3b13aa1ce6076e86a042048692792f3222045016c13a/c7abd804756ada3a1c9e3b13aa1ce6076e86a042048692792f3222045016c13a-json.log",
filebeat-4q2x2 filebeat   "prospector": {
filebeat-4q2x2 filebeat     "type": "docker"
filebeat-4q2x2 filebeat   },
filebeat-4q2x2 filebeat   "kubernetes": {
filebeat-4q2x2 filebeat     "namespace": "kube-system",
filebeat-4q2x2 filebeat     "labels": {
filebeat-4q2x2 filebeat       "component": "kube-addon-manager",
filebeat-4q2x2 filebeat       "kubernetes.io/minikube-addons": "addon-manager",
filebeat-4q2x2 filebeat       "version": "v6.4"
filebeat-4q2x2 filebeat     },
filebeat-4q2x2 filebeat     "container": {
filebeat-4q2x2 filebeat       "name": "kube-addon-manager"
filebeat-4q2x2 filebeat     },
filebeat-4q2x2 filebeat     "pod": {
filebeat-4q2x2 filebeat       "name": "kube-addon-manager-minikube"
filebeat-4q2x2 filebeat     }
filebeat-4q2x2 filebeat   }
```

**Comment by felipejfc** [comment] 2018-01-10 23:05
investigating this a little bit, it seems to happen when the container that the log is being read does not exists anymore into kubernetes, then metadata is not added to log and because of that my index that's configured like:
index: "kstash-%{[kubernetes.namespace]}-%{+yyyy.MM.dd}"

is not working, it sends a empty string to elasticsearch and then all bulk inserts are failing...

**Comment by exekias** [comment] 2018-01-15 18:49
You guessed correctly :1st_place_medal:, we cannot add metadata for containers that are no longer running, so we ship the logs without annotations, there are several things that you could do here:

* Use autodiscover to send logs from running containers only.
* Use drop_event to remove logs without metadata
* Use `indices` setting, so you get the chance to define a default in case namespace is not there: https://www.elastic.co/guide/en/beats/filebeat/current/elasticsearch-output.html#_literal_indices_literal

PD: I find the idea of using one index per namespace very interesting, thank you for sharing that!

**Comment by ruflin** [comment] 2018-01-16 01:34
@exekias For containers that are no longer running, could we have some "expiry" time of the meta data that can be configurable. Assuming for the logs, because of the output blocked we didn't read all the log lines of a file when the container was running. When the output comes available again 1 minute later, we still have the meta data in memory even though the container was stopped.

**Comment by exekias** [comment] 2018-01-16 10:30
We have that in place already, the issue normally comes from containers that died **before** filebeat starts but still have log in the filesystem

**Comment by ruflin** [comment] 2018-01-16 23:51
@exekias Awesome as usual 🎉

**Comment by bschaeffer** [comment] 2019-06-13 16:09
> it may also happen if we read a line before processing metadata for a new container, but that's unlikely.

@exekias I have almost gone insane because of this exact issue. We are [running a load test][forum post] and I was consistently seeing lines from the head of the first files filebeat saw being dropped. I just couldn't figure out what was wrong until it dawned on me the my drop filter on the kubernetes label was the cause and realized the processor had to be to blame.

I thought maybe a switch to using a autodiscovery would help but I am blocked by #11834 and the fact that file beat is now sending duplicate lines.

Our load test is a pretty accurate depiction of our current logging situation, so it is the opposite of rare that filebeat might see lines for containers it hasn't received metadata about yet.

What do you think about an initial, blocking fetch when the `add_kubernetes_metadata` sees new containers it hasn't gotten metadata about? 

[forum post]: https://discuss.elastic.co/t/filebeat-reliably-dropping-lines-from-head-of-first-new-files-it-sees-during-load-testing/185508

**Comment by exekias** [comment] 2019-06-14 10:12
> What do you think about an initial, blocking fetch when the `add_kubernetes_metadata` sees new containers it hasn't gotten metadata about?

Processors blocking the input can become an issue in many cases, so we would prefer to avoid that.

I think autodiscover is the good fit for this :slightly_smiling_face:, we should probably focs un getting #11834 fixed

**Comment by amoskyler** [comment] 2019-06-27 21:45
I am also seeing this issue. I routinely see ~10k untagged logs a day due to 1. recently started containers and 2. recently terminated containers.

I'm a bit confused how autodiscover may help solve this issue (contigent on #11834). Is anybody willing to help explain?

Thanks!

**Comment by bschaeffer** [comment] 2019-06-27 21:49
@amoskyler It's my understanding that k8s auto-discovery triggers the following of the actual log files, and given that, the metadata will be present from line one, so, if like me, you're dropping logs on purpose which are missing that metadata, you shouldn't have the problem with auto discovery...?

**Comment by amoskyler** [comment] 2019-06-27 21:55
Ah interesting, thanks for explaining! This does seem like it would resolve my issue..

My situation is a _bit_ different as I don't drop the logs, but they get dropped into a somewhat useless "uncategorized" catalog and lose their use to users/applications which consume from ES.

In the case of k8s autodiscovery, does it directly pull the logs from k8s using the API? Or does it simply use the API to determine log file paths?

**Comment by bschaeffer** [comment] 2019-10-22 00:35
> My situation is a _bit_ different as I don't drop the logs, but they get pushed into a somewhat useless "uncategorized" index and lose their use to users/applications which consume from ES.
Same here.

> In the case of k8s autodiscovery, does it directly pull the logs from k8s using the API? Or does it simply use the API to determine log file paths?

It gets metadata about the container, and, since container logs by id are in a well known location, we can start a harvester pointing at those log files. So, essentially, autodiscover is almost the same as scrapping `/var/lib/docker/container` logs every `X` seconds, except instead of scraping the dir, we are trusting the k8s watch API to notify us when a new container (and therefor log file) is ready to be ingested.

**Comment by exekias** [comment] 2019-12-20 10:24
closing this issue as autodiscover is the recommended way to avoid this

**Closed by exekias** 2019-12-20 10:24 UTC
Labels: Filebeat

**Comment by praveenkumarp893** [comment] 2020-05-13 09:50
Hi,

I am also facing the same issue where for some logs the kubernetes metadata is getting skipped and it is coming as filebeats in kibana.
I have also added the processor - add_kubernetes_metadata.
Can someone help here please.

Many Thanks,
Praveen
