### ISSUE TITLE
[Fleet] Add support for proxy in Elastic Agent

### ISSUE THREAD

**Issue by mostlyjason** [elastic/beats#25319] opened 2021-03-24 13:53 UTC
We've gotten a few requests from users of Elastic Agent to add support for proxy URLs in the output. Apparently, a user tried adding the `proxy_url` setting in the YAML output settings in Fleet settings but it did not work. 

This could have the same behavior as `proxy_url` in [Filebeat](https://www.elastic.co/guide/en/beats/filebeat/current/elasticsearch-output.html#_proxy_url). This could initially be done in the YAML configuration because this is an advanced setting. We could add UI support later.

Elastic Agent should also be able to communicate with Fleet Server through a proxy. This allows Fleet Server to run in a central location, while Elastic Agent is running on the edge behind a proxy. 

As an Elastic Agent user, I want the ability to:
- [x] Set a proxy url in the ES output of my standalone agent policy
- [x] Set a proxy url in my Kibana Fleet settings for the ES output 
- [ ] Set a proxy url for Elastic Agent to communicate with Fleet Server
- [ ] Set a proxy url in my Kibana Fleet settings for the Fleet Server connection

Non-goals (deferred to later):
- Set a proxy for Fleet Server to communicate with Elasticsearch

**Comment by ph** [comment] 2021-04-27 18:11
Closing as duplicate of https://github.com/elastic/beats/issues/25021

**Closed by ph** 2021-04-27 18:11 UTC
Labels: Team:Agent, v7.14.0
