### ISSUE TITLE
Pipeline doesn't work in Filebeats Alpha 3

### ISSUE THREAD

**Issue by petercort** [elastic/beats#1962] opened 2016-07-05 13:54 UTC
Running Filebeats Alpha 3 passing directly to an Elasticsearch Alpha 3 installation. See the discussion on the forums: https://discuss.elastic.co/t/pipeline-not-working-filebeats-elasticsearch-5-0-0-alpha-3/54197/10

The same configuration works fine with a Filebeats Alpha 2 installation, but not 3.

**Comment by tsg** [comment] 2016-07-13 09:49
@petercort I couldn't reproduce this with either alpha3 or alpha4. This is the config I used:

```
output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["localhost:9200"]

  parameters:
    pipeline: alpha3
```

And this is what I see with ngrep:

```
T ::1:64353 -> ::1:9200 [AP]
  POST /_bulk?pipeline=alpha3 HTTP/1.1..Host: localhost:9200..User-Agent: Go-http-client/1
  .1..Content-Length: 17291..Accept: application/json..Accept-Encoding: gzip....{"index":{
  "_index":"filebeat-2016.07.13","_type":"log"}}.{"@timestamp":"2016-07-13T09:47:26.611Z",
  "beat":{"hostname":"Tudors-MacBook-Pro.local","name":"Tudors-MacBook-Pro.local"},"input_
  type":"log","message":"\t`
```

Can you perhaps post your full config and steps to reproduce?

**Comment by urso** [comment] 2016-07-13 14:14
Also tested with master.

My pipeline config:
```
{
    "description": "Test pipeline",
    "processors": [
        {
            "lowercase": {
                "field": "beat.name"
            }
        }
    ]
}
```

and filebeat config:
```
filebeat.prospectors:
- input_type: log
  paths:
    - tmp/nasa/*.log

output.elasticsearch:
  hosts: ["192.168.99.100"]
  parameters.pipeline: "test-pipeline"

name: ABC
```

The `beat.name` is correctly modified by elasticsearch:
```
{
        "_source" : {
          "@timestamp" : "2016-07-13T14:10:17.818Z",
          "offset" : 5598,
          "beat" : {
            "hostname" : "X",
            "name" : "abc"
          },
          "input_type" : "log",
          "source" : "tmp/nasa/access.log",
          "message" : "205.212.115.106 - - [01/Jul/1995:00:01:13 -0400] \"GET /shuttle/missions/sts-71/images/images.html HTTP/1.0\" 200 7634",
          "type" : "log"
        }
      },
```

**Comment by petercort** [comment] 2016-07-19 12:53
I was on vacation last week so I'll test today and update with my findings.

**Comment by tsg** [comment] 2016-07-19 21:44
Hmm, 404 is not expected. Can you somehow copy & paste the request/response pair from wireshark, please? Or upload the trace somewhere.

**Comment by tsg** [comment] 2016-08-23 13:19
Closing this one, as we could never reproduce it. We suspect it was either a configuration error or something that got fixed in the newer alpha versions. In addition, alpha5 adds a different mechanism for configuring the pipeline.

**Closed by tsg** 2016-08-23 13:19 UTC
Labels: bug, libbeat, needs details, Pioneer Program, v5.0.0-beta1

**Comment by bessonovevgen** [comment] 2017-10-11 09:59
Hello.
Beats version 5.6.3 from deb repo on Ubuntu 16.04 not placed data in pipeline with config from [docs](https://www.elastic.co/guide/en/beats/filebeat/current/configuring-ingest-node.html) 

![image](https://user-images.githubusercontent.com/18403194/31433933-8e3ebc56-ae83-11e7-862f-03bb48c90d32.png)

but if i change parametrs to 

output.elasticsearch:
  # Array of hosts to connect to.
  hosts: ["localhost:9200"]
  properties.pipeleine: "onec_pipeline"

it works fine.



----
Sorry, for my bad English
