### ISSUE TITLE
[Metricbeat] Flaky test_couchbase.Test.test_couchbase_0_bucket

### ISSUE THREAD

**Issue by ph** [elastic/beats#7769] opened 2018-07-26 20:19 UTC
link: https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-linux/5782/beat=metricbeat,label=ubuntu/testReport/junit/test_couchbase/Test/test_couchbase_0_bucket/
platform: linux
```
Element counts were not equal:
First has 1, Second has 0:  'couchbase'
First has 0, Second has 1:  u'error'
-------------------- >> begin captured stdout << ---------------------
{u'beat': {u'hostname': u'2fcadc37c9ec', u'name': u'2fcadc37c9ec', u'version': u'7.0.0-alpha1'}, u'@timestamp': u'2018-07-26T19:19:27.848Z', u'host': {u'name': u'2fcadc37c9ec'}, u'error': {u'message': u'HTTP error 401 in bucket: 401 Unauthorized'}, u'metricset': {u'rtt': 6355, u'host': u'couchbase:8091', u'name': u'bucket', u'module': u'couchbase'}}

--------------------- >> end captured stdout << ----------------------
-------------------- >> begin captured logging << --------------------
compose.config.config: DEBUG: Using configuration files: ./docker-compose.yml
docker.utils.config: DEBUG: Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
docker.utils.config: DEBUG: No config file found
docker.utils.config: DEBUG: Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
docker.utils.config: DEBUG: No config file found
compose.parallel: DEBUG: Pending: set([<Container: metricbeat17e29fb47ee56c6580032e2f535818f05f192ae4_mongodb_1 (14feab)>])
compose.parallel: DEBUG: Starting producer thread for <Container: metricbeat17e29fb47ee56c6580032e2f535818f05f192ae4_mongodb_1 (14feab)>
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Finished processing: <Container: metricbeat17e29fb47ee56c6580032e2f535818f05f192ae4_mongodb_1 (14feab)>
compose.parallel: DEBUG: Pending: set([])
compose.config.config: DEBUG: Using configuration files: ./docker-compose.yml
docker.utils.config: DEBUG: Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
docker.utils.config: DEBUG: No config file found
docker.utils.config: DEBUG: Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
docker.utils.config: DEBUG: No config file found
compose.service: INFO: Building couchbase
docker.api.build: DEBUG: Looking for auth config
docker.api.build: DEBUG: No auth config in memory - loading from filesystem
docker.utils.config: DEBUG: Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
docker.utils.config: DEBUG: No config file found
docker.api.build: DEBUG: No auth config found
compose.parallel: DEBUG: Pending: set([<Service: couchbase>])
compose.parallel: DEBUG: Starting producer thread for <Service: couchbase>
compose.parallel: DEBUG: Pending: set([ServiceName(project='metricbeat17e29fb47ee56c6580032e2f535818f05f192ae4', service='couchbase', number=1)])
compose.parallel: DEBUG: Starting producer thread for ServiceName(project='metricbeat17e29fb47ee56c6580032e2f535818f05f192ae4', service='couchbase', number=1)
compose.service: DEBUG: Added config hash: 35e2347d8dc619864aa81fd019891e9aff24166ad342271b2305019314494b3a
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Finished processing: ServiceName(project='metricbeat17e29fb47ee56c6580032e2f535818f05f192ae4', service='couchbase', number=1)
compose.parallel: DEBUG: Pending: set([])
compose.parallel: DEBUG: Finished processing: <Service: couchbase>
compose.parallel: DEBUG: Pending: set([])
--------------------- >> end captured logging << ---------------------

Stacktrace
````

**Comment by ruflin** [comment] 2018-07-27 06:31
Duplicate of https://github.com/elastic/beats/issues/7683 ?

**Comment by ruflin** [comment] 2018-07-27 06:31
@ph Closing, please reopen if you think differently.

**Comment by ph** [comment] 2018-07-27 13:36
I've relooked at this again, seems to be the same error.

**Comment by jsoriano** [comment] 2018-11-13 11:02
Reopening and seems to be still happening.

**Closed** 2018-11-14 09:48 UTC
Labels: :Testing, Metricbeat, flaky-test
