### ISSUE TITLE
There is an issue where the filebeat registry file is deleted.

### ISSUE THREAD

**Issue by hc0105** [elastic/beats#19634] opened 2020-07-03 08:24 UTC
There is an issue where the filebeat registry file is deleted.
I found it while tracing the log duplication issue.

- Version: 6.3.0
- Operating System: Windows 2012 R2
- Discuss Forum URL: 
- Steps to Reproduce: 

1. Register filebeat on Windows service
2. Start the filebeat service.
3. Terminates filebeat windows service registered during filebeat log transmission. (process kill:X, windows service termination:O)
4. Repeat steps 1~3 (In my case, about 10 times)

※ Cause 
Registry file was deleted intermittently when shutting down filebeat service.

When flushing the registry,
If the filebeat service is terminated while executing the below code of the SafeFileRotate function

```
////////////////////// flushRegistry->writeRegistry->SafeFileRotate ////////////////////////
	if e = os.Rename(tempfile, path); e != nil {
		return e
	}
////////////////////////////////////////////////////////////////////////////////////////////
```
	
The process ends with the registry deleted.
There is no registry when restarting filebeat, so the log is resent from the beginning

※ My Solution
If there is no registry file when starting filebeat
Attempts to recover in below order.
registry.new -> registry.old

※ Question
If there is no registry file when starting filebeat, and there is only registry.new file
Is there any problem when restoring to registry.new -> registry?

As in the modified code below

```
////////////////////////////////////////////////////////////////////////////////////////////
// modify code (registry)
////////////////////////////////////////////////////////////////////////////////////////////

func (r *Registrar) Init() error {
	// The registry file is opened in the data path
	r.registryFile = paths.Resolve(paths.Data, r.registryFile)

	// Create directory if it does not already exist.
	registryPath := filepath.Dir(r.registryFile)
	err := os.MkdirAll(registryPath, 0750)
	if err != nil {
		return fmt.Errorf("Failed to created registry file dir %s: %v", registryPath, err)
	}

	// Check if files exists
	fileInfo, err := os.Lstat(r.registryFile)
	if os.IsNotExist(err) {
		logp.Info("No registry file found under: %s", r.registryFile)
		// No registry exists yet, write empty state to check if registry can be written

		recoverFile := r.registryFile + ".new"
		_, recoverErr := os.Lstat(recoverFile)
		logp.Debug("registrar", "Recover registry file: %s", recoverFile)

		if os.IsNotExist(recoverErr) {
			logp.Info("No registry.new file found under: %s", recoverFile)
			return r.writeRegistry()
		} else {
			if err = os.Rename(recoverFile, r.registryFile); err != nil {
				return err
			}
		}
	}

	if err != nil {
		return err
	}

	// Check if regular file, no dir, no symlink
	if !fileInfo.Mode().IsRegular() {
		// Special error message for directory
		if fileInfo.IsDir() {
			return fmt.Errorf("Registry file path must be a file. %s is a directory.", r.registryFile)
		}
		return fmt.Errorf("Registry file path is not a regular file: %s", r.registryFile)
	}

	logp.Debug("registrar", "Registry file set to: %s", r.registryFile)

	return nil
}
```

**Comment by jsoriano** [comment] 2020-07-03 16:05
Hi @hc0105,

In general we prefer to discuss non confirmed issue and questions in https://discuss.elastic.co/c/elastic-stack/beats/28, so next time please create first a topic there before opening an issue here :slightly_smiling_face: 

Regarding this issue, I am not sure of understanding. Do you mean that you see this happening in your systems on a normal shutdown? or this is something that could happen if filebeat is unexpectedly killed before renaming the registry file?

In any case since 6.3.0 there have been several refactors in the registry, and more are in progress, so you might find and improved behaviour in more current versions. Could you please upgrade filebeat to 6.8 or 7.x and check if you still have issues?

**Comment by hc0105** [comment] 2020-07-06 01:29
It seems to occur when the filebeat terminated unexpectedly.
I did not run the latest version of the file bit directly, 
but I am using "SafeFileRotate() -> os.Rename" in the latest version, and it is expected to happen if it ends unexpectedly at that time.

**Comment by urso** [comment] 2020-07-06 12:35
If there is a `registry.new` in the directory, then a former rotation was not completed. This can happen if filebeat was force killed during the rename process. But sometimes anti-virus can be a problem. If AV is acessing the registry file it can't be deleted (or renamed too) and the operation might fail. Some later update to the registry might fix this, but bad timing can lead to the rename failing as well. This is especially a problem on windows.

We are currently reworking the registry. One change the rework includes is that we will not overwrite old files anymore. Instead a new file with an update-sequence-counter (becomes part of the file name) will be created (files have some ordering). If the writing did fail in the last step we still have the last state to continue from. If AV is preventing us from deleting the old file we will try again in the future (deletion of old files will only happen after the new file is written).

**Comment by andresrc** [comment] 2020-07-06 16:16
Closing this for now.

**Closed by andresrc** 2020-07-06 16:16 UTC
Labels: Filebeat, Team:Services, [zube]: Inbox
