### ISSUE TITLE
Keep getting "ERROR kubernetes/watcher.go:258 kubernetes: Watching API error EOF"

### ISSUE THREAD

**Issue by vrathore18** [elastic/beats#19202] opened 2020-06-15 17:33 UTC
I am using filebeat for sending our application log to Kibana. The version I am using is 
`docker.elastic.co/beats/filebeat:6.6.2`

but this error keeps coming
`ERROR	kubernetes/watcher.go:258	kubernetes: Watching API error EOF`

Saw some of the old similar bugs but the issue is not fixed as said. Please don't close this one before testing.

**Comment by andresrc** [comment] 2020-06-23 15:01
Are you able to reproduce this behaviour in 6.8.10 or 7.8.0? Thanks!

**Comment by vrathore18** [comment] 2020-06-24 11:00
@andresrc : I can't use 6.8.10 as my elastic search version is 6.4.2. and When I try to use 6.8.10. I started getting below error(which I was not getting when using 6.6.2):

```
Failed to connect to backoff(elasticsearch(https://xxxxxxxxxxxxxxxx.es.amazonaws.com)): Connection marked as failed because the onConnect callback failed: cannot retrieve the elasticsearch license: unauthorized access, could not connect to the xpack endpoint, verify your credentials
2020-06-24T10:59:12.856Z        INFO    pipeline/output.go:93   Attempting to reconnect to backoff(elasticsearch(https://xxxxxxxxxxxxxxxxx.es.amazonaws.com)) with 20 reconnect attempt(s)
```

**Comment by andresrc** [comment] 2020-06-30 14:55
Are you using the default distribution for the OSS-only one? (asking for both ES and filebeat)

**Comment by QuincyC379** [comment] 2020-07-25 11:45
I encountered the same issue,please help,thank you so much :
**INFO pipeline/output.go:93 Attempting to reconnect to backoff(elasticsearch(http://172.28.252.21:19200)) with 9 reconnect attempt(s)**
I verified the xpack  from the inside of k8s, no problem at all ,no idea what is going on 。

**Comment by QuincyC379** [comment] 2020-07-26 06:22
we solved this prolem by upgrading the version of filebeat,perfect plan!

**Comment by QuincyC379** [comment] 2020-07-26 06:23
We solved this prolem by upgrading the version of filebeat images,perfect!

**Comment by sirianni** [comment] 2021-05-04 19:57
Seeing this error with `filebeat-oss:7.12.0`

**Comment by Jacendb** [comment] 2022-04-12 14:49
Currently seeing this same issue and it might be the reason we are missing data in our ES cluster.
Any suggestion on how to fix it?
filebeat-oss-6.4.23
EKS kube version 1.20
Logstash 6.8.23
AWS Open search 6.8.

**Comment by ChrsMark** [comment] 2022-04-12 15:53
`6.4.23` is quite old. Please upgrade to a newer version like `7.17.0`  and let us know if the issue persists.

**Comment by ChrsMark** [comment] 2022-04-28 09:07
Closing for now, we can re-open if we have more details on this.

**Closed by ChrsMark** 2022-04-28 09:07 UTC
Labels: Team:Platforms
