### ISSUE TITLE
Convert processor cannot be used in autodiscover hints

### ISSUE THREAD

**Issue by ChrsMark** [elastic/beats#17074] opened 2020-03-18 08:22 UTC
- Version: 7.6, 7.5
- Steps to Reproduce: 

Hints based autodiscover fails to load `convert` configuration if passed with annotation like this:
`co.elastic.logs/processors.0.convert: '{"fields": [{"from": "error", "to": "error.message"}]}'`.

It fails with:
```
ERROR   [autodiscover]  cfgfile/list.go:96      Error creating runner from config: can not convert 'string' into 'object' accessing 'processors.0.convert
```

It is not able to reproduce it with `master`.

cc: @david-kow

**Comment by blakerouse** [comment] 2020-03-18 16:14
Looks to be a duplicate of #16343.

**Comment by ChrsMark** [comment] 2020-03-18 16:57
Oh nice, shall we backport #16343 then to `7.6` too? 

cc: @exekias @andresrc

**Comment by ChrsMark** [comment] 2020-03-24 13:22
@david-kow I don't think we will have any more 7.6.x releases, so it is expected to be fixed with 7.7.

cc: @exekias @andresrc

**Comment by david-kow** [comment] 2020-03-24 13:42
@ChrsMark Got it, thanks for the update.

**Closed** 2020-03-24 13:47 UTC
Labels: Team:Platforms, [zube]: Inbox, autodiscovery, bug
