### ISSUE TITLE
[elastic-agent] in windows got some flakiness tests for TestActionStore/TestReplaceOrRollbackStore/TestDiskStore

### ISSUE THREAD

**Issue by v1v** [elastic/beats#19789] opened 2020-07-09 14:21 UTC
## Flaky Test

* **Test Name:** TestActionStore/TestReplaceOrRollbackStore/TestDiskStore
* **Branch:** https://github.com/elastic/beats/pull/19773
* **Artifact Link:** https://gist.github.com/v1v/eac48c1ccd86f68f54c0a8f9302f8abb
* **Notes:** 

### Stack Trace

```
C:\Users\jenkins\workspace\Beats_beats-windows-mbp_PR-19773\src\github.com\elastic\beats\x-pack\elastic-agent>mage  build unitTest 
14:42:59  go version go1.13.10 windows/amd64

14:44:22  --- FAIL: TestActionStore (0.04s)
14:44:22      --- PASS: TestActionStore/action_returns_empty_when_no_action_is_saved_on_disk (0.00s)
14:44:22      --- PASS: TestActionStore/will_discard_silently_unknown_action (0.00s)
14:44:22      --- FAIL: TestActionStore/can_save_to_disk_known_action_type (0.01s)
14:44:22          action_store_test.go:75: 
14:44:22              	Error Trace:	action_store_test.go:75
14:44:22              	            				action_store_test.go:29
14:44:22              	Error:      	Received unexpected error:
14:44:22              	            	could not replace target file C:\Users\JENKIN~1.PAC\AppData\Local\Temp\action-store379160453\config.yml: rename C:\Users\JENKIN~1.PAC\AppData\Local\Temp\action-store379160453\config.yml.tmp C:\Users\JENKIN~1.PAC\AppData\Local\Temp\action-store379160453\config.yml: Access is denied.
14:44:22              	Test:       	TestActionStore/can_save_to_disk_known_action_type
14:44:22      --- FAIL: TestActionStore/when_we_ACK_we_save_to_disk (0.01s)
14:44:22          action_store_test.go:101: 
14:44:22              	Error Trace:	action_store_test.go:101
14:44:22              	            				action_store_test.go:29
14:44:22              	Error:      	Received unexpected error:
14:44:22              	            	could not replace target file C:\Users\JENKIN~1.PAC\AppData\Local\Temp\action-store932123936\config.yml: rename C:\Users\JENKIN~1.PAC\AppData\Local\Temp\action-store932123936\config.yml.tmp C:\Users\JENKIN~1.PAC\AppData\Local\Temp\action-store932123936\config.yml: Access is denied.
14:44:22              	Test:       	TestActionStore/when_we_ACK_we_save_to_disk

14:44:29  --- FAIL: TestReplaceOrRollbackStore (0.03s)
14:44:29      --- FAIL: TestReplaceOrRollbackStore/when_the_save_is_successful_with_target_and_source_don't_match (0.02s)
14:44:29          storage_test.go:56: 
14:44:29              	Error Trace:	storage_test.go:56
14:44:29              	Error:      	Not equal: 
14:44:29              	            	expected: 0x180
14:44:29              	            	actual  : 0x1b6
14:44:29              	Test:       	TestReplaceOrRollbackStore/when_the_save_is_successful_with_target_and_source_don't_match
14:44:29      --- PASS: TestReplaceOrRollbackStore/when_save_is_not_successful (0.00s)
14:44:29      --- FAIL: TestReplaceOrRollbackStore/when_save_is_successful_with_target_and_source_content_match (0.00s)
14:44:29          storage_test.go:109: 
14:44:29              	Error Trace:	storage_test.go:109
14:44:29              	Error:      	Not equal: 
14:44:29              	            	expected: 0x180
14:44:29              	            	actual  : 0x1b6
14:44:29              	Test:       	TestReplaceOrRollbackStore/when_save_is_successful_with_target_and_source_content_match
...
14:44:29  --- FAIL: TestDiskStore (0.04s)
14:44:29      --- FAIL: TestDiskStore/when_the_target_file_already_exists (0.04s)
14:44:29          storage_test.go:142: 
14:44:29              	Error Trace:	storage_test.go:142
14:44:29              	Error:      	Not equal: 
14:44:29              	            	expected: 0x180
14:44:29              	            	actual  : 0x1b6
14:44:29              	Test:       	TestDiskStore/when_the_target_file_already_exists
14:44:29      --- FAIL: TestDiskStore/when_the_target_do_no_exist (0.00s)
14:44:29          storage_test.go:165: 
14:44:29              	Error Trace:	storage_test.go:165
14:44:29              	Error:      	Not equal: 
14:44:29              	            	expected: 0x180
14:44:29              	            	actual  : 0x1b6
14:44:29              	Test:       	TestDiskStore/when_the_target_do_no_exist
14:44:29      --- FAIL: TestDiskStore/return_an_io.ReadCloser_to_the_target_file (0.00s)
14:44:29          storage_test.go:185: 
14:44:29              	Error Trace:	storage_test.go:185
14:44:29              	Error:      	Not equal: 
14:44:29              	            	expected: 0x180
14:44:29              	            	actual  : 0x1b6
14:44:29              	Test:       	TestDiskStore/return_an_io.ReadCloser_to_the_target_file
```

**Comment by blakerouse** [comment] 2020-07-09 14:58
Its not flaky, its broken! ;-)

**Comment by v1v** [comment] 2020-07-13 11:39
I'm afraid I still see a couple of test failures:

```
 === RUN   TestActionStore/can_save_to_disk_known_action_type
     TestActionStore/can_save_to_disk_known_action_type: action_store_test.go:75: 
         	Error Trace:	action_store_test.go:75
         	            				action_store_test.go:29
         	Error:      	Received unexpected error:
         	            	could not replace target file C:\Users\JENKIN~1.PAC\AppData\Local\Temp\action-store284173813\config.yml: rename C:\Users\JENKIN~1.PAC\AppData\Local\Temp\action-store284173813\config.yml.tmp C:\Users\JENKIN~1.PAC\AppData\Local\Temp\action-store284173813\config.yml: Access is denied.
         	Test:       	TestActionStore/can_save_to_disk_known_action_type
 === RUN   TestActionStore/when_we_ACK_we_save_to_disk
     TestActionStore/when_we_ACK_we_save_to_disk: action_store_test.go:101: 
         	Error Trace:	action_store_test.go:101
         	            				action_store_test.go:29
         	Error:      	Received unexpected error:
         	            	could not replace target file C:\Users\JENKIN~1.PAC\AppData\Local\Temp\action-store091744976\config.yml: rename C:\Users\JENKIN~1.PAC\AppData\Local\Temp\action-store091744976\config.yml.tmp C:\Users\JENKIN~1.PAC\AppData\Local\Temp\action-store091744976\config.yml: Access is denied.
         	Test:       	TestActionStore/when_we_ACK_we_save_to_disk
 --- FAIL: TestActionStore (0.04s)
     --- PASS: TestActionStore/action_returns_empty_when_no_action_is_saved_on_disk (0.00s)
     --- PASS: TestActionStore/will_discard_silently_unknown_action (0.00s)
     --- FAIL: TestActionStore/can_save_to_disk_known_action_type (0.01s)
     --- FAIL: TestActionStore/when_we_ACK_we_save_to_disk (0.01s)
```

Build log details -> [here](https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats-windows-mbp/pipelines/PR-19773/runs/5/steps/1449/log/)
OS version -> `Windows-2012`, `Windows-2019` and `Windows-2016` (I guess it happens for all the windows versions anyway)
Build command -> `mage build unitTest `

**Comment by michalpristas** [comment] 2020-07-22 07:27
closing as a duplicate of https://github.com/elastic/beats/issues/19919

**Closed by michalpristas** 2020-07-22 07:27 UTC
Labels: Team:Ingest Management, flaky-test
