### ISSUE TITLE
Support hints based auto-discovery in Fleet managed agents

### ISSUE THREAD

**Issue by danielharada** [elastic/beats#28139] opened 2021-09-27 22:35 UTC
**Describe the enhancement:**
To achieve parity with Beats, the Fleet managed agents need to support hints based auto-discovery in all container inputs such as Docker and Kubernetes.

**Comment by adammike** [comment] 2021-09-28 16:35
This issue is blocking our adoption of elastic agent and elastic cloud. It's extremely urgent for our team.

**Comment by masci** [comment] 2022-02-04 09:36
Duplicate of https://github.com/elastic/beats/issues/23876

**Closed by masci** 2022-02-04 09:36 UTC
Labels: enhancement, Team:Elastic-Agent-Control-Plane, Team:Cloudnative-Monitoring
