### ISSUE TITLE
[Agent] Error 'Failed to rotate backups' displayed on installing Elastic Agent on Windows with install command 

### ISSUE THREAD

**Issue by rahulgupta-qasource** [elastic/beats#21627] opened 2020-10-07 12:41 UTC
**Kibana version:**
Kibana: 8.0.0-SNAPSHOT cloud environment with commit 6f983728d7f8c2cf065a6d5099157a5cfdc3cd08

**Elasticsearch version:**
Elasticsearch: 8.0.0-SNAPSHOT cloud environment

**Host OS and Browser version:**
Windows , All

**Original install method (e.g. download page, yum, from source, etc.):**
From 8.0.0-SNAPSHOT cloud environment

**Description**
Error is displayed in powershell on enrolling agent on Windows with install command 

**Preconditions**
1. 8.0.0-SNAPSHOT latest Kibana cloud environment should be available(commit 6f983728d7f8c2cf065a6d5099157a5cfdc3cd08).
2. Login to the above environment with elastic superuser.
3. 8.0.0 windows agent using https://snapshots.elastic.co/8.0.0-af3cda3c/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-windows-x86_64.zip file should be available. 

**Steps to Reproduce**
1. RDP to the windows endpoint 
2. Copy the above agent file and extract it under C:/Program Files
3. Navigate to C:/Program Files/ElasticAgent folder and open powershell as admin
4. Run the below command:
./elastic-agent install

5. Proceed and provide kibana url and enrollment token.
6. Observe that agent is enrolled in the UI but error is displayed in powershell.

**Test data**
N/A

**Impacted Test case id**
N/A

**Actual Result**
Error is displayed in powershell on enrolling agent on Windows with install command.

**Expected Result**
No Error should be displayed in powershell on enrolling agent on Windows with install command 

**What's working**
 - N/A

**What's not working**
 - N/A
 
**Screenshot**
![windows_powershell](https://user-images.githubusercontent.com/59917944/95332046-80a96a80-08c8-11eb-8426-fb38b9c0184a.jpg)

**Logs**
[Elastic-Agent-logs.zip](https://github.com/elastic/beats/files/5341305/Elastic-Agent-logs.zip)

**Comment by rahulgupta-qasource** [comment] 2020-10-07 12:43
@muskangulati-qasource Please review the bug.

**Comment by blakerouse** [comment] 2020-10-07 12:49
@rahulgupta-qasource Are you sure that you did not have the log open in Notepad or by another program?

**Comment by deepikakeshav-qasource** [comment] 2020-10-07 13:16
Reviewed and assigned to @EricDavisX

**Comment by EricDavisX** [comment] 2020-10-07 14:48
Assign Blake / PH to confirm who can work it

**Comment by blakerouse** [comment] 2020-10-07 15:07
I am only able to reproduce this with when I have the log file open. The error is expected in that case and it doesn't block the installation or enrollment.

**Comment by ph** [comment] 2020-10-07 15:27
I think this is a _correct_ behavior here too, @rahulgupta-qasource Can you confirm  https://github.com/elastic/beats/issues/21627#issuecomment-705000467 ?

**Comment by EricDavisX** [comment] 2020-10-07 20:27
removing 'high' impact for now, if it doesn't block install. and i don't see this on other vms.

**Comment by rahulgupta-qasource** [comment] 2020-10-08 12:59
Hi @blakerouse / @ph 

Failed to rotate backups error is still displayed when log file is not open on enrolling Windows agent. Windows agent is successfully enrolled under agents tab.

 
![failed to rotate backups](https://user-images.githubusercontent.com/59917944/95461720-31c90700-0994-11eb-841b-b0acbf1a95b2.jpg)

**Comment by blakerouse** [comment] 2020-10-12 14:33
I have been able to reproduce this. I think the issue is that enroll tries to rotate the logs while the Elastic Agent daemon is running in the background. I think that enroll should not be writing too that file at all as its a CLI command and not a daemon that should be writing to that file.

Again the error is not critical, but it does look bad.

**Closed** 2020-10-14 17:45 UTC
Labels: Team:Ingest Management, bug, v7.10.0
