### ISSUE TITLE
Files in config_dir ignored if permissions of the the files is set to 664 without an error or warning log

### ISSUE THREAD

**Issue by stefanrinderle** [elastic/beats#4187] opened 2017-05-03 13:06 UTC
The Filebeat log says "Additional configs loaded from ..." but the configs are ignored due to permissions issues and there is no ERR or WARN in the logs. After changing the permissions to 644 and restarting Filebeat, it begins to harvest the files.

- Discuss Post: https://discuss.elastic.co/t/filebeat-5-3-1-config-dir-files-needs-644-permissions/84108
- Version: Filebeat 5.3.1
- Steps to reproduce:

File in `config_dir` has the following permissions:
`-rw-rw-r-- 1 web_de tecusers 649 May  3 14:55 filebeat_blueberry_cae_a.yml`

Log after start:
```
2017-05-03T15:01:01+02:00 INFO Setup Beat: filebeat; Version: 5.3.1
2017-05-03T15:01:01+02:00 INFO Max Retries set to: 3
2017-05-03T15:01:01+02:00 INFO Activated logstash as output plugin.
2017-05-03T15:01:01+02:00 INFO Publisher name: pbdeldweb101
2017-05-03T15:01:01+02:00 INFO Flush Interval set to: 1s
2017-05-03T15:01:01+02:00 INFO Max Bulk Size set to: 2048
2017-05-03T15:01:01+02:00 INFO Additional config files are fetched from: /opt/web/filebeat/config
2017-05-03T15:01:01+02:00 INFO Additional configs loaded from: /opt/web/filebeat/config/filebeat_blueberry_cae_a.yml
2017-05-03T15:01:01+02:00 INFO filebeat start running.
2017-05-03T15:01:01+02:00 INFO No registry file found under: /opt/web/filebeat/filebeat-current/data/registry. Creating a new registry file.
2017-05-03T15:01:01+02:00 INFO Loading registrar data from /opt/web/filebeat/filebeat-current/data/registry
2017-05-03T15:01:01+02:00 INFO States Loaded from registrar: 0
2017-05-03T15:01:01+02:00 INFO Loading Prospectors: 1
2017-05-03T15:01:01+02:00 INFO Starting Registrar
2017-05-03T15:01:01+02:00 INFO Start sending events to output
2017-05-03T15:01:01+02:00 INFO Prospector with previous states loaded: 0`
```

Registry:
```
$ cat /opt/web/filebeat/filebeat-current/data/registry
[]
```

Thanks
Stefan

**Comment by ewgRa** [comment] 2017-05-25 18:15
Can't reproduce it on master.

Looks like fixed here #3572 with this commit https://github.com/elastic/beats/commit/d0e20a9fe8da09ab73c30bc6bad1faa1b91edf26

Probably can be closed as won't fix.

**Closed** 2017-05-25 18:18 UTC
Labels: Filebeat, libbeat, Metricbeat
