### ISSUE TITLE
Beats monitoring requires remote ES cluster to have monitoring enabled

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#7263] opened 2018-06-05 09:07 UTC
On 6.2, when configuring beats monitoring to send beats x-pack monitoring metrics to a remote ES cluster (eg. dedicated monitoring cluster), i.e.

```
xpack.monitoring.elasticsearch.hosts: ["http://remote_monitoring_host:port"]
xpack.monitoring.elasticsearch.username: username
xpack.monitoring.elasticsearch.password: password
```

The above only works if the remote monitoring node specified has xpack monitoring enabled on the ES side.  Note that xpack monitoring can potentially be disabled (xpack.monitoring.enabled: false) on the remote monitoring node (on the ES side before implementing beats monitoring) because the admin may not want the dedicated monitoring cluster to monitor itself (but only accept monitoring stats exported from ES production clusters).  Note that enabling xpack monitoring on the remote cluster but disabling xpack monitoring collection of stats (setting interval to -1) is not a workaround.  If you do this, the beats monitoring stats cannot be accessible from the UI since the list of clusters (entry-point) on the monitoring UI will not show the remote monitoring cluster to begin with.

If xpack monitoring is disabled on the ES side on the remote monitoring node, beats will throw a debug message `XPack monitoring is disabled` and not export stats to the remote ES node even though x-pack monitoring is enabled on the beats side.  

While we are at this, it will also be helpful if we log X-pack monitoring setup and connection issues at the WARN/INFO level (instead of at the debug level).  Currently, when Xpack monitoring is disabled on the dedicated/remote monitoring note, it continues to write "2018-06-05T01:35:17.596-0700	INFO	elasticsearch/elasticsearch.go:154	Start monitoring endpoint init loop." to the log file as if monitoring is working.  Same thing for connection issues, if you specify a remote monitoring cluster connection that is invalid, it will simply write "2018-06-05T01:35:17.596-0700	INFO	elasticsearch/client.go:145	Elasticsearch url: http://localhost:9802" (in this case there is no remote ES cluster running on 9802) as if the connection was made successfully.

If this is by design, it will be helpful to clarify in each beat's monitoring [documentation](https://www.elastic.co/guide/en/beats/metricbeat/current/monitoring.html#monitoring).

**Comment by ruflin** [comment] 2018-06-12 11:53
I had a chat with @skearns64 and @pickypg and this is currently by design. At the moment it is expected that the Beats monitoring data is sent through the production cluster as all other data. This might change in the future.

**Comment by urso** [comment] 2019-03-03 16:43
@ycombinator You think we can close this? Are we still missing documentation?

**Comment by ycombinator** [comment] 2019-03-09 20:10
I looked at the docs and it looks like we have the following note there:

![Screen Shot 2019-03-09 at 12 09 24 PM](https://user-images.githubusercontent.com/51061/54076798-48f9bd00-4264-11e9-8841-c5313979c90a.png)

So I think this is okay to close now.

**Closed by ycombinator** 2019-03-09 20:10 UTC
Labels: bug, libbeat
