### ISSUE TITLE
devices: error

### ISSUE THREAD

**Issue by akamajoris** [elastic/beats#346] opened 2015-11-02 14:48 UTC
Installed latest version from https://www.elastic.co/downloads/beats/packetbeat (DEB 64-bit).
Command: `packetbeat -devices`
Output: 

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x6c90c9]

goroutine 1 [running]:
github.com/tsg/gopacket/pcap.sockaddr_to_IP(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/tsg/gopacket/pcap/pcap.go:556 +0x49
github.com/tsg/gopacket/pcap.findalladdresses(0x16606d0, 0xc821223440, 0x0, 0x1)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/tsg/gopacket/pcap/pcap.go:542 +0xe1
github.com/tsg/gopacket/pcap.FindAllDevs(0xc82008e000, 0x3, 0x3, 0x0, 0x0)
        /go/src/github.com/elastic/packetbeat/Godeps/_workspace/src/github.com/tsg/gopacket/pcap/pcap.go:528 +0x35d
github.com/elastic/packetbeat/sniffer.ListDeviceNames(0x1, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/elastic/packetbeat/sniffer/sniffer.go:73 +0x75
main.(*Packetbeat).CliFlags(0xc820027680, 0xc8200103c0)
        /go/src/github.com/elastic/packetbeat/packetbeat.go:94 +0x79
main.main()
        /go/src/github.com/elastic/packetbeat/main.go:23 +0x270

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
        /usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
        /usr/local/go/src/os/signal/signal_unix.go:28 +0x37
```

uname -a
`Linux  2.6.32-042stab112.15 #1 SMP Tue Oct 20 17:22:56 MSK 2015 x86_64 GNU/Linux`

ifconfig

```
lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:5856986 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5856986 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:1145295230 (1.0 GiB)  TX bytes:1145295230 (1.0 GiB)

venet0    Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:127.0.0.2  P-t-P:127.0.0.2  Bcast:0.0.0.0  Mask:255.255.255.255
          inet6 addr: [hide]/128 Scope:Global
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1
          RX packets:1187946 errors:0 dropped:0 overruns:0 frame:0
          TX packets:1360359 errors:0 dropped:45 overruns:0 carrier:0
          collisions:0 txqueuelen:0
          RX bytes:352961923 (336.6 MiB)  TX bytes:969412972 (924.5 MiB)

venet0:0  Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:[hide]  P-t-P:[hide]  Bcast:[hide]  Mask:255.255.255.255
          UP BROADCAST POINTOPOINT RUNNING NOARP  MTU:1500  Metric:1
```

**Comment by tsg** [comment] 2015-11-02 23:25
I'd guess this is somehow related to the virtual interfaces because I cannot reproduce this on my debian system. I'll try to get an openvz system, google seems to think that would have those interfaces.

**Comment by gauthierc** [comment] 2015-12-03 15:58
I can reproduce this bug on my proxmox system. http://pve.proxmox.com

**Comment by gauthierc** [comment] 2015-12-15 11:04
Works with this patch:
https://github.com/gconnell/gopacket/commit/d823bebc7bd09751f67c42c8bf8750fcc0ddbbab

**Comment by andrewkroh** [comment] 2016-03-09 00:31
Thanks for the patch. We should pull that into our fork and possibly try to push it upstream if it makes sense.

**Comment by andrewkroh** [comment] 2016-03-09 00:35
That patch was pushed upstream so we just need to merge it to our fork. https://github.com/google/gopacket/pull/78

**Comment by monicasarbu** [comment] 2016-10-17 21:38
Closing as the PR was merged.

**Comment by monicasarbu** [comment] 2017-02-08 22:45
Here we just need to upgrade gopacket.

**Comment by ph** [comment] 2017-12-07 21:16
Closing this since #4719 was merged

**Closed by ph** 2017-12-07 21:16 UTC
Labels: adoptme, bug, Packetbeat
