### ISSUE TITLE
Startup Errors not visible under Windows Service

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [elastic/beats#5453] opened 2017-10-26 17:18 UTC
- Version: 5.5.2
- Operating System: Win2K12
- Steps to Reproduce: 

1) Install Filebeat under windows and install as a service.  
2) Make an indentation error in the config file.    
3) Try starting under service manager, and there will be an error like

```
The filebeat service failed to start due to the following error: 
The service did not respond to the start or control request in a timely fashion.
```

4) Try starting under power shell and you see something like this:

```
PS C:\Users\Administrator\Workspace\filebeat-5.5.2-windows-x86_64> Start-Service filebeat
Start-Service : Service 'filebeat (filebeat)' cannot be started due to the following error: Cannot start service
filebeat on computer '.'.
At line:1 char:1
+ Start-Service filebeat
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service],
   ServiceCommandException
    + FullyQualifiedErrorId : CouldNotStartService,Microsoft.PowerShell.Commands.StartServiceCommand
```

5) Try starting on the CLI, and you see the real error:

```
C:\Users\Administrator\Workspace\filebeat-5.5.2-windows-x86_64>"C:\Users\Administrator\Workspace\filebeat-5.5.2-windows-x86_64\\filebeat.exe" -c "C:\Users\Administrator\Workspace\filebeat-5.5.2-windows-x86_64\\filebeat.yml" -path.home "C:\Users\Administrator\Workspace\filebeat-5.5.2-windows-x86_64"
filebeat2017/10/26 17:08:19.957315 beat.go:339: CRIT Exiting: error loading config file: yaml: line 90: did not find expected key
Exiting: error loading config file: yaml: line 90: did not find expected key
```

I wonder if the windows service manager differentiates between stderr and stdout when including as error message for service start failure?  Just a guess.

**Comment by andrewkroh** [comment] 2017-10-26 20:19
I don't believe that the windows service manage does anything with stderr so we cannot provide an error message via that means. Two things some two mind and they are not mutually exclusive.

Advise users to use Beats to start the service through the Beat binary. We could add a sub-command like `winlogbeat install service` and `winlogbeat start service`. These could do error checking and then eventually invoke the windows service manager to start the service.

We could log errors to the Windows Event Log. This is where most Windows admins will look for the cause of the service not starting.

**Comment by maddin2016** [comment] 2017-11-06 11:02
@andrewkroh, what do you think of to add functionality for beats to write logs to the Windows Event Log. For example a config `to_windowsLog` or whatever for `logp.go`. We could extend `winlogbeat` for `RegisterEventSource` and `ReportEvent` or put it into `logp` . With these 2 calls it is possible to write to an Event Log without to create a manifest or something else. Assuming we only write strings into the log and not some binary data. I don't know if its good to write all events to the Windows Event Log or just critical informations. Any thoughts?

**Comment by urso** [comment] 2019-12-20 10:22
@andrewkroh We already have support for logging to Windows event logs. You know if we can make Beats detect if it is running as a service and then automatically configure the eventlog as log output before even reading the configuration?

**Comment by andrewkroh** [comment] 2019-12-20 17:55
I'm not sure about a good reliable way of detecting it's running as a service, but we could configure the event log as the output by adjusting the command used by the service. Like just add `-E logging.to_eventlog=true`.

**Comment by andrewkroh** [comment] 2019-12-20 18:14
But one thing that we did add since this issue was created was `logging.files.redirect_stderr`. After the logging package is initialized stderr will end-up in our log file. This let's us capture panics that occur. So maybe for 8.0 we can `logging.files.redirect_stderr` by default and close this issue.

**Closed** 2021-03-06 20:16 UTC
Labels: :Windows, Filebeat, Stalled, Team:Integrations, [zube]: Backlog, good first issue
