### ISSUE TITLE
Filebeat 6.4.0 .deb creates /lib/systemd/system/filebeat.service 0755

### ISSUE THREAD

**Issue by reshippie** [elastic/beats#8182] opened 2018-08-31 17:03 UTC
> Aug 30 16:52:59 elk-00 systemd[1]: Configuration file /lib/systemd/system/filebeat.service is marked executable. Please remove executable permission bits. Proceeding anyway.

- Version:  Filebeat 6.4.0
- Operating System: Debian 8.11, Debian 9.5
- Discuss Forum URL: https://discuss.elastic.co/t/filebeat-6-4-0-deb-creates-lib-lsystemd-system-filebeat-service-0755/146752
- Steps to Reproduce: 
apt-get install filebeat
ls -l /lib/systemd/system/filebeat.service

**Comment by andrewkroh** [comment] 2018-08-31 18:42
This is a duplicate of https://github.com/elastic/beats/pull/7873.

**Closed by andrewkroh** 2018-08-31 18:42 UTC
Labels: Packaging
