### ISSUE TITLE
[Filebeat][elasticsearch][gc] picking up wrong logs with docker autodiscover

### ISSUE THREAD

**Issue by kesslerm** [elastic/beats#13164] opened 2019-08-02 12:30 UTC
When the filebeat elasticsearch module is used with docker autodiscover, the gc logs pick up all JSON formatted log entries and index them into the `elasticsearch.gc` dataset.

**Comment by ycombinator** [comment] 2019-08-05 16:50
@kesslerm Thanks for filing this issue and the associated PR. I'm looking at the PR now.

**Comment by ycombinator** [comment] 2020-03-19 16:22
This looks like a duplicate of #16583.

**Closed** 2020-03-24 14:31 UTC
Labels: Filebeat, Stack monitoring, Team:Services, [zube]: In Progress, bug
