### ISSUE TITLE
[Stack Monitoring] Logstash module logs continual error when monitoring multiple pipelines

### ISSUE THREAD

**Issue by matschaffer** [elastic/beats#31739] opened 2022-05-25 04:49 UTC
- Version: main (d38dadbcc2b332450007c0da6c97994924861272)
- Operating System: linux
- Discuss Forum URL: https://discuss.elastic.co/t/metricbeat-cluster-monitoring-logstash-node-could-not-find-field-id-in-logstash-api-response/299651/3, also reported via customer support 

## Steps to Reproduce: 

- From https://github.com/elastic/kibana/pull/132870 (or main once merged)
- start ES (kibana optional)
- start logstash with multiple pipelines ([example](https://github.com/elastic/kibana/blob/0dcc901a146d1ae7f1933652711ea52e4e5eb07d/x-pack/plugins/monitoring/dev_docs/how_to/local_setup.md#standalone-cluster))
- start metricbeat to monitor ([example](https://github.com/elastic/kibana/blob/0dcc901a146d1ae7f1933652711ea52e4e5eb07d/x-pack/plugins/monitoring/dev_docs/how_to/local_setup.md#yarn-and-metricbeat-collection))

Note this in metricbeat logs:

```
{"log.level":"error","@timestamp":"2022-05-25T03:04:12.338Z","log.origin":{"file.name":"module/wrapper.go","file.line":256},"message":"Error fetching data for metricset logstash.node: Could not find field 'id' in Logstash API response","service.name":"metricbeat","ecs.version":"1.6.0"}
```

This seems to be caused by the `fields.Delete` calls like https://github.com/elastic/beats/blob/ff1041fc099ec69caea11c5c9c83d6ca59170ee7/metricbeat/module/logstash/node/data.go#L56

The deletions seem to have been added in https://github.com/elastic/beats/pull/10350 presumably to avoid leaving fields in the document that don't comply with ECS. But the `fields` struct gets reused for each pipeline in this loop https://github.com/elastic/beats/blob/ff1041fc099ec69caea11c5c9c83d6ca59170ee7/metricbeat/module/logstash/node/data.go#L101

So with more than one pipeline, you'll get errors.

This doesn't seem to impact the functionality of metricbeat for logstash stack monitoring, but the continual error creates a lot of log noise (once every cycle, 10s by default).

![Screen Shot 2022-05-25 at 13 48 18](https://user-images.githubusercontent.com/690/170181971-d211bb9e-c01b-4d4d-aae7-4e64d785f833.png)

![Screen Shot 2022-05-25 at 13 48 54](https://user-images.githubusercontent.com/690/170182067-a3abdc16-dfd1-488c-85aa-c6465e9fa530.png)

We may want to move the field deletion to the event level, or create a new map so we can leave `fields` intact through the iteration of all pipelines.

**Comment by lukeyeager** [comment] 2022-05-26 16:12
Duplicate of https://github.com/elastic/beats/issues/31698

**Comment by matschaffer** [comment] 2022-05-30 03:20
Thanks @lukeyeager , looks like the content is basically the same so I closed that one since this one has the team/board assignments.

**Closed** 2022-06-20 15:20 UTC
Labels: bug, Feature: Stack Monitoring, Team:Infra Monitoring UI
