### ISSUE TITLE
Filebeat panics on test_no_missing_events load test shutdown

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#6879] opened 2018-04-17 08:08 UTC
Today on Jenkins the `test_load/Test/test_no_missing_events` failed which I haven't seen failing in a long time: https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-linux/4037/beat=filebeat,label=ubuntu/testReport/junit/test_load/Test/test_no_missing_events/

Filebeat panics on shutdown with the following message:

```

2018-04-16T15:05:12.234Z    DEBUG    [harvester]    _obj/harvester.go:525    Stopping harvester for file: /go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_load.Test.test_no_missing_events/log/test.log.57
2018-04-16T15:05:12.235Z    DEBUG    [harvester]    runtime/asm_amd64.s:510    harvester cleanup finished for file: /go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_load.Test.test_no_missing_events/log/test.log.40
2018-04-16T15:05:12.235Z    INFO    _obj/harvester.go:258    Reader was closed: /go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_load.Test.test_no_missing_events/log/test.log.16. Closing.
2018-04-16T15:05:12.235Z    DEBUG    [harvester]    _obj/harvester.go:533    Closing file: /go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_load.Test.test_no_missing_events/log/test.log.57
2018-04-16T15:05:12.235Z    DEBUG    [harvester]    _obj/harvester.go:384    Update state: /go/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_load.Test.test_no_missing_events/log/test.log.57, offset: 48
panic: close of closed channel

goroutine 83 [running]:
github.com/elastic/beats/filebeat/channel.(*subOutlet).OnEvent(0xc42010eaa0, 0xc420906d80, 0xc420906d80)
    github.com/elastic/beats/filebeat/channel/_obj/util.go:58 +0x284
github.com/elastic/beats/filebeat/input/log.(*Input).createHarvester.func1(0xc420906d80, 0xc420906d80)
    github.com/elastic/beats/filebeat/input/log/_obj/input.go:694 +0x4d
github.com/elastic/beats/filebeat/input/log.(*Harvester).SendStateUpdate(0xc4203ae780)
    github.com/elastic/beats/filebeat/input/log/_obj/harvester.go:389 +0x23a
github.com/elastic/beats/filebeat/input/log.(*Harvester).cleanup(0xc4203ae780)
    github.com/elastic/beats/filebeat/input/log/_obj/harvester.go:536 +0x276
github.com/elastic/beats/filebeat/input/log.(*Harvester).Run.func1(0xc4203ae780)
    github.com/elastic/beats/filebeat/input/log/_obj/harvester.go:190 +0x43
github.com/elastic/beats/filebeat/input/log.(*Harvester).Run(0xc4203ae780, 0x0, 0x0)
    github.com/elastic/beats/filebeat/input/log/_obj/harvester.go:270 +0xf34
github.com/elastic/beats/filebeat/harvester.(*Registry).Start.func1(0xc420118980, 0x1e374e0, 0xc4203ae780)
    github.com/elastic/beats/filebeat/harvester/_obj/registry.go:90 +0xa9
created by github.com/elastic/beats/filebeat/harvester.(*Registry).Start
    github.com/elastic/beats/filebeat/harvester/_obj/registry.go:80 +0x166
```

https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-linux/4037/beat=filebeat,label=ubuntu/artifact/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_load.Test.test_no_missing_events/filebeat.log

I wonder if this could be related to a recent change we made to fix an other race condition.

**Comment by ruflin** [comment] 2018-04-25 14:57
One more error with a panic happened today on Jenkins:

```
Stacktrace
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 331, in run
    testMethod()
  File "/private/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-darwin/beat/filebeat/label/macosx/src/github.com/elastic/beats/filebeat/tests/system/test_input.py", line 108, in test_rotating_close_inactive_larger_write_rate
    proc.check_kill_and_wait()
  File "/private/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-darwin/beat/filebeat/label/macosx/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 94, in check_kill_and_wait
    return self.check_wait(exit_code=exit_code)
  File "/private/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-darwin/beat/filebeat/label/macosx/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 83, in check_wait
    exit_code, actual_exit_code)
AssertionError: Expected exit code to be 0, but it was 1
```
And the stack trace:
```
2018-04-25T04:23:02.931-0700	INFO	_obj/crawler.go:132	Stopping Crawler
2018-04-25T04:23:02.931-0700	DEBUG	[input]	_obj/input.go:420	Check file for harvesting: /private/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-darwin/beat/filebeat/label/macosx/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_input.Test.test_rotating_close_inactive_larger_write_rate/log/test.log1524655382.43
2018-04-25T04:23:02.932-0700	INFO	_obj/crawler.go:145	Stopping 1 inputs
2018-04-25T04:23:02.932-0700	DEBUG	[input]	_obj/input.go:527	Update existing file for harvesting: /private/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-darwin/beat/filebeat/label/macosx/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_input.Test.test_rotating_close_inactive_larger_write_rate/log/test.log1524655382.43, offset: 42
==================
WARNING: DATA RACE
Write at 0x00c42007f1a0 by goroutine 51:
  runtime.closechan()
      /var/lib/jenkins/.gvm/versions/go1.9.4.darwin.amd64/src/runtime/chan.go:313 +0x0
  github.com/elastic/beats/filebeat/channel.(*subOutlet).OnEvent()
      github.com/elastic/beats/filebeat/channel/_obj/util.go:60 +0x389
  github.com/elastic/beats/filebeat/input/log.(*Input).createHarvester.func1()
      github.com/elastic/beats/filebeat/input/log/_obj/input.go:696 +0x95
  github.com/elastic/beats/filebeat/input/log.(*Harvester).SendStateUpdate()
      github.com/elastic/beats/filebeat/input/log/_obj/harvester.go:391 +0x32d
  github.com/elastic/beats/filebeat/input/log.(*Harvester).cleanup()
      github.com/elastic/beats/filebeat/input/log/_obj/harvester.go:538 +0x387
  github.com/elastic/beats/filebeat/input/log.(*Harvester).Run.func1()
      github.com/elastic/beats/filebeat/input/log/_obj/harvester.go:192 +0x62
  github.com/elastic/beats/filebeat/input/log.(*Harvester).Run()
      github.com/elastic/beats/filebeat/input/log/_obj/harvester.go:272 +0x151a
  github.com/elastic/beats/filebeat/harvester.(*Registry).Start.func1()
      github.com/elastic/beats/filebeat/harvester/_obj/registry.go:92 +0xd2

Previous read at 0x00c42007f1a0 by goroutine 47:
  runtime.chansend()
      /var/lib/jenkins/.gvm/versions/go1.9.4.darwin.amd64/src/runtime/chan.go:128 +0x0
  github.com/elastic/beats/filebeat/channel.(*subOutlet).OnEvent()
      github.com/elastic/beats/filebeat/channel/_obj/util.go:63 +0x185
  github.com/elastic/beats/filebeat/input/log.(*Input).createHarvester.func1()
      github.com/elastic/beats/filebeat/input/log/_obj/input.go:696 +0x95
  github.com/elastic/beats/filebeat/input/log.(*Harvester).SendStateUpdate()
      github.com/elastic/beats/filebeat/input/log/_obj/harvester.go:391 +0x32d
  github.com/elastic/beats/filebeat/input/log.(*Harvester).cleanup()
      github.com/elastic/beats/filebeat/input/log/_obj/harvester.go:538 +0x387
  github.com/elastic/beats/filebeat/input/log.(*Harvester).Run.func1()
      github.com/elastic/beats/filebeat/input/log/_obj/harvester.go:192 +0x62
  github.com/elastic/beats/filebeat/input/log.(*Harvester).Run()
      github.com/elastic/beats/filebeat/input/log/_obj/harvester.go:272 +0x151a
  github.com/elastic/beats/filebeat/harvester.(*Registry).Start.func1()
      github.com/elastic/beats/filebeat/harvester/_obj/registry.go:92 +0xd2

Goroutine 51 (running) created at:
2018-04-25T04:23:02.932-0700	DEBUG	[input]	_obj/input.go:561	File rename was detected: /private/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-darwin/beat/filebeat/label/macosx/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_input.Test.test_rotating_close_inactive_larger_write_rate/log/test.log -> /private/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-darwin/beat/filebeat/label/macosx/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_input.Test.test_rotating_close_inactive_larger_write_rate/log/test.log1524655382.43, Current offset: 42
  github.com/elastic/beats/filebeat/harvester.(*Registry).Start()
      github.com/elastic/beats/filebeat/harvester/_obj/registry.go:82 +0x1b7
  github.com/elastic/beats/filebeat/input/log.(*Input).startHarvester()
      github.com/elastic/beats/filebeat/input/log/_obj/input.go:741 +0x3e4
  github.com/elastic/beats/filebeat/input/log.(*Input).scan()
      github.com/elastic/beats/filebeat/input/log/_obj/input.go:513 +0x7d7
  github.com/elastic/beats/filebeat/input/log.(*Input).Run()
      github.com/elastic/beats/filebeat/input/log/_obj/input.go:171 +0x119
  github.com/elastic/beats/filebeat/input.(*Runner).Run()
      github.com/elastic/beats/filebeat/input/_obj/input.go:142 +0x160
  github.com/elastic/beats/filebeat/input.(*Runner).Start.func1()
      github.com/elastic/beats/filebeat/input/_obj/input.go:117 +0x9c

Goroutine 47 (running) created at:
  github.com/elastic/beats/filebeat/harvester.(*Registry).Start()
      github.com/elastic/beats/filebeat/harvester/_obj/registry.go:82 +0x1b7
  github.com/elastic/beats/filebeat/input/log.(*Input).startHarvester()
      github.com/elastic/beats/filebeat/input/log/_obj/input.go:741 +0x3e4
  github.com/elastic/beats/filebeat/input/log.(*Input).scan()
      github.com/elastic/beats/filebeat/input/log/_obj/input.go:513 +0x7d7
  github.com/elastic/beats/filebeat/input/log.(*Input).Run()
      github.com/elastic/beats/filebeat/input/log/_obj/input.go:171 +0x119
  github.com/elastic/beats/filebeat/input.(*Runner).Run()
      github.com/elastic/beats/filebeat/input/_obj/input.go:142 +0x160
  github.com/elastic/beats/filebeat/input.(*Runner).Start.func1()
      github.com/elastic/beats/filebeat/input/_obj/input.go:117 +0x9c
==================
2018-04-25T04:23:02.932-0700	DEBUG	[input]	_obj/input.go:565	Updating state for renamed file: /private/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-darwin/beat/filebeat/label/macosx/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_input.Test.test_rotating_close_inactive_larger_write_rate/log/test.log -> /private/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-darwin/beat/filebeat/label/macosx/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_input.Test.test_rotating_close_inactive_larger_write_rate/log/test.log1524655382.43, Current offset: 42
2018-04-25T04:23:02.932-0700	DEBUG	[registrar]	_obj/registrar.go:261	Processing 1 events
2018-04-25T04:23:02.932-0700	DEBUG	[registrar]	_obj/registrar.go:234	Registrar state updates processed. Count: 1
2018-04-25T04:23:02.933-0700	DEBUG	[registrar]	_obj/registrar.go:251	Registrar states cleaned up. Before: 2, After: 2, Pending: 0
2018-04-25T04:23:02.933-0700	DEBUG	[registrar]	_obj/registrar.go:298	Write registry file: /private/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-darwin/beat/filebeat/label/macosx/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_input.Test.test_rotating_close_inactive_larger_write_rate/registry
2018-04-25T04:23:02.933-0700	DEBUG	[harvester]	_obj/harvester.go:546	harvester cleanup finished for file: /private/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-darwin/beat/filebeat/label/macosx/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_input.Test.test_rotating_close_inactive_larger_write_rate/log/test.log
2018-04-25T04:23:02.933-0700	DEBUG	[input]	_obj/input.go:589	File didn't change: /private/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-darwin/beat/filebeat/label/macosx/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_input.Test.test_rotating_close_inactive_larger_write_rate/log/test.log1524655382.43
2018-04-25T04:23:02.933-0700	DEBUG	[harvester]	_obj/harvester.go:546	harvester cleanup finished for file: /private/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-darwin/beat/filebeat/label/macosx/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_input.Test.test_rotating_close_inactive_larger_write_rate/log/test.log
```

https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-darwin/1568/beat=filebeat,label=macosx/testReport/junit/test_input/Test/test_rotating_close_inactive_larger_write_rate/

**Comment by ph** [comment] 2018-04-25 19:30
After looking at the code and the stack trace from the last panic I imagine the error, I think something is still wrong in the shutdown sequence of the harvester, we see that we are trying to write to the `stateOutlet` channel when its close, the thing is the `stateOutlet` should have been close after all the harvester are closed.

**Comment by ph** [comment] 2018-04-25 19:57
I think I have an idea what is causing this, I am trying to reproduce the original error locally first.

**Comment by ph** [comment] 2018-04-26 13:40
OK well, I am not able to reproduce it locally, I've let it run the whole night here :(
Plausible scenario:

- registry#StartHarvester is called.
   - we acquire the lock
- Stop is called
  - We request the lock.
- The Run go routine is started
 - We request the lock to add the harvester to the registry.
- registry#StartHarvester release the lock
- Stop got the lock, loop stop all the harvester and release the lock.

Still Stop should have wait for `WaitCompletion` called in the defer before closing the channel.

**Comment by ph** [comment] 2018-06-05 14:22
I will close this since #6959 was merged and I believe it was the culprit.

**Closed by ph** 2018-06-05 14:22 UTC
Labels: Filebeat, bug
