### ISSUE TITLE
Packetbeat host.name not fqdn like winlogbeat

### ISSUE THREAD

**Issue by dtclayton** [elastic/beats#16507] opened 2020-02-23 22:11 UTC
Packetbeat does not use the fqdn for the host when showing the host.name field, unlike winlogbeat which does.
This causes issues when using the SIEM tool as the correlation point is on host.name.

**Comment by willemdh** [comment] 2020-02-24 09:50
Just checked (7.5.2) and it seems that for us, Packetbeat does not use fqdn for `host.name` nor in Winlogbeat, nor in Packetbeat.

**Comment by andrewkroh** [comment] 2020-02-26 03:38
I think this is a duplicate of the underlying issue in https://github.com/elastic/beats/issues/1070. Let's close this one and collect comments on that issue.

**Closed by andrewkroh** 2020-02-26 03:38 UTC
Labels: Team:SIEM
