### ISSUE TITLE
Please have report filesystem type

### ISSUE THREAD

**Issue by ckmcd** [elastic/beats#1980] opened 2016-07-06 21:24 UTC
It would be very helpful to be able to filter on filesystem type (e.g. ext*, nfs, proc, etc.)

I know this as been mention in several discussion and it was suggested that an ER be opened.  I could not find one so here it is.

Thanks!

Chris

**Comment by tsg** [comment] 2016-07-08 09:51
For clarity, does this refer to Filebeat or the Topbeat/Metricbeat disk usage stats?

**Comment by monicasarbu** [comment] 2017-02-16 14:08
Closing this issue, as no more details were provided for 7 months.

**Closed by monicasarbu** 2017-02-16 14:08 UTC
Labels: enhancement, needs details

**Comment by andrewkroh** [comment] 2017-02-22 02:52
This may have been a duplicate of https://github.com/elastic/beats/issues/1980 if it was for Metricbeat.
