### ISSUE TITLE
[Elastic Agent] BETA reported on GA installation

### ISSUE THREAD

**Issue by mostlyjason** [elastic/beats#26966] opened 2021-07-19 18:14 UTC
I'm running the 7.14 snapshot for Elastic Agent and its reporting that's BETA on the installation console. This line should be removed.

```
$ sudo ./elastic-agent install -f --url=https://d6bdd2ac39e74f2dbc16a10a7b37.fleet.eastus2.staging.azure.foundit.no:443 --enrollment-token=M2xWUHYzb0JjTW8wbXRBRHdySGo6aEFqcjg0Z2VTaWx1LTNneXJNUQ==
The Elastic Agent is currently in BETA and should not be used in production
```

**Comment by mostlyjason** [comment] 2021-07-19 18:14
@nimarezainia @EricDavisX FYI

**Comment by blakerouse** [comment] 2021-07-20 12:13
Duplicate of #26748

**Closed by blakerouse** 2021-07-20 12:13 UTC
Labels: Team:Agent, bug, v7.14.0

**Comment by dikshachauhan-qasource** [comment] 2021-07-27 09:55
Hi @EricDavisX 

We have validated this issue and found it non-reproducible on 7.14BC4 Kibana cloud staging build.

`The Elastic Agent is currently in BETA and should not be used in production` 
**Observation**:  Above mentioned log is now not displayed during installation or in agent logs.

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/127134687-6a4c4eef-4fd5-4461-8087-de28201f2ffa.png)

Hence, it is working fine.

Thanks
QAS
