### ISSUE TITLE
Getting unauthorized error loading dashboards

### ISSUE THREAD

**Issue by liza-mae** [elastic/beats#10513] opened 2019-02-04 05:05 UTC
- Version: master snapshot 
- Operating System: Linux 
- Steps to Reproduce: 
Install, ES, Kibana, Filebeat 
Run ./filebeat setup --dashboards
Loading dashboards (Kibana must be running and reachable)
Exiting: fail to create the Kibana loader: Error creating Kibana client: Error creating Kibana client: fail to get the Kibana version: HTTP GET request to https://10.0.2.15:5601/api/status fails: <nil>. Response: {"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}

Are there updates required for 7.0 dashboards to work?  I have not changed anything in my configuration, but this stopped working on latest master snapshot.

**Comment by kaiyan-sheng** [comment] 2019-02-04 16:38
@liza-mae Thanks for reporting this! I just tested on Ubuntu with 7.0.0-alpha2 https://www.elastic.co/downloads/elasticsearch#preview-release, https://www.elastic.co/downloads/kibana#preview-release and https://www.elastic.co/downloads/beats/filebeat#preview-release. When I ran `./filebeat setup --dashboards`, the dashboards were loaded fine. What version did you use? Is there anything/steps I'm missing here?

**Comment by liza-mae** [comment] 2019-02-04 16:40
Hi @kaiyan-sheng it is on 7.0 snapshot build from release manager - 7.0 alpha2 did not have the problem
This is the one I am using: 7.0.0-cdc88865

**Comment by liza-mae** [comment] 2019-02-04 18:11
This is happening on trial license with security enabled.

**Comment by kaiyan-sheng** [comment] 2019-02-04 22:45
Thank you @liza-mae for all the help! I was able to reproduce this issue locally. The problem is, previously when `username: elastic` and `password: changeme` are set under `output.elasticsearch` in filebeat.yml, `setup.kibana` will use the same password and username from `output.elasticsearch`. But with the new 7.0.0 builds, filebeat doesn't do this anymore. Workaround here is to set `username: elastic` and `password: changeme` again under `setup.kibana` in filebeat.yml for now.

**Comment by liza-mae** [comment] 2019-02-04 22:58
Thanks @kaiyan-sheng

**Comment by liza-mae** [comment] 2019-02-04 23:21
We will need to find out if this is a bug or change in behavior for 7.0?

**Comment by kaiyan-sheng** [comment] 2019-02-05 01:22
If this is a regression/bug, then https://github.com/elastic/beats/pull/10553 will fix the problem. If this is a known change in behavior for 7.0.0, maybe some other changes in documentation will need to be added if not already there.

**Comment by ruflin** [comment] 2019-02-05 07:31
Sorry, this is a regression I introduced :-(

**Comment by liza-mae** [comment] 2019-02-08 23:52
This looks to still be failing on latest 7.0, @kaiyan-sheng if you can take a look?  Thanks.

**Comment by kaiyan-sheng** [comment] 2019-02-11 03:29
Tested with https://staging.elastic.co/7.0.0-beta1-60c90a9e/summary-7.0.0-beta1.html and it's still failing. Will look into this more!

**Comment by kaiyan-sheng** [comment] 2019-02-11 15:44
New fix for this issue: https://github.com/elastic/beats/pull/10675 
Tested locally and it fixed the issue :-)

**Comment by liza-mae** [comment] 2019-02-11 16:26
Thanks @kaiyan-sheng

**Comment by liza-mae** [comment] 2019-02-14 19:28
Tried on latest master - it is fixed :) .. still failing on 7.0 and 7.x - I think it needs to be back ported, @kaiyan-sheng can you check?

**Comment by kaiyan-sheng** [comment] 2019-02-15 00:10
@liza-mae Thanks for testing it! Backport to 7.0 was merged yesterday https://github.com/elastic/beats/pull/10702 and for 7.x, this fix is a part of https://github.com/elastic/beats/pull/10725

**Comment by liza-mae** [comment] 2019-02-21 16:42
Thanks @kaiyan-sheng - any idea when 7.x will be fixed?

**Comment by kaiyan-sheng** [comment] 2019-02-21 16:43
> Thanks @kaiyan-sheng - any idea when 7.x will be fixed?

Not yet. I will

**Comment by liza-mae** [comment] 2019-02-21 16:45
I reopened it pending 7.x fix.

**Comment by kaiyan-sheng** [comment] 2019-02-21 19:45
> I reopened it pending 7.x fix.

Sorry!!! I closed it by accident... :-)

**Comment by kaiyan-sheng** [comment] 2019-02-25 14:44
@urso Please correct me if I'm wrong here. We do not backport to 7.x, but merge master into 7.x and then will branch 7.1 when time comes. If we want this fix to be in 7.0.x, we only have to backport it to the 7.0 branch. 

Based on this, @liza-mae do you think this issue is ready to be closed?

**Comment by kaiyan-sheng** [comment] 2019-03-12 20:13
The fix for this issue should be merged into https://github.com/elastic/beats/tree/7.x now with https://github.com/elastic/beats/pull/11168

**Comment by liza-mae** [comment] 2019-03-12 20:14
Thanks @kaiyan-sheng

**Closed** 2019-04-10 16:08 UTC
Labels: :Dashboards, :infrastructure, bug, regression, v7.0.0, v7.1.0, v8.0.0
