### ISSUE TITLE
Not Possible to Cross-Compile for ARM?

### ISSUE THREAD

**Issue by bradennapier** [elastic/beats#3263] opened 2016-12-30 17:40 UTC
Not seeing any information on how I would cross-compile the system metrics beats to work for ARM OS.  I see some references to it but no instructions, information, and the make files dont seem to indicate how I may do this.

**Comment by tsg** [comment] 2017-01-02 10:35
You can cross-compile by setting the `GOOS` and `GOARCH` env variables (the standard Go way). E.g:

```
GOOS=linux GOARCH=arm make
```

Note that this works for Metricbeat but nor for all beats, since some require Cgo.

I'm closing this ticket as we are trying to keep Github only for confirmed bugs and enhancement requests. Please open a topic on [our forums](https://discuss.elastic.co/c/beats) if you need further help with this issue.

**Closed by tsg** 2017-01-02 10:35 UTC
Labels: question
