### ISSUE TITLE
Cannot load Filebeat 7.9.0 and higher template in Elasticsearch 6.8.12 because of flattened type

### ISSUE THREAD

**Issue by TonioRyo** [elastic/beats#23090] opened 2020-12-11 10:51 UTC
- Version: Filebeat 79.0 and higher, Elasticsearch 6.8.12
- Operating System: Windows & Linux
- Discuss Forum URL: https://discuss.elastic.co/t/cannot-load-filebeat-7-9-0-and-higher-template-in-elasticsearch-6-8-12/257663
- Steps to Reproduce: 

1. Generate filebeat template : `filebeat.exe export template --es.version 6.8.12 | Out-File -Encoding UTF8 filebeat.template.json`
2. Load the template : `curl -XPUT -H 'Content-Type: application/json' http://localhost:9200/_template/filebeat-7.9.0 -d@filebeat.template.json`

The following error is returned by ElasticSearch : 
```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "No handler for type [flattened] declared on field [devices]"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "Failed to parse mapping [doc]: No handler for type [flattened] declared on field [devices]",
    "caused_by": {
      "type": "mapper_parsing_exception",
      "reason": "No handler for type [flattened] declared on field [devices]"
    }
  },
  "status": 400
}
```

**Comment by jsoriano** [comment] 2020-12-11 12:23
Hi @TonioRyo,

I think that this change was intended, Filebeat 7.9 is not expected to work with Elasticsearch 6.x. You can find the compatibility matrix here: https://www.elastic.co/support/matrix#matrix_compatibility
Greater version expected to work with Elasticsearch 6.8 is Filebeat 6.8.

Thanks for reporting, but I don't think this is going to be fixed. I am closing this issue by now.

**Closed by jsoriano** 2020-12-11 12:23 UTC
Labels: needs_team
