### ISSUE TITLE
Fleet server agent stuck in Updating after triggering unenrollment

### ISSUE THREAD

**Issue by jen-huang** [elastic/beats#25561] opened 2021-04-15 17:45 UTC
- Version: 8.0 snapshot
- Operating System: MacOS
- Steps to Reproduce: 

1. Enroll FS agent using instructions in https://github.com/elastic/kibana/pull/97206
2. Trigger unenrollment for FS agent in UI
3. After a while, observe that the agent is stuck in `Updating` status

![image](https://user-images.githubusercontent.com/1965714/114914776-9a77bd00-9dd7-11eb-809e-bcd69cce401c.png)

**Comment by EricDavisX** [comment] 2021-05-10 16:26
@dikshachauhan-qasource can you re-test and make sure any relating test cases for the feature area are also passing still?  Thank you.

**Comment by dikshachauhan-qasource** [comment] 2021-05-11 10:43
Hi @EricDavisX 

We have re-validated above scenario and found it **reproducible** for elastic agents with offline status and fleet server agents.

Scenario 1: Agent in healthy status
- unenrolled successfully

Scenario 2: Agent in offline status
- Not unenrolled successfully and stuck in updating state

Scenario 3: Fleet server Agent in healthy status
- Not unenrolled successfully and stuck in updating state

Screenshots:
![image](https://user-images.githubusercontent.com/72375798/117802867-983c3d80-b273-11eb-9243-a82e68d8d248.png)

Please let us know if anything else is required.

**Comment by EricDavisX** [comment] 2021-05-11 14:23
@dikshachauhan-qasource I will re-open this, but we need to know the version (and specific hash, preferably) of the Agent tested with.

@blakerouse FYI.

**Comment by EricDavisX** [comment] 2021-05-11 15:39
@dikshachauhan-qasource also, we'd likely be helped if we could get the Agent logs off of the host that would speed up debugging too.

**Comment by dikshachauhan-qasource** [comment] 2021-05-12 10:20
Hi @EricDavisX @blakerouse 

We have validated this today on CLOUD-QA builds too and found reproducible.Please find the logs in attachment below.

[Fleet_agentLogs.zip](https://github.com/elastic/beats/files/6465483/Fleet_agentLogs.zip)
[elastic-agent-havingStatusOFFline.log](https://github.com/elastic/beats/files/6465484/elastic-agent-havingStatusOFFline.log)


Thanks
QAS

**Comment by blakerouse** [comment] 2021-05-12 12:19
From the logs it's clear that for some reason the API keys had already been invalidated before the ACK was sent to the Fleet Server. Fleet Server only invalidates the API keys once it receives the ACK, so something strange is occurring here.

```
2021-05-11T06:26:01-04:00 - message: Application: metricbeat--7.13.0[2a48f9a2-5fea-4298-be35-c724ffc111fd]: State changed to STOPPED: Stopped - type: 'STATE' - sub_type: 'STOPPED'
2021-05-11T06:26:01.487-0400	ERROR	fleet/fleet_gateway.go:180	failed to dispatch actions, error: acknowledge 1 actions '[action_id: e78be8f2-971c-43f7-9415-190c58e4c8fd, type: UNENROLL]' for elastic-agent '2a48f9a2-5fea-4298-be35-c724ffc111fd' failed: fail to ack to fleet: Post "https://mainqa-atlcolo-10-0-7-186.eng.endgames.local:8220/api/fleet/agents/2a48f9a2-5fea-4298-be35-c724ffc111fd/acks?": dial tcp 10.0.7.186:8220: connect: connection refused
2021-05-11T06:26:01.487-0400	ERROR	status/reporter.go:236	Elastic Agent status changed to: 'error'
2021-05-11T06:26:02.728-0400	ERROR	fleet/fleet_gateway.go:204	Could not communicate with Checking API will retry, error: fail to checkin to fleet: Post "https://mainqa-atlcolo-10-0-7-186.eng.endgames.local:8220/api/fleet/agents/2a48f9a2-5fea-4298-be35-c724ffc111fd/checkin?": dial tcp 10.0.7.186:8220: connect: connection refused
2021-05-11T06:27:55.464-0400	ERROR	fleet/fleet_gateway.go:204
```

As for the logs in the `elastic-agent-havingStatusOFFline.log`, is that a different host with a different issue? That one seems to be failing to checkin to fleet with `context cancelled` which makes me think that it is timing out on actually communicating with Fleet Server. That is through the cloud proxy, maybe that is having an issue? I am not seeing that in local testing, that could be the difference.

```
{"log.level":"error","@timestamp":"2021-05-12T05:31:12.233-0400","log.origin":{"file.name":"fleet/fleet_gateway.go","file.line":204},"message":"Could not communicate with Checking API will retry, error: fail to checkin to fleet: Post \"https://0fcbec633ddf40b08bd1be69b57b079e.fleet.us-central1.gcp.qa.cld.elstc.co:443/api/fleet/agents/0a3a18ad-1126-48c5-9d32-f8ef6a57dc34/checkin?\": context canceled","ecs.version":"1.6.0"}
```

**Comment by blakerouse** [comment] 2021-05-12 14:01
@dikshachauhan-qasource I am not able to reproduce this morning using QA cloud with Elastic Agent running on Mac OS X. Maybe it is an issue specific to a OS type, what OS and OS version are you running the Elastic Agent on? I want to be a similar in your setup as possible.

**Comment by dikshachauhan-qasource** [comment] 2021-05-12 15:25
I have attempted both agents on Linux centos 7.6 machines. Please let me know if anything else is required.

**Comment by EricDavisX** [comment] 2021-05-13 20:09
I have reproduced this on Windows 7 as the Fleet Server Agent host, using Cloud prod and latest BC, BC5 of 7.13 for stack and Agent code.  I can attach additional logging if helpful.

[logs.zip](https://github.com/elastic/beats/files/6474809/logs.zip)

So, it isn't specific to a given VM or OS.  This would impact cloud, if it is seen on Linux.

And I don't think anything on the 'cloud' side should relate, this would be all Agent and Fleet Kibana side code if we are using 'self managed' Fleet Servers we stood up (separate from the cloud provided 'hosted' FS agent)

**Comment by dikshachauhan-qasource** [comment] 2021-05-14 12:05
Yes Eric, we have also attempted to unenroll today fleet server agent on windows 10 machine and was left in state of updating.

So we used force unenroll option to get out of situation.

**Comment by EricDavisX** [comment] 2021-05-17 21:58
@ph @ruflin what should we do here?  Is it still on your radar for follow up @blakerouse ?  If it leaves the host in a bad or indeterminate state we ideally would fix it, if it just is a UI misinformation then it is not as urgent but worth fixing for the first patch if we run out of time.  That's my quick take.

**Comment by EricDavisX** [comment] 2021-05-17 22:09
@dikshachauhan-qasource @amolnater-qasource can you re-test against cloud-qa and cloud-prod with the latest BC6 stack side code and see if you can confirm it is working in either for us, or if there is some other disconnect as to why it is hard to reproduce, please?  thank you. :)

**Comment by blakerouse** [comment] 2021-05-18 12:04
Tested this morning on CentOS 7 with BC6 against QA cloud with running Fleet Server. Unenroll action worked successfully, Elastic Agent was stopped correctly and it was removed from the Kibana UI as expected.

At the moment I am still unable to reproduce this issue.

**Comment by dikshachauhan-qasource** [comment] 2021-05-18 12:16
Hi @EricDavisX 

We have validated this issue today on both staging and cloud-qa 7.13 BC6 builds and found it **still reproducible.**

Build details:
BUILD 40852
COMMIT 1ce2632ae192b3b41f6eef4625b97b18971a4864
Artifact link: https://staging.elastic.co/7.13.0-40b6b79a/summary-7.13.0.html

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/118649248-ecf63000-b800-11eb-87d3-916207f4b036.png)

**Logs:**
[fleet-server-json.log](https://github.com/elastic/beats/files/6501133/fleet-server-json.log)
[elastic-agent-json.log](https://github.com/elastic/beats/files/6501144/elastic-agent-json.log)

Please let us know if anything else is required.

**Comment by ruflin** [comment] 2021-05-18 12:26
Is my understanding correct that this is not related to Cloud in any way?

@blakerouse to reproduce this run the following:

```
elastic-package stack up --version=7.13.0-SNAPSHOT
```

Go to Kibana and unenroll the fleet-server. Updating stays and you see errors in Agent logs.

**Comment by blakerouse** [comment] 2021-05-18 13:32
@ruflin Wait? You are unenrolling an Elastic Agent running a Fleet Server? That will not work. How will the Elastic Agent communicate to a Fleet Server that is off?

**Comment by ruflin** [comment] 2021-05-18 13:35
@blakerouse https://github.com/elastic/beats/issues/25561#issuecomment-820633807

**Comment by blakerouse** [comment] 2021-05-18 13:56
I miss understood that comment then and the original issue with this bug. What I validated and confirmed working was that Elastic Agent can unenroll from a Fleet Server (not an Elastic Agent also running a Fleet Server).

An Elastic Agent that is running a Fleet Server cannot at the moment be safely unenrolled. It would need to be stopped manually on the host and then force removed in Kibana. I would question if it even make sense to allow an Elastic Agent that runs a Fleet Server to be unenrolled in Kibana. It being removed in Kibana can cause a cascade effect of issues, resulting in issues on other Elastic Agents.

**Comment by dikshachauhan-qasource** [comment] 2021-05-18 14:01
@blakerouse Thanks for the feedback. 

Further, we will be waiting to know the final expected behavior of feature and will update our test content accordingly.

cc @EricDavisX 

Thanks
QAS

**Comment by EricDavisX** [comment] 2021-05-18 17:42
I can reproduce the problem when no fleet-server component is in play on the Agent / host.  The original use case may include that but it is not the only case that is failing.  

About self-managed Fleet server usage, we have more polishing work to do to prevent users from hurting themselves, it is logged separate I believe.

**Comment by EricDavisX** [comment] 2021-05-18 19:53
I'll log my normal / standard Agent issue separately as this one has always been about a FS Agent.

**Comment by EricDavisX** [comment] 2021-05-18 20:35
I've logged this as a follow up:
https://github.com/elastic/beats/issues/25773

I will close this back out as we made some fixes and have UX rework to consider for the self-managed FS case.

**Closed by EricDavisX** 2021-05-18 20:35 UTC
Labels: Team:Agent, bug, v7.13.0
