### ISSUE TITLE
Filebeat: Output defined in config_dir, filebeat fails to start 

### ISSUE THREAD

**Issue by tripledes** [elastic/beats#1112] opened 2016-03-04 14:28 UTC
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For confirmed bugs, please report:
- Version: 5.0.0-nightly34cbe9d
- Operating System: CentOS 7 (docker container)
- Steps to Reproduce: 

I'm trying to build a bit of a dynamic docker image with `filebeat`, where the environment variables substitution works great :-), however, I'd like to use the `config_dir` directive to define the output based on some other environment variables but it turns out that the parser expects an output to be defined on the main configuration file before even trying to parse the files on `config_dir`.

```
[root@be01507ce673 filebeat]# filebeat -configtest -e -v debug
2016/03/04 13:56:24.036295 beat.go:221: DBG  Initializing output plugins
2016/03/04 13:56:24.036732 geolite.go:24: INFO GeoIP disabled: No paths were set under shipper.geoip.paths
2016/03/04 13:56:24.037011 publish.go:274: INFO No outputs are defined. Please define one under the output section.
Start error: error Initialising publisher: No outputs are defined. Please define one under the output section.

2016/03/04 13:56:24.037804 beat.go:126: CRIT Start error: error Initialising publisher: No outputs are defined. Please define one under the output section.
2016/03/04 13:56:24.038129 beat.go:307: INFO Start exiting beat
2016/03/04 13:56:24.038403 beat.go:282: INFO Stopping Beat
2016/03/04 13:56:24.038768 beat.go:290: INFO Cleaning up filebeat before shutting down.
2016/03/04 13:56:24.039192 beat.go:139: INFO Exit beat completed
```

Once the output is defined in the main configuration file, then I can see how `filebeat` parses the extra configuration files placed at `config_dir`.

Is that behaviour by design ? Anyway to workaround it?

Thanks!

**Comment by ruflin** [comment] 2016-03-04 14:40
That behaviour is by design. As this is a filebeat only feature only the prospector parts are read from the config_dir files (see the docs here: https://www.elastic.co/guide/en/beats/filebeat/current/configuration-filebeat-options.html#_config_dir). 

It is not possible to define outputs per prospectors. Here is an issue related to that: https://github.com/elastic/beats/issues/1035

Closing this at it is not a bug.

**Closed by ruflin** 2016-03-04 14:40 UTC
Labels: Filebeat, question

**Comment by tripledes** [comment] 2016-03-04 14:49
@ruflin thanks for the explanation, somehow I overlooked that part of the documentation. I'll keep the discuss in mind for next time, sorry about that.

**Comment by Justhing** [comment] 2019-01-31 08:14
Oh! it solved my problem
