### ISSUE TITLE
[Heartbeat][Agent] Heartbeat won't start when executed as root 

### ISSUE THREAD

**Issue by emilioalvap** [elastic/beats#30171] opened 2022-02-02 22:09 UTC
# Environment
**Version:** 7.16.3 
**Operating System:** Centos 7, dockerised

## Steps to Reproduce
1. Start docker container with root user and  monitor configuration that will kick off heartbeat (local or fleet-managed):
`docker run --rm --name=agent  --user=root --env FLEET_ENROLL=1 --env FLEET_URL=<url> --env FLEET_ENROLLMENT_TOKEN=<token> docker.elastic.co/beats/elastic-agent:7.16.3`
2. Check that `heartbeat` is reported as missing check unresponsive:
````
2022-02-02T22:14:03.608Z        INFO    log/reporter.go:40      2022-02-02T22:14:03Z - message: Application: heartbeat--7.16.3[34930eab-508d-45c6-b839-5787ec1ca7eb]: State changed to DEGRADED: Missed last check-in - type: 'STATE' - sub_type: 'RUNNING'
2022-02-02T22:14:03.608Z        WARN    status/reporter.go:236  Elastic Agent status changed to: 'degraded'
````

It seems when heartbeat executes `setuid` to a different user, it loses the capability to check-in with the agent.
Running container with `--user=root --env BEAT_SETUID_AS=root` works fine.

**Comment by andrewvc** [comment] 2022-02-03 19:48
So it seems like we'll need to adjust he agent seccomp profile then?

**Comment by emilioalvap** [comment] 2022-02-17 19:05
@andrewvc  There seem to be multiple errors raised [here](https://github.com/elastic/beats/blob/79229e7e79ed65e37b0746b306e6ee2e0e6d0690/libbeat/cmd/instance/beat.go#L628) caused by missing permissions for user `elastic-agent`, which prevent `heartbeat` from starting. These are:

```bash
# ls -al data/elastic-agent-5961a2/install/heartbeat-8.2.0-linux-x86_64/
...
-rw------- 1 root root      7276 Feb 17 16:30 heartbeat.yml
# ls -al state/data/logs/
...
drwxr-xr-x 2 root root  4096 Feb 17 16:38 default
# ls -al state/data/tmp/
...
drwxr-xr-x 2 root root  4096 Feb 17 16:38 default
# ls -al  state/data/run/
...
drwxr-x--- 5 root root 4096 Feb 17 18:33 default
```

These are just the permission that need to be adjusted to get heartbeat to execute, there might be other conflicts down the line that I haven't been able to find.

**Comment by emilioalvap** [comment] 2022-03-10 18:29
@andrewvc To provide some additional context on the potential fix. It seems some of the folders with missing permissions that are created from `elastic-agent` are created with correct level (`0775`). From `strace` logs:

````bash
$ grep mkdirat /tmp/agent.* | grep "state/data" | grep default\"
/tmp/agent.379:mkdirat(AT_FDCWD, "/usr/share/elastic-agent/state/data/logs/default", 0775) = 0 --> This one is correct
/tmp/agent.379:mkdirat(AT_FDCWD, "/usr/share/elastic-agent/state/data/tmp/default", 0775) = 0 --> This one too
/tmp/agent.387:mkdirat(AT_FDCWD, "/usr/share/elastic-agent/state/data/run/default", 0750) = 0
````

But these permissions are being combined with the default `umask 0022` inside the container, so the resulting permission is insufficient (`elastic-agent` user needs group write):

````bash
$ ls -al state/data/{logs,tmp,run} | grep default
drwxr-xr-x 2 root root   4096 Mar 10 18:00 default
drwxr-x--- 5 root root 4096 Mar 10 13:29 default
drwxr-xr-x 3 root root 4096 Mar 10 13:28 default
````

This should be fairly simple to fix inside docker container, we can just adapt `umask` to `000X` somewhere along the entrypoint. But to fix this issue on environments other than docker (eg: installed, systemd - managed), it would require adapting `umask` at on multiple locations. For reference, I've found #29708 addressing a similar problem. 

Considering that this issue has been reported internally, I was wondering whether we should focus on fixing the beahviour for docker containers as it seems to be the most plausible use case or update the configuration for all types of installs.

**Comment by andrewvc** [comment] 2022-03-10 23:02
@emilioalvap Hmmm, perhaps we should drop the `setuid` feature in non-docker envs, odd as that is. Our future, IMHO is probably solely supporting docker once the synthetics node integration is ready. I wouldn't want us to deprecate anything else earlier than that, but `setuid` is a relatively new feature for heartbeat, and truthfully most people have historically run it as root.

**Comment by emilioalvap** [comment] 2022-05-23 08:42
Working on` 8.3.0-SNAPSHOT` after merging #31694.

![image](https://user-images.githubusercontent.com/95703246/169778852-f5f12969-d3a7-467b-88fa-0084c0f50fb8.png)

To test: 
- Run `elastic-agent` docker image as `root`:
```
docker run --rm -u root -it --name agent \
    --env FLEET_ENROLL=1 \
    --env FLEET_URL=<FLEET_URL> \
    --env FLEET_ENROLLMENT_TOKEN=<FLEET_TOKEN>  \
    docker.elastic.co/beats/elastic-agent:8.3.0-SNAPSHOT  -e
```
- Check that HB reports as `RUNNING` instead of DEGRADED:
````
message: Application: heartbeat--8.2.0-SNAPSHOT[8d1779e6-2921-46b7-be63-5003c76a186c]: State changed to DEGRADED: Missed last check-in - type: 'STATE' - sub_type: 'RUNNING'","ecs.version":"1.6.0"}
````

**Comment by lucasfcosta** [comment] 2022-06-06 17:28
@emilioalvap I have post-FF tested this and actually had problems when running browser monitors, so I just wanted to ensure that this is expected behaviour for those:

```
{"log.level":"error","@timestamp":"2022-06-06T16:00:03.737Z","log.origin":{"file.name":"monitors/monitor.go","file.line":178},"message":"job could not be initialized: script monitors cannot be run as root","service.name":"heartbeat","ecs.version":"1.6.0"}
```

Besides that, the lightweight monitors I have set have run just fine.

Please notice that the agent also can't run browser monitors when executed as root.

In case you're curious about how I've ran these containers, here are the commands I've used so you can double check.

**Heartbeat**

```sh
docker run \
  -it \
  --rm \
  --name=heartbeat \
  --user=root \
  --volume="/tmp/hb1.yml:/usr/share/heartbeat/heartbeat.yml:ro" \
  --network="elastic-package-stack_default" \
  docker.elastic.co/beats/heartbeat:8.3.0-SNAPSHOT -e
```

**elastic-agent**

* Notice I'm running against a local version of the stack which is in the `elastic-package-stack_default` network.

```
docker run \
  -it \
  --rm \
  --name=elastic-agent \
  --user=root \
  --network="elastic-package-stack_default" \
  --env FLEET_INSECURE=true \
  --env FLEET_ENROLL=1 \
  --env FLEET_URL="http://fleet-server:8220" \
  --env FLEET_ENROLLMENT_TOKEN="<TOKEN>" \
  docker.elastic.co/beats/elastic-agent-complete:8.3.0-SNAPSHOT -e
```

**Comment by lucasfcosta** [comment] 2022-06-07 08:57
Hey @emilioalvap, thanks for the further guidance.

Just one question about the scope of this issue: does it refer to applying the fix for both Heartbeat and `elastic-agent` and the fix has only been applied to `elastic-agent` so far, or does it scope include only `elastic-agent`? I'm asking because if this issue is only about `elastic-agent` then we can close it.

Also, with regards to the test: indeed, although I pruned containers and images, I might still have had another image cached.

I've retested this and it has worked now. Here's the whole process for future reference:

1. I made sure to remove the image for `8.3.0-SNAPSHOT` so that a new one would be pulled (removed it directly rather than pruning to ensure it would indeed be removed and I didn't have any other containers using it)
    ```
        ➜ docker image rm docker.elastic.co/beats/elastic-agent-complete:8.3.0-SNAPSHOT
    Untagged: docker.elastic.co/beats/elastic-agent-complete:8.3.0-SNAPSHOT
    Untagged: docker.elastic.co/beats/elastic-agent-complete@sha256:92aa53a9fff557252313e81282b1bafb3dee3f15bfeaed5d1e6834aae33d8977
    Deleted: sha256:a45edbe78f968e57c8125318934a9c2ef1dd5e70488fcc9e3eb3eff55015554f
    Deleted: sha256:575955510b9ca672091e924a980859b87f4ccb03608b07bfad7e9d77f7945aad
    Deleted: sha256:5b9a7d6b2b28a0b0ce5bd1d0e9df97e173ab91c5c7222c22d277c53bfd7249ad
    Deleted: sha256:b031afec47c5aa114a64782b5fef1b4a420c312690ffa497439749fa79cd5271
    Deleted: sha256:e51a349b8d5d1e4d3243e9167cdab24f785200c0d5678eec9d484a3f1df98ba1
    Deleted: sha256:76df4a01e1a94afc74ec5f1780d9a156051aa757db5cf557cdee9efd688ed914
    Deleted: sha256:790f4e113a9fbc5454bcb94a4033ce73001411d5d4cc1a74cd7ed68040f20d01
    Deleted: sha256:2d056735cbc2b4582edf01bb850010d16a8ffef53132b2029b0560f27793aea6
    Deleted: sha256:a0f01184dce3a27136856cd717c4c54d26762e2a8d16d5af7a64b25457d0ca84
    Deleted: sha256:0e672e51b9f647b1dbe22ce8cd2fc48d3b555b6394bdc5337e692f45eda77c0a
    Deleted: sha256:41ae1273942d19e59feae2f7a76acdd83bc03b77211dad95b577dc89f263b745
    Deleted: sha256:bbf4de5cf9875505453e43d4b1503af589279979628d725e45070ac74c7846c7
    Deleted: sha256:cd1f677dfddd95761b5c9464c3879ead121c4eff620b39ded2f64c1124a93f73
    Deleted: sha256:4da4574083a1ffd9fcb8ed361608e3cd2a9bebb0c57aef33ffab159a72746a3f
    Deleted: sha256:95c0f602bf07a69b73f856f84db18291da42666dbe7b77a0c72614221eb7ef44
    Deleted: sha256:2196ff44dc8a019add20f994195f4b4fdc8297cb540fdbca313e2a33e21c134f
    Deleted: sha256:890b4b1dbe5f68e4493341bdb84d1bf3239b7af9f70281424debc6d5df71c68a
    ```
2. I obtained the `FLEET_ENROLLMENT_TOKEN` for an agent policy in `Management > Fleet > Enrollment Tokens`
    ![Screenshot 2022-06-07 at 09 47 46](https://user-images.githubusercontent.com/6868147/172338241-d19dd5bb-1e8e-4d64-8d26-2dfffc7ec4b2.png)
3. I've ran the following command to start a container as root.
    ```
        docker run \
      -it \
      --rm \
      --name=elastic-agent \
      --network="elastic-package-stack_default" \
      --env FLEET_INSECURE=true \
      --env FLEET_ENROLL=1 \
      --env FLEET_URL="http://fleet-server:8220" \
      --env FLEET_ENROLLMENT_TOKEN="<TOKEN>" \
      docker.elastic.co/beats/elastic-agent-complete:8.3.0-SNAPSHOT -e
    ```
4. I created a browser monitor for that policy.
   ![Screenshot 2022-06-07 at 09 50 50](https://user-images.githubusercontent.com/6868147/172338863-722e9b9b-c7a1-4b71-b053-b92d6e16e282.png)
 5. The monitor appeared in `Uptime` 🤔 
 6. If I create an HTTP monitor, it also works fine.

**Closed** 2022-06-07 09:13 UTC
Labels: bug, Team:Uptime, v8.3.0
