### ISSUE TITLE
[Fleet]: Log level dropdown is blank under Logs tab.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#27405] opened 2021-08-12 07:43 UTC
**Kibana version:** 7.15.0 Snapshot Kibana cloud environment

**Host OS and Browser version:** All, All

**Build details:**
```
Build: 43322
Commit: f448fcd00b319a3be0d1a1ae356956446e4d7ef8
Artifact Link: https://snapshots.elastic.co/7.15.0-af472020/downloads/beats/elastic-agent/elastic-agent-7.15.0-SNAPSHOT-linux-x86_64.tar.gz
```

**Preconditions:**
1. 7.15.0 Snapshot Kibana cloud environment should be available.
2. An agent must be installed with Default policy having System integration.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Agents>Logs tab.
3. Click Log level dropdown and observe no log level filters available.

**Expected Result:**
Log level dropdown should give user options to select log level say- error, info, debug, warn etc.

**Screenshot:**
![5](https://user-images.githubusercontent.com/77374876/129157543-4e671fd5-679c-4db4-871f-8520fa3a6257.JPG)

**Comment by jen-huang** [comment] 2021-08-16 19:20
@ruflin Do you think this could have been caused by recent changes we made to `elastic_agent` package data stream definitions? Did the package prior to those changes have mappings for `log.*` fields?

The dropdown in the UI uses a terms agg on `log.level` to populate the values, I think it's failing now (no terms are returned) due to the lack of keyword mappings. This used to work so I'm wondering what changed.

**Comment by ruflin** [comment] 2021-08-17 08:51
Yes, this is very likely to my change to the package. By default I turned dynamic mappings off, that is why it worked before as it just mapped everything. I see @nchaulet is working on a PR for elastic agent package, will this also be addressed?

**Comment by nchaulet** [comment] 2021-08-17 13:45
> Yes, this is very likely to my change to the package. By default I turned dynamic mappings off, that is why it worked before as it just mapped everything. I see @nchaulet is working on a PR for elastic agent package, will this also be addressed?

Yes I can add the mapping back in the same PR

**Comment by jen-huang** [comment] 2021-08-17 16:41
Thanks @nchaulet, I'll assign this one to you.

**Closed** 2021-08-19 19:03 UTC
Labels: bug, Team:Agent
