### ISSUE TITLE
[Filebeat] AWS S3 Input add multiline support

### ISSUE THREAD

**Issue by 111andre111** [elastic/beats#23350] opened 2021-01-05 00:10 UTC
**Describe the enhancement:**
At the moment AWS S3 Input doesn't offer multiline support

**Describe a specific use case for the enhancement or feature:**
In AWS S3 streaming to SQS there might be occasions for log files that hold multiline log lines like for instance AWS Hadoop or other Java products
https://www.elastic.co/guide/en/beats/filebeat/master/filebeat-input-s3.html
https://github.com/elastic/beats/blob/master/x-pack/filebeat/input/s3/config.go#L12
Would it be possible to add multiline support please like there exist for logs input already??
https://www.elastic.co/guide/en/beats/filebeat/master/multiline-examples.html
https://github.com/elastic/beats/blob/master/filebeat/input/log/config.go#L34
https://github.com/elastic/beats/blob/master/filebeat/input/log/config.go#L70

**Comment by kaiyan-sheng** [comment] 2021-05-05 15:59
Closing this issue as a duplicate of https://github.com/elastic/beats/issues/25249.

**Closed by kaiyan-sheng** 2021-05-05 15:59 UTC
Labels: Filebeat, Team:Integrations, enhancement
