### ISSUE TITLE
filebeat init script 

### ISSUE THREAD

**Issue by OwaisAhmadJan** [elastic/beats#2776] opened 2016-10-13 18:53 UTC
On CentOS 7 using version 1.3.1 [source](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-installation.html)
I am getting the following:

```
/etc/init.d/filebeat: line 34: /etc/rc.d/init.d/functions: No such file or directory
/etc/init.d/filebeat: line 38: status: command not found
/etc/init.d/filebeat: line 78: status: command not found
```

**Comment by monicasarbu** [comment] 2016-10-13 22:22
This file is provided by the `initscripts` package, which isn't included by default in the CentOS 7 image. Please try to install `initscripts` package, and then try again to start Filebeat.

**Comment by OwaisAhmadJan** [comment] 2016-10-14 06:01
Okay, now its:
/etc/init.d/filebeat status
Failed to get D-Bus connection: Operation not permitted
Failed to get D-Bus connection: Operation not permitted

**Comment by tsg** [comment] 2016-10-14 09:25
How did you install Centos 7? Are you inside docker by any chance?

**Comment by OwaisAhmadJan** [comment] 2016-10-14 09:34
Yes, inside docker with --privileged flag on.

**Comment by tsg** [comment] 2016-10-14 09:38
Then using the init script is probably not the right approach. Are you trying to have Filebeat in its own container or installed together with the application in the same container?

**Comment by OwaisAhmadJan** [comment] 2016-10-14 09:40
together with an app in the same container.

**Comment by tsg** [comment] 2016-10-14 10:01
I'd then recommend using something like [supervisord](https://docs.docker.com/engine/admin/using_supervisord/) to start both the application and filebeat. Unfortunately Docker doesn't make it easy to run multiple apps in the same container.

I'm closing this one because we're trying to keep Github for confirmed bugs and enhancement requests only. Please open a topic on [Discuss](https://discuss.elastic.co/) if you encounter other issues.

**Closed by tsg** 2016-10-14 10:01 UTC
Labels: needs details, question
