### ISSUE TITLE
[Filebeat] Add support for SLES 15

### ISSUE THREAD

**Issue by gemaliano** [elastic/beats#27230] opened 2021-08-04 09:31 UTC
**Describe the enhancement:**
Add SLES 15 support for filebeats
It is not in the support matrix https://www.elastic.co/support/matrix

**Comment by EricDavisX** [comment] 2021-08-04 21:00
@mostlyjason @nimarezainia @ruflin @urso if there isn't any known Technical limitation currently, it is under the purview of the qa /test team to do a test run on a new OS to see how it goes and test drive it for addition in the next cycle.

**Comment by EricDavisX** [comment] 2021-08-10 18:22
The Engg Productivity group has confirmed a template in our Endgame vSphere cluster:
qa-suse-les-15.2-x64-clone-base
@amolnater-qasource @dikshachauhan-qasource if you can schedule a test for 7.15 timeframe (as near-term as we can) that will help.  Let's run the stand-alone filebeat test as well as a basic System/Linux/Endpoint test on Agent side and verify data collection and a spot check of individual document details from each stream. 

@ruflin would this one-off test suffice for citing support if no issues are found?  or would you want a commitment to test it every minor cycle (at a minimum) to ensure, until such time as we have automation support?  This is getting into team process and strategy side thinking, feel free to take it off line to chat / review intentions if desired.

**Comment by amolnater-qasource** [comment] 2021-08-11 10:30
Hi @EricDavisX 
We have attempted to install filebeat and agent on `qa-suse-les-15.2-x64-clone-base`. However, due to Vsphere issues we are unable to install them.
Somehow we were able to access the VMs and setup the filebeat and agent folders. However on running install or setup commands it shows connectivity errors due to Vsphere issues. These connectivity errors are observed on all Linux and Mac VMs.

We will be re-testing this as soon as Vsphere issues will be fixed.

Thanks
QAS

**Comment by amolnater-qasource** [comment] 2021-08-12 06:47
Hi @EricDavisX 
We have attempted to install filebeat and Linux.tar.gz agent with `qa-suse-les-15.2-x64-clone-base` on 7.15.0 snapshot.

**Observations:**
- Filebeat installed successfully and filebeat data is available under Discover tab.
- Linux Agent installed successfully with default policy having System integration and data for elastic_agent and System integration is available under Data Streams tab.
- On adding Endpoint Security, agent is available under Endpoints tab.

**Screenshots:**
![sles](https://user-images.githubusercontent.com/77374876/129149283-81769e45-7658-47f0-820a-cf46424a4e6a.png)

**Build details:**
```
Build: 43322
Commit: f448fcd00b319a3be0d1a1ae356956446e4d7ef8
Artifact Link: https://snapshots.elastic.co/7.15.0-af472020/downloads/beats/elastic-agent/elastic-agent-7.15.0-SNAPSHOT-linux-x86_64.tar.gz
```

Please let us know if anything else is required.
Thanks
QAS

**Comment by EricDavisX** [comment] 2021-08-12 16:56
Thank you! This is enough for now - we have a larger decision on the team as to if we can / should / will support SLES, including SLES 15 - it isn't in the support matrix yet, so adding it requires (ideally, and likely, several efforts to add it to automated test regimen for several repos).

We will post back when we can cite more details, hopefully with a public 'plan' about how we approach the questions that come up for support and a list of what services need updating and what manual tests would be needed to supplement. Cheers.

**Comment by amolnater-qasource** [comment] 2021-08-13 07:04
Thanks for the confirmation @EricDavisX . Could you please confirm if we need to add testcases for the SLES 15 support for agent and filebeat in our test suite?

If we need to cover SLES 15 testing regularly we can add testcases with below scenarios:
- Filebeat installation
- Agent installation
- Agent reboot
- Agent support with Endpoint Security and visibility under Endpoints tab.

Thanks!

**Comment by EricDavisX** [comment] 2021-08-16 18:14
@amolnater-qasource @dikshachauhan-qasource hi - I don't want to create a specific SLES 15 test group.  But, you've triggered my thinking!  We should copy the above (and add in a next level of detail, I think) and call it a 'Agent & Beats platform certification' test group.  I'd expect it to have those tests as well as some data oriented tests on the key Integrations (System, Windows, Linux, Endpoint) and verification of data ingest.

**Comment by amolnater-qasource** [comment] 2021-08-17 09:13
Hi @EricDavisX 
We have created 05 testcases for SLES 15 support covering scenarios like reboot, support with System, Linux and Endpoint integrations under "Agent & Beats platform certification" section in our Ingest Manager test suite:
[C149911](https://elastic.testrail.io/index.php?/cases/view/149911)
[C149912](https://elastic.testrail.io/index.php?/cases/view/149912)
[C149913](https://elastic.testrail.io/index.php?/cases/view/149913)
[C149916](https://elastic.testrail.io/index.php?/cases/view/149916)
[C149919](https://elastic.testrail.io/index.php?/cases/view/149919)

Further, we already have installation and reboot tests on many Windows OS like:
- Windows 10
- Windows 8.1
- Windows Server 2019
- Windows Server 2012 r2
- Windows Server 2016

We also cover specific data oriented tests for System, Windows, Linux and Endpoint integrations. 
Currently we test Windows integration with Windows 10.
Linux integration with Ubuntu, Centos and (now SLES 15).

Please let us know if any particular OS's with related scenarios to be covered, we will create/update our test content accordingly.
Thanks

**Comment by amolnater-qasource** [comment] 2021-08-19 07:34
Hi @EricDavisX 
As per feedback we have created **02** new testcases for SLES 15 covering following scenarios:
- [C149941](https://elastic.testrail.io/index.php?/cases/view/149941) - Validate user is able to install Fleet Server on SLES 15.
- [C149942](https://elastic.testrail.io/index.php?/cases/view/149942) - Validate user is able to reboot Fleet Server installed on SLES 15 and new data is generated after reboot.

Further we will be creating these set of 07 testcases for any new OS that needs to be supported.

Please let us know if anything else is required from our end.
Thanks

**Comment by nimarezainia** [comment] 2021-08-19 17:37
@gemaliano Do you think there's a possibility that this customer could move to using the new Elastic Agent that just went GA - if SLES15 was supported there?

Would you know if:
1) they have other beats installed on these hosts?
2) what modules they are using with these beats?

thanks

**Comment by amolnater-qasource** [comment] 2022-10-31 07:02
Hi @gemaliano 
We cover the testing on SLES-15 for every release versions under testcases shared under https://github.com/elastic/beats/issues/27230#issuecomment-900130348

Further the support matrix is also updated for SLES 15 under https://www.elastic.co/support/matrix

**Screen Recording:**

https://user-images.githubusercontent.com/77374876/198940384-71eaa8af-aff3-4592-8652-c355d19831e7.mp4

Hence, this ticket can be closed.
Thanks

**Closed** 2022-11-30 20:29 UTC
Labels: enhancement, Team:Elastic-Agent
