### ISSUE TITLE
[Winlogbeat] Object types and names automatic translation

### ISSUE THREAD

**Issue by astefan** [elastic/beats#4881] opened 2017-08-11 16:35 UTC
Pretty much the feature described in [this discuss post](https://discuss.elastic.co/t/winlogbeat-displaying-guid-in-windows-events-instead-of-object-name/71442): a way of translating the SIDs into their actual readable names.

**Comment by andrewkroh** [comment] 2020-02-04 00:47
Duplicate of the newer #7451. There is a PR to implement this in #16013.

**Closed by andrewkroh** 2020-02-04 00:47 UTC
Labels: Winlogbeat, enhancement
