### ISSUE TITLE
Multiline returning an invalid @timestamp

### ISSUE THREAD

**Issue by gregdurham** [elastic/beats#784] opened 2016-01-20 19:19 UTC
Hello, Using the latest nightly of filebeat 1.1.0 I see that filebeat is sending a message with a timestamp of: "@timestamp": "0001-01-01T00:00:00.000Z",

Here is the log of the event.
```
Publish: {
  "@timestamp": "0001-01-01T00:00:00.000Z",
  "beat": {
    "hostname": "my.host.name",
    "name": "my.host.name"
  },
  "count": 1,
  "fields": null,
  "input_type": "log",
  "message": "01/20/16 18:57:27:414 ERROR Long stack trace....",
  "offset": 54586,
  "source": "/path/to/log.log",
  "tags": [
    "tag1",
    "tag2",
    "tag3"
  ],
  "type": "myType"
}
```
As you can see minus the redactions, it appears to work properly, other than the timestamp not being correct. 

Here is my configuration:
```filebeat:
  # List of prospectors to fetch data.
  prospectors:
    -
      paths:
        - "/path/to/log.log"
      document_type: myType
      multiline:
        pattern: ^[[:digit:]]\{2\}\/[[:digit:]]\{2\}\/[[:digit:]]\{2\}
        negate: true
        match: after
```

**Comment by ruflin** [comment] 2016-01-21 07:42
Which OS are you on? Can you provide the link to the exact snapshot you downloaded?

**Comment by gregdurham** [comment] 2016-01-21 16:02
RHEL 6 -
https://download.elastic.co/beats/filebeat/filebeat-1.1.0-SNAPSHOT-x86_64.rpm

**Comment by gregdurham** [comment] 2016-01-21 17:37
I may have found another bug as well, it could also be my configuration, but with the above configuration it is capturing 2 lines together even if they both match the pattern. 
```
{
"message":"01/21/16 17:28:13:477 .......\n01/21/16 17:28:13:477.....",
"@version":"1",
"@timestamp":"0001-01-01T00:00:00.000Z",
"beat":{"hostname":"this.host.name","name":"this.host.name"},
"count":1,
"fields":null,
"input_type":"log",
"offset":28510,
"source":"/path/to/log.log",
"tags":["tag1","tag2","tag3"],
"type":"myType",
"host":"this.host.name"
}
```

**Comment by ruflin** [comment] 2016-01-21 21:29
@gregdurham I managed to reproduce the timestamp issue. It seems to be related to some multiline configurations. I will let you know as soon as we have a fix. I will also look into the second issue. Thanks for reporting this.

**Comment by urso** [comment] 2016-01-21 22:55
good news is I have a fix ready. Bad news is, this issue will be automatically closed when fix gets merged.

@gregdurham the regex of type "after" is run on second line only. The regex looks fine in general, no idea why it's matching. Btw. when putting the regex in single quotes you don't have to escape all those characters in your regex I think

**Comment by urso** [comment] 2016-01-21 23:04
@gregdurham some [golang playground for testing your regex](http://play.golang.org/p/78Yc6hsud_). None of the lines seem to match the regex, that's why they are merged if negate is set to true. Removing the escaping to have

    var pattern = `^[[:digit:]]{2}/[[:digit:]]{2}/[[:digit:]]{2}`

makes the pattern match. Due to YAML requiring some escaping sometimes and sometimes not, try to put your regex inside single quotes and remove escapings.

**Comment by gregdurham** [comment] 2016-01-21 23:26
Ill give that a shot. Strange thing is this doesn't happen all of the time. Ill get that tested. And if you have a fix close out this issue. Ill test it with tonight's nightly and report back if it is still an issue in the coming days.

**Comment by urso** [comment] 2016-01-21 23:33
@gregdurham no nightlies yet. First needs some review and merge. Hopefully done by tomorrow.

**Comment by gregdurham** [comment] 2016-01-21 23:34
Cool, sounds good. Thanks for the responsiveness.

**Comment by gregdurham** [comment] 2016-01-25 16:46
Just an FYI the wrapping the regex pattern in single quotes solved the issue.

**Comment by ruflin** [comment] 2016-01-25 19:23
@gregdurham Thanks for reporting back. In the meantime https://github.com/elastic/beats/pull/808 was merged. Did you already have a chance to try it out? If not here are the links to the most recent builds:

https://download.elastic.co/beats/filebeat/filebeat-1.1.0-darwin.tgz
https://download.elastic.co/beats/filebeat/filebeat-1.1.0-x86_64.rpm
https://download.elastic.co/beats/filebeat/filebeat_1.1.0_i386.deb
https://download.elastic.co/beats/filebeat/filebeat-1.1.0-windows.zip
https://download.elastic.co/beats/filebeat/filebeat-1.1.0-i686.rpm
https://download.elastic.co/beats/filebeat/filebeat_1.1.0_amd64.deb
https://download.elastic.co/beats/filebeat/filebeat-1.1.0-x86_64.tar.gz
https://download.elastic.co/beats/filebeat/filebeat-1.1.0-i686.tar.gz

Will close this issue, please reopen if the issue persists.

**Closed by ruflin** 2016-01-25 19:23 UTC
Labels: bug, Filebeat

**Comment by gregdurham** [comment] 2016-01-25 19:34
Thanks for the update, Ill get this out with our next rollout today.
