### ISSUE TITLE
[Metricbeat] Discrepancy in graphs when using Prometheus query metricset 

### ISSUE THREAD

**Issue by sorantis** [elastic/beats#17931] opened 2020-04-23 11:18 UTC
When using Prometheus `query` metricset with queries like `rate(node_cpu_seconds_total{mode="system", cpu="7"}[1m])` sometimes a corresponding graph visualized in Kibana is different from what Prometheus server shows:

Kibana:
![image](https://user-images.githubusercontent.com/1685068/80093464-d2ea0f80-8564-11ea-9fec-29077444c9e6.png)

Prometheus:
![image](https://user-images.githubusercontent.com/1685068/80093477-dbdae100-8564-11ea-8c74-02a5886063ae.png)

From these graphs it's clear that some spikes/sinks are not visualized in Kibana.

cc: @exekias @ChrsMark

**Comment by ChrsMark** [comment] 2020-10-21 09:48
Hey @sorantis , what kind of visualisation/aggregation do you use? Could it be that Prometheus plots the rate directly but on Kibana we have an extra aggregation on it like `avg`?

**Comment by ChrsMark** [comment] 2022-02-17 11:53
Tried to reproduce and move it forward:
<img width="1364" alt="Screenshot 2022-02-17 at 1 52 54 PM" src="https://user-images.githubusercontent.com/11754898/154476200-c0b3a000-c5b7-42af-9b20-288bca5758d2.png">
<img width="1617" alt="Screenshot 2022-02-17 at 1 52 41 PM" src="https://user-images.githubusercontent.com/11754898/154476215-11d03519-cea8-4be2-90dd-5f48a9730895.png">



It's clear that we cannot completely replicate what we see in Prometheus graphs since we lack a way to represent the absolute values of the metrics and instead we are only able to plot based on specific aggregations like `avg`, `max`, `rate`. 
In this regard I'm not sure if we can evaluate this further and I would expect that waiting for TSVB improvements (https://github.com/elastic/elasticsearch/issues/74660) is the only option at the moment.

For future reference I'm posting a configuration to re-produce the environment:

`metricbeat/modules.d/prometheus.yml`:
```
- module: prometheus
  metricsets: ["query"]
  hosts: ["0.0.0.0:9090"]
  period: 10s
  queries:
  - name: "instant_vector"
    path: "/api/v1/query"
    params:
      query: 'rate(node_cpu_seconds_total{cpu="7",instance="nodeexporter:9100",job="nodeexporter",mode="system"}[1m])'
```

Prometheus setup: [docker-prometheus-playground](https://github.com/ChrsMark/docker-prometheus-playground)

@jsoriano since we were involved in metrics efforts feel free to comment here!

cc: @akshay-saraswat @masci

**Comment by jsoriano** [comment] 2022-02-17 13:08
Could this be also a problem of resolution? The Prometheus graph seems to have a 3s resolution, the config above is collecting the data with a 10s period. Do we have more similar graphs if we reduce the period? Can we make the Metrics Explorer to draw the graphs with "more dots"?

https://github.com/elastic/elasticsearch/issues/74660 may definitely help improving storage efficiency if we need to store more date to provide more similar results.

**Comment by ChrsMark** [comment] 2022-02-17 13:16
The thing is that we have 2 different things here:

Prometheus -> `rate(node_cpu_seconds_total{cpu="7",instance="nodeexporter:9100",job="nodeexporter",mode="system"}[1m])`
Kibana -> `avg(rate(node_cpu_seconds_total{cpu="7",instance="nodeexporter:9100",job="nodeexporter",mode="system"}[1m])`

At Kibana we need to use an extra aggregation to plot which brings us to have 2 different aggregations/plots to compare.

If this is true, we can only have an "approximate" solution and talking about discrepancies at this specific metricset/visualisation is sth quite obvious.

**Comment by jsoriano** [comment] 2022-02-17 14:23
> At Kibana we need to use an extra aggregation to plot which brings us to have 2 different aggregations/plots to compare.

Yes, to avoid the extra aggregation we need tsid-aware indexes and queries (phases 2 and 3.2 in https://github.com/elastic/elasticsearch/issues/74660).

What I was wondering is if we can get more similar results, even now, if we collect and show the data with lower periods.

**Comment by ChrsMark** [comment] 2022-02-21 11:42
It can be slightly better but again accurate spikes/values are not displayed properly. For now we can suggest lower periods as a workaround to take closer approximates and wait until better support for TSVB arrives.
![Screenshot 2022-02-21 at 11 40 00 AM](https://user-images.githubusercontent.com/11754898/154948581-984a93f8-c807-45a5-8459-a87d957c9747.png)
![Screenshot 2022-02-21 at 11 39 46 AM](https://user-images.githubusercontent.com/11754898/154948599-821eac96-c4b8-4e31-9cf2-ee95cf48399f.png)

Since there is nothing actionable here for now I'm gonna close this issue.

**Closed by ChrsMark** 2022-02-21 11:42 UTC
Labels: bug, Metricbeat, Team:Integrations, [zube]: Investigate, Team:Platforms, Topic:Integrations
