### ISSUE TITLE
[Agent] ECS aligned metadata

### ISSUE THREAD

**Issue by michalpristas** [elastic/beats#15500] opened 2020-01-13 13:53 UTC
As discuseed in elastic/beats#15496 let's enhance metadata sent to fleet and be aligned with ECS

Figure out what we are able to send

Handy link: https://www.elastic.co/guide/en/ecs/current/ecs-os.html

**Comment by ph** [comment] 2020-03-09 13:18
This is a dupe of #14461

**Closed by ph** 2020-03-09 13:18 UTC
Labels: Project:fleet, agent
