### ISSUE TITLE
Default Beats installations don't seem to work with a default XPack installation

### ISSUE THREAD

**Issue by dayjavid** [elastic/beats#2039] opened 2016-07-15 03:18 UTC
I've been fighting this for a few hours now, but I believe I finally resolved my issue and I'm not sure if this counts as a 'bug' per-se, but it was definitely confusing.

Doing a blanket default installation of 5.0-4 across the board:
ES, Kibana, Logstash, Packetbeats, Metricbeats, Filebeats, XPack

I was able to get Filebeat data to insert into ES, but Metricbeats and Packetbeats weren't showing up.

Everything was installed via RPM instructions per the docs.

This is on Centos 6, through a VM on VMWare Workstation running on Win10.
All Version 5.0-alpha4

The only thing I changed from the defaults was the Filebeat config - I added a few more log files to get more data flowing in.

I installed XPack per the documentation to have Marvel access.

A default Packetbeat config was used as well as Metricbeat config.

Ran as a service with sudo service (metric|packet)beat start
and...

No data came through, as well as no log files were being generated in /var/log/packetbeat or /var/log/metricbeat.

After fiddling with it and making some question posts on the discuss forums, I had the idea to disable security and once I did that, and restarted everything, data for both Packet and Metric beats came flowing in.

I will try to reproduce this again tomorrow.

Again, i'm not sure if this counts as a bug, so much as lack of information (or possibly lack of forethought on my part), but I do find it weird that filebeat worked and the other 2 did not.

**Comment by ruflin** [comment] 2016-07-18 08:39
This seems to be the related discuss topic: https://discuss.elastic.co/t/not-seeing-packetbeat-info-no-packetbeat-data-in-elasticsearch-for-5-0-alpha-4/55583/7 Did your configs for filebeat and packetbeat on the output side look identical? Did you configure username / password?

**Comment by dayjavid** [comment] 2016-07-19 14:26
The only changes I made were to the filebeat's input files. The default didn't include many active files, so I added ones such as /var/log/messages. 

I did not touch any authentication parameters on either.

**Comment by ruflin** [comment] 2016-07-20 06:29
For beats to work with Shield you must configure username and password, so this is an expected behaviour. Closing this issue. Please reopen if you think differently.

One thing I added to my list to check is if we show proper error messages in the log in case the authentication fails.

**Comment by dayjavid** [comment] 2016-07-20 14:10
2 Reasons I think this is still an issue:
1. All beats don't seem to react similarly on a default installation - inconsistency
2. With the move to XPack being an all-in-one solution, there is very little mention given to the implications of installing it, thus causing confusion like this.  For point 2, it's not so much I think it's a problem with how the apps work, but may there could be a little more heads-up that when you install XPack (because you can't just install Marvel by itself, and you have to explicitly disable  plugins if you don't want their functionality) there are changes in other apps that you need to make that you might not be aware of.

**Comment by ruflin** [comment] 2016-07-25 06:35
1. The behaviour of all beats should be identical as the use the exact same library and configs for the connection. The difference is that Filebeat waits for ACK and the other beats currently don't. What you are saying is that filebeat data was shipped without setting the auth configs, but the others weren't? That is really strange.
2. Agree here, we should have a look the docs and defaults here. For the defaults there are already some changes in the work to make it easier. An other part is better error messages on the beats side. @dedemorton Can you have a look at the comment above?

@dayjavid We should definitively keep investigating 1. Can you confirm that the part under `General` configuration in the yaml file was identical across the beats?

**Comment by dayjavid** [comment] 2016-08-02 02:22
1. I will work on confirming this. Sorry for the delay, work has been picking up recently.

**Comment by ruflin** [comment] 2016-08-02 08:47
@dayjavid Thanks for the investigations.

**Comment by monicasarbu** [comment] 2017-03-24 13:39
Mark it as enhancement to improve the out-of-the box experience of the Beats with x-pack.

**Closed** 2020-08-08 05:30 UTC
Labels: Stalled, discuss, enhancement, needs_team
