### ISSUE TITLE
Not all fields are present when importing the index-pattern to Kibana 5.6

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#4920] opened 2017-08-16 15:52 UTC
Steps to reproduce:
- start Elasticsearch and Kibana 5.6
- load Metricbeat dashboards to Kibana 5.6, including the rabbitmq ones available under https://github.com/elastic/beats/pull/4912
- Check in Kibana->Management->Index pattern that the fields starting with `rabbitmq` are missing from the `metricbeat-*` index-pattern.

cc-ed @simianhacker

**Comment by tsg** [comment] 2017-10-09 13:27
@monicasarbu I can't reproduce this with either rc1 and beta1, I tried from linux and mac. Not sure what could have been wrong in your run.

**Comment by ruflin** [comment] 2017-11-28 03:57
@tsg @monicasarbu Should we close this one?

**Comment by urso** [comment] 2019-03-03 16:30
No update for 1+ year, plus not reproduced so far.

**Closed by urso** 2019-03-03 16:30 UTC
Labels: :Dashboards, bug, libbeat, v6.0.0-beta1
