### ISSUE TITLE
[TopBeat 1.2.3.] Can't access PID, even with correct rights.

### ISSUE THREAD

**Issue by csuka** [elastic/beats#1897] opened 2016-06-22 14:07 UTC
Original thread here: https://discuss.elastic.co/t/server-2012-r2-some-metrics-not-send/51403
- Version: TopBeat 1.2.3
- Operating System: Windows Server 2012 R2 Standard (VMware host)
- Steps to Reproduce:
- Installed TopBeat via Powershell with Administrator Rights (right click, run as admin). 
- In processes, it is seen that TopBeat is owned by SYSTEM. Topbeat is also executed as SYSTEM.
- The error in topbeat.log with debug level:

2016-05-31T11:00:13+02:00 DBG Skip process pid=0: error getting process state for pid=0: OpenProcess fails with The parameter is incorrect.
2016-05-31T11:00:13+02:00 DBG Skip process pid=4: error getting process state for pid=4: OpenProcess fails with Access is denied.
2016-05-31T11:00:13+02:00 DBG Windows is interactive: false

For convience, the full image:
![lpv5ave](https://cloud.githubusercontent.com/assets/7441388/16269532/f3292dee-3892-11e6-8014-6ed065096b13.png)

**Comment by asednev** [comment] 2016-10-05 05:23
This issue also exists in Topbeat 1.3.1

**Comment by tsg** [comment] 2016-10-05 07:20
It would be useful to know what processes are not captured. The low PIDs numbers make me think they are system processes.

@asednev To clarify, you get the error for some of the processes but most of the processes are captured?

**Comment by asednev** [comment] 2016-10-05 08:07
In my case none of the processes were captured.

**Comment by tsg** [comment] 2016-10-05 10:06
What Windows version do you have? You start the Powershell session with "Run as Administrator", right?

**Comment by asednev** [comment] 2016-10-05 17:11
Windows Server 2012 R2 version 6.3 (build 9600)

btw, I discovered that older version Topbeat 1.2.3 works well on the same VM.

**Comment by asednev** [comment] 2016-10-05 17:15
Topbeat 1.3.1 I ran as windows service running under "Local Server" and also from command prompt "Run As Administrator". Neither worked.

Topbeat 1.2.3 mysteriously works.

**Comment by andrewkroh** [comment] 2016-10-12 04:12
To help debug the issue, could you use [SysInternals - Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer) to examine the permissions of the running process.

I suspect the interesting privilege might be the SeDebugPrivilege.

<img width="433" alt="topbeat-1 3 1_as_service" src="https://cloud.githubusercontent.com/assets/4565752/19297054/337b428c-900f-11e6-88dc-f3f4cd5a29d8.png">
<img width="435" alt="topbeat-1 3 1_as_user" src="https://cloud.githubusercontent.com/assets/4565752/19297055/337e9fea-900f-11e6-9f1f-1de2e641cb96.png">

**Comment by andrewkroh** [comment] 2016-10-12 13:59
There is [one place in gosigar](https://github.com/elastic/gosigar/blob/master/sigar_windows.go#L400) where it requests PROCESS_ALL_ACCESS permission but the operation that it performs, [GetProcessMemoryInfo](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683219%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396), requires only PROCESS_QUERY_INFORMATION and PROCESS_VM_READ. gosigar should only request the permissions that it requires. Not sure if this would address the problem at hand, but in any case it's something that should be changed.

In other parts of gosigar it requests PROCESS_QUERY_INFORMATION, but in Windows Vista and newer there is a more limited privilege we can request called PROCESS_QUERY_LIMITED_INFORMATION. This can be used for [GetProcessTimes](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683223%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396), [GetProcessImageFileName](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683217(v=vs.85).aspx), and [GetExitCodeProcess](https://msdn.microsoft.com/en-us/library/windows/desktop/ms683189(v=vs.85).aspx). It cannot be used for [OpenProcessToken](https://msdn.microsoft.com/en-us/library/windows/desktop/aa379295(v=vs.85).aspx).

**Comment by andrewkroh** [comment] 2016-10-13 02:03
I haven't figured out what OS settings are causing the issue for these users. Some feedback is required (see my earlier request for SysInternals data).

I have made the changes mentioned in my previous comment. See elastic/gosigar#50. We can put together a build of Topbeat/Metricbeat with these changes and see if the issue persists.

**Comment by monicasarbu** [comment] 2016-10-13 12:52
Closing for now. @csuka Feel free to re-open the issue if the error persists.

**Comment by andrewkroh** [comment] 2016-10-17 14:57
@csuka @asednev Would you be able to test the [snapshot build of Metricbeat](https://beats-nightlies.s3.amazonaws.com/index.html?prefix=metricbeat/) containing my changes on a machine that was having the "Access is denied" problem for all processes. BTW Metricbeat is [replacing](https://www.elastic.co/blog/beats-5-0-0-alpha3-released) Topbeat in 5.0.

Access is denied is expected for some system processes, specifically the csrss.exe processes. And "incorrect parameter" is expected for PID 0. From the [`OpenProcess`](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684320%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) docs:

> If the specified process is the System Process (0x00000000), the function fails and the last error code is ERROR_INVALID_PARAMETER. If the specified process is the Idle process or one of the CSRSS processes, this function fails and the last error code is ERROR_ACCESS_DENIED because their access restrictions prevent user-level code from opening them.

**Comment by csuka** [comment] 2016-10-18 14:04
@andrewkroh Destroyed the VM on which it was failing.
Will check if I can run it somewhere else, will take a while.

**Comment by asednev** [comment] 2016-10-26 16:46
@andrewkroh, I tried   metricbeat-6.0.0-alpha1-SNAPSHOT-windows-x86_64 and it still threw same errors:

`2016/10/26 16:44:33.521779 helper.go:276: ERR Error getting process details pid=91076: error getting process mem for pid=91076: OpenProcess
fails with Access is denied.


2016/10/26 16:44:33.527793 helper.go:276: ERR Error getting process details pid=702776: error getting process mem for pid=702776: OpenProces
s fails with Access is denied.`

**Comment by andrewkroh** [comment] 2016-10-26 16:51
@asednev Thanks for testing. Can you check in the process explorer what the names of those processes are? Are you seeing any events in Elasticsearch where `metricset.name:process`?

**Comment by asednev** [comment] 2016-10-26 16:57
I don't see any events with `metricset.name:process` in Elasticsearch. Only cpu, memory, filesystem, and network. 

Actually the list of PID in the output was rather long. I only copied 2 as an example. I went through the list of PID, these are the processes that I'm looking to monitor - our application services.

**Comment by andrewkroh** [comment] 2016-10-26 17:14
Sounds like the changes I made didn't help. In the metricbeat download you used, can you tell me what the commit has is inside the `.build_hash.txt` file. Just want to confirm that the version has my changes.

Are you aware of any local or group security policies that were tightened on this machine? The reason I ask is that it would be nice to be able to reproduce this locally so I don't have to take up your valuable time.

Could you run Sysinternals - ProcExp (like I did in https://github.com/elastic/beats/issues/1897#issuecomment-253114611) and check the privileges of Metricbeat?

There is one other change that I think could help. It basically involves escalating the Metricbeat processes access token to include the `SeDebugPrivilege`, like what is described in https://stackoverflow.com/questions/2932461/windows-vista-win7-privilege-problem-sedebugprivilege-openprocess.

**Comment by asednev** [comment] 2016-10-26 17:27
I compared the list of privileges between machine where Metricbeat can get list of processes and machine where Metricbeat can't get the list of processes. The list of privilages is the same. Also, I will reiterate that Topbeat 1.2.3 can get process-level metrics on both of these machines.

![image](https://cloud.githubusercontent.com/assets/3236025/19737054/be06615e-9b66-11e6-861c-b27287d27622.png)
![image](https://cloud.githubusercontent.com/assets/3236025/19737064/caf255a8-9b66-11e6-94ff-80a41afad84d.png)
![image](https://cloud.githubusercontent.com/assets/3236025/19737074/d5a9a44c-9b66-11e6-99ce-990198771373.png)

**Comment by asednev** [comment] 2016-10-26 17:28
Also, it's worth mentioning that machine where Metricbeat can't get process-level metrics is production machine that was hardened by InfoSec team. I'm not entirely sure what exact steps go into hardening.

**Comment by andrewkroh** [comment] 2016-10-26 20:28
@asednev  I added code locally to metricbeat that tries to add `SeDebugPrivilege` to the process' access token. It's just test code at the moment and should print "AdjustTokenPrivileges success" to stdout at start. This version also has a bit more info in the error messages that will help identify the call that failed due to "Access is denied".

https://s3.amazonaws.com/beats-files/metricbeat.exe

If you are willing to try this binary and report the output this would be very helpful. Thanks

**Comment by asednev** [comment] 2016-10-26 20:49
Voila, that fixed the problem. `SeDebugPrivilege` is Enabled in ProcessExplorer and I can see process-level metrics in Elasticsearch.

**Comment by andrewkroh** [comment] 2016-10-26 20:53
Awesome, thanks for the help. I will work on cleaning up my code and put out a PR to address the problem. I'll post here once the changes are available in the regular snapshot build.

**Comment by asednev** [comment] 2016-10-26 21:51
Thank you @andrewkroh. I'm glad you were able to come out of this with a fix.

**Closed** 2016-10-31 14:52 UTC
Labels: bug, Metricbeat, Topbeat, windows

**Comment by andrewkroh** [comment] 2016-10-31 15:40
The snapshot build now has the fix for this if you'd like to test it out. https://beats-nightlies.s3.amazonaws.com/index.html?prefix=winlogbeat/

If you look in the log output there will be some lines containing "SeDebugPrivilege" that provide some feedback. In your case, @asednev, you should see ["SeDebugPrivilege is now enabled."](https://github.com/elastic/beats/blob/master/metricbeat/module/system/system_windows.go#L66).
