### ISSUE TITLE
missing any metrics/(es field) what could matched by regex: kubernetes.container* in docs sending by metribeat

### ISSUE THREAD

**Issue by beylisstan** [elastic/beats#10353] opened 2019-01-27 18:03 UTC
- Version: 
docker.elastic.co/beats/metricbeat                               6.5.4                8a8266b420e5        5 weeks ago         375MB

- Operating System: 
cat /etc/*-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

 kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:28:14Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}

- Discuss Forum URL:
https://github.com/elastic/beats/issues/8574

Please include configurations and logs if available.

Configmap:

Name:         metricbeat-daemonset-modules
Namespace:    monitoring
Labels:       k8s-app=metricbeat
Annotations:  <none>

Data
====
kubernetes.yml:
----
- module: kubernetes
  metricsets:
    - node
    - system
    - pod
    - container
    - volume
  period: 20s
  host: ${NODE_NAME}
  hosts: ["localhost:10255"]
  # Enriching parameters:
  add_metadata: true
  in_cluster: true
- module: kubernetes
  enabled: true
  metricsets:
    - state_node
    - state_deployment
    - state_replicaset
    - state_statefulset
    - state_pod
    - state_container
  period: 10s
  hosts: ["kube-state-metrics:8080"]
  # Enriching parameters:
  add_metadata: true
  in_cluster: true
system.yml:
----
- module: system
  period: 10s
  metricsets:
    - cpu
    - load
    - memory
    - network
    - process
    - process_summary
    - core
    - diskio
    - socket
  processes: ['.*']
  process.include_top_n:
    by_cpu: 20      # include top 20 processes by CPU
    by_memory: 20   # include top 20 processes by memory

- module: system
  period: 1m
  metricsets:
    - filesystem
    - fsstat
  #processors:
  #- drop_event.when.regexp:
  #    system.filesystem.mount_point: '^/(sys|cgroup|proc|dev|etc|host|lib)($|/)'
Events:  <none>

Daemonset:
Name:           metricbeat
Selector:       k8s-app=metricbeat
Node-Selector:  <none>
Labels:         k8s-app=metricbeat
Annotations:    deprecated.daemonset.template.generation: 1
Desired Number of Nodes Scheduled: 3
Current Number of Nodes Scheduled: 3
Number of Nodes Scheduled with Up-to-date Pods: 3
Number of Nodes Scheduled with Available Pods: 3
Number of Nodes Misscheduled: 0
Pods Status:  3 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           k8s-app=metricbeat
  Service Account:  metricbeat
  Containers:
   metricbeat:
    Image:      docker.elastic.co/beats/metricbeat:6.5.4
    Port:       <none>
    Host Port:  <none>
    Args:
      -c
      /etc/metricbeat.yml
      -e
      -d
      publish
      -system.hostfs=/hostfs
    Limits:
      memory:  200Mi
    Requests:
      cpu:     100m
      memory:  100Mi
    Environment:
      POD_NAMESPACE:   (v1:metadata.namespace)
      NODE_NAME:       (v1:spec.nodeName)
    Mounts:
      /etc/metricbeat.yml from config (ro)
      /hostfs/proc from proc (ro)
      /hostfs/sys/fs/cgroup from cgroup (ro)
      /usr/share/metricbeat/modules.d from modules (ro)
      /var/run/docker.sock from dockersock (rw)
  Volumes:
   proc:
    Type:          HostPath (bare host directory volume)
    Path:          /proc
    HostPathType:
   cgroup:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/fs/cgroup
    HostPathType:
   dockersock:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/docker.sock
    HostPathType:
   config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      metricbeat-daemonset-config
    Optional:  false
   modules:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      metricbeat-daemonset-modules
    Optional:  false
   data:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
Events:
  Type    Reason            Age   From                  Message
  ----    ------            ----  ----                  -------
  Normal  SuccessfulCreate  22m   daemonset-controller  Created pod: metricbeat-jgl74
  Normal  SuccessfulCreate  22m   daemonset-controller  Created pod: metricbeat-pq4f8
  Normal  SuccessfulCreate  22m   daemonset-controller  Created pod: metricbeat-vjgvj

- Steps to Reproduce: 

kubectl logs -n monitoring metricbeat-fbpvl | grep -i kubernetes
2019-01-27T17:46:58.885Z	INFO	kubernetes/util.go:71	kubernetes: Using node node2 provided in the config
2019-01-27T17:46:58.885Z	INFO	kubernetes/util.go:71	kubernetes: Using node node2 provided in the config
2019-01-27T17:46:58.948Z	INFO	kubernetes/util.go:71	kubernetes: Using node node2 provided in the config
2019-01-27T17:46:58.948Z	INFO	kubernetes/util.go:71	kubernetes: Using node node2 provided in the config
2019-01-27T17:46:58.948Z	INFO	kubernetes/watcher.go:180	kubernetes: Performing a resource sync for *v1.PodList
2019-01-27T17:46:58.948Z	INFO	kubernetes/watcher.go:180	kubernetes: Performing a resource sync for *v1.NodeList
2019-01-27T17:46:58.949Z	INFO	kubernetes/watcher.go:180	kubernetes: Performing a resource sync for *v1.PodList
2019-01-27T17:46:58.950Z	INFO	kubernetes/watcher.go:180	kubernetes: Performing a resource sync for *v1.PodList
2019-01-27T17:46:58.950Z	INFO	kubernetes/watcher.go:180	kubernetes: Performing a resource sync for *v1beta1.ReplicaSetList
2019-01-27T17:46:58.950Z	INFO	kubernetes/watcher.go:180	kubernetes: Performing a resource sync for *v1beta1.DeploymentList
2019-01-27T17:46:58.950Z	INFO	kubernetes/watcher.go:180	kubernetes: Performing a resource sync for *v1.NodeList
2019-01-27T17:46:58.950Z	INFO	kubernetes/watcher.go:180	kubernetes: Performing a resource sync for *v1beta1.StatefulSetList
2019-01-27T17:46:58.950Z	INFO	kubernetes/watcher.go:180	kubernetes: Performing a resource sync for *v1.PodList
2019-01-27T17:46:58.964Z	ERROR	kubernetes/watcher.go:183	kubernetes: Performing a resource sync err kubernetes api: Failure 403 nodes is forbidden: User "system:serviceaccount:monitoring:metricbeat" cannot list resource "nodes" in API group "" at the cluster scope for *v1.NodeList
2019-01-27T17:46:58.964Z	WARN	util/kubernetes.go:281	Error starting Kubernetes watcher: kubernetes api: Failure 403 nodes is forbidden: User "system:serviceaccount:monitoring:metricbeat" cannot list resource "nodes" in API group "" at the cluster scope
2019-01-27T17:46:58.964Z	INFO	kubernetes/watcher.go:194	kubernetes: Resource sync done
2019-01-27T17:46:58.965Z	INFO	kubernetes/watcher.go:238	kubernetes: Watching API for resource events
2019-01-27T17:46:58.969Z	ERROR	kubernetes/watcher.go:183	kubernetes: Performing a resource sync err kubernetes api: Failure 403 nodes is forbidden: User "system:serviceaccount:monitoring:metricbeat" cannot list resource "nodes" in API group "" at the cluster scope for *v1.NodeList
2019-01-27T17:46:58.969Z	WARN	util/kubernetes.go:281	Error starting Kubernetes watcher: kubernetes api: Failure 403 nodes is forbidden: User "system:serviceaccount:monitoring:metricbeat" cannot list resource "nodes" in API group "" at the cluster scope
2019-01-27T17:46:58.970Z	ERROR	kubernetes/watcher.go:183	kubernetes: Performing a resource sync err kubernetes api: Failure 403 deployments.apps is forbidden: User "system:serviceaccount:monitoring:metricbeat" cannot list resource "deployments" in API group "apps" at the cluster scope for *v1beta1.DeploymentList
2019-01-27T17:46:58.970Z	ERROR	kubernetes/watcher.go:183	kubernetes: Performing a resource sync err kubernetes api: Failure 403 replicasets.extensions is forbidden: User "system:serviceaccount:monitoring:metricbeat" cannot list resource "replicasets" in API group "extensions" at the cluster scope for *v1beta1.ReplicaSetList
2019-01-27T17:46:58.970Z	WARN	util/kubernetes.go:281	Error starting Kubernetes watcher: kubernetes api: Failure 403 replicasets.extensions is forbidden: User "system:serviceaccount:monitoring:metricbeat" cannot list resource "replicasets" in API group "extensions" at the cluster scope
2019-01-27T17:46:58.971Z	ERROR	kubernetes/watcher.go:183	kubernetes: Performing a resource sync err kubernetes api: Failure 403 statefulsets.apps is forbidden: User "system:serviceaccount:monitoring:metricbeat" cannot list resource "statefulsets" in API group "apps" at the cluster scope for *v1beta1.StatefulSetList
2019-01-27T17:46:58.971Z	WARN	util/kubernetes.go:281	Error starting Kubernetes watcher: kubernetes api: Failure 403 statefulsets.apps is forbidden: User "system:serviceaccount:monitoring:metricbeat" cannot list resource "statefulsets" in API group "apps" at the cluster scope
2019-01-27T17:46:58.970Z	WARN	util/kubernetes.go:281	Error starting Kubernetes watcher: kubernetes api: Failure 403 deployments.apps is forbidden: User "system:serviceaccount:monitoring:metricbeat" cannot list resource "deployments" in API group "apps" at the cluster scope
2019-01-27T17:46:58.972Z	INFO	kubernetes/watcher.go:194	kubernetes: Resource sync done
2019-01-27T17:46:58.973Z	INFO	kubernetes/watcher.go:238	kubernetes: Watching API for resource events
2019-01-27T17:46:58.978Z	INFO	kubernetes/watcher.go:194	kubernetes: Resource sync done
2019-01-27T17:46:58.978Z	INFO	kubernetes/watcher.go:238	kubernetes: Watching API for resource events
2019-01-27T17:46:58.978Z	INFO	kubernetes/watcher.go:194	kubernetes: Resource sync done
2019-01-27T17:46:58.978Z	INFO	kubernetes/watcher.go:238	kubernetes: Watching API for resource events
2019-01-27T17:47:28.885Z	INFO	[monitoring]	log/log.go:144	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":620,"time":{"ms":627}},"total":{"ticks":1790,"time":{"ms":1799},"value":1790},"user":{"ticks":1170,"time":{"ms":1172}}},"handles":{"limit":{"hard":1048576,"soft":1048576},"open":15},"info":{"ephemeral_id":"d3fc2732-4945-4323-8887-c7f545b9a978","uptime":{"ms":30040}},"memstats":{"gc_next":15827472,"memory_alloc":13202480,"memory_total":272832488,"rss":62124032}},"libbeat":{"config":{"module":{"running":0},"reloads":1},"output":{"events":{"acked":358,"batches":3,"total":358},"read":{"bytes":108},"type":"logstash","write":{"bytes":25118}},"pipeline":{"clients":8,"events":{"active":0,"filtered":3069,"published":358,"retry":126,"total":3427},"queue":{"acked":358}}},"metricbeat":{"kubernetes":{"container":{"events":2,"failures":2},"node":{"events":2,"failures":2},"pod":{"events":2,"failures":2},"state_container":{"events":3,"failures":3},"state_deployment":{"events":3,"failures":3},"state_node":{"events":3,"failures":3},"state_pod":{"events":3,"failures":3},"state_replicaset":{"events":3,"failures":3},"state_statefulset":{"events":3,"failures":3},"system":{"events":2,"failures":2},"volume":{"events":2,"failures":2}},"system":{"core":{"events":24,"success":24},"cpu":{"events":3,"success":3},"diskio":{"events":189,"success":189},"filesystem":{"events":1,"success":1},"fsstat":{"events":1,"success":1},"load":{"events":3,"success":3},"memory":{"events":3,"success":3},"network":{"events":60,"success":60},"process":{"events":102,"success":102},"process_summary":{"events":3,"success":3},"socket":{"events":3010,"success":3010}}},"system":{"cpu":{"cores":8},"load":{"1":0.49,"15":0.56,"5":0.53,"norm":{"1":0.0613,"15":0.07,"5":0.0663}}}}}}

Metricbeat is not sending any metric what could matched by regex: kubernetes.container*
And look like problem is located on collecting metrics from kubernetes endpoints.

**Comment by alvarolobato** [comment] 2019-02-04 14:36
@jsoriano can you have a look at this?, please.

**Comment by jsoriano** [comment] 2019-02-05 13:54
Hi @beylisstan,

There seems to be some authentication problem there:
```
 2019-01-27T17:46:58.964Z ERROR kubernetes/watcher.go:183 kubernetes: Performing a resource sync err kubernetes api: Failure 403 nodes is forbidden: User "system:serviceaccount:monitoring:metricbeat" cannot list resource "nodes" in API group "" at the cluster scope for *v1.NodeList
```

Please review the permissions given to the service account used by metricbeat.

I am going to close this issue as we prefer to keep them for confirmed bugs and this looks like a configuration problem. Please use https://discuss.elastic.co if you need more help.

**Closed by jsoriano** 2019-02-05 13:54 UTC
Labels: :infrastructure, containers, discuss
