### ISSUE TITLE
Auditbeat agent fails to reconnect to Logstash

### ISSUE THREAD

**Issue by ferozsalam** [elastic/beats#16864] opened 2020-03-06 08:43 UTC
Similar to #16335, we are finding that the Auditbeat agent fails to reconnect to the Logstash instance that it is feeding logs to if the Logstash instance restarts. The Auditbeat agents claim to be able to reconnect to:

```
Feb 26 16:19:26 auditbeat[15518]: 2020-02-26T16:19:26.028Z        ERROR        logstash/async.go:256        Failed to publish events caused by: client is not connected
Feb 26 16:19:27 auditbeat[15518]: 2020-02-26T16:19:27.043Z        ERROR        pipeline/output.go:121        Failed to publish events: client is not connected
Feb 26 16:19:27 auditbeat[15518]: 2020-02-26T16:19:27.043Z        INFO        pipeline/output.go:95        Connecting to backoff(async(tcp://10.1.1.2:5000))
Feb 26 16:19:30 auditbeat[15518]: 2020-02-26T16:19:30.549Z        INFO        pipeline/output.go:105        Connection to backoff(async(tcp://10.1.1.2:5000)) established
Feb 26 16:19:30 auditbeat[15518]: 2020-02-26T16:19:30.559Z        INFO        [publisher]        pipeline/retry.go:196        retryer: send unwait-signal to consumer
Feb 26 16:19:30 auditbeat[15518]: 2020-02-26T16:19:30.559Z        INFO        [publisher]        pipeline/retry.go:198          done
```

...but these logs are not visible in the Elasticsearch cluster that Logstash forwards to.

Restarting the Auditbeat agents fixes this problem, but it doesn't seem like a robust solution. Interestingly, Filebeat (which we are also running) is able to recover connections without an issue.

The version of the agent that I am running is:
`auditbeat version 7.6.0 (amd64), libbeat 7.6.0 [6a23e8f8f30f5001ba344e4e54d8d9cb82cb107c built 2020-02-05 23:03:32 +0000 UTC`

The beats agents are primarily running on Ubuntu 18.04 machines.

We're running Logstash 7.4.2 to collect the logs, in a Kubernetes cluster.

We are able to intermittently reproduce by simply restarting the Logstash instance that an Auditbeat agent is sending logs to.

I posted this a week ago on the [Discuss](https://discuss.elastic.co/t/auditbeat-doesnt-reconnect-after-logstash-restart/221174) page but haven't had any feedback there.

**Comment by jsoriano** [comment] 2020-03-06 10:08
Hi @ferozsalam,

I am going to close it as duplicate of https://github.com/elastic/beats/issues/16335 as it seems to be the same issue, I will add a comment there referencing this issue.

Thanks for reporting!

**Closed by jsoriano** 2020-03-06 10:08 UTC
