### ISSUE TITLE
Flaky Test: TestProduceConsumer/flush

### ISSUE THREAD

**Issue by taylor-swanson** [elastic/beats#31916] opened 2022-06-13 14:00 UTC
## Flaky Test

* **Test Name:** `TestProduceConsumer/flush`
* **Link:** https://github.com/elastic/beats/blob/main/libbeat/publisher/queue/memqueue/queue_test.go#L73
* **Branch:** https://github.com/elastic/beats/pull/31798 (Tests are unrelated to changes in PR, so this should affect `main` as well)
* **Notes:** This test failed in CI, but I'm not able to reproduce it locally. This is most likely a test-issue and not one related to actual code. Running go test with the race detector didn't flag any problems, so this probably isn't a race condition issue. The failure is due to an assert (`libbeat/publisher/queue/queuetest/queuetest.go:234`), which was recently added in #31703.

Here are the test results: https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-31798/10/tests

### Stack Trace

```
=== RUN   TestProduceConsumer/flush
panic: Fail in goroutine after TestProduceConsumer/direct has completed
goroutine 217 [running]:
testing.(*common).Fail(0xc00033a9c0)
	/var/lib/jenkins/workspace/PR-31798-10-cf96cd6a-9844-4712-9d1f-b06a76777b42/.gvm/versions/go1.17.10.linux.amd64/src/testing/testing.go:710 +0xe5
testing.(*common).Fail(0xc00033b040)
	/var/lib/jenkins/workspace/PR-31798-10-cf96cd6a-9844-4712-9d1f-b06a76777b42/.gvm/versions/go1.17.10.linux.amd64/src/testing/testing.go:704 +0x47
testing.(*common).Fail(0xc000356b60)
	/var/lib/jenkins/workspace/PR-31798-10-cf96cd6a-9844-4712-9d1f-b06a76777b42/.gvm/versions/go1.17.10.linux.amd64/src/testing/testing.go:704 +0x47
testing.(*common).Errorf(0xc000416d38, {0xabf265, 0x40c890}, {0xc0001f13e0, 0x203000, 0xaf2440})
	/var/lib/jenkins/workspace/PR-31798-10-cf96cd6a-9844-4712-9d1f-b06a76777b42/.gvm/versions/go1.17.10.linux.amd64/src/testing/testing.go:818 +0x56
github.com/stretchr/testify/assert.Fail({0xb8c940, 0xc000356b60}, {0xac8119, 0xe}, {0x0, 0x0, 0x0})
	/var/lib/jenkins/workspace/PR-31798-10-cf96cd6a-9844-4712-9d1f-b06a76777b42/pkg/mod/github.com/stretchr/testify@v1.7.1/assert/assertions.go:262 +0x384
github.com/stretchr/testify/assert.True({0xb8c940, 0xc000356b60}, 0xc0, {0x0, 0x0, 0x0})
	/var/lib/jenkins/workspace/PR-31798-10-cf96cd6a-9844-4712-9d1f-b06a76777b42/pkg/mod/github.com/stretchr/testify@v1.7.1/assert/assertions.go:657 +0x8e
github.com/elastic/beats/v7/libbeat/publisher/queue/queuetest.testFetchMetrics(0x0, {0xba3258, 0xc00013c3f0})
	/var/lib/jenkins/workspace/PR-31798-10-cf96cd6a-9844-4712-9d1f-b06a76777b42/src/github.com/elastic/beats/libbeat/publisher/queue/queuetest/queuetest.go:234 +0x176
created by github.com/elastic/beats/v7/libbeat/publisher/queue/queuetest.runTestCases.func1
	/var/lib/jenkins/workspace/PR-31798-10-cf96cd6a-9844-4712-9d1f-b06a76777b42/src/github.com/elastic/beats/libbeat/publisher/queue/queuetest/queuetest.go:216 +0x25a
```

**Comment by cmacknz** [comment] 2022-06-13 14:09
Possibly related to the changes for https://github.com/elastic/beats/pull/31703 but it doesn't actually touch this test.

**Comment by cmacknz** [comment] 2022-06-15 17:42
@fearful-symmetry can you see if you can find the cause here? You were the last one to touch the files involved so might have been a side effect of https://github.com/elastic/beats/pull/31703

**Comment by fearful-symmetry** [comment] 2022-06-16 19:08
Yah, I think it might be best to remove that test, since afterwards I created some more in-depth memory tests, so I'm not sure that hacked-on test is actually doing much. Will create a PR in a bit.

**Comment by fearful-symmetry** [comment] 2022-06-20 18:04
Fix merged!

**Comment by jlind23** [comment] 2022-06-20 19:34
Closing this as @fearful-symmetry merged a fix.

**Closed by jlind23** 2022-06-20 19:34 UTC
Labels: flaky-test, Team:Elastic-Agent-Data-Plane, v8.4.0
