### ISSUE TITLE
Adjust Prometheus histogram buckets calculation

### ISSUE THREAD

**Issue by exekias** [elastic/beats#26903] opened 2021-07-15 08:39 UTC
We want to use the same algorithm to translate Prometheus histograms into Elasticsearch histograms. We have [agreed](https://github.com/elastic/apm-agent-python/pull/1165#discussion_r651397014) on the approach to something like this:

- for +Inf "le", use the preceding bucket's value
- for the first bucket only: if it has a negative "le", use the value as-is; otherwise use half its value (midpoint to zero)
- for all other buckets, use the midpoint from that bucket's value to the preceding bucket's

I few changes are need to comply with this implementation in Beats, mainly:

- Account for negative initial buckets
- Use the preceding bucket's value for +Inf "le"

**Comment by axw** [comment] 2022-07-17 07:58
Still relevant.

**Comment by gizas** [comment] 2023-01-17 15:25
Hello @axw , @exekias , 

The Prometheus Beat histogram implementation is solely focusing on centroids: https://github.com/elastic/beats/blob/main/x-pack/metricbeat/module/prometheus/collector/histogram.go#L48

From what I udnerstand, both types of Histograms we support is either TDigest or HDR, both support only count and values and the only difference is how we calculate the values.

So Is there any assumption why we solely focus on centroids? 
(https://github.com/elastic/apm-agent-python/pull/1165#discussion_r651481852)

cc @tetianakravchenko , @jsoriano

**Comment by gizas** [comment] 2023-01-18 08:13
Ohh thank you @axw ! Really helpful.

So checking the reference [Building Histogram](https://www.elastic.co/guide/en/elasticsearch/reference/8.6/histogram.html#mapping-types-histogram-building-histogram): `While this means the field can technically be aggregated with either algorithm, in practice the user should chose one algorithm and index data in that manner`

So this is a choice that users make on the tool of that produces the metrics. So if customer sends `HDRHistogram` metrics, will this mean that we can not support it? Can we catch this case with relevant error handling?

**Comment by axw** [comment] 2023-01-18 08:34
> So this is a choice that users make on the tool of that produces the metrics. So if customer sends HDRHistogram metrics, will this mean that we can not support it?

Not sure if I understand your question. We support it by converting the histogram to T-Digest. There will be some loss of precision, but it'll still be supported.

**Comment by gizas** [comment] 2023-01-18 08:42
Ok we supported because the format of data are the same in both types, but yes I am worried about this loss of precision. (this is actually what the can not support it was referring to). Thank you again

**Comment by tetianakravchenko** [comment] 2023-02-02 17:09
@gizas should we close this issue? in favor of https://github.com/elastic/integrations/issues/5042 ?

**Comment by gizas** [comment] 2023-02-06 07:53
Closing as per comment above, duplicate of #5042

**Closed by gizas** 2023-02-06 07:53 UTC
Labels: enhancement, Team:Integrations
