### ISSUE TITLE
Add Homebrew tap/formula

### ISSUE THREAD

**Issue by tsg** [elastic/beats#132] opened 2015-05-27 14:20 UTC
Homebrew would make it easier to give Packetbeat a try on OS X.

Probably easiest would be for the formula to download the tgz and extract the binary and the config file in the right places, as the formulae from [homebrew-binary](https://github.com/Homebrew/homebrew-binary) do.

**Comment by andrewkroh** [comment] 2016-02-11 16:19
Duplicate of #290

**Closed by andrewkroh** 2016-02-11 16:19 UTC
Labels: enhancement, infra, Packetbeat
