### ISSUE TITLE
Filebeat monitoring enters infinite error loop for "closed processor"

### ISSUE THREAD

**Issue by faec** [elastic/beats#34716] opened 2023-03-02 12:27 UTC
Intermittently, the monitoring started by Agent enters a loop where it repeats this message ~10K times a second:

```json
{"log.level":"error","@timestamp":"2023-03-02T11:59:42.394Z","message":"Failed to publish event: attempt to use a closed processor","component":{"binary":"filebeat","dataset":"elastic_agent.filebeat","id":"filestream-monitoring","type":"filestream"},"log":{"source":"filestream-monitoring"},"log.logger":"publisher","log.origin":{"file.line":102,"file.name":"pipeline/client.go"},"service.name":"filebeat","ecs.version":"1.6.0","ecs.version":"1.6.0"}
```

This error is inconsistent -- on some runs it begins soon after startup, on many runs it never happens at all. When it does happen, it severely degrades or blocks other ingestion. Subsequent runs using identical configurations with identical binaries are still inconsistent as to whether this bug occurs.

All the times I've encountered this so far have been while testing the shipper, but since most of my agent runs are testing the shipper I'm uncertain if that's a reliable correlation: the error is happening before events reach the shipper output, which is the first place event handling diverges significantly when the shipper is in use. (There could be some shipper-specific agent-injected configuration that would affect the processor list, though I'm not aware of anything like that.)

The most recent configuration I used to exhibit the error is:

```yml
outputs:
  default:
    type: elasticsearch
    log_level: debug
    enabled: true
    hosts: [https://127.0.0.1:9200]
    username: "elastic"
    password: [password]
    allow_older_versions: true
    ssl:
      verification_mode: none
    shipper:
      enabled: true

inputs:
  - type: system/metrics
    id: unique-system-metrics-input
    data_stream.namespace: default
    use_output: default
    streams:
      - metricset: cpu
        data_stream.dataset: system.cpu
      - metricset: memory
        data_stream.dataset: system.memory
      - metricset: network
        data_stream.dataset: system.network
      - metricset: filesystem
        data_stream.dataset: system.filesystem

```

**Comment by cmacknz** [comment] 2023-03-02 17:03
This error is new. It is coming from Beats:

https://github.com/elastic/beats/blob/331f792529d3848484f6039cb56cbefb902c2298/libbeat/processors/safe_processor.go#L28-L41

```go
var ErrClosed = errors.New("attempt to use a closed processor")

type SafeProcessor struct {
	Processor
	closed uint32
}

// Run allows to run processor only when `Close` was not called prior
func (p *SafeProcessor) Run(event *beat.Event) (*beat.Event, error) {
	if atomic.LoadUint32(&p.closed) == 1 {
		return nil, ErrClosed
	}
	return p.Processor.Run(event)
}
```

This error was added last week in https://github.com/elastic/beats/pull/34647. @rdner can you investigate what might be going on here?

**Comment by cmacknz** [comment] 2023-03-02 17:04
The filestream monitoring processors are defined in the agent, see https://github.com/elastic/elastic-agent/blob/98b8fe7ff2e5fc5db9a309ffd19c587f10ef8270/internal/pkg/agent/application/monitoring/v1_monitor.go#L320 for example. The monitoring Beats are configured in that file.

**Comment by cmacknz** [comment] 2023-03-02 17:06
This only affects the unreleased v8.7 and v7.17. Likely this needs to be an 8.7 release blocker, but I'll give us some time to investigate and triage before adding it to the dev issue.

@pierrehilbert FYI, added to the current sprint. I don't think we can release v8.7 with this.

**Comment by faec** [comment] 2023-03-02 17:10
I think this actually brought to light a long-standing related bug: none of the processors are really getting closed. Here's the code that closes the processors:

```go
// Close closes a processor if it implements the Closer interface
func Close(p Processor) error {
	if closer, ok := p.(Closer); ok {
		return closer.Close()
	}
	return nil
}
```

but `Processor` and `Closer` are both interfaces, not structs:

```go
type Processor interface {
	Run(event *beat.Event) (*beat.Event, error)
	String() string
}

type Closer interface {
	Close() error
}
```

and interface casts like that only work if one interface is a refinement of the other, they do not check the underlying type. See for example https://go.dev/play/p/Me1iU_Bs6Yg

**Comment by faec** [comment] 2023-03-02 17:12
(I'll file a separate issue for that one since it has less severe but much further-reaching impact)

**Comment by faec** [comment] 2023-03-02 17:26
Ah! A mistake in my testing, apologies. This is probably still working.

**Comment by faec** [comment] 2023-03-02 17:27
Sorry, closed the wrong bug -- the additional closer error I described was spurious, it was a mismatched prototype

**Comment by rdner** [comment] 2023-03-02 17:52
@cmacknz this error is a safeguard which makes sure that none of the processors is used after `Closed` is called, as the error message suggests.

We didn't introduce a new issue with https://github.com/elastic/beats/pull/34647 we exposed an existing one. So, there is no regression here.

This is some kind of race condition in the Beats internals, I looked through the code when working on https://github.com/elastic/beats/pull/34647 but could not find a possible place where it could occur, this is how the safeguard was introduced.

I'd like to ask a fresh pair of eyes to look at it.

**Comment by rdner** [comment] 2023-03-02 17:55
Removing the safeguard would most likely lead to a panic because on `Close` processors free their resources, e.g. close channels and another `Run` would panic in **some** processors.

**Comment by cmacknz** [comment] 2023-03-02 18:40
The `Failed to publish event: attempt to use a closed processor` here in the monitoring Filebeat strongly indicates we cannot ship Elastic agent logs to Fleet successfully.

I believe @rdner that https://github.com/elastic/beats/pull/34647 didn't cause this intentionally and has maybe uncovered an old problem, but given the error points to this change it seems like an unintended side effect.

@rdner you are the most familiar with this area of Beats, so are the best positioned to try to debug this. I'm not sure who else to give this too otherwise, maybe @pierrehilbert can help with this.

If we are indeed failing to send monitoring logs to Fleet we can't release 8.7 with this bug, so addressing this needs to take priority over something else in the sprint.

**Comment by faec** [comment] 2023-03-02 19:30
Based on how I encountered it (in particular its inconsistency across repeated runs), I wonder if it would previously have produced a panic or similar fatal error which would have just restarted the beat. In that case this would be uncovering an error that was already there, but by spin-locking on the error we are now preventing a natural restart + recovery that masked it in the past.

**Comment by rdner** [comment] 2023-03-02 20:51
> The Failed to publish event: attempt to use a closed processor here in the monitoring Filebeat strongly indicates we cannot ship Elastic agent logs to Fleet successfully.

Agreed but, as @faec said, previously it was just panicking and restarting, I don't consider this the right behaviour either. The only difference is that we have the actual log line that says we lost the event, it was not the case before. We definitely need to find the root cause which has nothing to do with my change, we should keep the change for cases exactly like this, to expose the incorrect behaviour.

> I believe @rdner that https://github.com/elastic/beats/pull/34647 didn't cause this intentionally and has maybe uncovered an old problem, but given the error points to this change it seems like an unintended side effect.

The opposite this is the intended side-effect. We didn't have any prove that we use `Run` after `Close`, this change was introduced to check exactly this and, as we can see, it found the issue. Would be nice to have a stacktrace of that log, perhaps we can somehow tune the logger. I'll try to reproduce using the config from the description.

> @rdner you are the most familiar with this area of Beats, so are the best positioned to try to debug this. I'm not sure who else to give this too otherwise, maybe @pierrehilbert can help with this.

I'll try to get to the bottom of this in the 2 days I have before my PTO.

@cmacknz  https://github.com/elastic/beats/pull/34647 was merged on 22th of February, if I understand correctly the BC for 8.7.0 was created earlier and the change would not affect the current release, it's included in 8.7.1. So, we have plenty of time to look into this, don't we?

**Comment by cmacknz** [comment] 2023-03-02 21:04
There are multiple build candidates scheduled to pick up fixes before release. 

The last 8.7.0 build candidate is scheduled for 2023-03-22, so we have until then to fix this (I can't link to the 8.7.0 here as it's private)

**Comment by faec** [comment] 2023-03-06 15:20
I would say the intended side effect is to report the error of run-after-close, and the unintended side effect is a spin lock that wedges the whole pipeline while filling the logs with 100MB of error messages per minute. We would prefer to keep the intended side effect, but we can't ship something that spinlocks on what would otherwise be a recoverable error.

**Comment by rdner** [comment] 2023-03-07 12:04
@faec 
> unintended side effect is a spin lock that wedges the whole pipeline while filling the logs with 100MB of error messages per minute. We would prefer to keep the intended side effect, but we can't ship something that spinlocks on what would otherwise be a recoverable error.

Absolutely agree but to be fair none of us knew that the use of processors was broken that much. I tested a simple processor configuration in my PR and it worked normally, so it's not like it was not tested at all.

Just to be clear, in my previous comments I never meant "won't fix", I tried to communicate that the fact that we caught this behaviour was a good thing and I started investigating right away.

Who would have thought that the problem was at this scale, it had been previously reported only for the `add_kubernetes_metadata` processor.

**Comment by rdner** [comment] 2023-03-07 19:05
@cmacknz @faec 

I've finally managed to find the cause. The fixing PR is here https://github.com/elastic/beats/pull/34761

## The Source of the Issue

I've tracked it down to where the multiple `Close` calls always come from:

```
tried to close already closed "add_cloud_metadata={}" processor: "goroutine 195 [running]:
runtime/debug.Stack()
	/opt/homebrew/Cellar/go@1.19/1.19.6/libexec/src/runtime/debug/stack.go:24 +0x64
github.com/elastic/beats/v7/libbeat/processors.(*SafeProcessor).Close(0x14000fb1788?)
	/Users/rdner/Projects/beats/libbeat/processors/safe_processor.go:51 +0xe0
github.com/elastic/beats/v7/libbeat/processors.Close(...)
	/Users/rdner/Projects/beats/libbeat/processors/processor.go:58
github.com/elastic/beats/v7/libbeat/publisher/processing.(*group).Close(0x14000ebea98?)
	/Users/rdner/Projects/beats/libbeat/publisher/processing/processors.go:96 +0x158
github.com/elastic/beats/v7/libbeat/processors.Close(...)
	/Users/rdner/Projects/beats/libbeat/processors/processor.go:58
github.com/elastic/beats/v7/libbeat/publisher/processing.(*group).Close(0x140004065e0?)
	/Users/rdner/Projects/beats/libbeat/publisher/processing/processors.go:96 +0x158
github.com/elastic/beats/v7/libbeat/processors.Close(...)
	/Users/rdner/Projects/beats/libbeat/processors/processor.go:58
github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*client).Close.func1()
	/Users/rdner/Projects/beats/libbeat/publisher/pipeline/client.go:167 +0x278
sync.(*Once).doSlow(0x14000d24750?, 0x140010b03c0?)
	/opt/homebrew/Cellar/go@1.19/1.19.6/libexec/src/sync/once.go:74 +0x104
sync.(*Once).Do(...)
	/opt/homebrew/Cellar/go@1.19/1.19.6/libexec/src/sync/once.go:65
github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*client).Close(0x1031250fe?)
	/Users/rdner/Projects/beats/libbeat/publisher/pipeline/client.go:148 +0x58
github.com/elastic/beats/v7/filebeat/beater.(*countingClient).Close(0x140010b03c0?)
	/Users/rdner/Projects/beats/filebeat/beater/channels.go:145 +0x28
github.com/elastic/beats/v7/filebeat/input/filestream/internal/input-logfile.startHarvester.func1({0x10447a7e0?, 0x14000d30000})
	/Users/rdner/Projects/beats/filebeat/input/filestream/internal/input-logfile/harvester.go:219 +0x6a4
github.com/elastic/go-concert/unison.(*TaskGroup).Go.func1()
	/Users/rdner/go/pkg/mod/github.com/elastic/go-concert@v0.2.0/unison/taskgroup.go:163 +0x94
created by github.com/elastic/go-concert/unison.(*TaskGroup).Go
	/Users/rdner/go/pkg/mod/github.com/elastic/go-concert@v0.2.0/unison/taskgroup.go:159 +0xc4
```

In my tests (the policy in the description of this issue) it happened for the following processors:

* add_cloud_metadata
* add_docker_metadata
* add_fields
* add_index_pattern
* add_kubernetes_metadata
* copy_fields
* drop_fields

Apparently, it does not really depend on a particular processor and happens only in `filestream` triggered by this code:

https://github.com/elastic/beats/blob/a8ab071c4ac09e99891af05595294a8473b86473/filebeat/input/filestream/internal/input-logfile/harvester.go#L193-L201

Every time a `filestream` harvester stops or restarts for any reason, it closes the client, which closes the processors:

https://github.com/elastic/beats/blob/a8ab071c4ac09e99891af05595294a8473b86473/libbeat/publisher/pipeline/client.go#L165-L172

Closing the client is normal behaviour, seems like something is re-using the same processors across multiple clients and this is causing the issue.

## The Root Cause

I found this function:

https://github.com/elastic/beats/blob/a8ab071c4ac09e99891af05595294a8473b86473/filebeat/channel/runner.go#L121-L190

Which is actually re-using all the user-space (defined in the config) processors since they're created in the closure and then used by the return factory function later. And that was it. Once I moved the initialisation inside the returned function I could not reproduce the errors anymore.

## My Analysis

The pipeline creates a new set of processors here:

https://github.com/elastic/beats/blob/a8ab071c4ac09e99891af05595294a8473b86473/libbeat/publisher/pipeline/pipeline.go#L247

Which eventually reaches these two functions:

This first – creates user-space processors from the config:
 https://github.com/elastic/beats/blob/a8ab071c4ac09e99891af05595294a8473b86473/libbeat/processors/processor.go#L73-L129

Then some internal processors on top of it here:

https://github.com/elastic/beats/blob/cbd1a38bafb47c0f5be131ccf0a0741f2d2ae878/libbeat/publisher/processing/default.go#L258-L370

<details>
<summary>Because of these assignments</summary>

https://github.com/elastic/beats/blob/a8ab071c4ac09e99891af05595294a8473b86473/libbeat/cmd/instance/beat.go#L810-L814

https://github.com/elastic/beats/blob/a8ab071c4ac09e99891af05595294a8473b86473/libbeat/publisher/processing/default.go#L78-L80

https://github.com/elastic/beats/blob/a8ab071c4ac09e99891af05595294a8473b86473/libbeat/publisher/processing/default.go#L96-L117

</details>

So, this `Processors.New` function is calling our processor `Plugin` API which eventually returns new instances of the requested processors. No problem here.

The builder also does not re-use anything and protects the global processors from being closed:

https://github.com/elastic/beats/blob/cbd1a38bafb47c0f5be131ccf0a0741f2d2ae878/libbeat/publisher/processing/default.go#L349-L352

However, Filebeat is a somewhat special in the way it handles its pipeline/input creation and it's using this function:

https://github.com/elastic/beats/blob/cbd1a38bafb47c0f5be131ccf0a0741f2d2ae878/filebeat/beater/filebeat.go#L326-L330

which is basically a factory for inputs, I suppose it's also to handle input restarts during runtime.

If we go to this function definition, we can see it calls:

https://github.com/elastic/beats/blob/a8ab071c4ac09e99891af05595294a8473b86473/filebeat/channel/runner.go#L109-L119

And here we can see the function that caused it all:

https://github.com/elastic/beats/blob/a8ab071c4ac09e99891af05595294a8473b86473/filebeat/channel/runner.go#L121-L190

**Closed** 2023-03-07 22:16 UTC
Labels: bug, Team:Elastic-Agent, v8.7.0
