### ISSUE TITLE
Fields from different prospectors can't be defined in a common namespace

### ISSUE THREAD

**Issue by adriansr** [elastic/beats#7528] opened 2018-07-06 12:50 UTC
For confirmed bugs, please report:
- Version: 6.3.1
- Operating System: -
- Discuss Forum URL: https://discuss.elastic.co/t/filebeat-field-name-collision-with-external-prospectors/138809
- Steps to Reproduce: 

Defining fields at the global level, nested into a namespace (test_namespace):
```
filebeat:
  registry_file: /var/lib/filebeat/registry
  config.prospectors:
    enabled: true
    path: /etc/filebeat/conf.d/*.yml
fields:
  test_namespace.fqdn: civet.fqdn.xxxx
fields_under_root: true
output:
[...]
```

and adding more fields to this namespace in a prospector:
```
- paths:
    - /var/log/auth.log
  type: log
  fields:
    test_namespace.container: syslog
  fields_under_root: true
```

Results in only the fields from the prospectors being present, completely replacing those at the global level:
```
{
  "@timestamp": "2018-07-06T12:48:41.783Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "doc",
    "version": "7.0.0-alpha1"
  },
  "prospector": {
    "type": "log"
  },
  "beat": {
    "hostname": "Adrian-Elastic.local",
    "version": "7.0.0-alpha1",
    "name": "Adrian-Elastic.local"
  },
  "host": {
    "name": "Adrian-Elastic.local"
  },
  "offset": 19644,
  "message": "Oct 11 20:12:03 CCIOReporterFormatter::addRegistryChildToChannelDictionary streams 62",
  "source": "/var/log/corecaptured.log",
  "input": {
    "type": "log"
  },
  "test_namespace": {
    "container": "syslog"
  }
}
```

**Comment by ceeeekay** [comment] 2018-08-26 23:37
Hi there,

Any update on this?  It's still occurring in 6.4, and it's preventing us from upgrading past 6.2, as the new 6.3 `host` object means we now need to namespace everything.

**Comment by ceeeekay** [comment] 2018-10-30 01:58
Any update here?  This is a major issue for us.

**Comment by urso** [comment] 2019-03-03 16:59
Likely same issue as reported in #3628

**Comment by ceeeekay** [comment] 2019-03-03 19:44
That's an unresolved issue from 2017!

With ECS on the way, and Elastic's recommendation that users namespace non-compliant fields, this is going to become a huge problem for a lot of people.

**Comment by ceeeekay** [comment] 2019-09-09 03:43
Any update here? Over a year later and this is still an issue with 7.3.1 when using external input configs via `filebeat.config.inputs.path`

We still haven't moved to ECS, and it's going to be a huge problem if we can't namespace things where we need to.

**Comment by ycombinator** [comment] 2019-10-04 01:12
@adriansr this looks like a duplicate of #3628 to me. WDYT?

**Comment by urso** [comment] 2019-10-04 12:28
Agreed, looks like a duplicate issue.

**Comment by ycombinator** [comment] 2019-10-04 12:35
Closing as duplicate of #3628.

**Closed by ycombinator** 2019-10-04 12:35 UTC
Labels: Filebeat, bug, libbeat

**Comment by adriansr** [comment] 2019-10-04 12:39
Yes @ycombinator , it was duplicate, I guess I didn't find it before opening this one because the title was a bit misleading.
