### ISSUE TITLE
Error while getting [memory,cpu] usage: error retrieving process stats: cannot find matching process for pid=1

### ISSUE THREAD

**Issue by f0** [elastic/beats#6734] opened 2018-04-03 05:34 UTC
Hi,

i run metricbeat inside kubernetes inside a docker container.
I see this errors in the log

```
{"level":"error","timestamp":"2018-04-03T05:31:26.854Z","caller":"instance/metrics.go:69","message":"Error while getting memory usage: error retrieving process stats: cannot find matching process for pid=1"}
{"level":"error","timestamp":"2018-04-03T05:31:26.854Z","caller":"instance/metrics.go:113","message":"Error retrieving CPU percentages: error retrieving process stats: cannot find matching process for pid=1"}
```

**Comment by kvch** [comment] 2018-04-03 12:35
Hi!

What version are you running? A similar issue has been reported and fixed: https://github.com/elastic/beats/issues/6620
Could you reproduce it on master?

**Comment by f0** [comment] 2018-04-03 16:55
@kvch  hi, i run 6.2.3

**Comment by andrzej-majewski** [comment] 2018-04-24 11:26
Is there a workaround for this? 

I am running 6.2.4 and issue still persist?

**Comment by jsoriano** [comment] 2018-04-24 13:13
The fix will be included in 6.3 and backported for 6.2.5 (#6931).

As a workaround, if you don't have any security concern, you can run metricbeat container without process table isolation with `--pid=host`.

This can be closed by now, please reopen if it is still an issue in future releases.

**Comment by andrzej-majewski** [comment] 2018-04-25 10:26
I am running it in docker swarms,  with following compose :

`
metricbeat:
  image: docker.elastic.co/beats/metricbeat:6.2.4
  user: root
  pid: host
  command: metricbeat -e -system.hostfs=/hostfs
  volumes:
    - /proc:/hostfs/proc:ro
    - /sys/fs/cgroup:/hostfs/sys/fs/cgroup:ro
    - /var/run/docker.sock:/var/run/docker.sock
    - /:/hostfs:ro
  configs:
    - source: conf-metricbeat-6.2.4
      target: /usr/share/metricbeat/metricbeat.yml
  networks:
    - efk
  deploy:
    mode: replicated`

I still see same issue 
'RROR   instance/metrics.go:61  Error while getting memory usage: error retrieving process stats: cannot find matching process for pid=1'

**Comment by jsoriano** [comment] 2018-04-25 10:49
@andrzej-majewski this seems to be caused by a current limitation of docker swarm, it cannot run containers in host pid namespace (see https://github.com/docker/docker.github.io/issues/5624 and https://github.com/docker/swarmkit/issues/1605).

Without this I cannot think of any other simple workaround...

**Comment by jsoriano** [comment] 2018-04-25 10:50
I'm closing it by now as it's fixed in master and will be fixed in upcoming 6.2 and 6.3 releases.

**Closed by jsoriano** 2018-04-25 10:50 UTC

**Comment by andrzej-majewski** [comment] 2018-04-25 17:42
Thanks for confirmation.

Any idea about dates for 6.2.5 and 6.3?

**Comment by jsoriano** [comment] 2018-04-26 09:33
I cannot confirm any sure date, but we expect to have a release in a few weeks.

**Comment by OpakAlex** [comment] 2018-05-17 08:11
@jsoriano any updates?

Also, how i can fix in kubernetes?

**Comment by jsoriano** [comment] 2018-05-17 09:07
@OpakAlex as a workaround in kubernetes you can run the metricbeat pod with `hostPid: true`.
