### ISSUE TITLE
Adding pure socket as an output

### ISSUE THREAD

**Issue by admlko** [elastic/beats#13391] opened 2019-08-29 09:16 UTC
**Describe the enhancement:**
It would be beneficial to add UDP/TCP/UNIX? socket support as an output.
**Describe a specific use case for the enhancement or feature:**
I was thinking of sending Beats data through Syslog, but noticed that it is not supported at the moment. At least TCP output is already implemented, so I think it wouldn't be too much of a trouble to add it. Then the Syslog could be handled with a codec, or manual formatting.

**Comment by ph** [comment] 2020-01-03 18:53
duplicate of https://github.com/elastic/beats/issues/11942

**Closed by ph** 2020-01-03 18:53 UTC
