### ISSUE TITLE
No activity logs and agent is stuck in enrolling state on endpoint integration with Linux deb and rpm

### ISSUE THREAD

**Issue by rahulgupta-qasource** [elastic/beats#21972] opened 2020-10-19 12:43 UTC
**Kibana version:**
Kibana: 7.10.0 Kibana BC2 cloud environment with commit f1c0bdd161975a0071afbc6f0b9dd4cc8889b2b8

**Elasticsearch version:**
Elasticsearch: 7.10.0 Kibana BC2 cloud environment

**Host OS and Browser version:**
Windows , All

**Original install method (e.g. download page, yum, from source, etc.):**
7.10.0 Kibana BC2 cloud environment from  https://staging.found.no

**Description**
No activity logs and agent is stuck in enrolling state on endpoint integration with Linux deb and rpm

**Preconditions**
1. Test Case Id https://elastic.testrail.io/index.php?/cases/view/22506 need to be executed.
2. Login into the above Kibana environment with 'elastic' superuser.
3. Endpoint integration should be added in Default Policy
4. 7.10.0 BC2 agent download from location:
https://staging.elastic.co/7.10.0-174bd372/downloads/beats/elastic-agent/elastic-agent-7.10.0-x86_64.rpm
https://staging.elastic.co/7.10.0-174bd372/downloads/beats/elastic-agent/elastic-agent-7.10.0-amd64.deb

**Steps to Reproduce**
1. Download tar file at /home/zeus location
2. sudo rpm -vi elastic-agent-7.10.0-x86_64.rpm
3. Run sudo elastic-agent enroll https://c00754a6ee874a5cbaea1aaf9ccc4327.us-central1.gcp.foundit.no:9243 ZnFWMVAzVUJxTVY3SXE0MnpfdGQ6R25zcjRUZ2VRcldWMnVMV05KemRfdw==
4. Run sudo systemctl enable elastic-agent
5. Run sudo systemctl start elastic-agent
6. Navigate to Agents tab in Kibana and 
7. Observe that agent is stuck in enrolling state and no activity logs are displayed for above host under Agents->Host

**Test data**
N/A

**Impacted Test case id**
https://elastic.testrail.io/index.php?/cases/view/33960
https://elastic.testrail.io/index.php?/cases/view/33960

**Actual Result**
No activity logs and agent is stuck in enrolling state on endpoint integration with Linux deb and rpm

**Expected Result**
Agent activity logs should be displayed and agent should be in online status on endpoint integration with Linux deb and rpm

**What's working**
 - Issue is not occurring with Winx64 zip file

**What's not working**
 - Issue is also occurring on enrolling agent with Linux deb package(with Endpoint Integration)
 
**Screenshot**
1. Linux RPM:
![axctivity_logs_rpm_enroll](https://user-images.githubusercontent.com/59917944/96454068-f6062b00-1238-11eb-87c5-8291ea91060e.jpg)

2. Linux deb :
![activity_logs_deb_enrolling](https://user-images.githubusercontent.com/59917944/96456328-fb18a980-123b-11eb-9e6a-d27c5740b6c6.jpg)

**Logs**
N/A

**Comment by rahulgupta-qasource** [comment] 2020-10-19 13:24
@vipulsrivastava-qasource Please review the bug.

**Comment by vipulsrivastava-qasource** [comment] 2020-10-19 13:26
Reviewed and Assigned to @EricDavisX

**Comment by EricDavisX** [comment] 2020-10-19 16:13
this is a duplicate of: https://github.com/elastic/beats/issues/21200
 - closing it as such

**Closed by EricDavisX** 2020-10-19 16:13 UTC
Labels: Team:Ingest Management, bug, impact:high, v7.10.0

**Comment by rahulgupta-qasource** [comment] 2020-11-25 12:52
**Bug Conversion:**

Testcase already exists for this ticket.
https://elastic.testrail.io/index.php?/cases/view/33960
