### ISSUE TITLE
Beats for Docker/Windows

### ISSUE THREAD

**Issue by cdssoftware** [elastic/beats#20223] opened 2020-07-24 07:07 UTC
Now that kubernetes (in AKS at least) supports windows hosts, would it be possible to produce docker images that run on windows for the daemon sets to use?

I've produced my own docker image based on golang which seems to work (obviously for my purposes I just baked in my configuration into the image)

```
FROM golang

ADD filebeat-7.6.2-windows-x86_64.tar /

COPY filebeat.yml /filebeat-7.6.2-windows-x86_64/filebeat.yml

ENTRYPOINT ["C:/filebeat-7.6.2-windows-x86_64/filebeat.exe", "-c", "C:/filebeat-7.6.2-windows-x86_64/filebeat.yml"]
```

**Comment by jsoriano** [comment] 2020-07-28 14:41
Related to/duplicated of https://github.com/elastic/beats/issues/16814

**Comment by andresrc** [comment] 2020-08-01 10:41
Closing as duplicate of https://github.com/elastic/beats/issues/16814

**Closed by andresrc** 2020-08-01 10:41 UTC
Labels: Team:Platforms
