### ISSUE TITLE
All processes are running on OSX

### ISSUE THREAD

**Issue by monicasarbu** [elastic/beats#2857] opened 2016-10-26 11:14 UTC
- Version: 5.0.0 
- Operating System: OSX

On OSX all processes are marked as running. You can simply see that in the following pie chart:
![screen shot 2016-10-26 at 1 12 55 pm](https://cloud.githubusercontent.com/assets/11757159/19723958/002fc25c-9b7e-11e6-86ae-6845a74d0c83.png)

There are 460 processes and all have the state running.

**Comment by ruflin** [comment] 2017-11-28 04:33
I just did a quick test and this seems still to be the case. I wonder if this is more an issue in gosigar (@andrewkroh)? Did not investigate yet.

**Comment by andrewkroh** [comment] 2017-11-28 11:12
A few months ago I inspected the gosigar code in regards to this issue and was not able to find any problems. IIRC it looked like the data was actually being returned with these states from the OS.

I think a second look by someone else would be beneficial.

**Comment by ruflin** [comment] 2017-12-04 03:59
I think what @andrewkroh state is correct that we receive the wrong values already from the OS.

For some further investigations / references, the files I looked at:

* Here is where the task info is built: https://github.com/elastic/gosigar/blob/master/sigar_darwin.go#L484
* pbi_status is defined here: https://opensource.apple.com/source/xnu/xnu-1228/bsd/sys/proc_info.h.auto.html 
* Some more details on the proc code (not sure if this repo is what we are looking for): https://github.com/aosm/xnu/blob/master/bsd/kern/proc_info.c

Running `top` on OS X shows most processes sleeping I would expect. I was wonder from where `top` fetches its info. I stumbled over `pth_run_state` in here but I don't think it's related https://opensource.apple.com/source/xnu/xnu-1228/bsd/sys/proc_info.h.auto.html

I wonder if we should open an issue in gosigar about this?

**Comment by cachedout** [comment] 2018-12-19 00:33
Can anybody reproduce this issue when running `metricbeat` as the root user?

In my investigation, it does not appear that OS X permits non-root users to get the status of pids from other users or those launched by the system itself. To the point from @ruflin -- I believe that the reason `top` can extract this information is that it is setuid root.

**Comment by ph** [comment] 2019-12-06 18:25
I did a quick look at this and the behavior in metricbeat and what is expressed by @cachedout is correct here, so I will close this issue.

**Closed by ph** 2019-12-06 18:25 UTC
Labels: Metricbeat, Team:Integrations, bug, module
