### ISSUE TITLE
[Metricbeat] system module cpu metrics data incorrect

### ISSUE THREAD

**Issue by SuxiangYundi** [elastic/beats#13370] opened 2019-08-28 09:54 UTC
- Version:  Metricbeat 7.3.1
- Operating System: CentOS 7.5
- Architecture: metricbeat =>logstash=>elasticsearch
- Configuration:
    metricbeat.yml config below:
```
setup.kibana:
  host: "XXX:5601"
output.logstash:
  hosts: ["XXX:5044"]

setup.ilm.enabled: false
cpu.metrics: [percentages, normalized_percentages, ticks]
```

    logstash pipeline conf below:
```
input {
  beats {
    port => 5044
  }
}
output {
  elasticsearch {
    hosts => ["http://XXX:9200"]
    ilm_enabled => true
  }
}
```

- Steps to Reproduce: 
    1. start elasticsearch logstash kibana metricbeat in turn
    2. disover data on Kibana

I got cpu metrics ( json format ) of system below:

```
{
  "_index": "logstash-2019.08.28-000001",
  "_type": "_doc",
  "_id": "IKps12wB_JYD-eftLuGN",
  "_version": 1,
  "_score": null,
...
    "system": {
      "cpu": {
        "cores": 40,
        "system": {
          "pct": 0.6574
        },
        "steal": {
          "pct": 0
        },
        "softirq": {
          "pct": 0.0564
        },
        "nice": {
          "pct": 0
        },
        "total": {
          "pct": 24.5968
        },
        "iowait": {
          "pct": 0
        },
        "idle": {
          "pct": 15.4032
        },
        "irq": {
          "pct": 0
        },
        "user": {
          "pct": 23.883
        }
      }
...
  "sort": [
    1566982217051
  ]
}
```

As shown above, the sum of system cpu usage values  was far less than 100.

The following information is displayed when  entering top command on the server：
top - 17:40:22 up 20 days, 22:06,  1 user,  load average: 22.07, 21.42, 21.94
Tasks: 433 total,   1 running, 432 sleeping,   0 stopped,   0 zombie
%Cpu(s): 57.5 us,  3.1 sy,  0.0 ni, 39.4 id,  0.0 wa,  0.0 hi,  0.0 si,  0.0 st
KiB Mem : 26390408+total, 17275616+free, 89973728 used,  1174204 buff/cache
KiB Swap: 10485756 total, 10485756 free,        0 used. 17280016+avail Mem

Then I configured log level to debug and the recorded data in syslog was consistent with what was shown on Kibana.

I don't know what's wrong with it.

**Comment by SuxiangYundi** [comment] 2019-08-30 01:32
@jsoriano Could you help to find out problems？

**Comment by jsoriano** [comment] 2019-08-30 13:01
Hi @SuxiangYundi,

These values are percentages in decimal value, and they are not normalized, so in your machine with 40 cores the value can go from 0 to 40, 40 would be 4000%.

For example looking at the user value in the event you pasted:
```
        "user": {
          "pct": 23.883
        }
```
You can see an usage of 2388.3%.

You can also collect normalized values (that would go from 0 to 1) using the [`cpu.metrics` option](https://www.elastic.co/guide/en/beats/metricbeat/7.3/metricbeat-metricset-system-cpu.html#_configuration_3) of the system module.

As this is not a bug or a request I am going to close it, we keep github issues for confirmed bugs and pending enhancement requests. Next time please use https://discuss.elastic.co/c/beats, we are happy to answer there.

**Closed by jsoriano** 2019-08-30 13:01 UTC

**Comment by SuxiangYundi** [comment] 2019-09-02 03:10
> Hi @SuxiangYundi,
> 
> These values are percentages in decimal value, and they are not normalized, so in your machine with 40 cores the value can go from 0 to 40, 40 would be 4000%.
> 
> For example looking at the user value in the event you pasted:
> 
> ```
>         "user": {
>           "pct": 23.883
>         }
> ```
> 
> You can see an usage of 2388.3%.
> 
> You can also collect normalized values (that would go from 0 to 1) using the [`cpu.metrics` option](https://www.elastic.co/guide/en/beats/metricbeat/7.3/metricbeat-metricset-system-cpu.html#_configuration_3) of the system module.
> 
> As this is not a bug or a request I am going to close it, we keep github issues for confirmed bugs and pending enhancement requests. Next time please use https://discuss.elastic.co/c/beats, we are happy to answer there.

Thank you very much.
