### ISSUE TITLE
Filebeat panic on missing multiline.pattern

### ISSUE THREAD

**Issue by jzoe** [elastic/beats#3023] opened 2016-11-17 09:17 UTC
Version: filebeat 5.0 + logstash 5.0 + elasticsearch 5.0
System: centos 7 (filesystem； XFS)

Here is my filebeat.yml
```
  1 filebeat.prospectors:
  2 - input_type: log
  3   paths:
  4     - /home/dba/mysqlnode/nodedata1/mysqlslow.log
  5   document_type: mysql_slow_log
  6   multiline.negate: true
  7   multiline.match: after
  8 filebeat.registry_file: /home/dba/tmp/registry
  9 output.logstash:
 10   hosts: ["localhost:5044"]
```
And my logstash configure like this:
```
  1 input {
  2     beats{
  3         host => "localhost"
  4         port => 5045
  5         tags => ["metric"]
  6     }
  7     beats{
  8         host => "localhost"
  9         port => 5044
 10         codec => multiline {
 11            pattern => "^# User@Host:"
 12            negate => true
 13            what => previous
 14         }
 15         tags => ["mysql_slow_log"]
 16     }
 17 }
```

I'm trying to startup filebeat, but I get the panic error as following:
```
[dba@localhost filebeat-5.0.0-linux-x86_64]$ ./filebeat -e -c mysql-slow-log-filebeat.yml -d "publish"
  16/11/17 08:49:51.351959 beat.go:264: INFO Home path: [/home/dba/elk/filebeat-5.0.0-linux-x86_64] Config path: [/home/dba/elk/filebeat-5.0.0-linux-x86_64] Data p▽th: [/home/dba/elk/filebeat-5.0.0-linux-x86_64/data] Logs path: [/home/dba/elk/filebeat-5.0.0-linux-x86_64/logs]
2016/11/17 08:49:51.352090 beat.go:174: INFO Setup Beat: filebeat; Version: 5.0.0
2016/11/17 08:49:51.352177 logstash.go:90: INFO Max Retries set to: 3
2016/11/17 08:49:51.352247 outputs.go:106: INFO Activated logstash as output plugin.
2016/11/17 08:49:51.352280 publish.go:234: DBG  Create output worker
2016/11/17 08:49:51.352330 publish.go:276: DBG  No output is defined to store the topology. The server fields might not be filled.
2016/11/17 08:49:51.352375 publish.go:291: INFO Publisher name: localhost.localdomain
2016/11/17 08:49:51.352554 async.go:63: INFO Flush Interval set to: 1s
2016/11/17 08:49:51.352587 async.go:64: INFO Max Bulk Size set to: 2048
2016/11/17 08:49:51.352610 async.go:72: DBG  create bulk processing worker (interval=1s, bulk size=2048)
2016/11/17 08:49:51.352693 beat.go:204: INFO filebeat start running.
2016/11/17 08:49:51.352705 registrar.go:66: INFO Registry file set to: /home/dba/elk/filebeat-5.0.0-linux-x86_64/data/registry
2016/11/17 08:49:51.352721 registrar.go:88: INFO No registry file found under: /home/dba/elk/filebeat-5.0.0-linux-x86_64/data/registry. Creating a new registry file.
2016/11/17 08:49:51.352729 crawler.go:34: INFO Loading Prospectors: 1
2016/11/17 08:49:51.352755 prospector_log.go:40: INFO Load previous states from registry into memory
2016/11/17 08:49:51.352764 prospector_log.go:67: INFO Previous states loaded: 0
2016/11/17 08:49:51.352810 crawler.go:46: INFO Loading Prospectors completed. Number of prospectors: 1
2016/11/17 08:49:51.352815 crawler.go:61: INFO All prospectors are initialised and running with 0 states to persist
2016/11/17 08:49:51.352839 prospector.go:106: INFO Starting prospector of type: log
2016/11/17 08:49:51.352965 log.go:84: INFO Harvester started for file: /home/dba/mysqlnode/nodedata1/mysqlslow.log
2016/11/17 08:49:51.353156 logp.go:219: INFO Metrics logging every 30s
2016/11/17 08:49:51.353221 sync.go:41: INFO Start sending events to output
2016/11/17 08:49:51.353262 registrar.go:211: INFO Starting Registrar
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5d55b6]

goroutine 29 [running]:
panic(0x8db060, 0xc420012090)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
regexp.(*Regexp).get(0x0, 0x2)
        /usr/local/go/src/regexp/regexp.go:208 +0x26
regexp.(*Regexp).doExecute(0x0, 0x0, 0x0, 0xc42004dc70, 0x46, 0x47, 0x0, 0x0, 0x0, 0x0, ...)
        /usr/local/go/src/regexp/exec.go:416 +0x40
regexp.(*Regexp).Match(0x0, 0xc42004dc70, 0x46, 0x47, 0x46)
        /usr/local/go/src/regexp/regexp.go:421 +0x8c
github.com/elastic/beats/filebeat/harvester/reader.genPatternMatcher.func1(0xc420172d80, 0x58, 0x59, 0xc42004dc70, 0x46, 0x47, 0x1000000010000)
        /go/src/github.com/elastic/beats/filebeat/harvester/reader/multiline.go:306 +0xa3
github.com/elastic/beats/filebeat/harvester/reader.negatedMatcher.func1(0xc420172d80, 0x58, 0x59, 0xc42004dc70, 0x46, 0x47, 0x47)
        /go/src/github.com/elastic/beats/filebeat/harvester/reader/multiline.go:296 +0x61
github.com/elastic/beats/filebeat/harvester/reader.(*Multiline).readNext(0xc4200d6180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/elastic/beats/filebeat/harvester/reader/multiline.go:189 +0x8b7
github.com/elastic/beats/filebeat/harvester/reader.(*Multiline).readFirst(0xc4200d6180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc4201a8468, ...)
        /go/src/github.com/elastic/beats/filebeat/harvester/reader/multiline.go:132 +0x167
github.com/elastic/beats/filebeat/harvester/reader.(*Multiline).Next(0xc4200d6180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420040cb0, ...)
        /go/src/github.com/elastic/beats/filebeat/harvester/reader/multiline.go:108 +0x62
github.com/elastic/beats/filebeat/harvester/reader.(*Limit).Next(0xc4201a06c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/elastic/beats/filebeat/harvester/reader/limit.go:17 +0x66
github.com/elastic/beats/filebeat/harvester.(*Harvester).Harvest(0xc420147ba0, 0xbe0180, 0xc4201a06c0)
        /go/src/github.com/elastic/beats/filebeat/harvester/log.go:93 +0x24d
github.com/elastic/beats/filebeat/prospector.(*Prospector).startHarvester.func1(0xc420105ba0, 0xc420147ba0, 0xbe0180, 0xc4201a06c0)
        /go/src/github.com/elastic/beats/filebeat/prospector/prospector.go:223 +0x65
created by github.com/elastic/beats/filebeat/prospector.(*Prospector).startHarvester
        /go/src/github.com/elastic/beats/filebeat/prospector/prospector.go:224 +0x2ee
```

Is there any one can help me to figure out what's wrong with my filebeat ?

**Comment by ruflin** [comment] 2016-11-18 12:36
This panic seems to be related to multiline. Any chance you could share your multiline log file so I can try to reproduce this?

**Comment by andrewkroh** [comment] 2016-11-18 14:10
@jzoe It looks like there is no multiline pattern specified in your config. 

@ruflin @urso Is this a config validation problem for Filebeat?

**Comment by jzoe** [comment] 2016-11-20 06:58
@andrewkroh I specify my multiline pattern in filter section of logstash.cnf  file, which write as:

```
 19 filter {
 20     if "mysql_slow_log" in [tags] {
 21         grok {
 22             match => [ "message", "(?m)^#\s+User@Host:\s+%{USER:user}\[[^\]]+\]\s+@\s+%{USER:clienthost}\s+\[(?:%{IP:clientip})?\]\s+Id:\s+%{NUMBER:id:int}\n#\
    s+Schema:\s+%{USER:schema}\s+Last_errno:\s+%{NUMBER:lasterrorno:int}\s+Killed:\s+%{NUMBER:killedno:int}\n#\s+Query_time:\s+%{NUMBER:query_time:float}\s+Lock_ti
    me:\s+%{NUMBER:lock_time:float}\s+Rows_sent:\s+%{NUMBER:rows_sent:int}\s+Rows_examined:\s+%{NUMBER:rows_examined:int}\s+Rows_affected:\s+%{NUMBER:rows_affected
    :int}\n#\s+Bytes_sent:\s+%{NUMBER:bytes_sent:int}\n\s*(?:use\s+%{USER:usedatabase};\s*\n)?SET\s+timestamp=%{NUMBER:timestamp};\n\s*(?<query>(?<action>\w+)\b.*)
    \s*(?:\n#\s+Time)?.*$"]
 23         }
 24         date {
 25             match => [ "timestamp", "UNIX" ]
 26             #remove_field => [ "timestamp" ]
 27         }
 28 
 29     }
 30 
 31 }
```

Should I put those multiline pattern in the filebeat config file?

**Comment by jzoe** [comment] 2016-11-20 07:02
@ruflin Here is the head few lines of my mysqlslow log file:
```
  1 /home/dba/mysql/bin/mysqld, Version: 5.5.20-v3i-log (Source distribution). started with:
  2 Tcp port: 5306  Unix socket: /home/dba/mysqlnode/nodedata2/mysqld.sock
  3 Time                 Id Command    Argument
  4 /home/dba/mysql/bin/mysqld, Version: 5.5.20-v3i-log (Source distribution). started with:
  5 Tcp port: 5306  Unix socket: /home/dba/mysqlnode/nodedata2/mysqld.sock
  6 Time                 Id Command    Argument
  7 # Time: 161103 10:04:17
  8 # User@Host: root[root] @  [10.240.139.90]
  9 # Query_time: 63.503940  Lock_time: 0.021007 Rows_sent: 1  Rows_examined: 3432620 Logical_reads: 0 Physical_reads: 0
 10 use osc;
 11 SET timestamp=1478138657;
 12 select count(1) from osc_demo;
 13 # Time: 161103 11:24:52
 14 # User@Host: root[root] @  [10.240.139.90]
 15 # Query_time: 1.034880  Lock_time: 0.000038 Rows_sent: 1  Rows_examined: 3752012 Logical_reads: 0 Physical_reads: 0
 16 SET timestamp=1478143492;
 17 select count(1) from osc_demo;
```

**Comment by ruflin** [comment] 2016-11-21 13:02
@jzoe You have to either use multiline on filebeat or on the logstash side. In your case you should remove the multiline config options from the filebeat config file.

What we need to look into is why the above panics but instead it should return an error. @andrewkroh I assume yes about the config validation problem :-(

**Comment by jzoe** [comment] 2016-11-21 13:42
Thank you for your advise! @ruflin @andrewkroh I put the ``` multiline.pattern: '^# Time [0-9]{6} [0-9]{2}:[0-9]{2}:[0-9]{2}'``` in my filebeat.yml , then the beats working fine in my system. I think this should specify in the document which my help more user in the feature. Thanks one more time for yours hardworking!

**Comment by andrewkroh** [comment] 2016-11-21 23:32
Let's keep this open until this no longer causes a panic. Having multiline enabled without a pattern should cause a validation error.

**Comment by ruflin** [comment] 2017-05-23 07:47
PR to fix this issue: https://github.com/elastic/beats/pull/4377

**Comment by urso** [comment] 2018-08-16 21:41
PR merged long time ago. Closing.

**Closed by urso** 2018-08-16 21:41 UTC
Labels: Filebeat, bug
