### ISSUE TITLE
Agent 7.8.0-SNAPSHOT: invalid ApiKey value

### ISSUE THREAD

**Issue by fearful-symmetry** [elastic/beats#19218] opened 2020-06-16 15:16 UTC
I'm using a docker-compose setup (based on @mtojek 's) to test fleet, and I'm running into an enroll failure:

```
elastic-agent_1     | 2020-06-16T15:05:50Z DEBUG	client.go:178	Request method: POST, path: /api/ingest_manager/fleet/agents/enroll
elasticsearch_1     | {"type": "server", "timestamp": "2020-06-16T15:05:50,835Z", "level": "WARN", "component": "o.e.x.s.a.AuthenticationService", "cluster.name": "docker-cluster", "node.name": "2e727e51936f", "message": "Authentication using apikey failed - invalid ApiKey value", "cluster.uuid": "G8OcOApcTIK2EpgrOArb6g", "node.id": "FpDR6jCeTtKfEPwDqm_aRA" ,
elasticsearch_1     | "stacktrace": ["java.lang.IllegalArgumentException: invalid ApiKey value",

kibana_1            | {"type":"log","@timestamp":"2020-06-16T15:05:50Z","tags":["info","plugins","security","authentication"],"pid":7,"message":"Authentication attempt failed: [security_exception] missing authentication credentials for REST request [/_security/_authenticate], with { header={ WWW-Authenticate={ 0=\"ApiKey\" & 1=\"Basic realm=\\\"security\\\" charset=\\\"UTF-8\\\"\" } } }"}

elastic-agent_1     | fail to enroll: fail to execute request to Kibana: Status code: 401, Kibana returned an error: Unauthorized, message: [security_exception] missing authentication credentials for REST request [/_security/_authenticate], with { header={ WWW-Authenticate={ 0="ApiKey" & 1="Basic realm=\"security\" charset=\"UTF-8\"" } } }

```

The files used by `docker-compose` : 

```
version: '2.3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.0-SNAPSHOT
    healthcheck:
      test: ["CMD", "curl", "-f", "-u", "elastic:changeme", "http://127.0.0.1:9200/"]
      retries: 300
      interval: 1s
    environment:
    - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    - "network.host="
    - "transport.host=127.0.0.1"
    - "http.host=0.0.0.0"
    - "indices.id_field_data.enabled=true"
    - "xpack.license.self_generated.type=trial"
    - "xpack.security.enabled=true"
    - "xpack.security.authc.api_key.enabled=true"
    - "ELASTIC_PASSWORD=changeme"
    ports:
      - "0.0.0.0:9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.8.0-SNAPSHOT
    depends_on:
      elasticsearch:
        condition: service_healthy
      package-registry:
        condition: service_healthy
    healthcheck:
      test: "curl -f http://127.0.0.1:5601/login | grep kbn-injected-metadata 2>&1 >/dev/null"
      retries: 600
      interval: 1s
    volumes:
      - ./kibana.config.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - "0.0.0.0:5601:5601"

  package-registry:
    image: docker.elastic.co/package-registry/package-registry:master
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8080"]
      retries: 300
      interval: 1s
    volumes:
      - ../../build/public:/registry/public
    ports:
      - "127.0.0.1:8080:8080"

```

```

version: '2.3'
services:
  elastic-agent:
    image: docker.elastic.co/beats/elastic-agent:7.8.0-SNAPSHOT
    depends_on:
      elasticsearch:
        condition: service_healthy
      kibana:
        condition: service_healthy
    environment:
    - "FLEET_ENROLL=1"
    - "FLEET_SETUP=1"
    - "KIBANA_HOST=http://kibana:5601"
```

This seems to be fairly new. Any ideas?

**Comment by ph** [comment] 2020-06-16 15:31
@EricDavisX Have you seen that issue  in the latest snapshot?

**Comment by EricDavisX** [comment] 2020-06-16 15:55
I don't see it in my limited docker usage.  I set up the 7.8
ES/Logstash/Kibana Docker images manually and didn't use the Agent Docker
container.  That is where the error seems to be, I don't think it is a
product bug.  As a company, we just need to figure out how to run the agent
container in all of the different releases where it will be used and in its
two modes (stand-alone and Fleet) and make sure that info is propagated
out.  Good questions coming in, glad to see the testing too.

**Comment by michalpristas** [comment] 2020-06-17 19:19
i reproduced the issue.
running 
- ES: 7.8
- Kibana: 7.8
- Package registry: untagged docker image :latest
- custom built agent from 7.8 branch

the problem is when i try to execute setup script 
```
function setup(){
  curl -X POST  ${KIBANA_HOST:-http://localhost:5601}/api/ingest_manager/setup -H 'kbn-xsrf: true' -u ${KIBANA_USERNAME:-elastic}:${KIBANA_PASSWORD:-changeme}
  curl -X POST  ${KIBANA_HOST:-http://localhost:5601}/api/ingest_manager/fleet/setup \
    -H 'Content-Type: application/json' \
    -H 'kbn-xsrf: true' \
    -u ${KIBANA_USERNAME:-elastic}:${KIBANA_PASSWORD:-changeme}
}

```

it Fails on 

```
Error installing prebuilt index templates [x_content_parse_exception] [1:47] [index_template] unknown field [data_stream]
```

after this fails it tries to enroll but it cannot as fleet is still not setup correctly

if i try to enroll without a setup i end up with the same error on enroll.

@nchaulet any ideas why setup might fail here?

**Comment by nchaulet** [comment] 2020-06-17 19:31
During the setup we are installing the `base` and `system` package and looks like the base package is containing a `data_stream` field that is not valid with ES 7.8 https://github.com/elastic/package-storage/blob/42744909a9154d6aa99806da6581cb1ee7dd587d/packages/base/0.2.0/elasticsearch/index-template/logs.json#L7 

Maybe @neptunian can give more advice on what is the best way to solve this

**Comment by EricDavisX** [comment] 2020-06-17 21:35
do we need to support the 7.8 line with the 'master' / prod package registry files?
 - thats a question coming from Michal's post of how he reproduced it, with 'latest' as:
Package registry: untagged docker image :latest

I don't have full context, just making sure here

**Comment by ruflin** [comment] 2020-06-18 06:13
The KB 7.8 release does not and should not work against the master registry. Closing this.

**Comment by mtojek** [comment] 2021-02-03 10:34
Let me reopen this issue, as it still happens on the package-storage side. The idea was to fix it with `xpack.security.authc.realms.file`, but we're failing so far.

For reference: https://github.com/elastic/elastic-package/pull/240

**Comment by mtojek** [comment] 2021-02-03 10:48
I looked deeper and it seems to be a different root cause. Sorry for the noise.

**Closed by mtojek** 2021-02-03 10:48 UTC
Labels: Team:Ingest Management, bug, v7.8.0
