### ISSUE TITLE
Err Failed to publish events caused by i/o timeout

### ISSUE THREAD

**Issue by aniude** [elastic/beats#3088] opened 2016-12-01 04:57 UTC
The filebeat log is:
`
2016-11-30T23:54:10-05:00 ERR Failed to publish events caused by: read tcp 127.0.0.1:45706->127.0.0.1:5043: i/o timeout
`

`
2016-11-30T23:54:10-05:00 INFO Error publishing events (retrying): read tcp 127.0.0.1:45706->127.0.0.1:5043: i/o timeout
`

And make sure the logstash is running. telnet 5043 is well.  Anyone can help?

**Comment by ruflin** [comment] 2016-12-01 07:24
There are quite a few threads related to this here: https://discuss.elastic.co/search?q=Failed%20to%20publish%20events%20caused%20by%3A%20read%20tcp Please check this threads. In case you can't find the solution, please open a discuss topic with your configs form filebeat and logstash and add your log files there. I'm closing this issue as we try to keep Github for confirmed bugs.

**Closed by ruflin** 2016-12-01 07:24 UTC

**Comment by iahmad-khan** [comment] 2018-01-25 09:46
Hi , 

Any update on this?

I have read those articles and applied all the things but still no luck

2018-01-25T09:44:22Z ERR  Failed to publish events caused by: client is not connected
2018-01-25T09:44:23Z ERR  Failed to publish events: client is not connected
2018-01-25T09:44:53Z ERR  Failed to publish events caused by: read tcp 193.62.193.70:36859->10.3.10.44:5043: i/o timeout
2018-01-25T09:44:53Z ERR  Failed to publish events caused by: read tcp 193.62.193.70:36859->10.3.10.44:5043: i/o timeout
2018-01-25T09:44:53Z ERR  Failed to publish events caused by: read tcp 193.62.193.70:36859->10.3.10.44:5043: i/o timeout
2018-01-25T09:44:53Z ERR  Failed to publish events caused by: read tcp 193.62.193.70:36859->10.3.10.44:5043: i/o timeout
2018-01-25T09:44:53Z ERR  Failed to publish events caused by: read tcp 193.62.193.70:36859->10.3.10.44:5043: i/o timeout
2018-01-25T09:44:53Z ERR  Failed to publish events caused by: read tcp 193.62.193.70:36859->10.3.10.44:5043: i/o timeout

**Comment by coofercat** [comment] 2018-02-05 11:58
I used a `bulk_max_size: 1024` as suggested in the link above, and it worked for me.

**Comment by iahmad-khan** [comment] 2018-02-05 12:19
What logstash plugins are you using? Try it with ip2location plugin and
report back the results

**Comment by coofercat** [comment] 2018-02-05 12:22
I'm just sucking up filebeat and pushing it to elasticsearch, and don't need ip2location, so sorry, I won't be trying it with that. I'd suggest you try removing the plugin and reporting back the results.

**Comment by cgough** [comment] 2018-03-07 17:04
Any update on this?

**Comment by cgough** [comment] 2018-03-09 20:28
what is the solution for this?

**Comment by iahmad-khan** [comment] 2018-03-10 12:56
Reduce the bulk size to 100. And see the plugin situration on server side ,
or configure logstash to buffer

**Comment by vitich** [comment] 2018-03-22 15:49
bulk_max_size didn't help for me.
Just don't use ip2location - use geoip...
https://discuss.elastic.co/t/ip2location-module/125203

**Comment by iahmad-khan** [comment] 2018-03-22 22:47
yes , but geoip doesn't provide what ip2location provides. my setup is running smooth now.

**Comment by vitich** [comment] 2018-03-22 22:52
What exactly geoip does not provide?
![photo_2018-03-23_00-51-36](https://user-images.githubusercontent.com/12166319/37802769-7325a336-2e34-11e8-9f71-d0b26c2405d7.jpg)

**Comment by iahmad-khan** [comment] 2018-03-22 23:07
In our case we are interested in ISP and Usage Type fields.

**Comment by vitich** [comment] 2018-03-23 07:38
Look carefully at the screenshot 
I tried to turn on ip2location with last DB11 base...


![37802769-7325a336-2e34-11e8-9f71-d0b26c2405d7](https://user-images.githubusercontent.com/12166319/37816873-52633bce-2e7d-11e8-82ca-6ad27610f1ed.jpg)

**Comment by vitich** [comment] 2018-03-23 08:08
![screenshot from 2018-03-23 09-51-48](https://user-images.githubusercontent.com/12166319/37818238-2a7683aa-2e82-11e8-8de3-f3b7b9732270.png)

**Comment by iahmad-khan** [comment] 2018-03-23 10:21
When I get free I will explain in detail with screenshots.

**Comment by iahmad-khan** [comment] 2018-03-23 11:31
Hi , 

IP2location provides me the following information , the most significant ones for me are:

domain
ISP
usage type

"ip2location": {
            "properties": {
              "area_code": {
                "type": "text",
                "norms": false,
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "city": {
                "type": "text",
                "norms": false,
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "country_long": {
                "type": "text",
                "norms": false,
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "country_short": {
                "type": "text",
                "norms": false,
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "domain": {
                "type": "text",
                "norms": false,
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "elevation": {
                "type": "float"
              },
              "idd_code": {
                "type": "text",
                "norms": false,
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "ip_address": {
                "type": "ip",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "isp": {
                "type": "text",
                "norms": false,
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "latitude": {
                "type": "float"
              },
              "longtitude": {
                "type": "float"
              },
              "mcc": {
                "type": "text",
                "norms": false,
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "mnc": {
                "type": "text",
                "norms": false,
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "mobile_brand": {
                "type": "text",
                "norms": false,
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "net_speed": {
                "type": "text",
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "region": {
                "type": "text",
                "norms": false,
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "time_zone": {
                "type": "text",
                "norms": false,
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "usage_type": {
                "type": "text",
                "norms": false,
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "weather_station_code": {
                "type": "text",
                "norms": false,
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "weather_station_name": {
                "type": "text",
                "norms": false,
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              },
              "zip_code": {
                "type": "text",
                "norms": false,
                "fields": {
                  "keyword": {
                    "type": "keyword",
                    "ignore_above": 256
                  }
                }
              }
            }
          }

**Comment by KeithTt** [comment] 2021-07-29 08:38
bulk_max_size didn't help for me...

Any update?

**Comment by KeithTt** [comment] 2021-07-29 09:22
Restart logstash and it worked...
