### ISSUE TITLE
panic: runtime error: index out of range goroutine 1 [running]: while running metricbeat setup

### ISSUE THREAD

**Issue by pratcool007** [elastic/beats#22704] opened 2020-11-21 19:18 UTC
Hi All,

I am new to GitHub and ELK. I am facing below issue and someone pointed out to report this on GitHub. (https://stackoverflow.com/questions/64942752/panic-runtime-error-index-out-of-range-goroutine-1-running-while-running-me?noredirect=1#comment114820765_64942752)
Can you please help to solve the issue. 

I am running metricbeat setup command through ansible but getting below error. Can someone please sugesst where to check to fix this issue. After 2nd playbook run can see this host is skipped or ignored (may be due to when condition) but issues still exists if I run this command manually on server.

```
TASK [metricbeat : Metricbeat default dashboards for Kibana] ***********************************************************************************************************
fatal: [server]: FAILED! => {
    "changed": true,
    "cmd": "metricbeat setup -e -E output.kafka.enabled=false -E output.elasticsearch.hosts=['http://<IP of server1>:5200', 'http://<IP of server2>:5200', 'http://<IP of server3>:5200'] -E output.elasticsearch.username=elastic -E output.elasticsearch.password=<Password> -E setup.kibana.host=<IP of server1> > /var/log/metricbeat_dashboard_load.log",
    "delta": "0:00:00.122571",
    "end": "2020-11-20 15:21:45.747724",
    "rc": 2,
    "start": "2020-11-20 15:21:45.625153"
}

STDERR:

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/internal/parse.(*flagParser).parseArray(0xc0004dd830, 0x3f2f4e0, 0xc0004dd758, 0x1de37a8, 0x7ffd0000002c)
        /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/internal/parse/parse.go:125 +0x3c3
github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/internal/parse.(*flagParser).parseValue(0xc0004dd830, 0x4517e63, 0x1, 0x4654878, 0x0, 0x1b, 0x1)
        /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/internal/parse/parse.go:102 +0x1e7
github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/internal/parse.(*flagParser).parse(0xc0004dd830, 0x1c, 0x4654878, 0x7ffdd60d5da2, 0x1c)
        /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/internal/parse/parse.go:67 +0x6d
github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/internal/parse.Value(0x7ffdd60d5da2, 0x1c, 0x4517e72, 0x1, 0x0, 0x1)
        /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/internal/parse/parse.go:56 +0x84
github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/flag.NewFlagKeyValue.func1(0x7ffdd60d5d87, 0x37, 0x0, 0x1d06a0f, 0xc0004dd9c0, 0xc87d504f, 0x84177415c81ea561)
        /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/flag/value.go:69 +0x325
github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/flag.(*FlagValue).Set(0xc0001400f0, 0x7ffdd60d5d87, 0x37, 0x4517e7a, 0xc0001b80d0)
        /go/src/github.com/elastic/beats/vendor/github.com/elastic/go-ucfg/flag/util.go:64 +0x42
github.com/elastic/beats/libbeat/common.(*SettingsFlag).Set(0xc0001400f0, 0x7ffdd60d5d87, 0x37, 0x1, 0xc0001b8160)
        /go/src/github.com/elastic/beats/libbeat/common/flags.go:209 +0x40
github.com/elastic/beats/vendor/github.com/spf13/pflag.(*FlagSet).Set(0xc0000bd0e0, 0x4517e7a, 0x1, 0x7ffdd60d5d87, 0x37, 0x6ef7700, 0xc00013aa80)
        /go/src/github.com/elastic/beats/vendor/github.com/spf13/pflag/flag.go:432 +0xe6
github.com/elastic/beats/vendor/github.com/spf13/pflag.(*FlagSet).Parse.func1(0xc0000b9ea0, 0x7ffdd60d5d87, 0x37, 0xc00013aa90, 0x1)
        /go/src/github.com/elastic/beats/vendor/github.com/spf13/pflag/flag.go:1028 +0x54
github.com/elastic/beats/vendor/github.com/spf13/pflag.(*FlagSet).parseSingleShortArg(0xc0000bd0e0, 0x7ffdd60d5d85, 0x1, 0xc0000f20c0, 0x9, 0xa, 0xc00034c6d0, 0x7ffdd60d5d67, 0x0, 0xc0000f20b0, ...)
        /go/src/github.com/elastic/beats/vendor/github.com/spf13/pflag/flag.go:964 +0x298
github.com/elastic/beats/vendor/github.com/spf13/pflag.(*FlagSet).parseShortArg(0xc0000bd0e0, 0x7ffdd60d5d84, 0x2, 0xc0000f20c0, 0x9, 0xa, 0xc00034c6d0, 0xc0000f20b0, 0xa, 0xb, ...)
        /go/src/github.com/elastic/beats/vendor/github.com/spf13/pflag/flag.go:974 +0xd4
github.com/elastic/beats/vendor/github.com/spf13/pflag.(*FlagSet).parseArgs(0xc0000bd0e0, 0xc0000f20c0, 0x9, 0xa, 0xc00034c6d0, 0xc0000bd770, 0xc0000bd0e0)
        /go/src/github.com/elastic/beats/vendor/github.com/spf13/pflag/flag.go:1005 +0x6a6
github.com/elastic/beats/vendor/github.com/spf13/pflag.(*FlagSet).Parse(0xc0000bd0e0, 0xc0000f2000, 0x15, 0x16, 0x0, 0xc000052c20)
        /go/src/github.com/elastic/beats/vendor/github.com/spf13/pflag/flag.go:1031 +0xe3
github.com/elastic/beats/vendor/github.com/spf13/cobra.(*Command).ParseFlags(0xc0001ce240, 0xc0000f2000, 0x15, 0x16, 0x6f8ec20, 0xc0004dde98)
        /go/src/github.com/elastic/beats/vendor/github.com/spf13/cobra/command.go:1373 +0x9c
github.com/elastic/beats/vendor/github.com/spf13/cobra.(*Command).execute(0xc0001ce240, 0xc0000f2000, 0x15, 0x16, 0xc0001ce240, 0xc0000f2000)
        /go/src/github.com/elastic/beats/vendor/github.com/spf13/cobra/command.go:647 +0x8f
github.com/elastic/beats/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0001c6000, 0x3b342ee, 0xc0004ddf88, 0xc0000560b8)
        /go/src/github.com/elastic/beats/vendor/github.com/spf13/cobra/command.go:785 +0x2ca
github.com/elastic/beats/vendor/github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/elastic/beats/vendor/github.com/spf13/cobra/command.go:738
main.main()
        /go/src/github.com/elastic/beats/x-pack/metricbeat/main.go:21 +0x30

MSG:

non-zero return code
```

Thanks,

**Comment by andresrc** [comment] 2020-11-21 21:46
Hi, can you provide the version that you are using?

**Comment by pratcool007** [comment] 2020-11-23 07:58
Hi, Please find the same.

# metricbeat version
metricbeat version 7.4.0 (amd64), libbeat 7.4.0 [f940c36884d3749901a9c99bea5463a6030cdd9c built 2019-09-27 07:51:21 +0000 UTC]

**Comment by pratcool007** [comment] 2020-11-24 10:43
Hi,

Can someone please reply.

**Comment by andresrc** [comment] 2020-11-24 12:29
Are you able to reproduce it with the latest version? (7.10)

**Comment by urso** [comment] 2020-11-24 16:10
Judging by the stack trace I can see how the panic can happen if there is a missing `]` at the end of the string. 
Does the password start with a `[` or is the kibana address put into `[`? I also wonder if the host list is passed as is, or if there is some escaping done.

**Comment by ycombinator** [comment] 2020-11-24 16:19
BTW, I'm pretty sure this issue is a duplicate of this discuss post: https://discuss.elastic.co/t/panic-runtime-error-index-out-of-range-goroutine-1-running-while-running-metricbeat-setup/256220. I'm actively working with the user on discuss, FWIW.

**Comment by urso** [comment] 2020-11-24 16:34
Thank you. This will help to write an unit test for the config parsing.

Yeah, this looks like an escaping problem. Still Beats should not crash but create a meaningful error.

**Comment by pratcool007** [comment] 2020-11-24 16:48
Yes this is the duplicate of https://discuss.elastic.co/t/panic-runtime-error-index-out-of-range-goroutine-1-running-while-running-metricbeat-setup/256220

**Comment by jlind23** [comment] 2022-03-31 08:27
Backlog grooming: Closing for now.

**Closed by jlind23** 2022-03-31 08:27 UTC
Labels: Team:Services
