### ISSUE TITLE
7.11 BC2 Elastic Agent on Windows 10 goes 'unhealthy' and doesn't report any in-UI logs to ES

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#23402] opened 2021-01-07 18:03 UTC
Kibana version:
Kibana: 7.11 BC2 from cloud prod env

Installed the BC2 Agent on a known good Windows 10 x64 image

Agent file: 
https://staging.elastic.co/7.11.0-8f5ce7c2/downloads/beats/elastic-agent/elastic-agent-7.11.0-windows-x86_64.zip

no logs shown in Fleet UI so I'll get them off the host.  I was attempting to install Agent & Endpoint at the same time. I attempted this with the BC2 macOS artifact and all was working.

![Screen Shot 2021-01-07 at 12 57 23 PM](https://user-images.githubusercontent.com/12970373/103927650-ac670700-50e8-11eb-94eb-c841327b29b0.png)
![Screen Shot 2021-01-07 at 12 56 35 PM](https://user-images.githubusercontent.com/12970373/103927651-ac670700-50e8-11eb-92fb-6b7a72854d10.png)

**Comment by EricDavisX** [comment] 2021-01-07 18:05
@michalpristas was reviewing Agent use with me the last few days and he didn't see this problem with his Windows testing.  Which gives us hope, but also needs to be explained as soon as we can - not sure if it will relate to local builds of Agent vs Infra builds or what.

**Comment by EricDavisX** [comment] 2021-01-07 18:23
logs for Agent.  note, no Endpoint logs exist on disk as the folder isn't there at all.
[7.11-Windows-elastic-agent-json.log](https://github.com/elastic/beats/files/5783285/7.11-Windows-elastic-agent-json.log)

And here are more images, showing that on disk there is no 'Endpoint 'folder, and the Agent install was seemingly ok - but a little oddly, no filebeat location exists.  is that possibly a separate issue to follow up?
![agent-install-output](https://user-images.githubusercontent.com/12970373/103929356-331ce380-50eb-11eb-98a9-ad0ca656f13b.png)
<img width="496" alt="no-filebeat-location-is-strange" src="https://user-images.githubusercontent.com/12970373/103929359-33b57a00-50eb-11eb-9b4c-164c49b5103a.png">
<img width="613" alt="no-endpoint-location-on-disk" src="https://user-images.githubusercontent.com/12970373/103929360-33b57a00-50eb-11eb-8bbe-b949bc7add81.png">

**Comment by ph** [comment] 2021-01-07 18:59
@EricDavisX @michalpristas I am going to mark it as a blocker for the next BC, let's investigate that.

**Comment by ph** [comment] 2021-01-07 19:02
fyi @ruflin

**Comment by EricDavisX** [comment] 2021-01-07 20:11
I ran a comparison test on a known working (with prior Agent versions) x86 Win 7 vm.  I installed Agent and Endpoint and ended up seeing this issue again, meaning: no logs showing in UI from Agent (or Endpoint) 

For a comparison point I uninstall and and then when I install *just Agent without Endpoint, Agent seems to work better.  I wonder if the Endpoint 'Protection' feature could be negatively interacting in some way we don't know? It was merged right at the time we branched for Build Candidates (so we don't have other snapshot based tests and so we don't have a BC to compare against that didn't have it).

**Comment by ferullo** [comment] 2021-01-07 20:26
>  logs for Agent. note, no Endpoint logs exist on disk as the folder isn't there at all.

Is this when Endpoint was enabled or disabled?

> x86 Win 7 vm

Endpoint Self Protection will not be enabled on Win 7 so this problem shouldn't be related to Endpoint Self Protection. @bjmcnic can you confirm that Endpoint will not project Agent on x86 Win 7?

**Comment by EricDavisX** [comment] 2021-01-07 21:05
for the above, I only expected Endpoint folders on the policy where Endpoint was enabled - happy to confirm that.

**Comment by bjmcnic** [comment] 2021-01-07 21:25
I tested Win7x86 through Kibana and verified I got a 7.11.0-BC2 endpoint installed through the Agent's integration.  It was initially "Healthy".  I successfully killed the agent process using task manager to confirm the agent was not protected.  I then restarted the agent and watched the endpoint connect back up (using netstat).  Back in Kibana...the Agent now showed "Unhealthy" and remained that way for at least 5 minutes with no further interaction from me on the endpoint.  The "Last Activity" column did frequently update during this time to show Agent comms to Kibana were working.  As far as the Endpoint's presence on disk, I noted all the usually installed directories appeared present.

**Comment by kevinlog** [comment] 2021-01-08 15:08
I saw the same behavior as @bjmcnic on Win7x86.  I can get the Endpoint to standup and stream to ES on Win7.

However, I still see the Agent report an Unhealthy status

![image](https://user-images.githubusercontent.com/56395104/104029996-b1838f00-5198-11eb-9506-99e77b494b3e.png)

I still haven't been able to get it to work on Windows 10

**Comment by michalpristas** [comment] 2021-01-11 09:19
First thing i see is error log saying
`'Exec' failed: : operation 'Exec' failed: `
after looking more closely to it i found out there is an exit code `21` when running `install` command of endpoint (`endpoint-security install --upgrade --resources endpoint-security-resources.zip`)

the next thing i tried was to get agent out of the equation so i just unpacked endpoint artifact and ran the command manually after unpacking and while it seemed nothing is going on (no output) `$LastExitCode` reports `21` as in case with Agent.

could i ask somebody from endpoint team for verification and more insight if possible?

**Comment by bjmcnic** [comment] 2021-01-11 10:19
@michalpristas ...I just tried to reproduce this on my same Win7x86 machine using the `endpoint-security-7.11.0-BC2` and `%errorlevel%` as well as checking procmon's Process Exit Status for the precise command line you indicated.   Both reflected 0 (`ERROR_SUCCESS`).  Could you maybe add a couple options to that command line and see if we can get some more details?

`endpoint-security install --upgrade --resources endpoint-security-resources.zip --log stdout --log-level trace`

Perhaps that will indicate where what function might be returning `21 (ERROR_NOT_READY)` on your host.

**Comment by michalpristas** [comment] 2021-01-11 10:31
cc @bjmcnic 
```
PS C:\a\es> ./endpoint-security install --upgrade --resources endpoint-security-resources.zip --log stdout --log-level trace
2021-01-11 10:26:00: info: Main.cpp:278 Upgrading existing installation (protected)
2021-01-11 10:26:00: info: InstallLib.cpp:388 Attempting to create a rollback package
2021-01-11 10:26:00: trace: File.cpp:581 Function returned error status (Failed to copy a file)
2021-01-11 10:26:00: trace: InstallLib.cpp:346 Function returned error status (Failed to copy a file)
2021-01-11 10:26:00: info: InstallLib.cpp:395 Failed to create rollback package, attempting full uninstall
2021-01-11 10:26:00: debug: Service.cpp:801 PPL is supported
2021-01-11 10:26:00: trace: Util.cpp:469 Function returned error status (Start failed)
2021-01-11 10:26:00: warning: Util.cpp:869 Error encountered while unprotecting service for unintall
2021-01-11 10:26:00: error: Service.cpp:359 OpenServiceW failed with error 1060
2021-01-11 10:26:00: trace: Service.cpp:360 Function returned error status (Failure in an external software component) because of system status (1060/The specified service does not exist as an installed service.)
2021-01-11 10:26:00: trace: Service.cpp:419 Function returned error status (Failure in an external software component)
2021-01-11 10:26:00: error: Service.cpp:178 DeleteService failed with error 5
2021-01-11 10:26:00: trace: Service.cpp:179 Function returned error status (Failure in an external software component) because of system status (5/Access is denied.)
2021-01-11 10:26:00: error: Util.cpp:895 Endpoint service was unable to be deleted or scheduled for deletion.
2021-01-11 10:26:00: error: Service.cpp:169 OpenServiceA failed with error 1060
2021-01-11 10:26:00: trace: Service.cpp:170 Function returned error status (Failure in an external software component) because of system status (1060/The specified service does not exist as an installed service.)
2021-01-11 10:26:00: error: Util.cpp:913 Endpoint driver service was unable to be deleted or scheduled for deletion.
2021-01-11 10:26:00: debug: File.cpp:471 Removing [C:\Windows\System32\Drivers\ElasticElam.sys]
2021-01-11 10:26:00: trace: File.cpp:343 Function returned error status (Failure in an external software component)
2021-01-11 10:26:00: trace: File.cpp:343 Function returned error status (Failure in an external software component)
2021-01-11 10:26:00: trace: File.cpp:343 Function returned error status (Failure in an external software component)
2021-01-11 10:26:00: trace: File.cpp:343 Function returned error status (Failure in an external software component)
2021-01-11 10:26:00: trace: File.cpp:686 Function returned error status (I/O error) because of system status (3/The system cannot find the path specified.)
2021-01-11 10:26:00: trace: File.cpp:686 Function returned error status (I/O error) because of system status (2/The system cannot find the file specified.)
2021-01-11 10:26:00: info: InstallLib.cpp:247 Uninstall completed
2021-01-11 10:26:00: info: InstallLib.cpp:397 Proceeding with install
2021-01-11 10:26:00: info: InstallLib.cpp:181 Installing from endpoint-security-resources.zip
2021-01-11 10:26:00: info: Internal.cpp:188 Extracting installation artifacts
2021-01-11 10:26:00: debug: Util.cpp:961 Endpoint service already in use.
2021-01-11 10:26:00: trace: Internal.cpp:154 Function returned error status (Already exists)
2021-01-11 10:26:00: trace: InstallLib.cpp:186 Function returned error status (Already exists)
2021-01-11 10:26:00: info: InstallLib.cpp:420 Install failed and no rollback package exists
2021-01-11 10:26:00: trace: InstallLib.cpp:421 Function returned error status (Already exists)
2021-01-11 10:26:00: trace: Main.cpp:279 Function returned error status (Already exists)
```

side note, i removed previously installed instance running `endpoint-security uninstall` from within `C:/Program Files/Elastic/Endpoint` (not sure if last dir was called Endpoint but the path is correct in general)

**Comment by bjmcnic** [comment] 2021-01-11 13:54
cc @michalpristas

Thanks for the log, I was able to recreate that issue and I believe I've figured it 3 issues, in increasing criticality.

1. I had assumed from my own context earlier we were talking about Win7 x86, but from the title of the ticket and the log, it's evident you're trying to test on a Win10x64 box.  My bad, sorry about that.
2. The error that eventually results in `ERROR_NOT_READY (21)` stems from an upgrade attempt after a failed install due to the bug (bullet 1) that's going to be fixed in this PR (https://github.com/elastic/endpoint-dev/pull/8287).  Again, that's my bug, sorry.
3. The install failed because the BC2 (at least what I believe is BC2, got the same hash installed through agent and downloaded from https://staging.elastic.co/7.11.0-8f5ce7c2/summary-7.11.0.html) isn't officially signed by Elastic.  It's still test signed while the packaged ELAM driver is officially signed and won't allow our test signed endpoint binary to be started after configured as protected.  Mentioning @ferullo so hopefully he can point me in the right direction on how to remedy this.

For you VM that's now not in a great state, if you use regedit.exe to delete `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\ElasticEndpoint` (and
`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\ElasticELAMDriver` and
`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\ElasticEndpointDriver` if they exist), then reboot and you should be clean enough to succeed an install of a subsequent endpoint once the signing is fixed.

**Comment by ph** [comment] 2021-01-11 19:16
So we agree here this is an issue with Endpoint and not the Elastic Agent for now, until we have new correctly signed binaries available to be tested?

**Comment by ferullo** [comment] 2021-01-11 19:23
@ph I think so, however 7.11.0 BC2 artifacts have been updated with correctly signed Endpoint binaries so this can be re-tested. Endpoint should now install on Windows. Anyone that has trouble can follow Ben's guidance at the end of this comment https://github.com/elastic/beats/issues/23402#issuecomment-757966429 to clean up their VM and get it back in a good state.

**Comment by bjmcnic** [comment] 2021-01-11 19:25
Yeah, here's the ticket with links to the newly signed endpoints: https://github.com/elastic/infra/issues/25794

**Comment by ph** [comment] 2021-01-11 19:30
Thanks everyone for working together on this!

**Comment by vipulsrivastava-qasource** [comment] 2021-01-12 12:09
Hi  @EricDavisX

We have validate this issue and found that endpoint installation successfully, But agent in Unhealthy state for window machine.. Please find the below observation and build details.

```
Platform: Staging
Version: 7.11.0
Commit: a5126f7a280a6f4a27dc3aca65c1c89ccd1ac694
Build number: 37605
Artifact: https://staging.elastic.co/7.11.0-8f5ce7c2/summary-7.11.0.html

```

OS | Test signing or SIP | Agent Installed with Policy Having Integration | Endpoint Installation | Agent status
-- | -- | -- | -- | --
Window 10 x64 | OFF | System and Endpoint Integration | Passed | Unhealthy
MAC Bigsur 11.1 | Enabled | System and Endpoint Integration | Passed | Healthy

Thanks.

**Comment by EricDavisX** [comment] 2021-01-12 19:48
I'm not seeing this in my 7.11 Windows tests, but we discussed it and it does seem it could be intermittent / unexpectedly showing.  At this point we believe we have all of the Windows specific signing / build problems sorted, tho it is possible the tester had an interim version of the BC which was rebuilt twice yesterday.

It may also be the same as this which we think spans all OS types:
https://github.com/elastic/beats/issues/21598

so we can keep this open for now, but we aren't tracking it until engineering is freed up and we fix the above issue we're researching.

**Comment by vipulsrivastava-qasource** [comment] 2021-01-13 13:05
Hi @EricDavisX

Thank for sharing the details.

We have re-validate this issue on widow 10  for both agent and agent with endpoint installation. Please find the below observation and build details.

Platform: Staging
Version: 7.11.0
Commit: a5126f7a280a6f4a27dc3aca65c1c89ccd1ac694
Build number: 37605
Artifact: https://staging.elastic.co/7.11.0-8f5ce7c2/summary-7.11.0.html


OS |Agent installation | Endpoint Installation
-- | -- | --
Window 10 x64 | Unhealthy Agent |  Success Endpoint but Unhealthy Agent


![agent_Integration](https://user-images.githubusercontent.com/69579402/104455995-0c204f00-55ce-11eb-898a-2b2b89bb3583.png)


```
Logs : [elastic_agent][info] 2021-01-13T05:38:45-05:00: type: 'STATE': sub_type: 'RUNNING' message: Application: endpoint-security--7.11.0[31656690-556c-11eb-b406-0f696238525e]: State changed to RUNNING: 
16:50:01.980
elastic_agent
[elastic_agent][info] 2021-01-13T06:19:58-05:00: type: 'STATE': sub_type: 'RUNNING' message: Application: endpoint-security--7.11.0[31656690-556c-11eb-b406-0f696238525e]: State changed to DEGRADED: Missed last check-in
16:50:08.986
elastic_agent
[elastic_agent][info] 2021-01-13T06:20:07-05:00: type: 'STATE': sub_type: 'RUNNING' message: Application: endpoint-security--7.11.0[31656690-556c-11eb-b406-0f696238525e]: State changed to RUNNING: 
17:59:23.662
elastic_agent
[elastic_agent][error] Could not communicate with Checking API will retry, error: Status code: 503, Kibana returned an error: Service Unavailable, message: socket hang up
```

Thanks

**Comment by EricDavisX** [comment] 2021-01-13 13:56
Thank you, I am expecting it may be visible until we test with BC3.  We'll want to re-test in a day when it is available.  Thank you, @vipulsrivastava-qasource !

**Comment by karanbirsingh-qasource** [comment] 2021-01-21 12:28
Hi @EricDavisX 

We have validated this issue on 7.11.0 BC4 Cloud Production and found that issue is still persisting . Agent remains in Unhealthy status.

**Build Details:**
```
Platform: production
version: 7.11.0
Commit:efd7b70e2803294a95395629dee55c89441d742a
Build:37776
```

Snapshot:
- Signing is OFF
![image](https://user-images.githubusercontent.com/59917825/105350834-bc670680-5c11-11eb-9577-bd710923eefc.png)
- agent installation
![image](https://user-images.githubusercontent.com/59917825/105350736-9b061a80-5c11-11eb-824a-1dc9b1654874.png)
- agent+Endpoint installation
![image](https://user-images.githubusercontent.com/59917825/105350894-cee14000-5c11-11eb-8f40-e260d7dc0e97.png)
![image](https://user-images.githubusercontent.com/59917825/105350903-d1439a00-5c11-11eb-8aee-84ce41e947f5.png)

**Logs:**
- Logs ( Agent Details Page)
```
17:49:36.203
elastic_agent
[elastic_agent][error] failed to load markeropen C:\Program Files\Elastic\Agent\data\.update-marker: The system cannot find the file specified.
17:49:38.357
elastic_agent
[elastic_agent][warn] failed to ack update open C:\Program Files\Elastic\Agent\data\.update-marker: The system cannot find the file specified.
17:49:38.361
elastic_agent
[elastic_agent][warn] Elastic Agent status changed to: 'degraded'
Showing entries until Jan 21, 17:49:38


```
- Logs for machine [elastic-agent-json.zip](https://github.com/elastic/beats/files/5849238/elastic-agent-json.zip)

**Comment by EricDavisX** [comment] 2021-01-21 15:41
Thank you for confirming - we have a fix for both issues (they are separate issues oddly enough) - and neither one is in BC4 - we will wait and re-test with BC5.  The 'logs' issue is not merged yet, but is in Engg testing

**Closed** 2021-01-25 19:17 UTC
Labels: Team:Ingest Management, impact:critical, v7.11.0

**Comment by vipulsrivastava-qasource** [comment] 2021-01-28 05:49
Hi @EricDavisX

We have validated this issue on `7.11.0 BC5` Cloud Production and found that issue is fixed . Now, Agent and Agent + Endpoint both installation is in Healthy status.

Please find below observation and build details.

```
Platform: production
version: 7.11.0
Commit : d801a7bb08e17368584d00fbd97a5d0006285b51
Build : 37827
```

**Screenshot**

- Signing is OFF

![Testsigning_off](https://user-images.githubusercontent.com/69579402/106092605-a0ed8580-6154-11eb-8410-edc4333174be.png)

- Agent and Agent + Endpoint installation

![Endpoint_installation](https://user-images.githubusercontent.com/69579402/106095849-828a8880-615a-11eb-9595-9fdfb402aadd.png)

![Admin_endpoint](https://user-images.githubusercontent.com/69579402/106092616-a8149380-6154-11eb-8fa2-5bd2f6f74ec2.png)

**Logs :**

No agent or endpoint installation error found.

```
10:56:04.477
elastic_agent.endpoint_security
[elastic_agent.endpoint_security][error] Util.cpp:1126 Remove process trust label for: C:\Windows\ELAMBKUP\ElasticElam.sys failed with: Failure in an external software component
10:56:04.815
elastic_agent.endpoint_security
[elastic_agent.endpoint_security][error] Http.cpp:38 CURL error 42: Error [Callback aborted]
10:57:12.799
elastic_agent
[elastic_agent][error] failed to load markeropen C:\Program Files\Elastic\Agent\data\.update-marker: The system cannot find the file specified.
10:58:21.308
elastic_agent.endpoint_security
[elastic_agent.endpoint_security][error] Response.cpp:495 Setting malware to failure because of workflow status
10:58:21.309
elastic_agent.endpoint_security
[elastic_agent.endpoint_security][error] Response.cpp:495 Setting ransomware to failure because of workflow status
10:58:21.309
elastic_agent.endpoint_security
[elastic_agent.endpoint_security][error] Response.cpp:495 Setting antivirus_registration to failure because of workflow status
10:58:21.309
elastic_agent.endpoint_security
[elastic_agent.endpoint_security][error] Response.cpp:495 Setting events to failure because of workflow status
10:58:21.310
elastic_agent.endpoint_security
[elastic_agent.endpoint_security][error] Response.cpp:495 Setting streaming to failure because of workflow status
10:58:21.310
elastic_agent.endpoint_security
[elastic_agent.endpoint_security][error] Response.cpp:495 Setting logging to failure because of workflow status
10:58:21.316
elastic_agent.endpoint_security
[elastic_agent.endpoint_security][error] Config.cpp:1570 Initial configuration application failed
10:58:21.317
elastic_agent.endpoint_security
[elastic_agent.endpoint_security][error] Entry.cpp:324 Failed to apply initial policy from on disk configuration (Initial Policy Application Failed)
10:58:21.317
elastic_agent.endpoint_security
[elastic_agent.endpoint_security][error] Entry.cpp:324 Failed to apply initial policy from on disk configuration (Initial Policy Application Failed)
```
