### ISSUE TITLE
Delete complete harvested log file in filebeat

### ISSUE THREAD

**Issue by yin-bp** [elastic/beats#16357] opened 2020-02-15 07:17 UTC
**Describe the enhancement:**
Delete log file after complete harvested it use filebeat ,use delete_complete: true to control.
**Describe a specific use case for the enhancement or feature:**

**Comment by ycombinator** [comment] 2020-02-18 15:52
Duplicate of #714. Please follow and contribute to the discussion there.

**Closed by ycombinator** 2020-02-18 15:52 UTC
