### ISSUE TITLE
Filebeat not closing deleted files

### ISSUE THREAD

**Issue by joshuaspence** [elastic/beats#2968] opened 2016-11-09 05:05 UTC
On an Ubuntu 16.04 host with Filebeat 5.0.0, we experience an issue in which the host ran out of disk space. It seems that Filebeat was keeping file descriptors open well after the original log file had been removed. This might be our own fault, because of the following two facts:

  - We have configured a Filebeat prospector to harvest Filebeat's own logs.
  - Whilst debugging an unrelated issue a few days ago, I set `logging.level` to `debug` on the host which ran out of disk space.

Here is the output of running `sudo lsof | grep filebeat | grep /var/log/filebeat` on the affected host: https://gist.github.com/joshuaspence/82489c5ee34f5c0c63596e0bab844d00

I was able to reproduce this issue with the following Filebeat configuration:

```
filebeat.spool_size: 2048
filebeat.publish_async: false
filebeat.idle_timeout: 5s
filebeat.registry_file: /var/lib/filebeat/registry
filebeat.config_dir: /etc/filebeat/conf.d
filebeat.shutdown_timeout: 0
fields_under_root: true
queue_size: 1000
output.logstash:
  hosts:
    - beats.service.consul:5044
  worker: 3
  loadbalance: true
logging.level: debug
filebeat:
  prospectors:
    - input_type: log
      paths:
        - /var/log/filebeat/filebeat
      encoding: plain
      fields_under_root: false
      document_type: filebeat
      scan_frequency: 10s
      harvester_buffer_size: 16384
      max_bytes: 10485760
      tail_files: false
      backoff: 1s
      max_backoff: 10s
      backoff_factor: 2
```

After around half an hour, this is what I saw:

```
> sudo lsof | grep filebeat | grep /var/log/filebeat | cut -c 81- | sort | uniq
393882 /var/log/filebeat/filebeat.7 (deleted)
411420 /var/log/filebeat/filebeat.7 (deleted)
411421 /var/log/filebeat/filebeat.7 (deleted)
414295 /var/log/filebeat/filebeat.7 (deleted)
414296 /var/log/filebeat/filebeat.7 (deleted)
427793 /var/log/filebeat/filebeat.7 (deleted)
427794 /var/log/filebeat/filebeat.7 (deleted)
427805 /var/log/filebeat/filebeat.7 (deleted)
427806 /var/log/filebeat/filebeat.7 (deleted)
427807 /var/log/filebeat/filebeat.7 (deleted)
427808 /var/log/filebeat/filebeat.7 (deleted)
427809 /var/log/filebeat/filebeat.7 (deleted)
427810 /var/log/filebeat/filebeat.7 (deleted)
427811 /var/log/filebeat/filebeat.7 (deleted)
427812 /var/log/filebeat/filebeat.7 (deleted)
427813 /var/log/filebeat/filebeat.7 (deleted)
427814 /var/log/filebeat/filebeat.7 (deleted)
427815 /var/log/filebeat/filebeat.7 (deleted)
427821 /var/log/filebeat/filebeat.7 (deleted)
427822 /var/log/filebeat/filebeat.7 (deleted)
427823 /var/log/filebeat/filebeat.7 (deleted)
427825 /var/log/filebeat/filebeat.7 (deleted)
427826 /var/log/filebeat/filebeat.7 (deleted)
427828 /var/log/filebeat/filebeat.7 (deleted)
427829 /var/log/filebeat/filebeat.7 (deleted)
427831 /var/log/filebeat/filebeat.7 (deleted)
427832 /var/log/filebeat/filebeat.7 (deleted)
427834 /var/log/filebeat/filebeat.6
427835 /var/log/filebeat/filebeat.5
427836 /var/log/filebeat/filebeat.4
427838 /var/log/filebeat/filebeat.3
427839 /var/log/filebeat/filebeat.2
427840 /var/log/filebeat/filebeat.1
427846 /var/log/filebeat/filebeat
```

**Comment by ruflin** [comment] 2016-11-09 07:15
Can you share some messages from the debug log? Could it be that your output is not catching up with the number of events sent?

**Comment by avleen** [comment] 2016-11-19 02:09
We're also experiencing the same issue and trying to figure out what's happening.
We have filebeat reading a number of files (not its own log) and shipping those.

When logrotate moves the file and a new one is created, the new file is followed correctly.
But the old file isn't let go, even though filebeat has reached EOF.

We see Filebeat reach the end of the file:
```
2016-11-19T02:00:01Z DBG  End of file reached: /var/log/elasticsearch1/soxelk-access.log; Backoff now.
```
The the new file is picked up:
```
2016-11-19T02:00:02Z DBG  Check file for harvesting: /var/log/elasticsearch1/soxelk-access.log
2016-11-19T02:00:02Z DBG  Update existing file for harvesting: /var/log/elasticsearch1/soxelk-access.log
2016-11-19T02:00:02Z DBG  File previously found: /var/log/elasticsearch1/soxelk-access.log
2016-11-19T02:00:02Z DBG  Launching harvester on rotated file: /var/log/elasticsearch1/soxelk-access.log
2016-11-19T02:00:02Z DBG  harvest: "/var/log/elasticsearch1/soxelk-access.log" (offset snapshot:0)
2016-11-19T02:00:02Z INFO Harvester started for file: /var/log/elasticsearch1/soxelk-access.log
```

And then nothing about the old file being closed.

**Comment by ruflin** [comment] 2016-11-21 12:22
@avleen Which filebeat version are you using? What is your config file (especially close_* options)?

**Comment by joshuaspence** [comment] 2016-11-22 03:48
Here is the contents of `/var/log/filebeat/filebeat`: https://gist.github.com/joshuaspence/ab4bd664832f357dc6401cd7260f009e

**Comment by ruflin** [comment] 2016-11-22 09:39
@joshuaspence See my comment here: https://github.com/elastic/beats/issues/2968#issuecomment-259348148

**Comment by joshuaspence** [comment] 2016-11-22 20:13
Yep, I figured that it was at least partially my fault. I just wonder if Filebeat can do a better job of detecting this problem?

**Comment by ruflin** [comment] 2016-11-23 11:35
@joshuaspence Are you referring to harvesting its own log files or that the output cannot keep up with the number of events? One of the problems is that filebeat has a very local view, so its hard to tell if there is a problem with the network or a remote service etc. Perhaps we could add some "hints" on what could be wrong if it get stalled for more then x seconds. What would be your expectation?

BTW: I suggest to close this issue if it is ok for you?

**Comment by ruflin** [comment] 2017-01-24 07:04
Closing as suggested above.

**Closed by ruflin** 2017-01-24 07:04 UTC
Labels: needs details

**Comment by mrjameshamilton** [comment] 2017-11-01 13:46
We have the same problem. Filebeat (5.3.0) is keeping open deleted files. Even worse it's opening files that don't even match the pattern.

We have a pattern like "/logs/folder1/folder2/*.log" and it's opening "/logs/folder1/folder2/*.log.bak".

We also have some errors int the log, is this related? 

`2017-09-05T13:42:55+02:00 ERR Failed to publish events caused by: read tcp 172.18.219.237:40918->188.184.86.242:5044: i/o timeout
2017-09-05T13:42:55+02:00 INFO Error publishing events (retrying): read tcp 172.18.219.237:40918->188.184.86.242:5044: i/o timeout`

**Comment by mrjameshamilton** [comment] 2017-11-02 16:17
The open files of name *.log.bak are because they are renamed at some point. So that part is explained.

But we have the problem of the files being kept open (which then take up all the disk space).

**Comment by ruflin** [comment] 2017-11-06 03:29
@mrjameshamilton Could you open a topic on discuss and share there your full config file?
