### ISSUE TITLE
Filebeat only checks for closed or renamed files when reaching EOF

### ISSUE THREAD

**Issue by ZhiqinYang** [elastic/beats#5556] opened 2017-11-11 08:37 UTC
https://github.com/elastic/beats/blob/master/filebeat/prospector/log/log.go#line49
```
func (f *Log) Read(buf []byte) (int, error) {
	totalN := 0

	for {
		select {
		case <-f.done:
			return 0, ErrClosed
		default:
		}

		n, err := f.fs.Read(buf)
		if n > 0 {
			f.offset += int64(n)
			f.lastTimeRead = time.Now()
		}
		totalN += n

		// Read from source completed without error
		// Either end reached or buffer full
		if err == nil {
			// reset backoff for next read
			f.backoff = f.config.Backoff
			return totalN, nil
		}

		// Move buffer forward for next read
		buf = buf[n:]

		// Checks if an error happened or buffer is full
		// If buffer is full, cannot continue reading.
		// Can happen if n == bufferSize + io.EOF error
		err = f.errorChecks(err)
		if err != nil || len(buf) == 0 {
			return totalN, err
		}

		logp.Debug("harvester", "End of file reached: %s; Backoff now.", f.fs.Name())
		f.wait()
	}
}
```
why  f.errorChecks method not follow  n, err := f.fs.Read(buf) ？ if file is ready and name is changed or remove how it know the action?   because  err == nil you return it back .

why not do as follow:
n, err := f.fs.Read(buf)
err = f.errorChecks(err)

**Comment by ruflin** [comment] 2017-11-13 02:30
If you have a look at `checkError` you will see that it creates some new errors in certain cases and set other errors to `nil`. So I think the above is correct as it is. 

Perhaps you can share some more background on the issue you see and what you worried about? 

Please also open an issue for that on discuss so we can move to Github in case we can confirm it's a bug or a feature request. Closing this, happy to follow further on discuss.

**Comment by ZhiqinYang** [comment] 2017-11-13 03:19
sorry I mean if a filename changed it could not know in time， because the file in reading and not reach eof!

**Comment by ruflin** [comment] 2017-11-14 00:53
Knowing about the renaming of files is "best effort". File are harvester by file handler and not based on the file name. So if a file name changes it's not required for filebeat to know about it immidiately as the file handler stays the same.

Can you share some more on your use case and where the above is a problem?

**Comment by ZhiqinYang** [comment] 2017-11-14 07:39
@ruflin 
I run docker daemon with this --log-opt max-size=1024m --log-opt max-file=2,  an application produce logs with 10w/s when  the log files is removed or name changed by docker, but filebeat remain read it and the inode not released!

**Comment by ruflin** [comment] 2017-11-15 01:47
If you want to stop reading the file when it's removed / renamed, you should use `close_renamed` and `close_removed`. There is a small delay which I think from my perspective is acceptable.

**Comment by ZhiqinYang** [comment] 2017-11-15 05:59
I did this, but I found it execute in errorChecks if a file is so big that not read the end ! how can I give up it?

**Comment by ruflin** [comment] 2017-11-20 04:07
The error check is done for each line it reads, so as soon as the next line is read, it should detect the change.

Perhaps I miss something here?

**Comment by ZhiqinYang** [comment] 2017-11-20 10:29
I'm sorry. If a file is very very large and filebeat is reading it at the same moment. If suddenly the file name was changed or the file was deleted at that time,  For example, when the code run at `59:  n, err :f.fs.Read(buf)`, if `68: if err == nil`, and it returned right now. The code `80: err: f.errorCheck(err)` will not executed. how to make the field `close_renamed` and `close_removed` effect?

**Comment by ruflin** [comment] 2017-11-26 20:53
@ZhiqinYang Thanks a lot for bearing with me on this one. I know finally understand what you are getting at. In case of a successful read, it's never checked if the file was renamed or closed only at the end of the file.

TBH I don't think it's intentional that we have it this way and it is not the expected behaviour. On interesting property of having it the way it is, is that `f.fs.Stat()` is not called for every line it reads which could cause quite a  bit of overhead I think. So we should be careful changing this.

I'm reopening this as an issue and will change the title to be more fitting.

**Comment by ZhiqinYang** [comment] 2017-11-27 01:37
@ruflin  Thank you!

**Comment by GaryHuangBD** [comment] 2018-01-25 14:05
@ZhiqinYang Have u resolved it?

**Comment by ruflin** [comment] 2018-01-25 23:44
@GaryHuangBD There is no fix for this yet as it requires quite a bit of change in the logic that close_* options work. I assume in your case you also have a very large file?

**Comment by GaryHuangBD** [comment] 2018-01-26 03:10
@ruflin Actually, I have dozens of files to collect at the same time，and the size of  each file is about ten Gb. Do you have any suggestions to avoid this problem?

**Comment by ruflin** [comment] 2018-01-28 02:41
@GaryHuangBD I think your best temporary fix here is to use `close_timeout`.

**Comment by ZhiqinYang** [comment] 2018-01-31 02:08
i did like follow， i don't think it's a good way !

`
func (f *Log) checkFileStatus() error {
+  48     // Refetch fileinfo to check if the file was truncated or disappeared.
+  49     // Errors if the file was removed/rotated after reading and before
+  50     // calling the stat function
+  51     info, statErr := f.fs.Stat()
+  52     if statErr != nil {
+  53         logp.Err("Unexpected error reading from %s; error: %s", f.fs.Name(), statErr)
+  54         return statErr
+  55     }
+  56
+  57     // check if file was truncated
+  58     if info.Size() < f.offset {
+  59         logp.Debug("harvester",
+  60             "File was truncated as offset (%d) > size (%d): %s", f.offset, info.Size(), f.fs.Name())
+  61         return ErrFileTruncate
+  62     }
+  63
+  64     // Check file wasn't read for longer then CloseInactive
+  65     age := time.Since(f.lastTimeRead)
+  66     if age > f.config.CloseInactive {
+  67         return ErrInactive
+  68     }
+  69
+  70     if f.config.CloseRenamed {
+  71         // Check if the file can still be found under the same path
+  72         if !file.IsSameFile(f.fs.Name(), info) {
+  73             return ErrRenamed
+  74         }
+  75     }
+  76
+  77     if f.config.CloseRemoved {
+  78         // Check if the file name exists. See https://github.com/elastic/filebeat/issues/93
+  79         _, statErr := os.Stat(f.fs.Name())
+  80
+  81         // Error means file does not exist.
+  82         if statErr != nil {
+  83             return ErrRemoved
+  84         }
+  85     }
+  86     return nil
+  87 }


func (f *Log) Read(buf []byte) (int, error) {
   92     totalN := 0
   93
   94     for {
   95         select {
   96         case <-f.done:
   97             return 0, ErrClosed
   98         default:
   99         }
  100
  101         // 防止数据过大inode 耗尽
  102         if err := f.checkFileStatus(); err != nil {
  103             return totalN, err
  104         }
  105
  106         n, err := f.fs.Read(buf)
  107         if n > 0 {
  108             f.offset += int64(n)
  109             f.lastTimeRead = time.Now()
  110         }
  111         totalN += n
  112

`

**Comment by ruflin** [comment] 2018-02-06 01:42
@ZhiqinYang The long term fix I have in mind is to change the way the close_* options are checked. Instead of checking them only on each iteration, there is also an external go routine running which checks from time to time if one of the close options is met and closes the handler. Very similar to what we do with `close_timeout` at the moment but would apply to all close options.

**Comment by GaryHuangBD** [comment] 2018-02-08 03:44
@ruflin It's the same as I thought. I add another  temporarily goroutine to check close_* options, and it looks normal now.

**Comment by ruflin** [comment] 2018-02-08 23:05
@GaryHuangBD Would be great if you could share your code. Depending on the change you did, make sure to use Go 1.9 as there was a change in Go 1.9 with the closing file handlers which lead to races before but now should work.

**Comment by GaryHuangBD** [comment] 2018-02-11 03:27
@ruflin Yeah~ i think i can do it after the Spring Festival, if it's still needed.

**Comment by ruflin** [comment] 2018-02-12 05:26
Thanks, would be great.

**Comment by pathcl** [comment] 2018-08-07 11:43
@ruflin Hi ! Im facing the same situation now. Is this fixed by now? so far we have to restart filebeat process in order to release disk usage.

**Comment by kvch** [comment] 2018-08-08 08:37
Right now there is a big refactoring going on in the log input. This part of the code is not yet touched. But any feedback and problems are welcome to make sure as many problems as possible can be resolved.

**Comment by ttapjinda** [comment] 2018-10-19 16:50
Hi, do we still need this feature? I have submitted the pull request here https://github.com/elastic/beats/pull/8627
`check_status_interval` have been added to control the frequency of status checking instead of checking when on read error or end of file.
The default behavior will still be the same since this can cause data loss.

**Comment by d-ulyanov** [comment] 2019-03-01 10:36
Any updates on this issue?

**Comment by jsoriano** [comment] 2019-12-20 10:29
This issue should be fixed with https://github.com/elastic/beats/pull/13907, it is already available in some released versions. Closing this.

**Closed by jsoriano** 2019-12-20 10:29 UTC
Labels: Filebeat, bug
