### ISSUE TITLE
[Fleet]: Host Details are not available under predefined filters in the Search bar of Agents Logs tab.

### ISSUE THREAD

**Issue by simranvaseer-qasource** [elastic/beats#34125] opened 2022-12-26 08:28 UTC
**Kibana version:**  8.6 Snapshot Kibana cloud environment 

**Host OS and Browser version:** All, All 

**Build details:** 

``` 
VERSION: 8.6 Snapshot
BUILD: 58830
COMMIT: 6a5d6d96a534be75fc58acda8f89f2610309d7ff
Artifacts: https://artifacts-api.elastic.co/v1/search/8.6-SNAPSHOT
```

**Preconditions:**
1. 8.6 BC1 Kibana cloud environment should be available.
2. Agent should be installed.

**Steps to reproduce:**
1. Login to Kibana environment.
3. Navigate to Fleet tab.
4. Navigate to Logs tab.
5. Search for agent with predefined filter. say' host.hostname
6. Observe host details are not available under filter.

**Expected Result:**
-  Host Details are not available under predefined filters in the Search bar of Agents Logs tab.

**What is working fine on 8.6:**
Only `host.name` is working fine.
![image](https://user-images.githubusercontent.com/102019374/209525739-c3824e1a-45a9-450b-bb52-4abe9a25f4a7.png)

**What is not working fine on 8.6:**
i.e. host.id
host.mac,
host.hostname

**Screenshots:**
![image](https://user-images.githubusercontent.com/102019374/209524426-dd2bf4d3-dfe0-430c-aa26-24c239555916.png)
![image](https://user-images.githubusercontent.com/102019374/209524653-9308d6e8-18d1-4c45-8e67-442106585c5a.png)

**What is working fine:**
Predefined filters are available under logs tab in 8.5.3
i.e. host.id
host.mac,
host.hostname
host.name
![Untitled](https://user-images.githubusercontent.com/102019374/209524825-04b5823a-3380-4299-9d97-5737bcbea787.png)
![Untitled](https://user-images.githubusercontent.com/102019374/209524940-4e328c0f-01a8-4c8d-9a9f-d048d9941b31.png)

**Comment by michalpristas** [comment] 2022-12-27 13:46
looks like `add_host_metadata` from default config is not taken into account

**Comment by AndersonQ** [comment] 2022-12-29 17:35
Here are my findings:

_output name_ is empty, what makes filebeat not load the pipelines and log:
>Filebeat is unable to load the ingest pipelines for the configured modules because the Elasticsearch output is not configured/enabled. [...]

The culprit seems to be [`BeatConfig`](https://github.com/elastic/beats/blob/d8204a2c9f76c5abecca3af77136cea4901d0ae6/libbeat/beat/beat.go#L90) which uses `output` (singular) instead of `outputs` (plural).

I fixed it. Using a debugger I can see the issue and the fix working, well almost. I does fix the empty output when the configs are loaded on `libbeat/cmd/instance/beat.go` by `func (b *Beat) configure(settings Settings) error`.
However when running under agent, it is, or at least at some point it becomes, empty.

How have I debugged it:
 - collect a diagnostics
 - get fielbeat config: `components/filestream-monitoring/filestream-monitoring-agent/beat-rendered-config`
 - run filebeat with the following parameters:
   - --path.config=/path/to/config/folder
   - -c=beat-rendered-config
   - --path.logs=/some/path
 - use dlv exec

```
 dlv \
--check-go-version=false \
--listen=:4242 \
--headless=true \
--api-version=2 \
--accept-multiclient \
exec /opt/Elastic/Agent/data/elastic-agent-3bff6f/components/filebeat \
-- --path.config=/root/beats/components/filestream-monitoring/filestream-monitoring-agent/ \
-c=beat-rendered-config \
--path.logs=/root/beats/
```
the double `-- --` is correct, the first is for delve know everything after is are parameters for the binary. More on how to debug the agent/beats with delve [here](https://github.com/elastic/ingest-dev/blob/main/elastic-agent/dev-guide/guides/debugging-elastic-agent.md) and [here](https://github.com/elastic/ingest-dev/blob/main/elastic-agent/dev-guide/guides/taming_the_elastic_agent.md#the-gotcha-timeouts)

SO far I can only imagine the issue is the config having hanged and `libbeat` trying to use an old format.

It could be that during the beats initialisation under agent it reads an empty config from disk then the agent send the new one, and I've only fixed when loading from disk. This would explain to work in standalone mode ran through delve.

**Comment by cmacknz** [comment] 2022-12-29 22:26
> looks like add_host_metadata from default config is not taken into account

Yes the Beats don't actually read the default configuration at startup anymore see https://github.com/elastic/beats/issues/31901. They are likely not creating an `add_host_metadata processor` instance anymore, nor any of the other default processors in any of the Beat default configurations.

This will be true for each Beat running under agent. The default processors for each Beat are:

* Filebeat: https://github.com/elastic/beats/blob/d8204a2c9f76c5abecca3af77136cea4901d0ae6/x-pack/filebeat/filebeat.yml#L167-L173
* Metricbeat: https://github.com/elastic/beats/blob/d8204a2c9f76c5abecca3af77136cea4901d0ae6/x-pack/metricbeat/metricbeat.yml#L123-L127
* Osquerybeat: https://github.com/elastic/beats/blob/d8204a2c9f76c5abecca3af77136cea4901d0ae6/x-pack/osquerybeat/osquerybeat.yml#L111-L113
* Auditbeat: https://github.com/elastic/beats/blob/d8204a2c9f76c5abecca3af77136cea4901d0ae6/auditbeat/auditbeat.yml#L151-L155
* Packetbeat: https://github.com/elastic/beats/blob/d8204a2c9f76c5abecca3af77136cea4901d0ae6/packetbeat/packetbeat.yml#L241-L256
* Heartbeat: https://github.com/elastic/beats/blob/d8204a2c9f76c5abecca3af77136cea4901d0ae6/heartbeat/heartbeat.yml#L130-L137

The simplest fix for this for the issue reported in just this bug is to add an instance of the `add_host_metdata` processor to the monitoring filestream configuration. I suspect we would actually want all four of the `_metadata` processors added by default there.

To restore the default processors used for every Beat now that they aren't read from a configuration file, we could add them in code when we generate the Beat configuration from the UnitExpectedConfig received from the agent as a global processor: https://github.com/elastic/beats/blob/acd70e911f97ebe7a2ca4efaaccb6e80497a3747/x-pack/libbeat/management/generate.go#L155

However since this default processor set actually varies per Beat we would probably want to do this on a Beat specific basis. If you search the Beats code for `SetTransform` you will find the place where the Beat specific configuration transformations are added.

For Filebeat it is https://github.com/elastic/beats/blob/d8204a2c9f76c5abecca3af77136cea4901d0ae6/x-pack/filebeat/cmd/root.go#L22 which calls https://github.com/elastic/beats/blob/d8204a2c9f76c5abecca3af77136cea4901d0ae6/x-pack/filebeat/cmd/agent.go#L16-L21

Doing that for every Beat and testing it is not straight forward.

**Closed** 2022-12-30 17:36 UTC
Labels: bug, Team:Fleet, impact:low

**Comment by simranvaseer-qasource** [comment] 2023-01-05 05:54
Hi Team,

We have revalidated this issue on latest 8.6 BC10 kibana cloud environment and found this issue is **fixed** now.

- Host Details are available under predefined filters in the Search bar of Agents Logs tab.

**Build Details:**
```
Version: 8.6.0 BC10
BUILD: 58852
COMMIT: d3a625ef4a6e611a5b3233a1ce5cbe8ef429eb47
Artifacts: https://staging.elastic.co/8.6.0-b6c773f9/summary-8.6.0.html
```

**Screenshots:**
![image](https://user-images.githubusercontent.com/102019374/210707825-16235c56-a27f-4750-9250-0846204bc8be.png)
![image](https://user-images.githubusercontent.com/102019374/210707879-ca125402-916c-441d-b51b-ee88cb1ba581.png)

Hence, marking this issue as QA:Validated
Thanks
