### ISSUE TITLE
[Elastic Agent] Provide more description for running processes

### ISSUE THREAD

**Issue by nimarezainia** [elastic/beats#29220] opened 2021-12-01 11:46 UTC
**Describe the enhancement:**

the Elastic Agent status command returns information about the processes running inside the Agent, as an example:

% sudo elastic-agent status
Status: HEALTHY
Message: (no message)
Applications:
  * filebeat	(HEALTHY)
    Running
  * metricbeat	(HEALTHY)
    Running
  * filebeat	(HEALTHY)
    Running
  * metricbeat	(HEALTHY)
    Running

It's not immediately obvious what each beat here is referring to (one pair are for monitoring).
We w0uld like to enhance this so that there's some description of what the process is responsible.

**Describe a specific use case for the enhancement or feature:**
In case where this status is showing a state other than HEALTHY, we could easily determine which component is having issues and help with the debugging.

**Comment by michel-laterman** [comment] 2021-12-01 19:24
This seems to be a duplicate of https://github.com/elastic/beats/issues/25449
which was merged for 7.16 https://github.com/elastic/beats/pull/27852

**Closed** 2021-12-06 00:29 UTC
Labels: enhancement, Team:Elastic-Agent-Control-Plane, 8.2-candidate
