### ISSUE TITLE
make: *** No rule to make target `create-metricset', needed by `setup' error when creating a beat based on metricbeat

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#8181] opened 2018-08-31 16:38 UTC
According to https://www.elastic.co/guide/en/beats/devguide/current/creating-beat-from-metricbeat.html, one of the steps is to run `make setup`. The `setup` target depends on the `create-metricset` target which doesn't exist and results in this error:

```
make: *** No rule to make target `create-metricset', needed by `setup' 
```

I believe this happens because the `create-metricset` target is [defined in the Metricbeat Makefile](https://github.com/elastic/beats/blob/master/metricbeat/Makefile#L55), which the new beat's Makefile [tries to include](https://github.com/elastic/beats/blob/master/generator/metricbeat/%7Bbeat%7D/Makefile#L12) **before** the Metricbeat Makefile exists. The Metricbeat Makefile only comes into existence via the [`copy-vendor` target](https://github.com/elastic/beats/blob/master/generator/metricbeat/%7Bbeat%7D/Makefile#L20) which is also a dependency of the [`setup` target](https://github.com/elastic/beats/blob/master/generator/metricbeat/%7Bbeat%7D/Makefile#L16).

**Comment by ycombinator** [comment] 2018-08-31 16:38
The workaround is to run `make setup`, let it fail with the error above, then run `make create-metricset`.

**Comment by fearful-symmetry** [comment] 2019-07-10 20:14
Okay, I was legit about to file this for a second time, didn't see someone ran into _a year ago_. Gonna try and see if I can fix this, since I'm already knee-deep in the generator.

@ycombinator we came to the same conclusion about the cause. In the Metricbeat makefile, `create-metricset` is basically a one-line stub that calls python. I don't think it's unreasonable to just tell the custombeat makefile to call that python script directly?

**Comment by ycombinator** [comment] 2019-07-11 12:15
Sure, I wish there was a better way that avoided the repetition but I'm not sure there is. I'm not terribly familiar with the generator but would it be possible for it to copy the one-liner from the Metricbeat makefile into the custombeat makefile? That way, if the Metricbeat one ever changes, (re)generating the custombeat makefile should bring the one-liner in sync.

**Comment by fearful-symmetry** [comment] 2019-07-11 13:01
I actually ran into that a while ago, and re-generating various build tooling is sort of a long-term goal. There's a already a large amount of code copied between metricbeat and the generator that as far as I can tell is individually maintained.

**Comment by ycombinator** [comment] 2019-07-11 13:06
> There's a already a large amount of code copied between metricbeat and the generator that as far as I can tell is individually maintained.

Oh, in that case, I don't see the harm in copying over one more line for now.

**Comment by fearful-symmetry** [comment] 2019-07-14 16:16
Fix was merged. Closing this

**Closed by fearful-symmetry** 2019-07-14 16:16 UTC
Labels: :Generator, :infrastructure, Metricbeat, bug
