### ISSUE TITLE
filebeat registry constantly updated

### ISSUE THREAD

**Issue by immon** [elastic/beats#21174] opened 2020-09-18 14:21 UTC
For confirmed bugs, please report:
- Version: `filebeat version 7.9.1 (amd64), libbeat 7.9.1 [ad823eca4cc74439d1a44351c596c12ab51054f5 built 2020-09-01 19:58:51 +0000 UTC]`
- Operating System:  Ubuntu 18.04

- Steps to Reproduce: 

I was playing with filebeat to understand how new registry format works and noticed the following (incorrect) behaviour:

1. create a lot files in `/tmp/fb/`
```
imo@lake:/tmp/fb$ for i in `seq 1 30000`; do date +%s > "$(date +%s).$i"; done
```

2. In the default config I enabled harvester of `/tmp/fb/*` and added `closed_inactive: 10s` parameter. 

```
- type: log
  enabled: true
  close_inactive: 10s
  paths:
    - /tmp/fb/*
```

3. I wanted to close inactive files quickly because once FB started it ran out of file descriptors (which is expected as I didn't tune my default 1024 ulimit value). Due to file descriptors exhausted I also noticed DNS resolution failures.

```
2020-09-18T16:07:42.386+0200	ERROR	log/input.go:519	Harvester could not be started on new file: /tmp/fb/1600438001.20889, Err: error setting up harvester: Harvester setup failed. Unexpected file opening error: Failed opening /tmp/fb/1600438001.20889: open /tmp/fb/1600438001.20889: too many open files
2020-09-18T16:07:45.172+0200	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(elasticsearch(http://localhost:9200)): Get "http://localhost:9200": lookup localhost: no such host
2020-09-18T16:07:45.172+0200	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(elasticsearch(http://localhost:9200)) with 2 reconnect attempt(s)
2020-09-18T16:07:45.172+0200	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2020-09-18T16:07:45.172+0200	INFO	[publisher]	pipeline/retry.go:223	  done
2020-09-18T16:07:45.172+0200	WARN	[transport]	transport/tcp.go:52	DNS lookup failure "localhost": lookup localhost: no such host
2020-09-18T16:07:51.762+0200	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(elasticsearch(http://localhost:9200)): Get "http://localhost:9200": lookup localhost: no such host
2020-09-18T16:07:51.762+0200	INFO	[publisher_pipeline_output]	pipeline/output.go:145	Attempting to reconnect to backoff(elasticsearch(http://localhost:9200)) with 3 reconnect attempt(s)
2020-09-18T16:07:51.763+0200	INFO	[publisher]	pipeline/retry.go:219	retryer: send unwait signal to consumer
2020-09-18T16:07:51.763+0200	INFO	[publisher]	pipeline/retry.go:223	  done
2020-09-18T16:07:51.763+0200	WARN	[transport]	transport/tcp.go:52	DNS lookup failure "localhost": lookup localhost: no such host
2020-09-18T16:07:53.968+0200	INFO	log/harvester.go:324	File is inactive: /tmp/fb/1600437997.19175. Closing because close_inactive of 10s reached.

```

4. After about 4 minutes after running `./filebeat -e -v` I can see registry files being constantly updated. Using `watch -n1 'ls -lhR data'` I noticed that:
* `log.json` reaches 11MB every 1-2 seconds
* once the 11MB limit is reached new `<id>.json` file is created, and `active.dat` file updated
* every few seconds new id.json file is created. It's easy to see id of millions.
* for a good 10 minutes id.json had 7097 lines and does not grow. md5 sum of id.json is changing. I didn't inspect the content.
* it looks like a loop of  log file constantly filling up(to 10-11MB and snapshot being created
* cpu utilization is high
* one of the monitoring metrics while this is happening

```
2020-09-18T16:17:06.003+0200	INFO	[monitoring]	log/log.go:145	Non-zero metrics in the last 30s	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":38730,"time":{"ms":2197}},"total":{"ticks":204730,"time":{"ms":10975},"value":204730},"user":{"ticks":166000,"time":{"ms":8778}}},"handles":{"limit":{"hard":1048576,"soft":1024},"open":13},"info":{"ephemeral_id":"6a70ef64-e213-4117-8fdd-6f52f737017d","uptime":{"ms":570100}},"memstats":{"gc_next":95958144,"memory_alloc":55012512,"memory_total":24319756528},"runtime":{"goroutines":398}},"filebeat":{"events":{"added":55,"done":55},"harvester":{"closed":55,"open_files":1,"running":372}},"libbeat":{"config":{"module":{"running":0}},"pipeline":{"clients":1,"events":{"active":1,"filtered":55,"total":55}}},"registrar":{"states":{"current":7096,"update":55},"writes":{"success":55,"total":55}},"system":{"load":{"1":2.72,"15":2.59,"5":2.61,"norm":{"1":0.34,"15":0.3238,"5":0.3263}}}}}}
```

Desired behavior: get all 30k files processed

**Comment by immon** [comment] 2020-09-18 14:23
cc @urso

**Comment by urso** [comment] 2020-09-18 14:52
Startup, event publishing and registry updates are currently interleaved, which can lead to very long startup times. If you have many files, the log file will indeed grow much faster, which forces a checkpoint much more often. Before filebeat 7.9.0 the checkpoint did happen after every ACK from the outputs.

Which output has been used? All state updates (even internal ones) need to be ordered with respect to event publishing. This means that the log input can only make progress if the output makes progress. If the output starts to create back-pressure, the input can not pick up any new fiiles. This can heavily prolong startup (picking up files), because startup is subject to backpressure from outputs as well.

Have all files in the registry be read to completion? Have they been closed by filebeat already? Did you hit a file descriptor limit at some point?

> cpu utilization is high

The more files/events to be published, the higher CPU usage. The output encoding events to JSON can generate quite a high load.

> `"pipeline":{"clients":1,"events":{"active":1,"filtered":55,"total":55}}`

Have you configured any filters that would force drop most events? This is not a problem with the registry, but the ACK handling then. By dropping events early, loads of ACKs of size 1 are generated. Normally ACKs are batched when outputs are active, but some signaling messages must be send early to the registry. ACK handling can not differentiate between events and signals and there is currently forced to forward them directly to the registrar. This unfortunately defeats batching can lead to a very high load on the registry. The common workaround for heavy filtering (or registry updates) is to configure the `filebeat.registry.flush` (e.g. set to `5s`). If the flush timeout is configured, all state updates are accumulated in memory only (updates are batched into one single operations and duplicates removed). Batched updates are finally written to the registry backend once the flush timeout kicks in. This can heavily reduce IO and back-pressure on very high rates or on very aggressive event dropping policies.

**Comment by immon** [comment] 2020-09-21 06:54
I was using elasticsearch output. ES was running locally.
I am able to reproduce exactly the same behavior with console output.

The picture is worth thousands words so here is how it looks:

![output](https://user-images.githubusercontent.com/541494/93738164-63488100-fbe5-11ea-9a34-70b2680bc8e2.gif)

To me it is not progressing as it should.



And yes, in the above test I've hit file descriptor limit.
When I change file descriptor limit to 40k all files are correctly processed and registry includes all 30k entries. However registry file is still being constantly updated:

![output_00002](https://user-images.githubusercontent.com/541494/93739082-b15e8400-fbe7-11ea-80e3-87d1350c392b.gif)

**Comment by paul-stevenson** [comment] 2021-05-23 19:43
We were also experiencing this issue after a recent restart of the filebeat service (version 7.10.2).
Pretty much exactly the same symptoms as displayed in https://github.com/elastic/beats/issues/21174#issuecomment-695935887

Downgrading to 7.7.1 resolved the issue for us for now.  We'll likely try filebeat 7.12.x in the near future and see if the issue persists.

**Comment by urso** [comment] 2021-05-27 11:55
Would be interesting to compare with output from an older Beat. But in general given the gifs, it works as expected.

In older Filebeat versions we have this behavior:
- N events are acked by the output
- N acked events are given to the registrar
- registrar updates the local state
- registrar serializes the complete internal state to a tmp file. The tmp file is fsynced before closing it
- the registry file is replaced with the temporary file.

In 7.12 this happens:
- N events are acked by the output
- N acked events are given to the registrar
- registrar updates the local state
- (Unfortunately) the complete state is written to the `log.json` file.
- Once log.json reaches 11MB the registrar creates a snapshot (similar to the older FB versions):
  - registrar serializes the complete internal state to a tmp file. The tmp file is fsynced before closing it
  - the registry file is replaced with the temporary file.
  - truncate log file

The log file is not fsynced. But if the registry is very big, it still requires the state to be written twice unfortunately.

In each setup the registry file will be written over and over again. In newer versions we version the registry files, which allows us to more gracefully recover in case there was an outage when trying to write the new file.

With the console output and a large registry, the system gets under pressure due to the registry writes. There are other scenarios this is the case (e.g. many events being dropped). A mitigation that reduces IO is to use [`filebeat.registry.flush`](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-general-options.html#_registry_flush).

The main problem is that the registrar serializes all state into the log.json, instead of just deltas.
The new [`filestream`](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-filestream.html) (still in beta) will ensure that only deltas for files that we did actually publish events for will be written to logs.json. This reduces the pressure on the registry.

**Comment by paul-stevenson** [comment] 2021-05-27 23:33
Thanks for the reply @urso!
The change in behavior after a restart of the service is what caught us off guard.
As long as this is what was intended (and it doesn't cause disk space usage issues), we'll start using the newer version.

**Comment by jlind23** [comment] 2022-03-31 08:42
Backlog grooming: Closing for now.

**Closed by jlind23** 2022-03-31 08:42 UTC
Labels: Filebeat, Team:Services
