### ISSUE TITLE
Mysql-Module Percona Support

### ISSUE THREAD

**Issue by strowi** [elastic/beats#6665] opened 2018-03-26 17:06 UTC
Hi,

As requested: https://discuss.elastic.co/t/mysql-module-grok-parsing-error/125561

trying to get percona slow-logs into es with the mysql-module. But it seems there is some pattern mismatch? 

- Version: 6.2.3
- Operating System: Ubuntu 16.04.3 LTS

- Steps to Reproduce: 
```
filebeat.prospectors:

filebeat.config.modules:
  # Glob pattern for configuration loading
  path: ${path.config}/modules.d/*.yml

  # Set to true to enable config reloading
  reload.enabled: false

  # Period on which files under path should be checked for changes
  #reload.period: 10s

output.elasticsearch:
  hosts: ["es:30092"]
  index: "percona-%{[beat.version]}-%{+yyyy.MM.dd}"

setup:
  template:
    name: "percona-%{[beat.version]}"
    pattern: "percona-%{[beat.version]}-*"

filebeat.modules:
 - module: mysql
   # Error logs
   error:
     enabled: true
     var.paths: [/var/log/mysql/error.log]
   # Slow logs
   slowlog:
     enabled: true
     var.paths: [/var/log/mysql/mysql-slow.log]
```

error:
```
||Provided Grok expressions do not match field value: [# Time: 2018-03-26T08:03:59.598547Z]|

```

message:
```
@timestamp:
    March 26th 2018, 10:04:06.883
offset:
    6,594
beat.hostname:
    db03
beat.name:
    db03
beat.version:
    6.2.3
prospector.type:
    log
source:
    /var/log/mysql/mysql-slow.log
fileset.module:
    mysql
fileset.name:
    slowlog
fields.env:
    prod2
message:
    # User@Host: root[root] @ localhost [] Id: 37045034 # Schema: Last_errno: 0 Killed: 0 # Query_time: 10.000204 Lock_time: 0.000000 Rows_sent: 1 Rows_examined: 0 Rows_affected: 0 # Bytes_sent: 57 Tmp_tables: 0 Tmp_disk_tables: 0 Tmp_table_sizes: 0 # QC_Hit: No Full_scan: No Full_join: No Tmp_table: No Tmp_table_on_disk: No # Filesort: No Filesort_on_disk: No Merge_passes: 0 # No InnoDB statistics available for this query # Log_slow_rate_type: session Log_slow_rate_limit: 100 SET timestamp=1522051439; select sleep(10);
error.message:
    Provided Grok expressions do not match field value: [# User@Host: root[root] @ localhost [] Id: 37045034\n# Schema: Last_errno: 0 Killed: 0\n# Query_time: 10.000204 Lock_time: 0.000000 Rows_sent: 1 Rows_examined: 0 Rows_affected: 0\n# Bytes_sent: 57 Tmp_tables: 0 Tmp_disk_tables: 0 Tmp_table_sizes: 0\n# QC_Hit: No Full_scan: No Full_join: No Tmp_table: No Tmp_table_on_disk: No\n# Filesort: No Filesort_on_disk: No Merge_passes: 0\n# No InnoDB statistics available for this query\n# Log_slow_rate_type: session Log_slow_rate_limit: 100\nSET timestamp=1522051439;\nselect sleep(10);]
_id:
    Uv9WYWIBCQzjQvHMD8TZ
_type:
    doc
_index:
    percona-6.2.3-2018.03.26
_score:
    - 
```

original log:
```
# Time: 2018-03-26T08:03:59.598547Z
# User@Host: root[root] @ localhost []  Id: 37045034
# Schema:   Last_errno: 0  Killed: 0
# Query_time: 10.000204  Lock_time: 0.000000  Rows_sent: 1  Rows_examined: 0  Rows_affected: 0
# Bytes_sent: 57  Tmp_tables: 0  Tmp_disk_tables: 0  Tmp_table_sizes: 0
# QC_Hit: No  Full_scan: No  Full_join: No  Tmp_table: No  Tmp_table_on_disk: No
# Filesort: No  Filesort_on_disk: No  Merge_passes: 0
# No InnoDB statistics available for this query
# Log_slow_rate_type: session  Log_slow_rate_limit: 100
SET timestamp=1522051439;
select sleep(10);

```
regards,
strowi

**Comment by Fanduzi** [comment] 2018-04-13 02:52
same problem
![image](https://user-images.githubusercontent.com/24428128/38714390-88e43fe0-3f08-11e8-874f-e9b5f7f045e9.png)
percona

Suggest mysql-module compatible official, percona and mariadb versions

**Comment by asrob** [comment] 2018-06-12 14:29
Any updates?

**Comment by strowi** [comment] 2018-09-20 20:40
Sad to say my grok is not fit enough... will have to dig deeper into this.. Or has anyone found a way to at least ignore the problematic lines?

**Comment by dkanchev** [comment] 2018-09-28 11:03
@vadimtk @puneet0191 @delgod Can you guys provide more information about what are the exact differences between the Percona slow logs and the MySQL slow logs. I may have some time to fix the grok filters that beats uses. It will be even better if you already have fixed this for some of your Percona users. Thanks in advance for the info!

**Comment by Fanduzi** [comment] 2018-09-28 11:17
@dkanchev 
MySQL
```
# Time: 2018-08-30T07:02:33.272088Z
# User@Host: someuser[someuser] @  [192.168.x.xx]  Id: 1974416
# Query_time: 0.007656  Lock_time: 0.000378 Rows_sent: 103  Rows_examined: 103
use mysql;
SET timestamp=1535612553;
select * from information_schema.tables where table_schema not in ('mysql','information_schema','sys');
```

Percona
```
# Time: 2018-07-31T11:08:11.985915Z
# User@Host: someuser[someuser] @  [192.168.x.xx]  Id: 1011337
# Schema: mafengwo  Last_errno: 0  Killed: 0
# Query_time: 4.439996  Lock_time: 0.000086  Rows_sent: 15  Rows_examined: 5567804  Rows_affected: 0
# Bytes_sent: 295
SET timestamp=1533035291;
SELECT id FROM xxxxxxx  WHERE ctime < "2018-07-28 19:08:07"  ORDER BY id asc LIMIT 5000;
```

**Comment by strowi** [comment] 2018-09-28 11:43
Percona 5.7.19
```
 zcat /var/log/mysql/mysql-slow.log.7.gz 
/usr/sbin/mysqld, Version: 5.7.19-17-57-log (Percona XtraDB Cluster (GPL), Release rel17, Revision 35cdc81, WSREP version 29.22, wsrep_29.22). started with:
Tcp port: 3306  Unix socket: /var/run/mysqld/mysqld.sock
Time                 Id Command    Argument
# Time: 2018-09-21T09:10:32.614283Z
# User@Host: root[root] @ localhost []  Id: 718391
# Schema:   Last_errno: 0  Killed: 0
# Query_time: 10.000281  Lock_time: 0.000000  Rows_sent: 1  Rows_examined: 0  Rows_affected: 0
# Bytes_sent: 57  Tmp_tables: 0  Tmp_disk_tables: 0  Tmp_table_sizes: 0
# QC_Hit: No  Full_scan: No  Full_join: No  Tmp_table: No  Tmp_table_on_disk: No
# Filesort: No  Filesort_on_disk: No  Merge_passes: 0
# No InnoDB statistics available for this query
# Log_slow_rate_type: session  Log_slow_rate_limit: 100
SET timestamp=1537521032;
select sleep(10);
```

**Comment by HagK** [comment] 2019-01-16 13:45
i can now provide a well tested GROK pattern for some configurations and usage of percona

**Comment by jsoriano** [comment] 2019-01-16 15:11
@HagK wow, thanks! I am finishing a PR to support mariadb (#9731) and I was thinking on trying with Percona later. Your patterns can be really valuable, specially as they also include the innodb metrics :slightly_smiling_face: 

Would you like to open a PR with your patterns and some example files for percona after #9731 gets merged?

**Comment by jsoriano** [comment] 2019-01-16 15:12
@HagK wow, thanks! I am finishing a PR to support mariadb (#9731) and I was thinking on trying with Percona later. Your patterns can be really valuable, specially as they also include the innodb metrics :slightly_smiling_face: 

Would you like to open a PR with your patterns and some example files for percona after #9731 gets merged?

**Comment by HagK** [comment] 2019-01-17 07:41
sure, i can collect some different log configuration examples for percona and create a pull request.

btw, your mariadb pattern doesnt support  https://mariadb.com/kb/en/library/explain-in-the-slow-query-log/
?
and is the line (# Thread_id...)? sometimes optional? i could not reproduce this. The schema in this line could be empty, but the thread-id is always logged for me.

**Comment by jsoriano** [comment] 2019-01-17 11:48
> sure, i can collect some different log configuration examples for percona and create a pull request.
> 
Thanks

> btw, your mariadb pattern doesnt support https://mariadb.com/kb/en/library/explain-in-the-slow-query-log/
> ?

Right, this is not supported yet, we can also add it later, as well as support for the innodb entries. Does your pattern support it?

> and is the line (# Thread_id...)? sometimes optional? i could not reproduce this. The schema in this line could be empty, but the thread-id is always logged for me.

Older mysql versions don't log the thread id, or do it as `Id:...`, all these options are supported.

**Comment by jsoriano** [comment] 2019-01-18 17:57
@HagK #9731 merged, I added at the end a pattern to ignore the "explain" part by now, so logs are still parsed.

**Comment by HagK** [comment] 2019-01-21 11:14
the pull request is commited but conflicts, because a have commited your modification too :(

percona doesnt support the explain lines, so i must not think about a support

**Comment by jsoriano** [comment] 2019-01-21 15:29
> the pull request is commited but conflicts, because a have commited your modification too :(

Oh, thanks for the PR, I'll take a look.
 
> percona doesnt support the explain lines, so i must not think about a support

I left these lines as optional, so the module works in any case. They are still not parsed, if they are included they are just ignored by filebeat.

**Closed** 2019-01-22 16:01 UTC
Labels: :infrastructure, Filebeat, enhancement, module
