### ISSUE TITLE
files created in build/ by docker have root/root ownership

### ISSUE THREAD

**Issue by cyrilleverrier** [elastic/beats#3167] opened 2016-12-10 16:09 UTC
- Version: libbeat on master branch
- Operating System: ALL
- Steps to Reproduce: 

```
cd src/github.com/elastic/beats/libbeat
make testsuite

ll build/
➜  libbeat git:(master) ✗ ll build/     
total 20K
drwxrwxr-x 2 cyrille cyrille 4.0K Dec 10 17:06 coverage
drwxr-xr-x 3 root    root    4.0K Dec 10 17:06 system-tests
-rw-rw-r-- 1 cyrille cyrille   65 Dec 10 17:06 test.env
```

```
cd src/github.com/elastic/beats/winlogbeat
make package

ll build/     
total 48M
drwxrwxr-x 2 cyrille cyrille 4.0K Dec 10 17:02 coverage
drwxr-xr-x 3 root    root    4.0K Dec 10 17:02 homedir
-rwxr-xr-x 1 root    root     11M Dec 10 17:02 import_dashboards-windows-386
-rwxr-xr-x 1 root    root     12M Dec 10 17:02 import_dashboards-windows-amd64
-rw-rw-r-- 1 cyrille cyrille  521 Dec 10 17:02 install-service-winlogbeat.ps1
-rw-rw-r-- 1 cyrille cyrille  279 Dec 10 17:02 package.yml
-rw-rw-r-- 1 cyrille cyrille  188 Dec 10 17:02 uninstall-service-winlogbeat.ps1
drwxrwxr-x 2 cyrille cyrille 4.0K Dec 10 17:03 upload
-rw-r--r-- 1 root    root     23K Dec 10 17:02 winlogbeat-darwin.full.yml
-rw-r--r-- 1 root    root    2.9K Dec 10 17:02 winlogbeat-darwin.yml
-rw-r--r-- 1 root    root     23K Dec 10 17:02 winlogbeat-linux.full.yml
-rw-r--r-- 1 root    root    2.9K Dec 10 17:02 winlogbeat-linux.yml
-rw-r--r-- 1 root    root    5.2K Dec 10 17:02 winlogbeat.template-es2x.json
-rw-r--r-- 1 root    root    4.1K Dec 10 17:02 winlogbeat.template.json
-rwxr-xr-x 1 root    root     12M Dec 10 17:02 winlogbeat-windows-386.exe
-rwxr-xr-x 1 root    root     14M Dec 10 17:02 winlogbeat-windows-amd64.exe
-rw-r--r-- 1 root    root     23K Dec 10 17:02 winlogbeat-win.full.yml
-rw-r--r-- 1 root    root    2.9K Dec 10 17:02 winlogbeat-win.yml
```

**Comment by andrewkroh** [comment] 2016-12-10 16:21
Duplicate of #1475

**Closed** 2016-12-13 20:00 UTC
