### ISSUE TITLE
Heartbeat support for NTLM auth

### ISSUE THREAD

**Issue by brandonmensing** [elastic/beats#5237] opened 2017-09-25 15:13 UTC
NTLM authentication is required in order to poll certain endpoints on Microsoft services/infrastructure when configured with [NTLM](https://en.wikipedia.org/wiki/NT_LAN_Manager).

**Comment by andrewkroh** [comment] 2017-09-25 15:47
This was once requested on Discuss. https://discuss.elastic.co/t/url-check-page-in-subdirectory/75572/6?u=andrewkroh

This is a Go library (MIT license) for NTML (https://github.com/Azure/go-ntlmssp) that someone could try integrating with.

**Comment by gurumaia** [comment] 2018-11-22 10:50
I've come across this issue because I need to test an NTLM-enabled URL and decided to take a look at the code. I've managed to integrate https://github.com/Azure/go-ntlmssp into heartbeat, and I can see via tcp dumps that it is trying to authenticate, but it fails.

My analysis of the issue is that it stems from heartbeat closing the connections for every request it makes. 

In more detail:
The NTLM process is very awkward and requires some back and forth between the server (including getting a couple of 401s and only then trying to authenticate). From what I can gather, this back and forth should occur on the same socket (as is the case when using a simple implementation of go-ntlmssp, which works fine).
But when I analyze the dumps for the heartbeat implementation, it does all of the requests on separate sockets and I can only conclude that this is the cause of the issue.

It seems I should be looking into this section of code: https://github.com/elastic/beats/blob/master/heartbeat/monitors/active/http/simple_transp.go#L129

But I am not sure. And since Go is something new to me (just read my first few lines of Go), this would be a very slow process. So if anyone would like to give some pointers as to how to convince heartbeat to make these requests re-using the same socket, I'm more than happy to keep looking into this and make a PR.

**Closed** 2020-08-07 22:30 UTC
Labels: Heartbeat, Stalled, Team:Uptime, enhancement
