### ISSUE TITLE
Topbeat - Reported process memory capped at 4GB

### ISSUE THREAD

**Issue by jkdenton** [elastic/beats#986] opened 2016-02-18 00:32 UTC
I have topbeat running on a windows server 2008 machine where IIS is running.  The worker processes are using over 4 GB memory however topbeat does not report it accurately; it always reports proc.mem.size = 4,294,967,295.

<img width="1031" alt="discover iis process max memory" src="https://cloud.githubusercontent.com/assets/15988861/13129761/b25cd5c8-d5a4-11e5-94f0-8f3779c37e75.png">
<img width="851" alt="topbeat memory usage per process max size" src="https://cloud.githubusercontent.com/assets/15988861/13129768/b9edb730-d5a4-11e5-946c-0469c4f31529.png">
<img width="702" alt="topbeat memory usage per process" src="https://cloud.githubusercontent.com/assets/15988861/13129775/c60499c6-d5a4-11e5-8062-10af01871fea.png">
<img width="287" alt="server iis process" src="https://cloud.githubusercontent.com/assets/15988861/13129776/cab96118-d5a4-11e5-898f-4e70e7b43d37.png">

**Comment by jkdenton** [comment] 2016-02-18 00:42
I suspect this is due to an assumption that the OS is 32bit and a process can only use 4GB.

**Comment by hc4** [comment] 2016-02-25 13:57
I think the problem is in Sigar Windows module:
https://github.com/elastic/beats/blob/master/vendor/github.com/elastic/gosigar/sigar_windows.go

It uses function GetProcessMemoryInfo(), which returns memory size in fields with type SIZE_T, which is 32-bit for 32-bit executable (and tobeat.exe is 32 bit).

I think there is should be implemented something like for getting file system stats.

**Comment by hc4** [comment] 2016-02-25 17:24
Just compiled 64-bit version of topbeat v1.1.1 and problem solved

**Comment by andrewkroh** [comment] 2016-02-25 23:07
@hc4  Thanks for tracking down the issue. Can you elaborate a bit on "I think there is should be implemented something like for getting file system stats." Did you have a particular method in mind?

**Comment by hc4** [comment] 2016-02-26 10:08
I was wrong.

It seems there is only 2 ways to fix bug:
1) Use performance counters (or maybe WMI)
2) Make 64-bit version of topbeat.

**Comment by hc4** [comment] 2016-02-26 10:43
I found that **[QueryWorkingSet](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684946(v=vs.85).aspx)** function could be used to get process memory.


It also allows to calculate shared memory size (and fill ProcMem.Share member)

Also there is **[QueryWorkingSetEx](https://msdn.microsoft.com/en-us/library/windows/desktop/ms684949(v=vs.85).aspx)**. information from MSDN:

> Unlike the QueryWorkingSet function, which is limited to the working set of the target process, the QueryWorkingSetEx function can be used to query addresses that are not in the process working set but are still part of the process, such as AWE and large pages.

**Comment by hc4** [comment] 2016-02-26 10:45
There is an [example](http://www.codeproject.com/Articles/87529/Calculate-Memory-Working-Set-Private-Programmatica) exists (the code is ugly, but it explains main idea)

**Comment by andrewkroh** [comment] 2016-07-18 13:14
For the 5.x releases there are 32 and 64-bit versions available for Windows on the download page (the Topbeat features are now in Metricbeat).

**Comment by andrewkroh** [comment] 2016-09-02 14:11
Closing. The workaround is to build Topbeat 1.X for 64-bit. The final solution is to upgrade to 5.x which has 64-bit binaries (Topbeat features are now in Metricbeat for 5.X).

**Closed by andrewkroh** 2016-09-02 14:11 UTC
Labels: bug, Topbeat
