### ISSUE TITLE
[Metricbeat][Windows] Could not get Windows Performance Counters since Metricbeats 7.3.0

### ISSUE THREAD

**Issue by StefanSa** [elastic/beats#14684] opened 2019-11-21 13:22 UTC
- Version: 7.4.2
- Operating System: Windows 2016
- Discuss Forum URL: [https://discuss.elastic.co/t/could-not-get-windows-performance-counters-since-metricbeats-7-3-0/198676](url)

i came across the same problem as in the discussion forum.
any solution to solve this problem?

**Comment by narph** [comment] 2019-11-21 15:15
hi @StefanSa , 
Can you provide more information here:
- how does the metricbeat configuration looks like
- do you see any error messages in the logs, if so, can you provide them here
- is metricbeat ran as a service or from cmd (metricbeat -e -d "*")? Do you see the same behavior in both situations?
- in the discuss ticket the user was using the german version of os? Any specific language you are using (we do not expect this to be an issue)

**Comment by StefanSa** [comment] 2019-11-21 15:28
Hi Mariana,

the config:

```- module: windows
  metricsets:
    - perfmon
  period: 10s
  perfmon.ignore_non_existent_counters: true
  perfmon.group_measurements_by_instance: true
  perfmon.counters:
    - instance_label: processor.name
      instance_name: total
      measurement_label: processor.time.total.pct
      query: '\prozessor(_total)\prozessorzeit (%)'

    - instance_label: processor.name
      instance_name: total
      measurement_label: processor.usertime.total.pct
      query: '\prozessor(_total)\benutzerzeit (%)'

    - instance_label: processor.name
      instance_name: total
      measurement_label: processor.dpctime.total.pct
      query: '\prozessor(_total)\dpc-zeit (%)'

    - instance_label: processor.name
      instance_name: total
      measurement_label: processor.interrupttime.total.pct
      query: '\prozessor(_total)\interruptzeit (%)'

    - instance_label: processor.name
      instance_name: total
      measurement_label: processor.ideletime.total.pct
      query: '\prozessor(_total)\leerlaufzeit (%)'

    - instance_label: processor.name
      instance_name: total
      measurement_label: processor.privilegedtime.total.pct
      query: 'prozessor(_total)\privilegierte zeit (%)'
```
the error message:

```2019-11-21T16:20:49.951+0100	WARN	[cfgwarn]	perfmon/perfmon.go:60	BETA: The perfmon metricset is beta
2019-11-21T16:20:50.078+0100	INFO	[monitoring]	elasticsearch/elasticsearch.go:262	Successfully connected to X-Pack Monitoring endpoint.
2019-11-21T16:20:50.078+0100	INFO	[monitoring]	elasticsearch/elasticsearch.go:276	Start monitoring stats metrics snapshot loop with period 10s.
2019-11-21T16:20:50.078+0100	INFO	[monitoring]	elasticsearch/elasticsearch.go:276	Start monitoring state metrics snapshot loop with period 1m0s.
2019-11-21T16:20:50.556+0100	INFO	[monitoring]	log/log.go:153	Total non-zero metrics	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":437,"time":{"ms":437}},"total":{"ticks":702,"time":{"ms":702},"value":702},"user":{"ticks":265,"time":{"ms":265}}},"handles":{"open":870},"info":{"ephemeral_id":"366579b3-b858-44bc-aae2-69d17915e92a","uptime":{"ms":6093}},"memstats":{"gc_next":11325728,"memory_alloc":7274520,"memory_total":14891656,"rss":57913344},"runtime":{"goroutines":49}},"libbeat":{"config":{"module":{"running":0}},"output":{"type":"logstash"},"pipeline":{"clients":0,"events":{"active":0}}},"system":{"cpu":{"cores":4}}}}}
2019-11-21T16:20:50.556+0100	INFO	[monitoring]	log/log.go:154	Uptime: 6.0942652s
2019-11-21T16:20:50.556+0100	INFO	[monitoring]	log/log.go:131	Stopping metrics logging.
2019-11-21T16:20:50.556+0100	INFO	instance/beat.go:432	metricbeat stopped.
2019-11-21T16:20:50.556+0100	INFO	[monitoring]	elasticsearch/elasticsearch.go:284	Stop monitoring state metrics snapshot loop.
2019-11-21T16:20:50.556+0100	INFO	[monitoring]	elasticsearch/elasticsearch.go:284	Stop monitoring stats metrics snapshot loop.
2019-11-21T16:20:50.557+0100	ERROR	instance/beat.go:878	Exiting: 1 error: initialization of reader failed: failed to add counter (query="\prozessor(_total)\prozessorzeit (%)"): Das angegebene Objekt wurde nicht auf dem Computer gefunden.
```
Either as a service or or via command line, same behavior and error message.

OS Version is "german"

**Comment by StefanSa** [comment] 2019-11-22 08:13
Mariana,
Do it OS independent languages, that is much more efficient. The query can always be in english and you get the answer back in the OS language.

```
function Get-LocalPerfCounterName {

   param (
      [Parameter(Mandatory=$true)]
      $Name
    )

   $key009 = 'Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Perflib\009'
   $counters009 = (Get-ItemProperty -Path $key009 -Name Counter).Counter.tolower()
   $Index = $counters009.IndexOf($name.tolower())
   if ($index -eq -1) {
      $null   # not found
   }
   else {
      $keylocal = 'Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Perflib\CurrentLanguage'
      $counterslocal = (Get-ItemProperty -Path $keylocal -Name Counter).Counter
      $counterslocal[$index]
   }
}
```

**Comment by StefanSa** [comment] 2019-11-25 11:57
Mariana, some ETA when this bug is fixed ?
Currently, at least for German OS, metricbeat windows module can not be used.

**Comment by narph** [comment] 2019-11-26 12:29
@StefanSa , I have noticed the following type of exceptions from the discuss ticket:

> : initialization of reader failed: failed **to expand counter** (query="\Process(bbGateService)% Processor Time"): Das angegebene Objekt wurde nicht auf dem Computer gefunden.

> : initialization of reader failed: failed **to add counter** (query="\prozessor(_total)\prozessorzeit (%)"): Das angegebene Objekt wurde nicht auf dem Computer gefunden.

In both cases we assume the actual counter path on the comp is in German.

It looks like the object is not found when trying to expand the counter path is in English but when the counter path is in German, it passes the the expand function but it fails when adding it to the query (looks like it is trying to add it in English).

We were able to reproduce the scenario locally by switching the counter path from EN to NL in this case :
```
 - instance_label:  process.name
   measurement_label: process.time.total.pct
   #query: '\Proces(*)\Percentage processortijd'
   query: '\Process(*)\% Processor Time'
```
We are currently looking for solutions for this process to be independent to the os language.

**Comment by StefanSa** [comment] 2019-12-03 11:11
@narph 
problem still exists in v7.5.
is there a chance that the problem will be solved this year?

**Comment by narph** [comment] 2019-12-03 14:30
@StefanSa , a probable fix is linked to this issue, PR here https://github.com/elastic/beats/pull/14800 and is not yet merged. We hope to have it included in the future releases, meanwhile feel free to test the PR.

**Closed** 2019-12-09 11:15 UTC
Labels: Metricbeat, Team:Integrations, [zube]: In Progress
