### ISSUE TITLE
Multiline pattern determinate harvesting of Filebeat

### ISSUE THREAD

**Issue by knobli** [elastic/beats#1370] opened 2016-04-11 06:25 UTC
Filebeat
Version: 1.2.0
Operating System: RHEL 7.2

I think these configuration make some problems:
```YAML
filebeat:
  # List of prospectors to fetch data.
  prospectors:
    # Each - is a prospector. Below are the prospector specific configurations
    -
      paths:
        - /var/log/faast-auth/*.log
      input_type: log
      # exclude_lines: ["^DBG"]
      # include_lines: ["^ERR", "^WARN"]
      # exclude_files: [".gz$"]
      fields:
        service: auth
        type: java
      fields_under_root: true
      ignore_older: 24h
      #close_older: 1h
      multiline:
        pattern: '(^[a-zA-Z.]+(?:Error|Exception): .+)|(^\s+at .+)|(^\s+...)|(^\s*Caused by:.+)'
        negate: false
        match: after
        max_lines: 1000
      #force_close_files: false
```
Filebeat log:
```
2016-04-08T16:57:36+02:00 INFO Harvester started for file: /var/log/service-log.log
2016-04-08T16:57:36+02:00 ERR Stop Harvesting. Unexpected encoding line reader error: error parsing regexp: missing argument to repetition operator: `?`
2016-04-08T16:57:36+02:00 ERR Stop Harvesting. Unexpected encoding line reader error: error parsing regexp: missing argument to repetition operator: `?`
```

**Comment by ruflin** [comment] 2016-04-11 06:37
@knobli I currently assume this is not a bug but more related to the regexp processing filebeat uses. There are already several threads related to this on discuss: https://discuss.elastic.co/search?q=regexp%20category%3A42 Also here some open issues: https://github.com/elastic/beats/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+regexp

We try to keep github for confirmed bugs. Please either join one of the discussions on Discuss or create a new one to have the discussion there with the content above. Happy to help there.

Closing this one based on the above comment.

**Closed by ruflin** 2016-04-11 06:37 UTC
