### ISSUE TITLE
[Elastic-Agent] Test to make sure persisted install works 

### ISSUE THREAD

**Issue by ph** [elastic/beats#19946] opened 2020-07-15 14:13 UTC
We are depending on the beats packaging system to package the elastic-agent correctly, we need to test and ensure that following is working correctly.

- Windows with a powershell installer script.
- Linux DEB package
- Linux RPM package

We need to ensure that the elastic-agent works with the above artifacts:

- Can run Filebeat
- Can run Metricbeat
- Can install Endpoint and run it.
- Data is correctly saved in the appropriate path.

**Comment by blakerouse** [comment] 2020-07-15 14:23
Testing on Ubuntu 20.04 from DEB results in configuration being read from the wrong location.

```
blake@blake-ubnt-20-vm:~/Downloads$ sudo elastic-agent enroll http://192.168.150.1:5601 ejVQNFRYTUI4d014NkZvT25KMDU6S0IySk5CV3JRcW1od1l3VWVFUlBEUQ
The Elastic Agent is currently in BETA and should not be used in production
could not read configuration file /usr/share/elastic-agent/elastic-agent.yml: open /usr/share/elastic-agent/elastic-agent.yml: no such file or directory
```

Looking at the installed script in path, looks like `path.config` is set correctly. But the binary is not reading that option it seems.

```
blake@blake-ubnt-20-vm:~/Downloads$ cat /usr/bin/elastic-agent
#!/usr/bin/env bash

# Script to run Elastic-Agent in foreground with the same path settings that
# the init script / systemd unit file would do.

exec /usr/share/elastic-agent/bin/elastic-agent \
  --path.home /usr/share/elastic-agent \
  --path.config /etc/elastic-agent \
  --path.data /var/lib/elastic-agent \
  --path.logs /var/log/elastic-agent \
  "$@"
```

The installer does place the config in the correct path.

```
blake@blake-ubnt-20-vm:~/Downloads$ ls -l /etc/elastic-agent/elastic-agent.yml
-rw------- 1 root root 7749 Jul 15 10:06 /etc/elastic-agent/elastic-agent.yml
```

**Comment by blakerouse** [comment] 2020-07-16 15:12
I have confirmed that on Windows the `install-service-elastic-agent.ps1` and `uninstall-service-elastic-agent.ps1` also work.

Closing this bug, because the DEB and RPM's are fixed and Windows works correctly.

**Closed by blakerouse** 2020-07-16 15:12 UTC
Labels: Team:Ingest Management, ingest:beta1

**Comment by EricDavisX** [comment] 2020-07-31 13:03
I have confirmed again this is working from BC5 with Windows x64 and Ubuntu 18 - feeling pretty good about it.  thanks for all the effort

**Comment by georgifundrecs** [comment] 2020-10-15 08:35
Using rpm with 7.9.2 throws an error as the elastic-agent does not have command "test config"

I have removed the test command to enable the service to work.

sed -i 's/$user_wrapper $user_wrapperopts "$agent $args $test_args"/echo 0/' /etc/init.d/elastic-agent
