### ISSUE TITLE
Assign tags during Central Management enrollment

### ISSUE THREAD

**Issue by Gunnerva** [elastic/beats#11146] opened 2019-03-08 01:53 UTC
**Describe the enhancement:**
Beats currently supports Centralized Management with the ability to script enrollment.  It would be nice if during the command line for enrollment (and therefore scripting of enrollment across multiple hosts) you could also provide the tag.  Currently after enrolling the beats you must navigate to Kibana and then enroll your beats manually via Kibana.

Ideas:
Either a new logstash.yml setting like centralmanagement.tag
Additional flag during enrollment where you specify the Central Management Tag.

**Describe a specific use case for the enhancement or feature:**
Speed up the enrollment process when using Beats Central Management.

**Comment by ph** [comment] 2019-03-08 19:42
Duplicate of https://github.com/elastic/beats/issues/9596

**Closed by ph** 2019-03-08 19:42 UTC
Labels: Filebeat, Management, Metricbeat, enhancement
