### ISSUE TITLE
Winlogbeat not showing failed login events (and possibly others) properly

### ISSUE THREAD

**Issue by Deathwing182** [elastic/beats#34896] opened 2023-03-22 14:05 UTC
Hi - was told that opening an issue here may be a good idea after posting at https://discuss.elastic.co/t/winlogbeat-wrong-values/326070

Issue seems to be that with failed login events in particular, from endpoints running Winlogbeat 8.6.2 on Windows 11 Enterprise, data is not being shown properly. For example, instead of seeing the actual event info, data seems to be replaced with placeholders/variable symbols like so:

```
An account failed to log on.

Subject:
	Security ID:		%1
	Account Name:		%2
	Account Domain:		%3
	Logon ID:		%4

Logon Type:			%11

Account For Which Logon Failed:
	Security ID:		%5
	Account Name:		%6
	Account Domain:		%7

Failure Information:
	Failure Reason:		%9
	Status:			%8
	Sub Status:		%10

Process Information:
	Caller Process ID:	%18
	Caller Process Name:	%19

Network Information:
	Workstation Name:	%14
	Source Network Address:	%20
	Source Port:		%21

Detailed Authentication Information:
	Logon Process:		%12
	Authentication Package:	%13
	Transited Services:	%15
	Package Name (NTLM only):	%16
	Key Length:		%17
```
The issue seems to only be affecting data from Windows 11 machines, and if I look at Event Viewer on those machines directly all the data is there as it should be. Windows 10 seems to be completely fine even with the same version of Winlogbeat. Also seems to have only started after upgrading from Winlogbeat 8.6.1 or lower.

**Comment by opoplawski** [comment] 2023-04-19 20:42
Duplicate of #33966 it seems

**Comment by ebeahan** [comment] 2024-01-31 21:04
Closing as duplicate.

**Closed by ebeahan** 2024-01-31 21:04 UTC
Labels: needs_team
