### ISSUE TITLE
Input reload not working as expected under Elastic-Agent

### ISSUE THREAD

**Issue by belimawr** [elastic/beats#33653] opened 2022-11-11 10:24 UTC
- Version: 8.6.0/main (confirmed before the V2 merge https://github.com/elastic/beats/pull/33630)
- Operating System: All (tested on Linux)

# Description

When there is a policy change on Elastic-Agent, it will send the new configuration to Filebeat witch will trigger the input reload code path that stops the necessary inputs and starts the new ones.
https://github.com/elastic/beats/blob/3e928b702b660d5cf31e8f3090c57f2feb541338/libbeat/cfgfile/list.go#L84-L119

The inputs are correctly stopped, the harvesters/reader is also correctly shutdown before new inputs are started which will set the harvester status to 'finalised'. However if there are still events in the publishing pipeline that belong to that input as soon as they're acked the harvester status will be set back to 'not finalised'. If the one of the new inputs will harvest the same file (which is common on a policy update, e.g:  when adding a new integration to the policy, the 'old ones' will have their inputs stopped/started) this will lead to the following error when starting the new input:
```
{"log.level":"info","@timestamp":"2022-11-09T18:55:33.554+0100","log.logger":"centralmgmt.fleet","log.origin":{"file.name":"management/manager.go","file.line":162},"message":"Status change to Failed: 1 error occurred:\n\t* 1 error: Error creating runner from config: Can only start an input when all related states are finished: {Id: native::149908-33, Finished: false, Fileinfo: &{flog.log 7722175 420 {729849109 63803613311 0x55d878467f20} {33 149908 1 33188 1000 1000 0 0 7722175 4096 15088 {1668016405 809851333} {1668016511 729849109} {1668016511 729849109} [0 0 0]}}, Source: /tmp/flog.log, Offset: 7724092, Timestamp: 2022-11-09 18:55:32.698690878 +0100 CET m=+20.865936562, TTL: -1ns, Type: log, Meta: map[], FileStateOS: 149908-33}\n\n","service.name":"filebeat","ecs.version":"1.6.0"}
```

On an ideal world we'd flush the publishing pipeline before trying to start new inputs, that will make all harvesters states consisten.

Another option is for the Elastic-Agent to re-start Filebeat on every policy change.

**Comment by cmacknz** [comment] 2022-11-14 18:43
My suspicion is that just restarting Filebeat will cause more problems. We will stop inputs whose configuration did not actually change.

There is an existing [shutdown.timeout](https://www.elastic.co/guide/en/beats/filebeat/current/configuration-general-options.html#shutdown-timeout) option that we may need to implement on a per input basis.

I feel this would also benefit from implementing per input status reporting back to the agent, so that we could correctly reporting the input that is waiting for shutdown as STOPPING or CONFIGURING while the rest continue to work.

> If the one of the new inputs will harvest the same file (which is common on a policy update, e.g: when adding a new integration to the policy, the 'old ones' will have their inputs stopped/started) this will lead to the following error when starting the new input:

One last thought, can we detect that the input configuration has not changed and leave the inputs alone in this case? This won't fix the problem but it might make it much rarer.

**Comment by cmacknz** [comment] 2022-11-14 19:06
> I'm almost sure Filebeat is already stopping/starting all inputs on a policy change.

Ah you are probably right, we could test just having Filebeat respond to configuration changes by gracefully shutting itself down. We could also modify the spec file to set the `shutdown.timeout` option: https://github.com/elastic/elastic-agent/blob/main/specs/filebeat.spec.yml#L20

**Comment by cmacknz** [comment] 2022-11-14 19:08
The one problem with Filebeat shutting down without some special coordination with agent is that it is likely to be reported as unhealthy while the shutdown happens. Really we should just make live configuration reload work properly.

**Comment by belimawr** [comment] 2022-11-15 14:18
> The one problem with Filebeat shutting down without some special coordination with agent is that it is likely to be reported as unhealthy while the shutdown happens. Really we should just make live configuration reload work properly.

I meant that the Elastic-Agent should re-start Filebeat. I just created the issue here on the Beats repo because the issue is within  the Beats codebase.

**Comment by belimawr** [comment] 2022-11-15 14:27
> Really we should just make live configuration reload work properly.

The current implementation for the config reload on a standalone Filebeat just keeps re-trying until it works, it retries every `filebeat.config.inputs.reload.period`, if this value is too high, there could be some periods without data being harvested.

Things start to get complicated if the output is down or if there is back pressure and the queue/publishing pipeline is not emptying.

We can add a retry logic with some backoff and a timeout. If the timeout occurs Filebeat will be restarted anyways.

**Comment by belimawr** [comment] 2022-12-19 15:17
Waiting for https://github.com/elastic/beats/pull/34066 to be merged before moving on with this task.

**Comment by jlind23** [comment] 2023-01-11 13:57
@belimawr do you have all informations to move on with this?

**Comment by belimawr** [comment] 2023-01-12 07:18
> @belimawr do you have all informations to move on with this?

Yes, I just need to find some time to go back to this task. I still need to verify if it is still happening in the 8.6 release. I should have an update by the end of the week.

**Comment by cmacknz** [comment] 2023-01-16 14:25
> Currently when there is a policy change, the output also changes

This should only apply when the output unit changes, not the input unit. The Beat should not actually be restarting if the only thing that changed was the input unit configuration.

If changing a log or filestream input is causing the Beat to restart, to me that is a separate bug that is unintentionally fixing this one.

@belimawr do you know what in the output is changing here? Is it the API keys perhaps? We ideally shouldn't restart the Beats at all since any events in the memory queue will be lost, if we are observing restarts on any policy change that is something we should fix.

**Comment by belimawr** [comment] 2023-01-16 19:22
I did some testing and the API keys are not changing. The output config seems to be exactly the same.

I agree we should avoid unnecessary re-starts.

Looking at the code there is always a Beat restart on output change:
https://github.com/elastic/beats/blob/65fb69c23ba7a6a34397261d15c6c4a9ba6054c3/x-pack/libbeat/management/managerV2.go#L502-L507

I did a bit of digging on V1 and found some logic to identify if the output had changed:
https://github.com/elastic/elastic-agent/blob/006784462a006cc31fbba70ec43522500c1816bb/internal/pkg/core/plugin/common.go#L23-L50

And the reload on output change is enabled for the Beats: https://github.com/elastic/elastic-agent/blob/fb6c0f1017cfb9b30e8b7ad99b1c0ecee1f00325/specs/filebeat.spec.yml#L33

I'm just not sure (didn't have time to test, but I can test tomorrow) if a change in policy would be enough to trigger this restart.

Maybe what we need to do is to re-introduce this "output change detection logic" and fix the input reload issue as well.

**Comment by cmacknz** [comment] 2023-01-16 19:37
Yeah I think the behaviour you are observing will be fixed as part of https://github.com/elastic/beats/issues/34178, and then this bug will come back.

I am going to reopen this as there is some work in flight to undo the unnecessary restarts here.

**Comment by cmacknz** [comment] 2023-01-16 19:42
We should have a similar level of filtering in the Elastic agent client itself here https://github.com/elastic/elastic-agent-client/blob/4477e3ace394ef1abfec55afa5cc5e1f6f87980c/pkg/client/unit.go#L253-L274 to prevent triggering restarts unnecessarily

I think the logic to try to group/debounce unit changes is calling the reload function even when the unit hasn't changed at all: https://github.com/elastic/beats/blob/65fb69c23ba7a6a34397261d15c6c4a9ba6054c3/x-pack/libbeat/management/managerV2.go#L354-L379

**Comment by cmacknz** [comment] 2023-01-16 19:53
Confirmed by testing locally, any unit change causes the Beat to restart: https://github.com/elastic/beats/issues/34178#issuecomment-1384488628

This is a bug, once that bug is fixed this issue will need to be fixed per the original plan by retrying failed reloads just like a standalone Filebeat instance does.

**Comment by belimawr** [comment] 2023-01-17 15:03
> Confirmed by testing locally, any unit change causes the Beat to restart: [#34178 (comment)](https://github.com/elastic/beats/issues/34178#issuecomment-1384488628)
> 
> This is a bug, once that bug is fixed this issue will need to be fixed per the original plan by retrying failed reloads just like a standalone Filebeat instance does.

That makes sense. We should also align to make sure they're released together otherwise we might bring back the issue of Elastic-Agent going unhealthy on a policy change.

**Comment by jlind23** [comment] 2023-01-18 08:38
Moving this to a later sprint until https://github.com/elastic/beats/issues/34178#issuecomment-1384488628 lands

**Comment by belimawr** [comment] 2023-04-06 16:58
After a bit of testing it seems I got to the current root cause of this issue: The Elastic-Agent sends Unit updates on any order, so it's possible that Filebeat first receives the UnitAdded then UnitRemoved, that effectively tries to start a second input (log input on my tests) on the same file, which will always fails.

All the issues described on https://github.com/elastic/beats/issues/34388#issuecomment-1483408300 are very likely also relevant here.

The first fix should be ensuring first all Units are stopped, then updated and only then new ones can be started.

I'll start working on this next week.

**Closed** 2023-05-31 13:50 UTC
Labels: bug, Team:Elastic-Agent-Data-Plane, 8.8-candidate

**Comment by sheikharsalanelastic** [comment] 2025-01-15 03:51
Team customer is facing this issue Error creating runner from config: Can only start an input when all related states are finished

Upload for Hong Kong Telecommunications Limited - SOC POC - 01812084 is complete.
File name: checkpoint_error_message.png
You can download the file here: https://upload.elastic.co/d/9b996e9e05c2f5c54d4c9e21e4bed7f8e2759d3146828cbf169cae1ae3704baf.
Use this Authorization Token: ac6ac1f3572cdf17
