### ISSUE TITLE
Fleet Agent Logging Behaviour

### ISSUE THREAD

**Issue by louisong** [elastic/beats#28419] opened 2021-10-14 01:25 UTC
Trying to understand the behaviour of fleet/agent logging when osquery manager related index `.ds-logs-osquery_manager.result-default-*` isn't available for some reason (index being closed, etc).

Not sure if this is intended but I found Kibana > Fleet > Agent > [Agent] > Logs showing empty logs for all data sets:

<img width="2220" alt="Screenshot 2021-10-13 at 5 50 14 PM" src="https://user-images.githubusercontent.com/26863726/137233479-a7b34110-c914-4426-af13-91781c8e7007.png">

Observability > Logs > Stream shows empty logging as well:

<img width="2553" alt="Screenshot 2021-10-13 at 6 20 59 PM" src="https://user-images.githubusercontent.com/26863726/137233549-c2726654-32b9-4fbc-9504-22a4ffdaf58f.png">

- Version: 7.15.x
- Operating System: Fleet/Agent running on Elastic Cloud, Osquery endpoint running Windows 2019 Server
- Discuss Forum URL:
- Steps to Reproduce: 
1. On a windows machine, install Elastic Agent (enrolled to Fleet)
2. Apply a policy with Osquery Manager integration.
3. Run a live query with `select * from shimcache;`via [Osquery Manager UI ](https://www.elastic.co/blog/whats-new-elastic-security-7-13-0)
4. The results should now be written to a data stream index `.ds-logs-osquery_manager.result-default-*` , to simulate this index is not available we run a close index api `POST .ds-logs-osquery_manager.result-default-*/_close`.
5. At this point, we should see fleet/agent logging showing empty logging per the above screenshots.
6. To view the actual errors/warnings, you have to access the agent logs on the physical windows endpoint machine to see this warning:
`
{"log.level":"warn","@timestamp":"2021-10-13T09:37:49.564Z","log.logger":"elasticsearch","log.origin":{"file.name":"elasticsearch/client.go","file.line":412},"message":"Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Time{wall:0xc051c81ab3443d14, ext:67385737826301, loc:(*time.Location)(0x4855de0)}, Meta:{\"raw_index\":\"logs-osquery_manager.result-default\"}, Fields:{\"action_data\":{\"id\":\"4b874f4e-b3a5-4b46-a791-f23e4ae95928\",\"query\":\"select * from shimcache\"},\"action_id\":\"ed085b59-b728-48a2-8ac2-dbb38c98484e\",\"agent\":{\"ephemeral_id\":\"bb69bdef-d6d4-4a10-b19d-f3355b2697ca\",\"hostname\":\"louis-osquery-win2019\",\"id\":\"9cab93bc-fbcb-40de-9248-a89b79d6be78\",\"name\":\"louis-osquery-win2019\",\"type\":\"osquerybeat\",\"version\":\"7.15.0\"},\"cloud\":{\"account\":{\"id\":\"elastic-support\"},\"availability_zone\":\"us-central1-a\",\"instance\":{\"id\":\"2865844075666879708\",\"name\":\"louis-osquery-win2019\"},\"machine\":{\"type\":\"e2-standard-4\"},\"project\":{\"id\":\"elastic-support\"},\"provider\":\"gcp\",\"service\":{\"name\":\"GCE\"}},\"ecs\":{\"version\":\"1.11.0\"},\"elastic_agent\":{\"id\":\"9cab93bc-fbcb-40de-9248-a89b79d6be78\",\"snapshot\":false,\"version\":\"7.15.0\"},\"event\":{\"module\":\"osquery_manager\"},\"host\":{\"architecture\":\"x86_64\",\"hostname\":\"louis-osquery-win2019\",\"id\":\"a7a2091f-a2db-46d9-816f-687eb63919a4\",\"ip\":[\"fe80::11d1:dee2:a9ef:ca05\",\"10.128.0.16\"],\"mac\":[\"42:01:0a:80:00:10\"],\"os\":{\"build\":\"17763.2183\",\"family\":\"windows\",\"kernel\":\"10.0.17763.2183 (WinBuild.160101.0800)\",\"name\":\"Windows Server 2019 Datacenter\",\"platform\":\"windows\",\"type\":\"windows\",\"version\":\"10.0\"}},\"osquery\":{\"entry\":160,\"execution_flag\":-1,\"modified_time\":1631659031,\"path\":\"C:\\\\Windows\\\\system32\\\\services.exe\"},\"type\":\"louis-osquery-win2019\"}, Private:interface {}(nil), TimeSeries:false}, Flags:0x0, Cache:publisher.EventCache{m:common.MapStr(nil)}} (status=400): {\"type\":\"index_closed_exception\",\"reason\":\"closed\",\"index_uuid\":\"i2CROM5MSe-BUNhak0luoA\",\"index\":\".ds-logs-osquery_manager.result-default-2021.10.12-000001\"}, dropping event!","service.name":"osquerybeat","ecs.version":"1.6.0"}
`

Thoughts:
- This looks to be hindering troubleshooting via the UI during when things go wrong with indices, Is this an intended behaviour?

**Comment by melissaburpo** [comment] 2021-10-15 15:25
Interesting, thanks for the extra info @dikshachauhan-qasource.

It sounds like the initial issue may be resolved -- the osquerybeat artifact is now published -- but that you're now getting some access errors.

Could you please share some details about the privileges your test user has? In 7.15, we added an RBAC feature for osquery, and one of the [required privileges](https://www.elastic.co/guide/en/kibana/current/osquery.html#_required_privileges_2) is to have `Read` access for the `logs-osquery_manager.result*` index. I suspect that's why you're getting that error.

I do wonder if we need to surface these errors in another way, both for the access issue and for the question @louisong raised initially: "This looks to be hindering troubleshooting via the UI during when things go wrong with indices, Is this an intended behaviour?"

 Thanks for any additional info!

**Comment by dikshachauhan-qasource** [comment] 2021-10-18 09:37
Hi @melissaburpo 

Thanks for providing feedback on above observation.

We tried again and provided superuser rights to our current user and found logs were available this time on discover tab. However, same error too displayed with filtered results.

**Image 1:**
![image](https://user-images.githubusercontent.com/72375798/137704522-66f4c450-9ba1-4ad2-a9da-af02fe35e0f0.png)

**Image 2:**

![image](https://user-images.githubusercontent.com/72375798/137705019-97d0f3b0-98c0-40ae-8cb0-f27043ad3cf0.png)

Also, we have a query for below step:
`The results should now be written to a data stream index .ds-logs-osquery_manager.result-default-* , to simulate this index is not available we run a close index api POST .ds-logs-osquery_manager.result-default-*/_close.`

Could you please make us under stand why we are closing index with this api.

As soon as we close the index, Agent logs are no longer available on UI along with data streams. no data is shown up on Data streams page as well

On further Investigation as logs side on Endpoint, we were unable to observe shared error logs in ticket under agent or OSquery logs.

Logs for reference: 
[logs.zip](https://github.com/elastic/beats/files/7363550/logs.zip)


Please let us know if we are missing anything to validate above feature functionality.

Thanks
QAS

**Comment by jlind23** [comment] 2021-10-19 08:14
@kvch @ruflin any clue about datastreams behaviors?

**Comment by louisong** [comment] 2021-10-22 01:06
Thanks for the clarification @kvch 

>The usage described in "steps" to reproduce, especially closing a backing index of a data stream is invalid. Invalid in the sense that users must not edit/close/delete backing indices of data streams.

Initial thought around this was to test the behaviour of UI (agent logging) when backing datastream becomes unavailable for some reasons (for example, an admin user may be forced to close an index during diaster recovery (eg. restoring snapshot, etc):
<img width="1607" alt="Screenshot 2021-10-22 at 8 40 37 AM" src="https://user-images.githubusercontent.com/26863726/138375738-7642d175-5b67-4f24-954d-f5f58e73b8fa.png">

while users on the other side checking UI (agent logs) may be confused with seeing empty logs => @melissaburpo mentioned a good point that perhaps we should bubble up the error somewhere to the UI to improve the UI experience:
``` 
...
(status=400): {\"type\":\"index_closed_exception\",\"reason\":\"closed\",\"index_uuid\":\"i2CROM5MSe-BUNhak0luoA\",\"index\":\".ds-logs-osquery_manager.result-default-2021.10.12-000001\"}, dropping event!","service.name":"osquerybeat","ecs.version":"1.6.0"}
```

> AFAIK, for troubleshooting data streams, one can check the states of the backing indices using Kibana. Or what else would you like to troubleshoot?

As you mentioned, checking of index states are very well covered. One potential hinderance to troubleshooting being if UI (agent logs) stops showing logging when backing index becomes unavailable, we will have to ask users to access agent logs on the physical machine which they might not have access to immediately. 

No further questions and ++ on adding docs disclaimer.  
Also it would be good for us to improve the UI experience as well 😃

**Comment by nimarezainia** [comment] 2021-11-01 20:52
@kvch & @jlind23 

There needs to be an error/warning banner when a user must tries to edit/close/delete backing indices of data streams. As much as I like enhancing documentation, in most cases the product in itself is the documentation. the question is which team do we  route this request to.

**Comment by jlind23** [comment] 2021-11-02 14:51
@nimarezainia as it's under stack management it will say stack. Maybe @joshdover knows better than I do as he is pretty knowledgeable on interfaces topics.

**Comment by nimarezainia** [comment] 2021-12-15 23:47
@joshdover would you know which team this request can be routed to? thx

**Comment by joshdover** [comment] 2021-12-21 16:47
Yes that is correct, you can open an issue in the Kibana repo for the stack management team here: https://github.com/elastic/kibana/issues/new?labels=Team:Stack%20Management

**Comment by nimarezainia** [comment] 2022-01-21 00:28
opened https://github.com/elastic/kibana/issues/123524

**Closed by nimarezainia** 2022-01-21 00:28 UTC
Labels: Agent, Team:Fleet, Osquerybeat, Team:Elastic-Agent-Data-Plane
