### ISSUE TITLE
[FILEBEAT] - Autodiscover with module when multiple container

### ISSUE THREAD

**Issue by disaster37** [elastic/beats#27284] opened 2021-08-09 15:35 UTC
Hi,

I try to collect some logs on kubernetes cluster form filebeat.
So I use autodiscover to to that. It's work fine for major of use case, but it seems not working on following use case:
I have a workload that run 2 containers on same pod:
- **nginx**:  nginx with custom logs format
- **nginx-error**: sidecard that tail the nginx error.

The custon access logs is handled by Logstash grok. But I should to use Nginx module with fileset error to parse standard Nginx error log.

So I add the following annotations:
```
       co.elastic.logs.nginx/processors.add_fields: '{"target": "", "fields": {"type": "nginx_access", "appServer": "nginx"}}'
        co.elastic.logs.nginx-error/module: 'nginx'
        co.elastic.logs.nginx-error/fileset.stdout: 'error'
```

after that, I look that module `nginx` is use for the 2 container and not only for `nginx-error` container as expected.

For confirmed bugs, please report:
- Version: 7.14.0
- Operating System: Official Docker image
- Discuss Forum URL:
- Steps to Reproduce: 

Create workload that is compose of 2 containers. add annotations to use module on only one container ` co.elastic.logs.CONTAINER_NAME/module: 'nginx'`. Check on output, the module is used for all container.

**Comment by ChrsMark** [comment] 2021-11-24 11:48
@disaster37 since it seems to be working in general on our side I'm going to close this one. Feel free to re-open if issue persists on your end and you have a specific scenario to provide so we can reproduce it.

**Closed by ChrsMark** 2021-11-24 11:48 UTC
Labels: Team:Integrations
