### ISSUE TITLE
crash after 1.3.0 upgrade

### ISSUE THREAD

**Issue by danielmotaleite** [elastic/beats#2526] opened 2016-09-12 15:25 UTC
After upgrade to 1.3.0, 3 of my systems (about 40) fail to start the filebeat.

When i start it, i get this output in systemd journal:

i could not upload the file, so here is a full pastebin:

https://0bin.net/paste/mllg2xjp7LbJZDVH#M9tBEicXPsy794ZvhkbpZZJM5rUVkR6cLOGTemrH6V3

here is the start of the log:

Sep 12 16:52:05 jumA10 filebeat[24558]: fatal error: concurrent map read and map write
Sep 12 16:52:05 jumA10 filebeat[24558]: goroutine 107 [running]:
Sep 12 16:52:05 jumA10 filebeat[24558]: runtime.throw(0x86dbdb, 0x21)
Sep 12 16:52:05 jumA10 filebeat[24558]: /usr/local/go/src/runtime/panic.go:566 +0x95 fp=0xc4207b7878 sp=0xc4207b7858
Sep 12 16:52:05 jumA10 filebeat[24558]: runtime.mapaccess2_faststr(0x7e8480, 0xc42014eab0, 0xc42015aba0, 0x2c, 0x3, 0x8)
Sep 12 16:52:05 jumA10 filebeat[24558]: /usr/local/go/src/runtime/hashmap_fast.go:306 +0x52b fp=0xc4207b78d8 sp=0xc4207b7878
Sep 12 16:52:05 jumA10 filebeat[24558]: github.com/elastic/beats/filebeat/crawler.(*Registrar).getState(0xc420162cc0, 0xc42015aba0, 0x2c, 0x0, 0x0)
Sep 12 16:52:05 jumA10 filebeat[24558]: /go/src/github.com/elastic/beats/filebeat/crawler/registrar.go:231 +0xa0 fp=0xc4207b7920 sp=0xc4207b78d8
Sep 12 16:52:05 jumA10 filebeat[24558]: github.com/elastic/beats/filebeat/crawler.(*Registrar).GetFileState(0xc420162cc0, 0xc42015aba0, 0x2c, 0x20, 0x20)
Sep 12 16:52:05 jumA10 filebeat[24558]: /go/src/github.com/elastic/beats/filebeat/crawler/registrar.go:140 +0x3f fp=0xc4207b7958 sp=0xc4207b7920
Sep 12 16:52:05 jumA10 filebeat[24558]: github.com/elastic/beats/filebeat/crawler.(*Registrar).fetchState(0xc420162cc0, 0xc42015aba0, 0x2c, 0xa410a0, 0xc42048e340, 0x0, 0x1)
Sep 12 16:52:05 jumA10 filebeat[24558]: /go/src/github.com/elastic/beats/filebeat/crawler/registrar.go:170 +0x5a fp=0xc4207b7a38 sp=0xc4207b7958
Sep 12 16:52:05 jumA10 filebeat[24558]: github.com/elastic/beats/filebeat/crawler.(*Prospector).scan(0xc42047f880, 0xc42015aba0, 0x2c, 0xc42005f8c0)
Sep 12 16:52:05 jumA10 filebeat[24558]: /go/src/github.com/elastic/beats/filebeat/crawler/prospector.go:304 +0x7fc fp=0xc4207b7e28 sp=0xc4207b7a38
Sep 12 16:52:05 jumA10 filebeat[24558]: github.com/elastic/beats/filebeat/crawler.(*Prospector).logRun(0xc42047f880, 0xc42005f8c0)
Sep 12 16:52:05 jumA10 filebeat[24558]: /go/src/github.com/elastic/beats/filebeat/crawler/prospector.go:165 +0x162 fp=0xc4207b7f48 sp=0xc4207b7e28
Sep 12 16:52:05 jumA10 filebeat[24558]: github.com/elastic/beats/filebeat/crawler.(*Prospector).Run(0xc42047f880, 0xc42005f8c0)
Sep 12 16:52:05 jumA10 filebeat[24558]: /go/src/github.com/elastic/beats/filebeat/crawler/prospector.go:149 +0x1bc fp=0xc4207b7fa0 sp=0xc4207b7f48
Sep 12 16:52:05 jumA10 filebeat[24558]: runtime.goexit()
Sep 12 16:52:05 jumA10 filebeat[24558]: /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1 fp=0xc4207b7fa8 sp=0xc4207b7fa0
Sep 12 16:52:05 jumA10 filebeat[24558]: created by github.com/elastic/beats/filebeat/crawler.(*Crawler).Start
Sep 12 16:52:05 jumA10 filebeat[24558]: /go/src/github.com/elastic/beats/filebeat/crawler/crawler.go:52 +0x272
Sep 12 16:52:05 jumA10 filebeat[24558]: goroutine 1 [runnable]:
Sep 12 16:52:05 jumA10 filebeat[24558]: github.com/elastic/beats/filebeat/crawler.(*Crawler).Start(0xc4204edd90, 0xc420184000, 0x3b, 0x3b, 0xc42005f8c0)
Sep 12 16:52:05 jumA10 filebeat[24558]: /go/src/github.com/elastic/beats/filebeat/crawler/crawler.go:60 +0x4e5
Sep 12 16:52:05 jumA10 filebeat[24558]: github.com/elastic/beats/filebeat/beat.(*Filebeat).Run(0xc42016a4c0, 0xc420152b90, 0x0, 0x0)
Sep 12 16:52:05 jumA10 filebeat[24558]: /go/src/github.com/elastic/beats/filebeat/beat/filebeat.go:92 +0x33c
Sep 12 16:52:05 jumA10 filebeat[24558]: github.com/elastic/beats/libbeat/beat.(*Beat).Run(0xc420152b90)
Sep 12 16:52:05 jumA10 filebeat[24558]: /go/src/github.com/elastic/beats/libbeat/beat/beat.go:197 +0x196
Sep 12 16:52:05 jumA10 filebeat[24558]: github.com/elastic/beats/libbeat/beat.Run(0x85efa1, 0x8, 0x85b6c3, 0x5, 0xa3fe40, 0xc42016a4c0, 0xc4200001a0)
Sep 12 16:52:05 jumA10 filebeat[24558]: /go/src/github.com/elastic/beats/libbeat/beat/beat.go:107 +0x141
Sep 12 16:52:05 jumA10 filebeat[24558]: main.main()
Sep 12 16:52:05 jumA10 filebeat[24558]: /go/src/github.com/elastic/beats/filebeat/main.go:21 +0x9a
Sep 12 16:52:05 jumA10 filebeat[24558]: goroutine 17 [syscall, locked to thread]:
Sep 12 16:52:05 jumA10 filebeat[24558]: runtime.goexit()
Sep 12 16:52:05 jumA10 filebeat[24558]: /usr/local/go/src/runtime/asm_amd64.s:2086 +0x1
Sep 12 16:52:05 jumA10 filebeat[24558]: goroutine 5 [syscall]:
Sep 12 16:52:05 jumA10 filebeat[24558]: os/signal.signal_recv(0x0)
Sep 12 16:52:05 jumA10 filebeat[24558]: /usr/local/go/src/runtime/sigqueue.go:116 +0x157
Sep 12 16:52:05 jumA10 filebeat[24558]: os/signal.loop()
Sep 12 16:52:05 jumA10 filebeat[24558]: /usr/local/go/src/os/signal/signal_unix.go:22 +0x22
Sep 12 16:52:05 jumA10 filebeat[24558]: created by os/signal.init.1
Sep 12 16:52:05 jumA10 filebeat[24558]: /usr/local/go/src/os/signal/signal_unix.go:28 +0x41
Sep 12 16:52:05 jumA10 filebeat[24558]: goroutine 7 [select, locked to thread]:
Sep 12 16:52:05 jumA10 filebeat[24558]: runtime.gopark(0x899d30, 0x0, 0x85d25c, 0x6, 0x18, 0x2)

The filebeat config is very long, i'm trying to comment out blocks to see if i can find what is causing this, but i'm unable to find it as sometimes it manage to start up.

i'm suspecting this is one error that is applied internally many times and only after certain number of errors, the filebeat fails to start... lower than that, it will log the error, but manage to not crash

**Comment by ruflin** [comment] 2016-09-12 15:31
@danielmitterdorfer Thanks for reporting this one. Based on the message I would assume this it the same panic as here? https://github.com/elastic/beats/pull/2509

**Comment by ruflin** [comment] 2016-09-12 15:44
@danielmotaleite Looking at the fix it seems to be related to a large number of prospectors. As you are talking about a long config file, I assume you can confirm that you have lots of prospectors?

**Comment by danielmotaleite** [comment] 2016-09-12 19:33
@ruflin yes, this machines are the ones that have highest number of prospectors, so yes, this is probably related.

Reverting to the 1.2.x filebeat, all works fine ( i have reverted on those 3 machines for now)

**Comment by tfgm-bud** [comment] 2016-09-12 21:37
Getting the same issue after a 1.2 to 1.3 upgrade.  Happens on startup.  Quite a few prospectors.

Affecting 13 of 50ish servers.  Any eta on 1.3.1?

**Comment by ruflin** [comment] 2016-09-13 06:57
Fix just got merged. Thanks to @amyangfei . No ETA yet on 1.3.1 but this definitively started the discussion on it. Will keep you posted.

I had also a quick look at our 5.0 release and this bug should not affect the 5.0 releease as the setup part and state handling part was completely rewritten.

**Comment by ruflin** [comment] 2016-09-13 10:12
I'm closing this issue as https://github.com/elastic/beats/pull/2509 was merged. That does not mean the release is out yet.

**Closed by ruflin** 2016-09-13 10:12 UTC

**Comment by bmhatfield** [comment] 2016-09-13 20:32
@ruflin There doesn't seem to be much commentary about folks who were also hitting this, so I wanted to chime and say we hit this on hundreds of machines, especially on those that have large numbers of monitored log files. We've rolled back to 1.2. Just more information for you as you decide about how quickly to cut 1.3.1.

**Comment by ruflin** [comment] 2016-09-14 08:50
@danielmitterdorfer @tfgm-bud @bmhatfield We build a pre-release snapshot with the fix here:

* https://download.elastic.co/beats/filebeat/filebeat-1.3.1-SNAPSHOT-darwin.tgz
* https://download.elastic.co/beats/filebeat/filebeat-1.3.1-SNAPSHOT-x86_64.rpm
* https://download.elastic.co/beats/filebeat/filebeat_1.3.1-SNAPSHOT_i386.deb
* https://download.elastic.co/beats/filebeat/filebeat-1.3.1-SNAPSHOT-i686.tar.gz
* https://download.elastic.co/beats/filebeat/filebeat-1.3.1-SNAPSHOT-x86_64.tar.gz
* https://download.elastic.co/beats/filebeat/filebeat-1.3.1-SNAPSHOT-windows.zip
* https://download.elastic.co/beats/filebeat/filebeat_1.3.1-SNAPSHOT_amd64.deb
* https://download.elastic.co/beats/filebeat/filebeat-1.3.1-SNAPSHOT-i686.rpm

It would be great if you could run it on your side to see if it solves the issue.

**Comment by danielmotaleite** [comment] 2016-09-14 14:12
I have testes the filebeat_1.3.1-SNAPSHOT_amd64.deb and it solved the problem for my config.

Thanks for the help

**Comment by tfgm-bud** [comment] 2016-09-14 19:58
I also tested filebeat_1.3.1-SNAPSHOT_amd64.deb and it seems to have solved my issue too...

**Comment by bmhatfield** [comment] 2016-09-14 19:59
We've also rolled it out and confirmed it as fixed.

**Comment by ruflin** [comment] 2016-09-15 06:20
@danielmitterdorfer @tfgm-bud @bmhatfield Thanks a lot for testing and confirming that the fix works. The official 1.3.1 should be rolled out rather soon.
