### ISSUE TITLE
Provide a performance tuning guide for Beats

### ISSUE THREAD

**Issue by ppf2** [elastic/beats#3850] opened 2017-03-30 01:19 UTC
When we moved the unsolved items from https://github.com/elastic/beats/issues/871 to https://github.com/elastic/beats/issues/2482 and then to https://github.com/elastic/beats/issues/3019,  the performance tuning guide didn't get carried over:

>
>Performance Tuning - discuss configuration settings that improve performance, such as increasing throughput, improving memory usage, etc

Given the various options we expose that can affect performance, it will be helpful to provide a performance tuning guide similar to what we have on the Logstash side so end users will know what settings are recommended (eg. spool_size, output pipelining, workers, publish_async, etc..), what are basic tuning sections vs. advanced, etc..

**Comment by dedemorton** [comment] 2017-03-30 17:23
@ppf2 Thanks for opening this item. I removed the performance tuning item from my list intentionally after meeting with Monica a couple months ago. The item was part of my personal "wish list" for documentation, but it didn't represent what was actually in our plans for the near future. I still think it's a worthwhile effort; I just didn't want to cause confusion (but it seems that I have anyhow). :-)

I'll talk to the team about whether we should make this work a higher priority.

**Comment by dedemorton** [comment] 2017-12-08 22:02
Just noticed that this is a duplicate of https://github.com/elastic/beats/issues/2638. I'll close the other issue and keep this one open.

**Comment by dedemorton** [comment] 2021-04-09 02:14
This issue has been open for a very long time. I'm sorry that we have not been able to provide this content. I'm closing this issue for now, but feel free to open an issue in the observability-docs repo against the Elastic Agent docs if you think we should provide this content for Elastic Agent.

**Closed by dedemorton** 2021-04-09 02:14 UTC
Labels: Stalled, docs, enhancement, needs_team
