### ISSUE TITLE
[Metricbeat dashboards] Item url not working on system overview

### ISSUE THREAD

**Issue by toddferg** [elastic/beats#12012] opened 2019-05-01 16:01 UTC
Versions: 6.6.2, 6.7.0, 6.7.1
Version issue **DOES NOT** Occur in: 7.0

When clicking on a host in the system overview it does not apply the filter in the search bar on the next page.  

Reproduced on 6.7.1
![metricbeatbug6 7 1](https://user-images.githubusercontent.com/34006787/57026854-69a91800-6c00-11e9-81d9-173d68beaccf.gif)

Unable to reproduce on:
![metricbeat7nobug](https://user-images.githubusercontent.com/34006787/57026875-72015300-6c00-11e9-9c96-ffac59fd97b7.gif)

I've tried removing all dashboards, and reinstalling them, still having the same issue.

**Comment by ycombinator** [comment] 2019-05-20 17:25
I just tried reproducing this on 6.7.1 (all stack components) and wasn't able to.

**Comment by ycombinator** [comment] 2019-05-20 17:27
I just tried reproducing this on 6.7.0 as well (all stack components) and wasn't able to.

**Comment by ycombinator** [comment] 2019-05-20 17:31
I just tried reproducing this on 6.6.2 as well (all stack components) and **was able to. Looks like this is a bug in 6.6.2 ** but not in 6.7.1 or 6.7.0.

**Comment by andresrc** [comment] 2020-01-17 10:28
Closed as fixed in 6.7.x

**Closed by andresrc** 2020-01-17 10:28 UTC
Labels: :Dashboards, Metricbeat, bug
