### ISSUE TITLE
 [Filebeat]Go Glob paths in system module differ from others

### ISSUE THREAD

**Issue by damianpfister** [elastic/beats#14642] opened 2019-11-20 10:24 UTC
**Describe the enhancement:**
Are we able to provide more consistency in whether we choose the Go Glob parsing method for yml configurations, such as in [system module](https://www.elastic.co/guide/en/beats/filebeat/6.7/filebeat-module-system.html#_syslog_fileset_settings), whilst using a regex pattern for other areas like `exclude_files` in [filebeat.yml](https://github.com/elastic/beats/blob/c8128cb026eecbb0f3833e12ba2729fffd1a8894/filebeat/input/log/input.go#L605)

**Describe a specific use case for the enhancement or feature:**
Although our documentation states we use Go Globbing in some instances, it can lead to confusion when one can have something like `exclude_files: ['.gz$']` in `filebeat.yml` which works yet `exclude_files: ['.gz$']` does not work in the filebeat system module yml config.

**Comment by kvch** [comment] 2019-12-10 08:12
The `paths` setting of the `log` input supports globbing because pattern matching involving paths usually use globbing, for example, shells. The option `exclude_files`/`include_files` are available to provide more fine-grained settings to users on top of globbing.

I have tried reproducing the issue you have mentioned about `exclude_files` not working in `system.yml`. I was not able to reproduce it with the following minimal config:

```yaml
- module: system
  # Syslog
  syslog:
    enabled: true

    input:
      exclude_files: [".gz$"]
```

**Comment by kvch** [comment] 2020-01-30 14:57
I am closing as it cannot be reproduced and we do not want to change the current behaviour right now. Feel free to reopen it.

**Closed** 2020-02-03 14:14 UTC
Labels: Filebeat, Team:Beats, [zube]: Inbox, configuration, discussion, enhancement, v7.4.2
