### ISSUE TITLE
[Winlogbeat] .exe file does not contain version information in Windows

### ISSUE THREAD

**Issue by mellieA** [elastic/beats#4504] opened 2017-06-14 22:12 UTC
Customer requested that we add the version information to the details tab of the .exe file. If the path name is changed it is some work (digging in logs) to find the version. 

He would like to see the version listed in the service description and the .exe details pane. 

![virtualbox_vagrant_win12r2_default_1484250887904_40305_14_06_2017_16_07_28](https://user-images.githubusercontent.com/18175287/27156758-c8a9f52e-511b-11e7-89c6-dd67bd18cc70.png)

**Comment by andrewkroh** [comment] 2020-02-04 00:50
This is a duplicate of the newer #15232. There is a pull request open to add this info to binaries. https://github.com/elastic/beats/pull/16048

**Closed by andrewkroh** 2020-02-04 00:50 UTC
Labels: Winlogbeat, enhancement
