### ISSUE TITLE
Filebeat vs Ansible

### ISSUE THREAD

**Issue by Mykolaichenko** [elastic/beats#2673] opened 2016-10-04 13:26 UTC
Hi guys, i have issue with ad-hoc ansible commands and restarting filebeat service 

Im make this command: 
`ansible -i hosts all -m shell -a 'service filebeat restart' --sudo`
But after it all hosts it filebeat down state

I'm also trying  to make this: 
`ansible -i hosts all -m shell -a 'nohup service filebeat restart &' --sudo`
But its not working too. 

Filebeat stopped, but not started. 
Tnx.

**Comment by tsg** [comment] 2016-10-04 13:32
What OS and filebeat version are you on?

**Comment by Mykolaichenko** [comment] 2016-10-16 11:31
It's server details: 

```
root@cron:/home/mukolaich# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04 LTS
Release:	14.04
Codename:	trusty

root@cron:/home/mukolaich# uname -a
Linux cron 3.13.0-24-generic #46-Ubuntu SMP Thu Apr 10 19:11:08 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

root@cron:/home/mukolaich# filebeat --version
filebeat version 1.1.2 (amd64)
```

**Comment by tsg** [comment] 2016-10-17 14:42
In that case this might be a duplicate of https://github.com/elastic/beats/issues/1394. That was fixed a while back, I'd recommend upgrading to 1.3.1.

**Comment by tsg** [comment] 2016-10-17 14:44
I'm going to close this issue, as we're trying to keep Github only for confirmed bugs and feature request. I'd like to ask you to open issues like this first on https://discuss.elastic.co and we can move it here if it proves to be a confirmed issues. Thanks!

**Closed by tsg** 2016-10-17 14:44 UTC
Labels: needs details, question
