### ISSUE TITLE
[Agent]: No logs under Logs tab when lower version agent is installed with non-default namespace.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#27967] opened 2021-09-16 11:10 UTC
**Kibana version:**  7.14.2 BC-1 Kibana Cloud environment

**Host OS and Browser version:** Windows 10, Linux tar, MAC, All

**Build details:**
```
Build: 42959
Commit: 6b971d6410ca4a99271f2abf9d3de68b7a3653a5
Artifact Link: https://www.elastic.co/downloads/past-releases/elastic-agent-7-13-4
```

**Preconditions:**
1. 7.14.2 BC-1 Kibana Cloud environment should be available.
2. 7.13.4 released Agents must be installed with New policy having non default namespace and System integration.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Agent>Logs tab.
3. Observe no Logs available for Lower version agent installed with non-default namespace. 

**Debug level Logs:**
[logs.zip](https://github.com/elastic/beats/files/7177222/logs.zip)

**Policy:**
[elastic-agent (1).zip](https://github.com/elastic/beats/files/7177224/elastic-agent.1.zip)

**Expected Result:**
Logs under Logs tab should be available when lower version agent is installed with non-default namespace.

**Screenshot:**
![4](https://user-images.githubusercontent.com/77374876/133603190-f0e17f93-dff9-4ea7-b634-b64378eba1e6.JPG)

**Note:**
This issue is **also reproducible** on latest 7.14.1 Snapshot build having below build details:
Build: 42958
Commit: d9f477ca6cd2f5afb25de97728a039021f7ad277

**Comment by amolnater-qasource** [comment] 2021-09-16 11:23
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment] 2021-09-16 11:26
Reviewed & assigned to @blakerouse

**Comment by blakerouse** [comment] 2021-09-16 11:39
Do logs show when in default namespace? 

Do the matching datastream for the namespace exist? It should be auto-created on first event. Trying to see if the issue is with Elastic Agent sending them or if its an issue with Kibana showing them.

**Comment by amolnater-qasource** [comment] 2021-09-16 11:58
Hi @blakerouse 
Yes logs shows up on default namespace with lower version agent.

>Do the matching datastream for the namespace exist? It should be auto-created on first event.

Further yes Data Stream for system are available for lower version agent. However no `elastic_agent.elastic_agent` dataset for this namespace is available for lower version agent.
Seems like System integration data generated at regular intervals of time for this agent.

**Screenshots:**
![5](https://user-images.githubusercontent.com/77374876/133607279-f62fae52-8a3e-48da-98db-83aee593ad3a.JPG)
![6](https://user-images.githubusercontent.com/77374876/133607285-b9412bde-5cba-4466-a103-f4670ce37787.JPG)

For the same version(7.14.2) agent  `elastic_agent.elastic_agent` dataset was available with non default namespace.

Please let us know if anything else is required from our end.
Thanks

**Comment by blakerouse** [comment] 2021-09-16 12:42
@amolnater-qasource Thank you for the detail! Seems that this is an issue that needs to be looked at.

@michel-laterman Could you take a look at this?

**Comment by michel-laterman** [comment] 2021-09-22 01:19
This seems to only effect the `7.13.4` release of the elastic-agent. We are not going to fix it for that version.
I have not been able to recreate it for `7.14.2` and will try again with `7.15.0` tomorrow.

**Comment by michel-laterman** [comment] 2021-09-22 21:08
does not effect `7.15.0`

**Closed by michel-laterman** 2021-09-22 21:08 UTC
Labels: bug, impact:high, Team:Agent

**Comment by amolnater-qasource** [comment] 2021-09-23 09:27
Thanks for the feedback @michel-laterman 
We will also keep a track of this in our 7.15.x and 7.16.0 testing.

**Comment by dikshachauhan-qasource** [comment] 2021-09-27 10:07
### Bug conversion

Hi @EricDavisX 

We have created 01 testcase for above reported issue under bug conversion task. Testcase link is:

- [C150166](https://elastic.testrail.io/index.php?/cases/view/150166)

Thanks
QAS
