### ISSUE TITLE
Filebeat with AWS, Azure and Google

### ISSUE THREAD

**Issue by Nimdy** [elastic/beats#12493] opened 2019-06-11 07:27 UTC
I've tested filebeat on AWS, Azure and Google for piping Suricata logs to ELK from network shares.  I still receive "File was truncated. Begin reading file from offset 0".  

Each setup has Suricata jsons are rotating every 6 hours and the filebeat.yml is the following:

```
filebeat:

prospectors:

    - type: log
      paths:
       - /mnt/log/*.json

output:
  logstash:
    hosts:
    - 10.1.0.6:5044
```

What can I do to prevent the truncation errors?  It is painful to see 5-10 duplicated entries and missing possible data logging. 

Maybe different filebeat configurations to help? 

Thank you in advance.

**Comment by jasonish** [comment] 2019-06-26 22:08
@Nimdy How do you have Suricata setup to rotate the eve json files?

**Comment by Nimdy** [comment] 2019-06-27 06:43
I have Suricata rotating logs every 12 hours.  I have tested with 1,2,4,6,8,10 hour settings as well. 

Default configuration setup with only the full PCAP and JSON logging enabled.  Both dump to Azure File Storage areas.

The reason I have logs rotating with this file frame is because I have 16 nodes all running Suricata and dumping to the file storage area.  Each node has its own file naming structure whatever-node-suricata-<timestamp format>.json

Everything works.... and has been working for 6+ months but the truncation errors have never gone away.  I am just at the end of my rope on why. 

Thank you for taking time out of your day to help.

**Comment by Nimdy** [comment] 2019-06-27 06:46
All other settings are default

`- eve-log:
      enabled: yes
      filetype: regular #regular|syslog|unix_dgram|unix_stream|redis
      filename: somecoolfilenamefornod-eve-%Y-%m-%d-%H.json
      rotate-interval: 12h
      #prefix: "@cee: " # prefix to prepend to each log entry
      # the following are valid when type: syslog above
      #identity: "suricata"
      #facility: local5
      #level: Info ## possible levels: Emergency, Alert, Critical,
                   ## Error, Warning, Notice, Info, Debug
      #redis:
`

**Comment by jasonish** [comment] 2019-06-28 04:22
I'm curious if there is any other process that could be truncated files. With this Suricata configuration, it will be closing the current log file and opening a new one, with a different name every 12 hours.  Suricata itself would not be truncating the files itself.

What happens with the old files? Are they deleted? Moved away? I wonder if its some side affect of them being on a network drive.  Sorry, I won't be of much help there, I was mainly taking a look at this from the Suricata side of things.

**Comment by Nimdy** [comment] 2019-06-28 08:17
Jasonish,

No problem. 

The old files are archived every two days.  I believe Suricata is working as expected.  I am not a expert at filebeat so I do not know if filebeat hates json files that are currently being wrote to. 

That's why I was wondering if Filebeat could have some way to buffer its workers to read json files that are current active with writing data.  

I normally have no issues when tapping network equipment but this cloud stuff is starting to bug the living heck out of me.  There is pretty much no documentation of people having these types have issues and how to work around them. 

I suppose this is just the hard part of paving new roads. 

Maybe a Filebeat Jedi can help?

**Comment by andrewkroh** [comment] 2020-02-11 23:39
Filebeat doesn't always work well with network shares due to the file identifiers possibly changing. The problem you are experiencing could very well be caused by the network share. Even if Suricata is properly rotating the log file (rather than truncating), but the file identifier exposed over the network share stays the same then to FIlebeat it would appear to be truncated.

https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-network-volumes.html

**Closed by andrewkroh** 2020-02-11 23:39 UTC
Labels: Filebeat
