### ISSUE TITLE
Unable to view data in discover tab for heartbeat

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#26366] opened 2021-06-18 11:03 UTC
Link followed: https://www.elastic.co/guide/en/beats/libbeat/current/beats-reference.html

Artifact links used: https://artifacts.elastic.co/downloads/beats/heartbeat/heartbeat-7.13.2-linux-x86_64.tar.gz

- Followed steps in guide and made required changes as mentioned.
- Download the heartbeat and extracted the artifacts.

Then ran below commands:
```
 ./heartbeat setup
sudo chown root heartbeat.yml 
sudo ./heartbeat -e
```

Yml file: [heartbeat_yml.txt](https://github.com/elastic/beats/files/6676553/heartbeat_yml.txt)
logs file: [Heart-beat-logs-at-console.txt](https://github.com/elastic/beats/files/6676555/Heart-beat-logs-at-console.txt)

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/122551516-b5bead00-d052-11eb-9b91-f8c05b6508d6.png)

**Comment by dikshachauhan-qasource** [comment] 2021-06-18 11:04
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment] 2021-06-18 12:43
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment] 2021-06-24 19:13
@urso @andresrc can you help triage / follow up if this can be real?  @dikshachauhan-qasource I know we have run into issues with Beats testing in the past, did we review all the notes / lessons learned prior while testing this? 

Also, the 'Fleet' team is the Kibana UI side folks, I'll push it to 'Agent' team.

**Comment by dikshachauhan-qasource** [comment] 2021-06-28 08:45
Hi @EricDavisX 

Keeping in all learnings from past and on following steps mentioned in guide, we have attempted to install beats. 

It could be great if agent team can follow up and let us know if still we are missing anything.

Thanks
QAS

**Comment by andrewvc** [comment] 2021-07-30 12:26
Heartbeat doesn't ship an index pattern (nor dashboards) so this is expected behavior and has been for quite some time. The main reason is that users overwhelmingly use the Uptime UI

Going forward with fleet the behavior will change due to the use of data streams.

I'm closing this issue for now since it's not a bug, but if anyone feels adding the index pattern would be a worthwhile enhancement please do so.

**Closed by andrewvc** 2021-07-30 12:26 UTC
Labels: Team:Agent, bug, impact:high

**Comment by EricDavisX** [comment] 2021-07-30 12:49
@dikshachauhan-qasource can you go through the Heartbeat docs and see where anything may have been confusing or misleading to your expectations?  You can also try the Uptime UI as noted to complete the evaluation further.  Either way, please update the test notes with changes and new expectations. thank you!

**Comment by vipulsrivastava-qasource** [comment] 2021-08-19 10:36
Hi @EricDavisX

We have performed installation for heartbeat on 7.14.0 released build and we are successfully able to view data under Uptime tab for heartbeat.

Please find the below the detailed steps to configure heartbeat on Linux rpm machine.

1. Download the heartbeat and extract the artifacts.
2. Set the connection information in heartbeat.yml to connect to the Elastic stack.
3. Make changes for heartbeat in heartbeat.yml (location of heartbeat.yml is /etc/heartbeat)
![ahgljiajhcmkdfmb](https://user-images.githubusercontent.com/69579402/130049566-609af965-756e-498c-b89e-9963a519eb83.png)
4. Go to location cd /etc/heartbeat/monitors.d
5. Create a yml file in this folder let say (sudo vi sshddemo.yml) and provide below data to configure tcp monitor and then save it.
```
- type: tcp
  name: sshddemo
  enabled: true
  schedule: "@every 5s"
  hosts: ["localhost"]
  ports: [22]
```
6. To check if sshd is running or not (run command : "systemctl status sshd" ) if not running, run the command : "systemctl start sshd" )
7. Run the setup and service command i.e
```
sudo heartbeat setup
sudo service heartbeat-elastic start
```
8.  Go to Uptime tab under kibana.
9. Observe that tcp monitor is displayed under Monitor Section.
![heartbeat-installation](https://user-images.githubusercontent.com/69579402/130050455-64d207f7-6711-4842-9fb8-3f75387a4c13.png)
Please let us know if we are missing anything
Thanks!!
