### ISSUE TITLE
[Metricbeat] Kibana module does not seem to follow 302s and instead errors

### ISSUE THREAD

**Issue by cachedout** [elastic/beats#13809] opened 2019-09-26 08:53 UTC
When using the Kibana module with Metricbeat, if one does not specify a `basepath` in the configuration, Metricbeat will immediately exit after start with an error that is difficult to understand:

```
2019-09-26T10:45:41.652+0200    INFO    [monitoring]    log/log.go:131  Stopping metrics logging.
2019-09-26T10:45:41.652+0200    INFO    instance/beat.go:440    metricbeat stopped.
2019-09-26T10:45:41.652+0200    ERROR   instance/beat.go:886    Exiting: 1 error: invalid character '<' looking for beginning of value
Exiting: 1 error: invalid character '<' looking for beginning of value
```

The above is displayed when attempting to use Metricbeat with the `kibana-xpack.yml` file with values as follows:

```
10:49 $ cat modules.d/kibana-xpack.yml
# Module: kibana
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-kibana.html

- module: kibana
  metricsets:
    - stats
  period: 10s
  hosts: ["localhost:5601"]
  #  basepath: "/lhq"   # <--Note that this is commented out
  username: "elastic"
  password: "changeme"
  xpack.enabled: true
```

If one sets `basepath`, this error does not occur and Metricbeat starts normally.
```
10:49 $ cat modules.d/kibana-xpack.yml
# Module: kibana
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-kibana.html

- module: kibana
  metricsets:
    - stats
  period: 10s
  hosts: ["localhost:5601"]
  basepath: "/lhq"   # <--Note that this is no longer commented out
  username: "elastic"
  password: "changeme"
  xpack.enabled: true
```

An HTTP request to Kibana set shows that it is returning a 302 redirect when a request is sent to /:

```
10:28 $ http --auth elastic:changeme http://localhost:5601/
HTTP/1.1 302 Found
Connection: keep-alive
Date: Thu, 26 Sep 2019 08:44:57 GMT
cache-control: no-cache
content-length: 0
content-type: text/html; charset=utf-8
location: /lhq  # <--Note the location field in the response
vary: origin
```
I think that we should do one or the other, with the first option being preferable:

1) If a basepath is not set in the configuration, examine the result of the 302 for the `location` field and use it as the value for `basepath` and continue on without an error.

2) If a `basepath` is not set and we don't want to follow the 302, let's at least return an error that informs the user that we cannot start without an explicit path set in the configuration.

**Comment by cachedout** [comment] 2019-09-26 08:54
@ycombinator I thought you might be interested in this so I set you to the owner. Feel free to re/un-assign or do whatever you think is best.

**Comment by ycombinator** [comment] 2019-10-01 00:37
I agree that option 1 is what we should try to do. I will look into it. Thanks!

**Comment by ycombinator** [comment] 2019-10-02 18:54
I investigated this issue. This is not a problem with following redirect. The HTTP client being used by Metricbeat follows redirects (up to 10 times) by default and Metricbeat isn't changing this default behavior via configuration.

The issue is that Kibana is responding with the incorrect value in the Location header. This can be seen via the following curl transaction:

```
» curl -v 'http://localhost:5680/api/status'                                                                                                                                         7 ↵
*   Trying ::1...
* TCP_NODELAY set
* Connection failed
* connect to ::1 port 5680 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 5680 (#0)
> GET /api/status HTTP/1.1
> Host: localhost:5680
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 302 Found
< location: /kwm/status
< content-type: text/html; charset=utf-8
< vary: origin
< cache-control: no-cache
< content-length: 0
< Date: Wed, 02 Oct 2019 18:51:20 GMT
< Connection: keep-alive
<
* Connection #0 to host localhost left intact
```

Notice that the original request is made to `/api/status` but the `location` header in the response has `/kwm/status`. Metricbeat is following this redirect correctly but the content at `/kwm/status` is HTML, not JSON.

I would have expected Kibana to return the `location` header's value as `/kwm/api/status`.

So this seems to be a Kibana bug to me. Do you agree, @cachedout?

**Comment by cachedout** [comment] 2019-10-03 08:36
@ycombinator Good catch! I can confirm what you are seeing and I agree that this is the true source of this bug. I will go ahead and file this in the Kibana repo. Thanks for the investigation!

**Comment by ycombinator** [comment] 2019-10-03 13:32
Closing since this isn't a Beats bug and the Kibana bug issue has now been opened.

**Closed by ycombinator** 2019-10-03 13:32 UTC
Labels: Metricbeat, Stack monitoring, bug
