### ISSUE TITLE
[Elastic Agent] Error in "elastic-agent version" output before installation

### ISSUE THREAD

**Issue by ruflin** [elastic/beats#25300] opened 2021-04-26 06:50 UTC
After downloading the Elastic Agent, I wanted to check for the exact version / build it is. For this I run `./elastic-agent version`. It gives me the information I need in the first line `Binary` but then outputs a communication error. This is probably happening because the Elastic Agent is not running yet.

```
./elastic-agent version
Binary: 7.13.0-SNAPSHOT (build: a5c2d34faec243be58fa4127e1fda343493dbe93 at 2021-04-26 04:09:55 +0000 UTC)
Daemon: <failed to communicate>
failed to communicate with running daemon: rpc error: code = Unavailable desc = connection error: desc = "transport: Error while dialing dial unix /tmp/elastic-agent/a5a5161fc06d8c165718431124704c323a1cce647465976960a74b94b6674842.sock: connect: no such file or directory"
```

**Comment by blakerouse** [comment] 2021-04-27 11:48
Yes this is expected behavior. You can run with `--binary-only` if you don't want it to try and get the version from the running Elastic Agent daemon.

**Comment by ruflin** [comment] 2021-04-28 12:11
I opened a quick PR here to give the user a hint on how to fix it: https://github.com/elastic/beats/pull/25380

**Comment by ph** [comment] 2021-04-30 20:01
I've closed it because of the `--binary-only` reason and the #25380

**Closed** 2021-04-30 20:00 UTC
Labels: Team:Agent, bug
