### ISSUE TITLE
Document HTTP headers setting

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#7738] opened 2018-07-25 17:12 UTC
For metricbeat modules/metricsets that use HTTP hosts, it is actually possible to specify request `headers` in the module configuration. See: https://github.com/elastic/beats/blob/2b1f1e69b018a52dd8d9fddc66dcfaeed2c7cbdb/metricbeat/helper/http.go#L51

However, this setting is currently [not documented](https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-metricbeat.html#module-http-config-options) so we should document it.

**Comment by dedemorton** [comment] 2018-07-25 18:15
There's another issue open that I think is a duplicate of this one: https://github.com/elastic/beats/issues/3948 (it's really old...agreed that we should get this resolved soon). Can we close this in favor of the other issue? I think the other one isn't resolved because I was looking for more input from dev. Might help if you could add more detail to the original issue along with an example config.

**Comment by ruflin** [comment] 2018-07-26 06:54
++ on starting with headers. Better something then nothing.

**Closed** 2018-07-26 22:41 UTC
Labels: Metricbeat, adoptme, docs, good first issue
