### ISSUE TITLE
File permissions in .deb package

### ISSUE THREAD

**Issue by kristian-kocher** [elastic/beats#8605] opened 2018-10-11 16:24 UTC
When installing beats from the .deb packages on a system that uses systemd the daemons start but due to wrong file system permissions there is unintended log noise.

Filebeat package issue: 
`systemd[1]: Configuration file /lib/systemd/system/filebeat.service is marked executable. Please remove executable permission bits. Proceeding anyway.`
Auditbeat package issue: 
`systemd[1]: Configuration file /lib/systemd/system/auditbeat.service is marked executable. Please remove executable permission bits. Proceeding anyway.`
I assume this will hold for all other beats but this has not been tested.

Beats version: tested on 6.4.0
Linux version: tested on Debian stretch (latest security patches applied)
steps to reproduce:
 - install filebeat using Elastic provided .deb package
 - run systemctl daemon-reload
 - check system logs

proposed fix: remove executable permission bits from unit files

**Comment by andrewkroh** [comment] 2018-10-12 23:19
This is a duplicate of #7873 so I'm going to close it. If you upgrade to a newer version the issue should be fixed.

**Closed by andrewkroh** 2018-10-12 23:19 UTC
Labels: Packaging
