### ISSUE TITLE
Filebeat has huge memory usage

### ISSUE THREAD

**Issue by aparkhomenko** [elastic/beats#4555] opened 2017-06-25 22:07 UTC
Hi all.

I use Filebeat 5.3.1 and CentOS 6.9. I have some services that produce a lot logs (~50GB per day) and as I saw for huge log files Filebeat used a lot memory. For example in one instance for process one file it used 10-12 gb. I tried to understand where is the problem and do some debug:

- 2148.14MB 51.30% 51.30%  2148.14MB 51.30%  github.com/elastic/beats/libbeat/common/streambuf.(*Buffer).doAppend
- 1326.37MB 31.68% 82.98%  1326.37MB 31.68%  bytes.makeSlice
- 348.75MB  8.33% 91.31%  2843.76MB 67.92%  github.com/elastic/beats/filebeat/harvester.(*Harvester).Harvest
- 346.86MB  8.28% 99.59%  2495.01MB 59.59%  github.com/elastic/beats/filebeat/harvester/reader.(*Line).advance
         0     0% 99.59%   284.52MB  6.80%  bytes.(*Buffer).WriteByte

~346MB it was size of my example log file. As I understood from source code Filebeat do a lot copies of my data and keep it to internal buffers but the memory increase up more than x6

I tried to use more fresh version and this case still alive.

Could you please help me to understand what I'm doing wrong or maybe it's a bug? )

PS: I don't use async options.

**Comment by Amar-Chaudhari** [comment] 2017-07-12 00:03
@aparkhomenko 
Could you post your config file ?
I have tested Filebeats with ~7000 logs/sec including filtering and multi-line matching and never the MEM > 100 MB

**Comment by aparkhomenko** [comment] 2017-07-18 10:37
Hi @Amar-Chaudhari 

Nothing special in my config file:

filebeat.prospectors:
- input_type: log
  paths:
  - "/var/log/test.log"
filebeat.registry_file: /var/lib/filebeat/registry
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  rotateeverybytes: 10485760 # = 10MB
  keepfiles: 3

But each line in log file has big size, for example one line in that file can be near 2MB
So, unfortunately, for ~346MB file I have:

wc -l /var/log/test.log
182 /var/log/test.log

**Comment by myoung34** [comment] 2017-11-30 21:03
Any updates? Im seeing this on boxes that dont do much (NAT) that can grow up to almost 1GB memory on 5.6.2

```
filebeat.prospectors:
- type: log
  enabled: true
  paths:
    - /var/log/messages
    - /var/log/secure
    - /var/log/cron
    - /var/log/dmesg
    - /var/log/audit/audit.log
  fields.class: "syslog"
- type: log
  enabled: true
  paths:
    - /opt/threatstack/cloudsight/logs/*.log
  exclude_files: ['tsaudit.log$']
  fields.class: "threatstack"
- type: log
  enabled: true
  paths:
    - /var/log/amazon/ssm/*.log
    - /var/log/xray/*.log
    - /var/log/boot.log
    - /var/log/cfn*.log
    - /var/log/cloud-init*.log
  fields.class: "aws"
- type: log
  enabled: true
  paths:
    - /var/log/filebeat/filebeat
  fields.class: "filebeat"
- type: log
  enabled: true
  paths:
    - /var/log/metricbeat/metricbeat
  fields.class: "metricbeat"
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.codec: best_compression
  _source.enabled: false
tags: ["nat"]
fields:
  env: "operations"
  ec2.tags.environment: "${ENVIRONMENT}"
  ec2.tags.managed_by: "${MANAGED_BY}"
  ec2.tags.name: "${NAME}"
processors:
- add_cloud_metadata:
output.elasticsearch:
  hosts: ["${ELASTICSEARCH_HOST:localhost}:${ELASTICSEARCH_PORT:9200}"]
  protocol: "https"
  username: "${ELASTICSEARCH_USER:elastic}"
  password: "${ELASTICSEARCH_PASSWORD:changeme}"
  index: "%{[fields.class]}-%{+yyyy.MM.dd}"
```

**Comment by ruflin** [comment] 2017-12-03 10:00
Please have a look at the following FAQ about Golang: https://golang.org/doc/faq#Why_does_my_Go_process_use_so_much_virtual_memory 

Could you figure out if the value you are reporting is virtual memory or actual memory? Could you also share some logs?

**Comment by bramford** [comment] 2018-02-21 20:16
We're also seeing very large amounts of memory usage (~1G) after running for a few days:
```
root@myhost# top -n 1 | grep filebeat
25053 root      20   0 1764956 860556      0 S   0.0 22.6  70:38.00 filebeat
```

We are using the _experimental_ docker autodiscover which I assume could be the cause:
```
filebeat.autodiscover:
  providers:
  - templates:
    - condition:
        regexp: {docker.container.image: .*}
      config:
      - container.ids: ['${data.docker.container.id}']
        type: docker
    type: docker

processors:
- add_docker_metadata:
    host: unix:///var/run/docker.sock
    match_fields: [system.process.cgroup.id]

filebeat:
  prospectors: [{"type": "docker", "containers.ids": ["*"]}]

output:
  logstash:
    hosts: ["logstash.host:5044"]

logging:
  level: info
  to_files: true
  to_syslog: true
```

**Comment by ruflin** [comment] 2018-02-23 02:57
As this issue now contains a mix of different memory issues, I'm going to close it to make sure not more posts end up here.

@bramford Any chance you could post your issue here? https://discuss.elastic.co/c/beats/filebeat Please post also the filebeat version as I remember there were some memory fixes recently. Please also add debug log files if possible.

**Comment by ruflin** [comment] 2018-07-20 08:05
@urso @exekias ^ This might be interesting.

**Comment by urso** [comment] 2018-07-31 21:48
Where do your logs reside? Endless 0byte sequence sounds like network shares. Some sample logs for reproducing the problem locally would be helpfull.

**Comment by jfiedler** [comment] 2018-08-09 06:06
@urso We are running all this in Kubernetes (filebeat as DaemonSet). The logs we look at are the Docker daemon logs that reside on the Kubernetes host. These are "host volumes" in K8s speak. No network storage should be involved in that.

I will try to produce some steps to repeat with sample logs if I find the time and if this is indeed reproducible.

**Comment by jiusanzhou** [comment] 2019-02-27 06:58
@jfiedler Hi Jfiedler, any update on this issue?

**Comment by jiusanzhou** [comment] 2019-03-03 08:46
Our team has figured out why huge memory used. Actually, we have a big log file almost 10Gb and just **1 line** in the file!

**Comment by PhaedrusTheGreek** [comment] 2019-03-21 20:05
I am also seeing Filebeat using massive amounts of memory on a huge file with very long lines (144GB file with 2MB per line)

**Comment by roncohen** [comment] 2019-12-20 10:43
Thank you all for engaging on this issue. 

We have an enhancement issue which should cover the issue with long lines: https://github.com/elastic/beats/issues/13740. If you disagree, please feel free to re-open. 

In earlier version of Filebeat there was a memory issue related to kubernetes which has been fixed. If that problem persists after upgrading Filebeat, please don't hesitate to open up a new issue.

**Closed by roncohen** 2019-12-20 10:43 UTC
Labels: Filebeat, discuss
