### ISSUE TITLE
32-BIT Metricbeat (7.8.0) return abnormal value for system.network.in.bytes on 64 bit machines

### ISSUE THREAD

**Issue by papaneeds** [elastic/beats#24145] opened 2021-02-20 12:52 UTC
Hi,
 I experienced exactly the same issue as another user. The issue is very well described in this discussion:
https://discuss.elastic.co/t/32-bit-metricbeat-7-8-0-return-abnormal-value-for-system-network-in-bytes/254369
 
When running a 32 bit version of metricbeat on a 64 bit machine system.network.in.bytes produces nonsensical and large values. 

- Version:  32-bit 7.8.0
- Operating System: Windows 64-bit
- Discuss Forum URL: https://discuss.elastic.co/t/32-bit-metricbeat-7-8-0-return-abnormal-value-for-system-network-in-bytes/254369
- Steps to Reproduce: Please see the discuss forum URL.

**Comment by fearful-symmetry** [comment] 2021-02-22 18:25
So, as someone else pointed out, the problem is likely here: https://github.com/shirou/gopsutil/blob/fc7e5e7af6052e36e83e5539148015ed2c09d8f9/net/net_windows.go#L170 It looks like we use an error value to see if we're running on a 32 or 64 bit OS, and assume we're running a similar version of metricbeat.

Maybe a dumb question because it's Monday and my brain is booting up @masci do we support running 32-bit version on a 64-bit host?

**Comment by jlind23** [comment] 2022-01-04 09:18
@nimarezainia @ruflin as 32bits binaries will be deprecated. Shouldn't we close this issue then?

**Comment by jlind23** [comment] 2022-03-30 12:22
Closing it as 32bits binaries are now deprecated

**Closed by jlind23** 2022-03-30 12:22 UTC
Labels: Team:Elastic-Agent-Data-Plane
