### ISSUE TITLE
Potential memory leak in `logstash-xpack` Metricbeat module

### ISSUE THREAD

**Issue by ycombinator** [elastic/beats#21661] opened 2020-10-07 20:14 UTC
For confirmed bugs, please report:
- Version: 7.8.1
- Operating System: Mac OS X
- Steps to Reproduce: 
   1. Create a sufficiently large (> 500 vertices) Logstash pipeline. 
   2. Start Logstash with this pipeline.
   3. Disable all modules in Metricbeat.
   4. Enable the `logstash-xpack` module.
   5. Edit `modules.d/logstash-xpack.yml` and set `period: 500ms`. This will speed up collection and memory accumulation so overall less time (just a few minutes) will be needed to observe the memory leak.
   6. Start Metricbeat.
   7. Using `top`, sample the memory usage of Metricbeat every 10 seconds: `top -s 10 -pid $(pgrep metricbeat) -stats command,mem | grep metricbeat`
   8. After 5-10 minutes, observe the `top` output and notice that the memory usage is steadily growing.

**Comment by ycombinator** [comment] 2020-10-07 20:15
Notes from @urso and @ycombinator:

> We checked the `logstash-xpack` module and didn't find any significant changes [as compared to Metricbeat 7.4.2] that we could attribute to a potential leak. The difference between the `logstash-xpack` module and the other modules is that the `logstash-xpack` module requires libbeat to json encode and decode the event (which is a quite expensive operation by itself). Maybe the go version the Beat was compiled with (different JSON encoder/decoder due to changes in the stdlib) has an impact as well.

**Comment by faec** [comment] 2020-11-17 20:13
Repro confirmed, pprof heap data linked below (thanks @ycombinator for very detailed groundwork / repro steps!). The memory growth is essentially all from the json decoding, and it's pretty clearly a leak. I'm not sure yet whether it's in the underlying library or we aren't properly cleaning up our helper objects, although I suspect the latter since our json decoder hasn't been updated in a couple years and this leak seems to be coming up a lot only in recent Beats versions. Currently investigating the specific code paths that handle the leaked data.

[Heap pprof data](https://github.com/elastic/beats/files/5555931/mbheap1.pprof.zip)

**Comment by faec** [comment] 2020-11-18 19:02
Updates from following this thread:
- The memory wasn't really accumulating that fast. My metricbeat output was misconfigured, and the snapshot was ordinary accumulation in the queue. (What _is_ true is that these events are fairly large, ~2MB / sample, so any bottleneck or problem later in the ingestion can grow the memory use quite fast.)
- Everything shows up as being an allocation from the json decoder because (unlike many beats / modules?) all event data is passed through json encoding / decoding, so any accumulation of events, whether leaked at some later stage or just bottlenecked in the regular queue, will show up as having been allocated by the json decoder. (We could still use this to trace down a real leak, by artificially shifting allocations elsewhere to find the "real" endpoint, but only if there is a big enough observable leak to start from.)

With the output configured correctly, I no longer see any notable memory growth -- total use ranges from ~25-35MB, but doesn't appear to grow beyond that no matter how long I run it.

**Comment by andresrc** [comment] 2020-11-25 08:32
It seems the high memory consumption is due to just the accumulation of big events in the memory queue. Closing.

**Closed by andresrc** 2020-11-25 08:32 UTC
Labels: Metricbeat, Stack monitoring, Team:Services, bug
