### ISSUE TITLE
elastic-agent: [warn] cannot index event publisher

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#17778] opened 2020-04-17 07:41 UTC
Most likely I misconfigured the Elasticsearch instance, but the Kibana UI reports online/green status, the agent process is up and running.

The only place where I can find the information about misconfiguration is WARN message stored in logs.

```bash
2020-04-17T09:37:09.292+0200	WARN	[elasticsearch]	elasticsearch/client.go:385	Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Time{wall:0xbf9e75091443f918, ext:560286903758, loc:(*time.Location)(0x9c950e0)}, Meta:null, Fields:{"agent":{"ephemeral_id":"00500f6a-39b7-4fcc-a893-8eeb06f96dbc","hostname":"MacBook-Elastic.local","id":"ede0be38-46a9-4ffc-8f1e-2ff9195193b6","type":"metricbeat","version":"8.0.0"},"ecs":{"version":"1.5.0"},"event":{"dataset":"system.process","duration":39556060,"module":"system"},"host":{"architecture":"x86_64","hostname":"MacBook-Elastic.local","id":"24F065F8-4274-521D-8DD5-5D27557E15B4","ip":["fe80::aede:48ff:fe00:1122","fe80::1cf7:b917:ae2:f9ce","192.168.0.13","fe80::9011:adff:fe9a:e878","fe80::b92d:5718:8a3f:297b","fe80::8542:d769:a147:539f","fe80::9d5:dc6:105b:bb1d"],"mac":["ac:de:48:00:11:22","a6:83:e7:ae:70:01","a4:83:e7:ae:70:01","06:83:e7:ae:70:01","92:11:ad:9a:e8:78","a2:00:45:49:64:01","a2:00:45:49:64:00","a2:00:45:49:64:05","a2:00:45:49:64:04","a2:00:45:49:64:01"],"name":"MacBook-Elastic.local","os":{"build":"18G4032","family":"darwin","kernel":"18.7.0","name":"Mac OS X","platform":"darwin","version":"10.14.6"}},"metricset":{"name":"process","period":10000},"process":{"args":["/Applications/Google Chrome.app/Contents/MacOS/Google Chrome","-psn_0_81940"],"executable":"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome","name":"Google Chrome","pgid":530,"pid":530,"ppid":1},"service":{"type":"system"},"system":{"process":{"cmdline":"/Applications/Google Chrome.app/Contents/MacOS/Google Chrome -psn_0_81940","cpu":{"start_time":"2020-04-01T07:42:36.114Z","total":{"norm":{"pct":0.000100},"pct":0.002300,"value":16170194.000000}},"memory":{"rss":{"bytes":565788672,"pct":0.016500},"share":0,"size":8295260160},"state":"running"}},"user":{"name":"marcin.tojek"}}, Private:interface {}(nil), TimeSeries:true}, Flags:0x0, Cache:publisher.EventCache{m:common.MapStr(nil)}} (status=403): {"type":"security_exception","reason":"action [indices:admin/create] is unauthorized for API key id [I8QJh3EBHF2TPyDEQoXx] of user [fleet_enroll]"}
```

As user I would appreciate any notice about wrong configuration or an analyzer tool that can detect problems.

**Comment by mtojek** [comment] 2020-04-17 07:47
Actually the user `fleet_enroll` has been created by the product, so I wonder if there is any permission missing.

**Comment by mtojek** [comment] 2020-04-17 07:57
Possibly a side issue: I deleted the user `fleet_enroll` and the corresponding role. Kibana says nothing happened and I can enroll new agents (failed of course). I think we might need a magic reconfiguration "button" to bring back the user.

**Comment by ruflin** [comment] 2020-04-17 08:05
@nchaulet ^

**Comment by mtojek** [comment] 2020-04-17 08:21
I found also these calls while wiresharking:

```bash
{"create":{"_index":"metricbeat-8.0.0-2020.04.17"}}
{"@timestamp":"2020-04-17T08:20:20.960Z","agent":{"type":"metricbeat","ephemeral_id":"03298b6b-84ba-45a4-abee-adaebf7f6315","hostname":"MacBook-Elastic.local","id":"ede0be38-46a9-4ffc-8f1e-2ff9195193b6","version":"8.0.0"},"event":{"dataset":"system.network","module":"system","duration":4427520},"metricset":{"name":"network","period":10000},"service":{"type":"system"},"system":{"network":{"in":{"errors":0,"dropped":0,"bytes":0,"packets":0},"out":{"dropped":0,"packets":0,"bytes":0,"errors":0},"name":"en2"}},"ecs":{"version":"1.5.0"},"host":{"architecture":"x86_64","os":{"kernel":"18.7.0","build":"18G4032","platform":"darwin","version":"10.14.6","family":"darwin","name":"Mac OS X"},"id":"24F065F8-4274-521D-8DD5-5D27557E15B4","ip":["fe80::aede:48ff:fe00:1122","fe80::1cf7:b917:ae2:f9ce","192.168.0.13","fe80::9011:adff:fe9a:e878","fe80::b92d:5718:8a3f:297b","fe80::8542:d769:a147:539f","fe80::9d5:dc6:105b:bb1d"],"name":"MacBook-Elastic.local","mac":["ac:de:48:00:11:22","a6:83:e7:ae:70:01","a4:83:e7:ae:70:01","06:83:e7:ae:70:01","92:11:ad:9a:e8:78","a2:00:45:49:64:01","a2:00:45:49:64:00","a2:00:45:49:64:05","a2:00:45:49:64:04","a2:00:45:49:64:01"],"hostname":"MacBook-Elastic.local"}}
```

Shouldn't it be `metric-...`?

**Comment by ruflin** [comment] 2020-04-17 11:16
In the error you post it seems like it wants to index into the metricbeat index (and it shouldn't). This also gets confirmed with your wireshark call. Your API key does not have the permissions to index into Metricbeat which is a good thing.

@michalpristas We had such an issue in the past, I thought this is fixed?

**Comment by michalpristas** [comment] 2020-04-30 13:58
metricbeat index was coming from monitoring beat which has only beat module enabled, this looks like system module.
so this would indicate that it is coming from agent managed beat, but it lacks injected stream.dataset ... fields we're injecting.
Marcin is there  any chance some metricbeat is running somewhere on your machine?

**Comment by ruflin** [comment] 2020-04-30 18:59
@michalpristas I think this error was reported before the monitoring setup was fixed. So I think this went away.

**Comment by michalpristas** [comment] 2020-05-04 07:50
you're right it was 1 week earlier. closing this issue and will reopen if needed in a future

**Closed by michalpristas** 2020-05-04 07:50 UTC
Labels: Ingest Management:alpha1, Team:Ingest Management, bug

**Comment by ruflin** [comment] 2021-08-30 07:50
@nicpenning Is this a fresh 7.14 setup for the stack an Elastic Agent or something you migrated from 7.13?

The problem in the above is that the metricbeat process tries to index into `metricbeat-7.14.0-2021.08.26` which it shouldn't as it is the wrong destination.

**Comment by nicpenning** [comment] 2021-08-30 13:08
Hi @ruflin ,

This is a test Stack that has been upgrade many times since 6.0.

We have implemented fleet every version it became available. 

Is there a way to undo or rebuild fleet? We are currently using the most up to date fleet server and agents.

**Comment by ruflin** [comment] 2021-08-31 09:44
There should definitively be a way to get you back to "green". What version of elastic_package is installed? It might be that you have to delete and recreate the policy to solve it :-(
