### ISSUE TITLE
Incorrect Date and Time for system auth and syslogs is displayed under 'Last Activity' field under Data streams tab

### ISSUE THREAD

**Issue by ghost** [elastic/beats#22468] opened 2020-11-06 13:16 UTC
**Kibana version:**
Kibana: 7.10.0 BC4 cloud environment

**Elasticsearch version:**
Elasticsearch: 7.10.0 BC4 cloud environment

**Host OS and Browser version:**
Linux CentOS 7 , All

**Original install method (e.g. download page, yum, from source, etc.):**
7.10.0 BC4 Kibana cloud environment from https://cloud.elastic.co

**Description**
Incorrect Date and Time for system auth and syslogs is displayed under 'Last Activity' field under Data streams tab

**Preconditions**
1. 7.10.0 BC4 Kibana cloud environment(with commit 1796b5ec8fa1e60ccea63f2e5c25ccc665b92fdc) should be available.
2. Login into the above Kibana environment with 'elastic' superuser.
3. 7.10.0 BC4 Linux tar.gz agent package should be downloaded and installed(on Linux CentOS7) from below location:
https://staging.elastic.co/7.10.0-c650b297/downloads/beats/elastic-agent/elastic-agent-7.10.0-linux-x86_64.tar.gz
4. System Integration must be applied(with auth, syslogs enabled) on above Linux CentOS7 OS

**Steps to Reproduce**
1. Navigate to Datastreams tab in Kibana
2. Observe that incorrect date/time Dec 23, 2020 @ 02:38:xx.000 is displayed for system.auth and system.syslogs as current date is 6 November 2020

**Test data**
N/A

**Impacted Test case id**
N/A

**Actual Result**
Incorrect Date and Time for system auth and syslogs is displayed under 'Last Activity' field under Data streams tab

**Expected Result**
Correct Date and Time for system auth and syslogs should be displayed under 'Last Activity' field under Data streams tab

**What's working**
 - Issue is not occurring for other datasets

**What's not working**
 - N/A
 
**Screenshot**
![bug](https://user-images.githubusercontent.com/59917944/98370281-57fbc880-2060-11eb-8843-d8fc44e806ed.jpg)

**Logs**
N/A

**Comment by rahulgupta-qasource** [comment] 2020-11-06 13:29
@vipulsrivastava-qasource Please review the bug.

**Comment by vipulsrivastava-qasource** [comment] 2020-11-06 13:33
Reviewed and Assigned @EricDavisX

**Comment by EricDavisX** [comment] 2020-11-06 20:41
Hi - Ideally I'd like to know if this was happening on other OSes, too.  For now I can say I am seeing some irregularity on Centos7 with the 7.9.X Agent as well... so I don't think it is new.  Lets figure it out in a coming release.  @ph thoughts?

**Comment by EricDavisX** [comment] 2020-11-06 20:51
I corrected a typo, I had above - I want to indicate I can see the same error in Centos I have 7 with the 7.10 BC 5 Agent, it is showing a timestamp in the future.  
with 7.9 Agent / Kibana I am not seeing any irregularity, so it may be something introduced (in the package, or in Beats perhaps) in this last cycle.

I had System Logs turned off in my example 7.9 host until today, but it had some prior logs, and then also shows a new data_stream for today (Nov 6) when I turned it on:

![7 9-Agent](https://user-images.githubusercontent.com/12970373/98413562-d26c1e80-2047-11eb-81d9-1148fee162bf.png)

**Comment by jen-huang** [comment] 2021-02-10 17:41
Hi @EricDavisX, FYI for 7.11 we fixed an issue where data streams were being shown in the UI: #89812. That code affected where we pull the "last activity" field from - now we pull it from the ES data stream information, rather than a max aggregation on matching documents. I'm curious to know if that fix might have resolved this issue?

**Comment by ph** [comment] 2021-02-10 17:57
Interesting I though it was an integration issue?

**Comment by jen-huang** [comment] 2021-02-10 18:02
It could be, I'm not completely sure, just wanted to point out that PR as it did related changes.

**Comment by EricDavisX** [comment] 2021-02-10 18:15
@dikshachauhan-qasource can you re-test and see if we find it and report findings back please?

**Comment by amolnater-qasource** [comment] 2021-02-11 12:04
Hi @EricDavisX 

We have observed similar issue and was reported at https://github.com/elastic/integrations/issues/501. However we have revalidated this issue today on 7.11 BC-8 Kibana cloud environment and found this issue **partially reproduceable**.
**What's working:**
-Logs for "system.syslog" are generated for present timestamp.

**What's not working:**
-"system.auth" logs are observed for future timestamp.

**Screenshot:**
![13](https://user-images.githubusercontent.com/77374876/107633586-48f36a80-6c8e-11eb-8333-dbcdd87facd6.JPG)

**Build details:**

Artifact link: https://staging.elastic.co/7.11.0-657c0367/downloads/beats/elastic-agent/elastic-agent-7.11.0-linux-x86_64.tar.gz
Platform: Linux Ubuntu 20
Build: 37897
Commit: 3f71ce7177a41e067ddb1e670ec4ace5f6d4f5fe

Please let us know if anything else is required.

Thanks

**Comment by EricDavisX** [comment] 2022-01-14 19:08
@dikshachauhan-qasource @amolnater-qasource wanted to note I am unassigning myself.  do you want to pick this up and re-test it ?  If not that's ok but it remains open, would be nice to know if it still happens in 8.1.

**Comment by jen-huang** [comment] 2022-01-14 22:24
I'm closing this as dupe of https://github.com/elastic/integrations/issues/501 (and that issue is in the right area).

**Closed by jen-huang** 2022-01-14 22:24 UTC
Labels: bug, Team:Integrations, impact:medium

**Comment by dikshachauhan-qasource** [comment] 2022-01-17 05:45
Hi @EricDavisX 

Thanks for the follow up and updates. We will test this on 8.0 and 8.1 and will post our observation under related open ticket.

Thanks
QAS
