### ISSUE TITLE
socket_summary metricset not collecting host sockets when metricbeat is in a network namespace

### ISSUE THREAD

**Issue by jsoriano** [elastic/beats#10637] opened 2019-02-07 17:53 UTC
If metricbeat is run in a network namespace (like in docker or kubernetes), even if it has access to host `/proc`, it still only collects sockets from its own namespace.
This is because after gopsutil collects the list of sockets per pid it queries the network of metricbeat istead of the network of the process that owns the socket.

~~This is already [fixed](https://github.com/shirou/gopsutil/commit/f87d9813da23e81b47bb990e67a010be32324d9a) in gopsutil, we should update.~~

**Comment by fearful-symmetry** [comment] 2019-04-18 16:03
So, I'm guessing that this is because the `Connections` function we cal eventually calls this:
`ConnectionsPid(kind, 0)`

Hence the namespacing. Right?

**Comment by fearful-symmetry** [comment] 2019-04-18 20:29
I'm struggling to reproduce this?
Spun up MB in docker with:
```
  --mount type=bind,source=/proc,target=/hostfs/proc,readonly \
  --mount type=bind,source=/sys/fs/cgroup,target=/hostfs/sys/fs/cgroup,readonly \
  --mount type=bind,source=/,target=/hostfs,readonly \
  --net=host \
  --volume="$(pwd)/metricbeat.docker.yml:/usr/share/metricbeat/metricbeat.yml:ro" \
   docker.elastic.co/beats/metricbeat:7.0.0 -e -system.hostfs=/hostfs
```

And got:
```
  "system": {
    "socket": {
      "summary": {
        "tcp": {
          "all": {
            "time_wait": 0,
            "count": 5,
            "listening": 4,
            "established": 1,
            "close_wait": 0
          }
        },
        "udp": {
          "all": {
            "count": 3
          }
        },
        "all": {
          "count": 8,
          "listening": 4
        }
      }
    }
```

Same as with MB 7.0 installed on the same host via RPM:


```
Apr 18 15:25:17 griffon.nest metricbeat[7319]:   "system": {
Apr 18 15:25:17 griffon.nest metricbeat[7319]:     "socket": {
Apr 18 15:25:17 griffon.nest metricbeat[7319]:       "summary": {
Apr 18 15:25:17 griffon.nest metricbeat[7319]:         "tcp": {
Apr 18 15:25:17 griffon.nest metricbeat[7319]:           "all": {
Apr 18 15:25:17 griffon.nest metricbeat[7319]:             "count": 5,
Apr 18 15:25:17 griffon.nest metricbeat[7319]:             "listening": 4,
Apr 18 15:25:17 griffon.nest metricbeat[7319]:             "established": 1,
Apr 18 15:25:17 griffon.nest metricbeat[7319]:             "close_wait": 0,
Apr 18 15:25:17 griffon.nest metricbeat[7319]:             "time_wait": 0
Apr 18 15:25:17 griffon.nest metricbeat[7319]:           }
Apr 18 15:25:17 griffon.nest metricbeat[7319]:         },
Apr 18 15:25:17 griffon.nest metricbeat[7319]:         "udp": {
Apr 18 15:25:17 griffon.nest metricbeat[7319]:           "all": {
Apr 18 15:25:17 griffon.nest metricbeat[7319]:             "count": 3
Apr 18 15:25:17 griffon.nest metricbeat[7319]:           }
Apr 18 15:25:17 griffon.nest metricbeat[7319]:         },
Apr 18 15:25:17 griffon.nest metricbeat[7319]:         "all": {
Apr 18 15:25:17 griffon.nest metricbeat[7319]:           "count": 8,
Apr 18 15:25:17 griffon.nest metricbeat[7319]:           "listening": 4
Apr 18 15:25:17 griffon.nest metricbeat[7319]:         }
Apr 18 15:25:17 griffon.nest metricbeat[7319]:       }
Apr 18 15:25:17 griffon.nest metricbeat[7319]:     }
```

Is there something I'm missing?

**Comment by fearful-symmetry** [comment] 2019-04-19 14:56
So, interesting update. I'm now looking at the socket vs socket_summary metricsets, and it looks like they seem to report the same sockets, but a bunch of proc data is missing from the containerized metricbeat.

Outside of a container:
```
Apr 19 08:59:39 griffon.nest metricbeat[9164]:   "system": {
Apr 19 08:59:39 griffon.nest metricbeat[9164]:     "socket": {
Apr 19 08:59:39 griffon.nest metricbeat[9164]:       "process": {
Apr 19 08:59:39 griffon.nest metricbeat[9164]:         "cmdline": "/usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 9092 -container-ip 172.18.0.2 -container-port 9092"
Apr 19 08:59:39 griffon.nest metricbeat[9164]:       },
Apr 19 08:59:39 griffon.nest metricbeat[9164]:       "local": {
Apr 19 08:59:39 griffon.nest metricbeat[9164]:         "ip": "::",
Apr 19 08:59:39 griffon.nest metricbeat[9164]:         "port": 9092
Apr 19 08:59:39 griffon.nest metricbeat[9164]:       }
Apr 19 08:59:39 griffon.nest metricbeat[9164]:     }
Apr 19 08:59:39 griffon.nest metricbeat[9164]:   },
```

And inside the container:
```
  "system": {
    "socket": {
      "local": {
        "ip": "::",
        "port": 9092
      }
    }
  },
```

**Comment by fearful-symmetry** [comment] 2019-04-19 17:27
There's still some kind of problem if you run the docker container as root:
```
  "system": {
    "socket": {
      "local": {
        "port": 22,
        "ip": "::"
      }
    }
  },
  "ecs": {
    "version": "1.0.0"
  },
  "server": {
    "ip": "::",
    "port": 22
  },
  "error": {
    "code": "process not found. inode=29023, tcp_state=LISTEN"
  },
```

**Comment by fearful-symmetry** [comment] 2019-04-22 20:34
Okay, so what's happening is that even with `--user=root`, docker can't read the symlinks in `/proc/[pid]/fd` hence a lot of network info is missing. You can hhack around this with `--privileged`. Not sure there's a better way to do it.

**Comment by andrewkroh** [comment] 2019-04-22 20:41
Does the guidance in the doc work to get the process info while containerized? https://www.elastic.co/guide/en/beats/metricbeat/current/running-on-docker.html

**Comment by fearful-symmetry** [comment] 2019-04-22 20:43
It doesn't appear so. It mentions `--user=root` which will get you halfway there, but it seems like `--privileged` is needed to actually read the symlinks that you get from the procfs bindmount. Not sure if there's a more granular way to add those permissions.

**Comment by jsoriano** [comment] 2019-04-24 08:55
@fearful-symmetry the problem happens `If metricbeat is run in a network namespace`, so when `--net=host` is not used. Maybe the problem is not that important as we use to run metricbeat in the host network, but it'd be nice to collect the info when running namespaced if it is within reach.

The thing is that the information is available in `/hostfs/proc`, but we are looking for it in `/hostfs/proc/self`, that points to the metricbeat process, that is not in the host namespace.
Maybe the fix is to try to use `net.ConnectionsPid("inet", 1)` instead of `net.Connections("inet")`, at least when `hostfs` is set, so it lists the connections in the namespace of the init process in the host, that should be the host namespace.

You are right that there can be permission problems involved too.

The `socket` metricset is a different problem, I think it uses netlink to get the connections and this probably needs to be run in the host network namespace to work. We might think about getting the information for this one also with `net.Connections` so we would make it also more OS-independant. But I would focus first in `socket_summary` because this is enabled by default now.

**Comment by fearful-symmetry** [comment] 2019-04-24 13:42
Ah, I see. @jsoriano  So you think this should work when `--net=host` is not used? Is there a reason why we wouldn't want to set that?

Yah, with the `socket` metricset, it uses netlink to get the connections, then uses `/proc` to actually get the process info for the socket via an inode lookup. I actually had the same idea of using netlink entirely as well, but I wasn't sure if we should devote that much effort to it. Should I make a separate issue for this?

**Comment by jsoriano** [comment] 2019-04-24 16:17
> Ah, I see. @jsoriano So you think this should work when `--net=host` is not used? Is there a reason why we wouldn't want to set that?
> 
It'd be nice to make it work if it is possible. I think we had reports of users preferring not to require `--net=host`. For example with docker swarm using the host namespace was not supported, and even now I think it is a bit hacky to do it.

> Yah, with the `socket` metricset, it uses netlink to get the connections, then uses `/proc` to actually get the process info for the socket via an inode lookup. I actually had the same idea of using netlink entirely as well, but I wasn't sure if we should devote that much effort to it. Should I make a separate issue for this?

I created one issue to support more OSs that would be in this line https://github.com/elastic/beats/issues/11915

**Comment by jlind23** [comment] 2022-04-01 09:10
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.

**Closed by jlind23** 2022-04-01 09:10 UTC
Labels: bug, Metricbeat, [zube]: In Progress, Team:Integrations
