### ISSUE TITLE
Custom beat:  Cannot export and re-import dashboard.  Missing steps?

### ISSUE THREAD

**Issue by joshuar** [elastic/beats#8200] opened 2018-09-03 05:57 UTC
Hey all,

I'm developing a custom beat against the 6.4 branch. I'm following the beats developer guide.  My problem is with the [export/import of dashboards](https://www.elastic.co/guide/en/beats/devguide/current/new-dashboards.html). 

So I have a clean Elasticsearch/Kibana running from the official Docker images.  I'll use my beat to index data into ES and then build out some visualisations and a dashboard in KB.  Then I go to export the dashboard to include it in my beat with:

```
go run vendor/github.com/elastic/beats/dev-tools/cmd/dashboards/export_dashboards.go -dashboard 79a7d0e0-a755-11e8-8251-ff8bb68f52ef -output _meta/kibana/6/dashboard/mydashboard.json 
```

I believe `_meta/kibana/6/dashboard/`  is the correct location for these dashboards.

I then wipe my Elasticsearch clean (i.e, `curl -XDELETE localhost:9200/_all`), logout and log back into Kibana so it recreates its index with its OOTB defaults.  

I then run `make update` in my beat which seems to create a `_meta/kibana.generated/6` directory which contains both the dashboard and index pattern.

I'll then re-run the setup of my beat and specify this directory with `./mybeat -d "*" -e setup -E "setup.dashboards.directory=_meta/kibana.generated"`, which seems to load the index pattern and dashboards/visualisations correctly.

Then run my beat to re-generate my data and then try to view my imported dashboard.  But then I get:

![image](https://user-images.githubusercontent.com/7401/44967896-c7a93100-af87-11e8-8592-89f592c629f0.png)

The visualisations themselves work individually,  but the dashboard seems to be broken.  I have to recreate the dashboard from scratch.  The time is borked and no visualisations are displayed. I have to delete this dashboard object and re-create with the visualisations.  

Is this a know problem? Or am I missing some step here?

**Comment by ruflin** [comment] 2018-09-03 11:45
Could you check the content of your dashboard file inside `kibana.generated` to see how it looks like? Does it have encoded json inside or not? Can you compare it to what you get after you exported it?

**Comment by joshuar** [comment] 2018-09-04 07:32
It does contain JSON but looks like a completely different file.  If I diff the export in `_meta/kibana/6/dashboard` vs the generated one in `_meta/kibana.generated/6/dashboard` it appears the entire file is different.

Interestingly, if I export the dashboard with:

```
go run vendor/github.com/elastic/beats/dev-tools/cmd/dashboards/export_dashboards.go -dashboard 79a7d0e0-a755-11e8-8251-ff8bb68f52ef -output _meta/kibana/6/dashboard/mydashboard.json 
```

Then wipe my `.kibana` index and try to re-import by running the beat with the setup command pointed at the dashboards I just exported:

```
/mybeat -d "*" -e setup -E "setup.dashboards.directory=_meta/kibana"
```

I get the following error:

```
Loaded index template
Loading dashboards (Kibana must be running and reachable)
Exiting: Error importing Kibana dashboards: fail to import the dashboards in Kibana: Error importing directory _meta/kibana: Failed to import dashboard: Failed to load directory _meta/kibana/6/dashboard:
  error loading _meta/kibana/6/dashboard/node_stats_overall.json: failed to parse [visualization.kibanaSavedObjectMeta.searchSourceJSON]. Response: {"objects":[{"id":"55f0a7a0-a68b-11e8-80c7-5b7f0ebd2d9a","type":"visualization","error":{"message":"failed to parse [visualization.kibanaSavedObjectMeta.searchSourceJSON]"}},{"id":"2a2f4570-b00b-11e8-bd2f-2dc03ea3fd59","type":"visualization","error":... (truncated)
  error loading _meta/kibana/6/dashboard/thread_pools_overall.json: failed to parse [visualization.kibanaSavedObjectMeta.searchSourceJSON]. Response: {"objects":[{"id":"58eac910-ab52-11e8-922c-c7db1716ef83","type":"visualization","error":{"message":"failed to parse [visualization.kibanaSavedObjectMeta.searchSourceJSON]"}},{"id":"6d69e860-ab54-11e8-922c-c7db1716ef83","type":"visualization","error":... (truncated)
```

**Comment by joshuar** [comment] 2018-09-05 01:12
Okay I did some more digging, and it looks like the `export_dashboards.go` tool does not properly export the `panelsJSON` field for the dashboard.  If I run for example:

```
go run vendor/github.com/elastic/beats/dev-tools/cmd/dashboards/export_dashboards.go -dashboard 79a7d0e0-a755-11e8-8251-ff8bb68f52ef -output _meta/kibana/6/dashboard/mydashboard.json 
```

`mydashboard.json` contains all the necessary saved searches and visualisations for the dashboard, but the dashboard object itself has "null" as the value for the `panelsJSON` field.  If I run the export API request that the tool is using directly against Kibana, i.e.:

```
curl -XGET 'localhost:5601/api/kibana/dashboards/export?dashboard=79a7d0e0-a755-11e8-8251-ff8bb68f52ef'
```

It's the same JSON response, but the `panelsJSON` field is correctly exported with it's value.

**Comment by joshuar** [comment] 2018-09-05 01:31
Alright, it looks like this [line](https://github.com/elastic/beats/blob/master/dev-tools/cmd/dashboards/export_dashboards.go#L117) is the culprit.

Catching the error thrown by json.Unmarshal  produces:

```
error: json: cannot unmarshal array into Go value of type common.MapStr
```

Indeed the `panelsJSON` value is an array in my case.  Is this a known issue?

**Comment by joshuar** [comment] 2018-09-29 00:44
So trying to use the above command with either my beat or metricbeat results in:

```
{
  "error": "Bad Request",
  "message": "Cannot read property 'length' of null",
  "objects": null,
  "statusCode": 400
}
```

So I'm wondering if this null value is a result of being unable to parse that `panelsJSON` value?

**Comment by joshuar** [comment] 2018-09-29 00:58
Okay scratch that last comment (deleted it) as that was with a broken dashboard.  So I just recreated a new dashboard in Kibana, saved it, then ran the export command above.  Here is the JSON export:

[dashboard.zip](https://github.com/elastic/beats/files/2430109/dashboard.zip)

**Comment by ruflin** [comment] 2018-11-05 07:50
@ycombinator Could you have a look at this one?

**Comment by ycombinator** [comment] 2018-11-05 15:03
Yep, I got it.

**Comment by ycombinator** [comment] 2018-11-15 14:48
@joshuar I believe #8954 should've fixed this issue. Any chance you could work off `master` and try to reproduce the issue? If `master` is not an option, the fix should be getting backported to `6.x` (for release in `6.6`) shortly: https://github.com/elastic/beats/pull/9102

**Comment by ChrsMark** [comment] 2018-12-19 13:32
Hello there, facing a similar problem.

Having exported a Kibana dashboard with:
```sh
go run vendor/github.com/elastic/beats/dev-tools/cmd/dashboards/export_dashboards.go -dashboard 79a7d0e0-a755-11e8-8251-ff8bb68f52ef -output _meta/kibana/6/dashboard/mydashboard.json 
```
I'm not able to import with:
```sh
 ./custombeat -v -e -d "*" setup -E setup.dashboards.enabled=true
```

The error I get is:
```sh
failed to parse [visualization.uiStateJSON]. Response: {"objects":[{"id":"12fe0dc0-0374-11e9-980d-c5ba02cd266a","type":"visualization","error":{"message":"failed to parse [visualization.uiStateJSON]"}},{"id":"70f41ec0-0373-11e9-980d-c5ba02cd266a","type":"visualization","error":{"message":"failed to parse... (truncated)
```

So comparing my json file with the one @joshuar uploaded I find that `uiStateJSON`, `visState`, `searchSourceJSON` are decoded instead of being strings. So to tackle this, I comment out the decoding options on
https://github.com/elastic/beats/blob/1ed8e32a266595982f3866f372482d58bc9afe09/libbeat/dashboards/decode.go#L30,  export again and everything  works fine.

So I'm wondering if this is something expected, or there is incompatibility, bug, problematic behavior.

**Comment by ycombinator** [comment] 2018-12-19 17:36
Hey @ChrsMark, what version/branch are you developing your custom beat from?

**Comment by jsoriano** [comment] 2019-08-14 08:52
I think #9097 solved this issue with the added `--decode` flag.

**Comment by jlind23** [comment] 2022-04-01 09:11
Backlog grooming: Closing it for now until further activity, can still be reopened if needed.

**Closed by jlind23** 2022-04-01 09:11 UTC
Labels: :Dashboards
