### ISSUE TITLE
Saved object import of beats dashboards is not working on 7.0.0 rc1

### ISSUE THREAD

**Issue by bhavyarm** [elastic/beats#11269] opened 2019-03-15 18:45 UTC
- Version: 7.0.0 RC1 BC1
- Operating System:  darwin_x_86_64
- Steps to Reproduce: 

I am not yet sure if this is a bug. Logging it so somebody from the beats team can confirm it.

The exported beats dashboards  through saved objects UI in Kibana from 5.6.16 are not working in 7.0.0. I did use the reindex helper in 5.6.16 to get them 6.7.0 BC7. They worked fine but on 7.0.0 - they are not working.

1. Get es/kibana/metricbeat/heartbeat stack going in 5.6.16 (bc1)
2. add the beats dashboards and run both the beats
3. Use the upgrade assistant in 5.6.16 to reindex .kibana
4. export the saved objects json using saved objects UI
4. Shut down 5.6.16 and get the 6.7.0 BC7 stack going for es/kibana/metricbeat/heartbeat
5. run beats but don't add dashboards - create index patterns in Kibana for heartbeat and metricbeat
6. import the exported json from step 4 and associate with the correct index pattern while resolving missing index patterns
7. Open dashboards - everything looks good
8. Check the upgrade assistant - there are no errors
9. Export the beats dashboards using saved objects UI
10. Get the 7.0.0 stack going for es/kibana/metricbeat/heartbeat
11. run beats but don't add dashboards - create index patterns in Kibana for heartbeat and metricbeat
12. import the exported json from step 9 and associate with the correct index pattern while resolving missing index patterns
14. Open one of the beats dashboard 
15. Kibana displays could not locate that index pattern field
<img width="1440" alt="Screen Shot 2019-03-15 at 2 44 52 PM" src="https://user-images.githubusercontent.com/7074629/54454921-f66f4380-4730-11e9-8e45-49a48a1e6da5.png">

**Comment by bhavyarm** [comment] 2019-03-15 19:43
We seem to be missing information about Add an opt-in BWC layer in 7.x.

**Comment by bhavyarm** [comment] 2019-03-15 19:55
tagging @cjcenizal as we went through this issue together!

**Comment by ruflin** [comment] 2019-03-18 08:55
@bhavyarm I assume you are referring to using `migration.enabled=true` in 7.0 to use the old dashboards? When you enabled the flag, did it work?

**Comment by bhavyarm** [comment] 2019-03-25 15:35
cc @LeeDr @ruflin this didn't work but I haven't tested it on BC3 which has the fix for this bug: https://github.com/elastic/beats/issues/11271. I am going to take a look at it tomorrow morning if nobody else looked at it. Thanks!

**Comment by narph** [comment] 2019-03-25 15:49
@bhavyarm , I have tried reproducing this scenario. 
Somehow it worked only once and I assume some caching was involved here. After that, every time I started 6.7.0 stack and import the saved objects I would get the same issues due to the 6.x mapping changes in the heartbeat index.
Let me know if you can reproduce this issue again.

**Comment by LeeDr** [comment] 2019-03-25 16:10
@ruflin do you have to set `migration.enabled=true` in the 6.7.0 `*beat.yml` before you upgrade to 7.0?  Or just in 7.0 before you start the beat?

**Comment by ruflin** [comment] 2019-03-27 07:20
@LeeDr No, the flag only exists for 7.0

**Comment by ruflin** [comment] 2019-03-27 07:24
I'm stumbling over "Create index pattern for HB / MB in Kibana". Does this mean letting Kibana create the index pattern? This should not be done, always the index pattern created by the Beat should be used.

**Comment by ruflin** [comment] 2019-03-27 09:57
After chatting with @narph I think we know have a better understanding on what is happening.

Kibana dashboards and index patterns should also be in sync. So a 5.6 index pattern fits to 5.6 dashboards, 6.5 index pattern to 6.5 dashboards. When exporting in 5.6, it seems the index pattern is not exported so we end up in the situation that users have to generated the index pattern manually (which they shouldn't). So going from 5 to 6, users should just use the dashboards and index pattern shipped with 6.x and load the index pattern again.

As far as I'm aware, the above has not really popped up so far with users migrating from 5 to 6. My assumption is that most users want to use the new dashboards with more features anyway, so export / import is not needed.

For the migration to 7: From 6.7 to 7.0 it seems like the migration is working if we don't have a manually created index pattern because of the 5.6 migration. The part I wonder in general is why do we export / import dashboards for the migration from 6 to 7? Why not just migrate with them in Kibana?

One thing @narph discovered, that when importing dashboards in 7 with a half broken 6.x index pattern and having 7.0 data in Elasticsearch, it seems for some reason the import of the dashboards is successful but some visualisations are missing. The visualisations are in the initial json file which is imported but don't show up in the Save Objects list. Still the UI does not show any errors. Perhaps someone from the Kibana team could shed some lights on this?

**Comment by bhavyarm** [comment] 2019-03-27 13:14
> I'm stumbling over "Create index pattern for HB / MB in Kibana". Does this mean letting Kibana create the index pattern? This should not be done, always the index pattern created by the Beat should be used.

@ruflin that was a manual step. I assumed that user doesn't want to load the new kibana dashboards so didn't configure my kibana.yml to load dashboards. Which means - I created the indexpattern manually. The docs do not mention that user is not supposed to create index patterns by themselves? Or I am missing it somewhere? Thanks!

**Comment by bhavyarm** [comment] 2019-03-27 13:22
@narph @ruflin - this is a different scenario? What does half broken 6.x index pattern means here? 
Thanks!

> One thing @narph discovered, that when importing dashboards in 7 with a half broken 6.x index pattern and having 7.0 data in Elasticsearch, it seems for some reason the import of the dashboards is successful but some visualisations are missing. The visualisations are in the initial json file which is imported but don't show up in the Save Objects list. Still the UI does not show any errors. Perhaps someone from the Kibana team could shed some lights on this?

**Comment by ruflin** [comment] 2019-03-27 13:25
@bhavyarm Good point about the docs, especially as we had in the past also the issue that some users created their own index pattern and had issues. @dedemorton Should we add something around that?

Half broken index pattern in 6.x I mean the self generated index pattern. Sorry for not being specific here. I think it's the same scenario but a different issue. It did not show up in the testing yet, as it broke earlier.

**Comment by bhavyarm** [comment] 2019-03-27 13:33
@ruflin we did fix a similar bug during upgrading from 5.6 to 6.0 - https://github.com/elastic/kibana/issues/14592.

**Comment by LeeDr** [comment] 2019-03-27 13:33
If we try to list out the main possible cases during upgrade, I think they would be;
1. user upgrades the full stack but wants to keep their existing index patterns, visualizations, and dashboards
2. user upgrades but wants to run setup to install the latest and greatest index patterns, visualizations, and dashboards
3. user exports before upgrade, and wants to import those things after upgrade

I would think #1 would be the majority of users.  They very likely have customized things and don't want the upgrade to break anything.

@ruflin suggests #2 might be most likely.  In this case, does running the beats setup automatically overwrite all the saved objects?  Or do they not overlap perfectly and some old save objects are left after setup of new saved objects?  Or are we documenting that the user should delete all the previous version saved objects first?

#3 seems least likely, but might be used in the case where a business wants to test their data on the upgrade version on a separate environment before upgrading their production system.  In this case they might install a fresh stack of the upgrade version and want to import the saved objects from their earlier version production system.

In the end, I think they all should be supported use cases.

**Comment by ruflin** [comment] 2019-03-27 15:02
@LeeDr Agree, all 3 should be supported and be working. Problem with #3 in 5.6 is that the index pattern is not exported which makes it incomplete.

So far I think we only added new visualisations / dashboards, so all should be overwritten. But for example when going from 6.7 to 7.0, there are not Heartbeat dashboards anymore by default. So these would be left overs. But I would also not expect these to affect the import.

I'm worried a bit around #3 as the testing by @narph showed that not everything is imported, but no errors are shown. @LeeDr do you know who from the Kibana team we should pull in here?

@bhavyarm Interesting, seems we hit this from 5 to 6 before which is good to know. Do you know what the expected behaviour in 7.0 during the import is now?

**Comment by narph** [comment] 2019-03-27 15:10
hi @bhavyarm , regarding,
> @narph @ruflin - this is a different scenario? What does half broken 6.x index pattern means here?
> Thanks!

I have followed all the steps in the description (with the specific stack versions) and from step 4 I have the following file [export5616.zip](https://github.com/elastic/beats/files/3013706/export5616.zip) and from steps 10 the file [export67.zip](https://github.com/elastic/beats/files/3013713/export67.zip) .
When I import the export67.json file in 7.0 and I either do not have the index patterns manually created or I chose to overwrite everything I am able to import only 107 saved objects. If I have manually created the 2 index patterns and chose to resolve the conflicts then I am able to import 110 objects (the 3 missing saved objects seem to come from the Heartbeat HTTP monitoring dashboard). 
The import on these visualizations fails silently, I can attach the kibana debug logs if necessary. 
@bhavyarm , I wonder if you can reproduce this behavior as well or the exported files look different in your case.

**Comment by bhavyarm** [comment] 2019-03-27 17:15
@narph @ruflin can we please zoom tomorrow to see whats up with this? Thanks!

**Comment by bhavyarm** [comment] 2019-03-28 22:32
@narph @ruflin I didn't have any silent failures. I can see that all my saved objects got exported. But some of the vizs are not getting displayed. So I am logging a bug in kibana repo and will tag you. Also heartbeat dashboard doesn't work between 5.6.x to 6.7.0. Will talk to kibana app team about it too.

**Comment by bhavyarm** [comment] 2019-03-28 22:45
https://github.com/elastic/kibana/issues/34129

**Comment by narph** [comment] 2019-04-15 07:44
closing issue, PR merged

**Closed by narph** 2019-04-15 07:44 UTC
Labels: :Dashboards, :infrastructure, [zube]: In Progress, bug, docs
