### ISSUE TITLE
Fail to start Filebeat with couldn't unpack memory queue config

### ISSUE THREAD

**Issue by alexsapran** [elastic/beats#35198] opened 2023-04-24 17:49 UTC
For confirmed bugs, please report:
- Version: main
- Operating System:  macOS
- Steps to Reproduce: 

With the following configuration if you start Filebeat you will see the following error

```yml
filebeat.inputs:
  - type: filestream
    id: my-filestream-id
    paths:
    - /var/log/*.log

output.console:
  pretty: true

monitoring.enabled: true
monitoring.elasticsearch:
  hosts: ["xxxxxxxx"]
  username: "elastic"
  password: "changeme"
```

Starting Filebeat with the above `./filebeat -c will_fail.yml` will result into the following error

```
Exiting: couldn't unpack memory queue config: requires value >= 32 accessing 'mem.events'
```

**Comment by alexsapran** [comment] 2023-04-24 18:10
Adding one more information. If I remove the monitoring section from the config filebeat works fine. I have not tested if it would fail in the same way if I replace the monitoring with an es output.

**Comment by cmacknz** [comment] 2023-04-24 19:49
There are tests for stack monitoring but they were disabled due to being flaky https://github.com/elastic/beats/blob/d64e6321a50797aaad64d1000bfb04808317d846/libbeat/tests/system/test_monitoring.py#L14

We should clearly revive these tests.

**Comment by cmacknz** [comment] 2023-04-24 19:59
If we can identify the change that caused this should can consider reverting it to get an immediate fix for this. Based on what I know most of the work in this area isn't urgently needed for 8.8.

**Comment by cmacknz** [comment] 2023-04-26 18:18
Possibly this is fixed with https://github.com/elastic/beats/pull/35156

**Comment by rdner** [comment] 2023-05-04 08:55
I can confirm that at 967c29221d672f7fb0f3c631d7a9082b9fc05100 ( 669d8b3f3e8d62b5dc11bd96a767466d1067d27d~1) Filebeat (x-pack) fails to start and I can see:

```json
{
  "log.level": "error",
  "@timestamp": "2023-05-04T10:50:23.128+0200",
  "log.origin": {
    "file.name": "instance/beat.go",
    "file.line": 1274
  },
  "message": "Exiting: couldn't unpack memory queue config: requires value >= 32 accessing 'mem.events'",
  "service.name": "filebeat",
  "ecs.version": "1.6.0"
}
```

After https://github.com/elastic/beats/commit/669d8b3f3e8d62b5dc11bd96a767466d1067d27d the problem is gone.

**Closed by rdner** 2023-05-04 08:55 UTC
Labels: bug, Filebeat, Team:Elastic-Agent
