### ISSUE TITLE
Filebeat events.added metric reports negative value

### ISSUE THREAD

**Issue by vjsamuel** [elastic/beats#7503] opened 2018-07-03 18:10 UTC
Found on master.

We have noticed that `filebeat.events.added` metric reports negative values. This is seen in both `tcp` and `log` input types.

Ex:
`"filebeat":{"events":{"active":-72238,"added":3032542,"done":3104780}`

**Comment by ruflin** [comment] 2018-07-04 10:53
Where did you fetch these metrics? From the log or API endpoint? `active` is a UInt so should never go negative: https://github.com/elastic/beats/blob/master/libbeat/outputs/metrics.go#L33

I assume this related to our metrics gathering which by default takes the diff from the previous value. So here you this would mean you have 72238 less active events then 30 seconds ago if it is from the log.

Long term we should introduce the concept of gauges, short term I assume we should add an entry to this list: https://github.com/elastic/beats/blob/master/libbeat/monitoring/report/log/log.go#L37

**Comment by ycombinator** [comment] 2019-12-20 18:50
This looks like a duplicate of https://github.com/elastic/beats/issues/3114.

**Closed by ycombinator** 2019-12-20 18:50 UTC
Labels: :Outputs, bug, libbeat
