### ISSUE TITLE
http.go:421: WARN Response from unknown transaction. Ingoring

### ISSUE THREAD

**Issue by hollligan** [elastic/beats#2201] opened 2016-08-09 14:25 UTC
Hello, please help to get rid of the error in the PacketBeat.
I use **PacketBeat** (ver 1.2.3).
**OS**: Microsoft Windows 7; Microsoft Windows Server 2008 R2 Standard

**Error**:

> 2016/08/09 14:08:59.311531 decoder.go:97: INFO packet decode failed with: Invali
> d (too small) IP length (0 < 20)
> 2016/08/09 14:09:02.479712 http.go:421: WARN Response from unknown transaction.
> Ingoring.

**If you look at the trace.pcap there should be three request/response:**
![image](https://cloud.githubusercontent.com/assets/19423656/17519688/a9084180-5e55-11e6-8328-58e19e82c3a9.png)

**The error can be reproduced:** 
`C:\temp\packetbeat> packetbeat.exe -e -I C:\temp\packetbeat\trace.pcap`

The trace files.pcap and packetbeat.yml file in the attachment.
[trace.pcap](https://github.com/elastic/beats/files/409149/trace.pcap.txt)
[packetbeat.yml](https://github.com/elastic/beats/files/409150/packetbeat.yml.txt)

PS. Thank you in advance for your help!

**Comment by hollligan** [comment] 2016-08-16 07:12
The problem also exists in version **5.0.0-alpha5**.
Please help me.

**Comment by monicasarbu** [comment] 2016-08-17 14:16
Thank you @hollligan for reporting the issue. I can easily reproduce it in `master`, and we will try to fix it as soon as possible.

**Comment by hollligan** [comment] 2016-08-17 14:50
Hello, @monicasarbu . The problem is how paketbeat processes large packets (larger than MTU). 
My dump is a package No. 17 (**Total Length: 2142 bytes (reported as 0, presumed to be because of the "TCP segmentation offload" (TSO))**). 

> 2016/08/09 14:08:59.311531 decoder.go:97: INFO packet decode failed with: Invali
d (too small) IP length (0 < 20)

[ip4.go#L146](https://github.com/elastic/beats/blob/5827b44bf53d28c488faa29dd18a3d52f19ca247/vendor/github.com/tsg/gopacket/layers/ip4.go#L146)

Note package No. 8, he passed because there was a TCP Retransmission (packages No. 10 and No. 12).

Useful links:
- http://rtodto.net/generic_segmentation_offload_and_wireshark/
- https://ask.wireshark.org/questions/24699/tcp-packet-length-was-much-greater-than-mtu


[**A temporary solution is to disable hardware packet fragmentation at the level of NIC**](https://support.rackspace.com/how-to/disabling-tcp-offloading-in-windows-server-2012/)

**Comment by monicasarbu** [comment] 2016-08-17 15:05
@hollligan The problem appears as `ip.length` is zero, and there is a "[workaround](https://github.com/google/gopacket/blob/master/layers/ip4.go#L191)" in the official [https://github.com/google/gopacket](https://github.com/google/gopacket), that we don't have in the [gopacket](https://github.com/tsg/gopacket) fork that we use. 
I hope once we include this workaround in our gopacket fork, the issue is fixed.

**Comment by monicasarbu** [comment] 2016-08-19 07:45
@hollligan Please try the latest SNAPSHOT of Packetbeat from our [nightlies](https://beats-nightlies.s3.amazonaws.com/index.html?prefix=packetbeat/). I have tried it myself, and no error is raised.

**Comment by hollligan** [comment] 2016-08-19 12:27
the bug is fixed! thank you.

version 1.2 removed from support? updates will be made?

**Comment by monicasarbu** [comment] 2016-08-26 07:15
Closing the issue as it's fixed now. Version 1.2 is currently supported, and the fix will be available in the next release.

**Closed by monicasarbu** 2016-08-26 07:15 UTC
Labels: bug, Packetbeat
