### ISSUE TITLE
Filebeat timeouts to Elastic

### ISSUE THREAD

**Issue by reqless** [elastic/beats#1871] opened 2016-06-15 17:38 UTC
I have configured Elasticsearch and now I am using Filebeat to try to send logs directly to it.

Elasticsearch sits behind an internal load balancer.

I can confirm an HTTP GET to the IP address of the ILB and responds within a few ms. This proves the ability to connect to ES via REST API.

I configured Filebeat to connect to the same ILB:9200 but I get constant timeouts inside the log.

Example ::

2016-06-15T17:23:15Z INFO Error publishing events (retrying): Post http://10.0.1.20:9200/_bulk: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2016-06-15T17:23:15Z INFO send fail
2016-06-15T17:23:15Z INFO backoff retry: 1m0s

This happens over and over.

I do have Shield in front of ES, but the credentials are specified inside the filebeat.yml file. I even bumped the timeout up to 30 but this still happens.

Version : 1.2.3
OS : Windows Server 2012 R2 Datacenter

**Comment by ruflin** [comment] 2016-06-16 09:40
This sounds similar to https://discuss.elastic.co/t/filebeat-not-connecting-directly-to-elasticsearch-from-particular-machine/51999

**Comment by ruflin** [comment] 2016-06-16 09:46
@reqless I'm closing this issue so we can have the conversation in one place. I think the problem here seems to be identical: https://discuss.elastic.co/t/filebeat-not-connecting-directly-to-elasticsearch-from-particular-machine/51999/19?u=ruflin

Also we want to keep Github issues for confirmed bugs and keep the investigations in discuss. Please let me know if you think it is an unrelated issue and feel free to reopen the issue.

**Closed by ruflin** 2016-06-16 09:46 UTC
