### ISSUE TITLE
filebeat 7.12.1  logging.files.permissions: 0644 no work

### ISSUE THREAD

**Issue by Notelzg** [elastic/beats#25685] opened 2021-05-12 12:12 UTC
filebeat 7.12.1  logging.files.permissions: 0644 no work

Please include configurations and logs if available.
logging.level: debug
logging.selectors: ["*"]
logging.to_files: true
logging.files:
  path: /usr/local/Caskroom/filebeat-7.12.1-darwin-x86_64/log
  name: mifi-filebeat
  keepfiles: 7
  permissions: 0644

when i run filebeat with cmd: ./filebeat -c filebeat.yml
ls -alh /usr/local/Caskroom/filebeat-7.12.1-darwin-x86_64/log/mifi-filebeat 
-rw-r-----   1 logan92  admin    16K May 12 19:56 mifi-filebeat
the file permission is not 0644, is 0630 that's why?

For confirmed bugs, please report:
- Version: 7.12.1
- Operating System:  Mac OS X
- Discuss Forum URL:
- Steps to Reproduce:

**Comment by andrewkroh** [comment] 2021-05-17 19:49
Duplicate of https://github.com/elastic/beats/issues/24555 and sort of https://github.com/elastic/beats/issues/20584.

**Closed by andrewkroh** 2021-05-17 19:49 UTC
Labels: bug, libbeat, needs_team
