### ISSUE TITLE
[Ingest Manager]: Error logs are getting displayed under Logs tab, when Agent logging level setting is updated.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#23395] opened 2021-01-07 14:48 UTC
**Kibana version:**
7.11 BC Kibana Cloud environment 

**Elasticsearch version:**
7.11 BC Kibana Cloud environment 

**Host OS and Browser version:**
Windows 10, All

**Original install method (e.g. download page, yum, from source, etc.):**
7.11 BC Kibana Cloud environment  

**Preconditions**
1.  7.11 BC Kibana Cloud environment  should be available.
```
BUILD 37605
COMMIT a5126f7a280a6f4a27dc3aca65c1c89ccd1ac694
Artifact link: https://staging.elastic.co/7.11.0-8f5ce7c2/summary-7.11.0.html/elastic-agent-7.11.0-windows-x86_64.zip
```
2. Any policy having system integration should exist.[No change in namespace].
3. Agent should be installed using above policy.

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. Go to Fleet>Agents. 
3. Observe, currently agent logs are generated.
4. Select Agent Logging Level and update setting to say 'warning'.
5. Apply Changes.
6. Wait for few seconds. Refresh the Browser.
7. Now, Agent logging level is updated on Agent details page.
8. Navigate back to Logs tab.Notice, Error logs are getting displayed under Logs tab, when Agent logging level setting is updated.

**Reference ticket Id:**
https://github.com/elastic/kibana/issues/84119

**Actual Result**
Error logs are getting displayed under Logs tab, when Agent logging level setting is updated.

**Expected Result**
Error logs should not be displayed under Logs tab, when Agent logging level setting is updated.

**What's working**
- Logging level is updated properly.
- Logs are generated as per above logging level.

**What's not working**
N/A

**Logs**
```
[elastic_agent][warn] failed to ack update open C:\Program Files\Elastic\Agent\data\.update-marker: The system cannot find the file specified.
```

**Screenshots:** 
![errorLogs](https://user-images.githubusercontent.com/72375798/103906008-5bc1cf00-5125-11eb-94f5-644d226c60ac.png)

**Comment by manishgupta-qasource** [comment] 2021-01-07 14:51
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment] 2021-01-13 23:02
It is understandable to log this, but after review - it is not a bug.  The errors in the logs are unrelated to the change to the log level.  

 - the 'marker' item can be logged separately if we want to remove them from the log, it relates to the Agent upgrade feature.

**Closed by EricDavisX** 2021-01-13 23:02 UTC
Labels: Team:Ingest Management, bug, impact:high

**Comment by dikshachauhan-qasource** [comment] 2021-01-14 12:45
Hi @EricDavisX 

Thanks for the feedback.

However, as per our understanding its only updating agent settings to capture logs and not upgrading agent. 
With above feedback, we have come up withy few queries:

1. If we change agent logging level, does it triggers Agent to upgrade at Backend and that's why these logs are generating. 

2. In above reported defect we have seen logs stating :"The system cannot find the file specified." when Agent logging level is changed.
So, does this action changes file at  C:\Program Files\Elastic\Agent\data\.update-marker location which as per bug system could not locate.
Logs reported in defect:
```
[elastic_agent][warn] failed to ack update open C:\Program Files\Elastic\Agent\data\.update-marker: The system cannot find the file specified.
```

Thanks
QAS

**Comment by EricDavisX** [comment] 2021-01-14 16:38
1) The log level does not impact the Agent 'backend' or version at all.

2) The update-marker log is just coincidental timing that it shows up around the time that you are testing log level changes.  It will show up when Agent is first installed, and possibly for a brief time after that (up to 10 minutes maybe), glad to see the question.

**Comment by dikshachauhan-qasource** [comment] 2021-01-15 12:12
Hi @EricDavisX 

Thanks for the feedback on queries and providing clear concepts to functionality.

Thanks
QAS
