### ISSUE TITLE
metricbeat rpm installs /usr/lib/systemd/system/metricbeat.service with executable bit set

### ISSUE THREAD

**Issue by KEZHwMlXV1vFzs6QvY8v5WjX5** [elastic/beats#10290] opened 2019-01-23 13:53 UTC
Not sure if this is the right place to ask for fixes on elastic rpms. After installation of the metricbeat rpm we see this in the logs:

Configuration file /usr/lib/systemd/system/metricbeat.service is marked executable. Please remove executable permission bits. Proceeding anyway.

please do not set executable bit on the service unit file.

- Operating System: CENTOS7
- Repo: https://artifacts.elastic.co/packages/6.x/yum metricbeat-6.5.4-x86_64.rpm
- Steps to Reproduce: install metricbeat rpm from restic repo

**Comment by andrewkroh** [comment] 2019-01-23 18:31
This sounds like a duplicate of https://github.com/elastic/beats/pull/7873. Checking the RPM file you referenced:

```
# rpm -qpilv metricbeat-6.5.4-x86_64.rpm  | grep '/lib/systemd/system/metricbeat.servic'
-rw-r--r--    1 root    root                      456 Dec 17 20:33 /lib/systemd/system/metricbeat.service
```

The .service file is not executable. Perhaps you have an older version installed?

**Closed by andrewkroh** 2019-01-23 18:31 UTC
