### ISSUE TITLE
central management - wrong instructions

### ISSUE THREAD

**Issue by jalvz** [elastic/beats#9204] opened 2018-11-22 11:14 UTC
When trying to enrol `metricbeat` for  central management, the code snippet says `filebeat`

![filebeat](https://user-images.githubusercontent.com/3432712/48899477-faa8e580-ee4f-11e8-97cb-9f472a8e7cfc.png)

Spotted in 6.5.1

**Comment by exekias** [comment] 2018-11-22 11:16
Thanks for testing this Juan! closing it as a duplicate of https://github.com/elastic/kibana/issues/25372 cc @mattapperson

**Closed by exekias** 2018-11-22 11:16 UTC

**Comment by jalvz** [comment] 2018-11-22 11:18
ah, didn't think of checking kibana issues, ofc! thanks :+1:
