### ISSUE TITLE
Add ability to load sample dashboards for modules selectively

### ISSUE THREAD

**Issue by shalvah** [elastic/beats#12167] opened 2019-05-10 13:34 UTC
**The enhancement:**
In Filebeat, it would be nice if we were able to specify which of the included sample dashboards we want to load, possibly by module. This can be done in either of the following ways:
1. Provide a config option, say, `setup.dashboards.files`, that lets you specify the files you want to load (`Filebeat-nginx-logs.json,Filebeat-nginx-overview.json`), or:
2. Organise the dashboards within the local `kibana/7/dashboards` directory in sub-directories by module. This would allow us to use the existing `setup.dashboards.directory` option.

**Use case for the enhancement or feature:**
I want to make use of the included Filebeat sample dashboards, but only the ones for Nginx, since that is the only module I'm using. Altogether, there are 139 sample dashboards, which is going to make navigation somewhat more confusing and stressful for other team members. I'm running Filebeat via Docker (Kubernetes). While I can modify the `cmd` so it reorganizes the dashboards as in (2) above, I would prefer not to.

**Comment by coudenysj** [comment] 2019-07-02 12:19
After asking it on the discussion boards (https://discuss.elastic.co/t/load-one-dashboard-instead-of-all-filebeat-default-dashboards-follow-up/188455), I found this issue.

When you run `filebeat setup`, only the pipelines for the enabled modules are loaded in Elasticsearch, which is a nice default. It would be awesome if the same logic is applied for Kibana dashboards.

**Comment by PhaedrusTheGreek** [comment] 2019-07-25 21:56
+1 for only loading dashboards for enabled modules

**Comment by coudenysj** [comment] 2020-08-18 19:31
Can we reopen this? We were waiting for reaction of the Elastic team.

**Comment by lfmunoz** [comment] 2022-04-22 03:07
+1

workaround: delete all the dashboard you won't use then load

**Comment by nimarezainia** [comment] 2022-05-18 19:10
@lfmunoz & @Fabian1976 just a clarification; are you using   "filebeat setup --module x , y"  ? 
this should indeed only load the dashboards for x and y modules and nothing else.

**Comment by lfmunoz** [comment] 2022-05-18 19:24
@nimarezainia did you confirm this works? On what version? When I tried that it didn't work.

**Comment by nimarezainia** [comment] 2022-05-18 20:49
if there's a bug in using this setup command we will address that. But as far as new functionality is concerned, I would like to point out that the Elastic Agent that is managed via Fleet already does what is being requested here. That is, when a user adds an integration to a policy, all the assets (including dashboards) for that integration are added to Kibana.

Please consider deploying the agent instead and if you can't let us know what feature/functionality is required to make that transition happen.

**Comment by nimarezainia** [comment] 2022-05-18 20:56
@lfmunoz just looking to see if we have a bug here.
I am wondering if the Agent would work for you?

**Comment by kvch** [comment] 2022-05-19 07:04
> Yes, please reopen this. It's just strange that any setup can be run with the --module option, except for the dashboards.

It is incorrect. `setup` subcommand load everything for all modules. All dashboards and all fields of all modules in the template. `--modules` flag only applies to loading pipelines because we had to add that later.

> this should indeed only load the dashboards for x and y modules and nothing else.

No, `--modules` does not apply to dashboards. If we say something else in the documentation, we should fix that.

The only workaround we have at the moment is to move the dashboards you want to load to a new folder and set its path in `setup.dashboards.directory`.

**Comment by Fabian1976** [comment] 2022-05-19 07:55
So if i understand correctly. If you only need 1 or 2 modules, you can load the pipelines for them. But then you have to import all dashboard (which are a lot) and search for the correct dashboard which uses those modules?

Sounds cumbersome.

**Comment by kvch** [comment] 2022-05-19 08:37
Unfortunately, this is how module loading was designed. It is indeed cumbersome, that is one of the reasons why we have a different approach in [Integrations](https://www.elastic.co/integrations/data-integrations).

**Comment by nimarezainia** [comment] 2022-05-19 17:58
I'm closing this enhancement request. I realize that what we have with Filebeat could be cumbersome in this regard but there are workarounds available. In addition there has been considerable effort to improve the situation by designing and releasing the Elastic Agent with it's integrations that addresses these concerns.

**Closed by nimarezainia** 2022-05-19 17:58 UTC
Labels: enhancement, Filebeat, Metricbeat, Team:Elastic-Agent-Data-Plane

**Comment by brsolomon-deloitte** [comment] 2023-01-03 20:55
> there are workarounds available.

Actually, no - when using `docker.elastic.co/beats/filebeat` and running as the `filebeat` user, there are virtually no workarounds, or at least none that are not painstaking and very cumbersome. (Please do produce a minimal example of such a workaround here if you have one.) Not every customer is using Elastic Agent, and it doesn't always make sense. For example, someone may use Filebeat as a "seed" container to set up for a Filebeat ->  Kafka -> Logstash -> Elasticsearch. The inability to load specific dashboards even when using `--modules` feels more like a bug than a missing feature. Loading all module dashboards with their corresponding visualizations and saved searches takes a prohibitively long time.
