### ISSUE TITLE
Filebeat issue with ready logs from NFS

### ISSUE THREAD

**Issue by erniteshjain** [elastic/beats#2056] opened 2016-07-19 08:03 UTC
Filebeat 1.2.3

Using it to ready logs from shared mount folder (nfs). However after sometime filebeat stops sending logs to logstash cluster.

Requesting for any solution to fix this issue.

**Comment by ruflin** [comment] 2016-07-19 08:18
It is not recommended to read log files from shared volumes: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-network-volumes.html

I'm not sure if your issue is related to the shared volume or an issue in 1.2.3 as it sounds very similar to this here: https://github.com/elastic/beats/issues/1974

I'm closing this issue as I think either it is a duplicate of an existing issue. Please try to install filebeat on the edge nodes instead of using shared volumes. Some improvements were made in the 5.0.0 builds to handle shared volumes, it would be interesting to hear if these solve your issue. https://beats-nightlies.s3.amazonaws.com/index.html?prefix=filebeat/

**Closed by ruflin** 2016-07-19 08:18 UTC
