### ISSUE TITLE
Elastic Agent: default docker setup spins the CPU

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#18351] opened 2020-05-07 12:36 UTC
The default configuration includes "system" package, causing CPU spinning in the agent container.

I noticed that's correlated with logging all data locally.

```
[root@ee1925337431 default]# pwd
/usr/share/elastic-agent/data/logs/default
[root@ee1925337431 default]# ls -la
total 153940
drwxr-xr-x 2 root root     4096 May  7 12:32 .
drwxr-xr-x 3 root root     4096 May  7 12:19 ..
-rw------- 1 root root  5799117 May  7 12:32 filebeat
-rw------- 1 root root 10467912 May  7 12:32 filebeat-2020-05-07-12-145
-rw------- 1 root root 10480928 May  7 12:32 filebeat-2020-05-07-12-146
-rw------- 1 root root 10476909 May  7 12:32 filebeat-2020-05-07-12-147
-rw------- 1 root root 10483017 May  7 12:32 filebeat-2020-05-07-12-148
-rw------- 1 root root 10484833 May  7 12:32 filebeat-2020-05-07-12-149
-rw------- 1 root root 10481757 May  7 12:32 filebeat-2020-05-07-12-150
-rw------- 1 root root 10481963 May  7 12:32 filebeat-2020-05-07-12-151
-rw------- 1 root root  5058299 May  7 12:32 metricbeat
-rw------- 1 root root 10482725 May  7 12:31 metricbeat-2020-05-07-12-10
-rw------- 1 root root 10483934 May  7 12:22 metricbeat-2020-05-07-12-4
-rw------- 1 root root 10482641 May  7 12:24 metricbeat-2020-05-07-12-5
-rw------- 1 root root 10483376 May  7 12:25 metricbeat-2020-05-07-12-6
-rw------- 1 root root 10484553 May  7 12:27 metricbeat-2020-05-07-12-7
-rw------- 1 root root 10480666 May  7 12:28 metricbeat-2020-05-07-12-8
-rw------- 1 root root 10483007 May  7 12:30 metricbeat-2020-05-07-12-9
```

```
[root@ee1925337431 default]# ps aux
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         1  0.5  0.2 888380 22888 ?        Ssl  12:09   0:08 elastic-agent run
root       190  0.0  0.0  11964  3136 pts/1    Ss   12:15   0:00 /bin/bash
root       214  0.0  0.7 842232 59584 ?        Sl   12:19   0:00 /usr/share/elastic-agent/data/install/filebeat-8.0.0-SNAPSHOT-linux-x86_64/filebeat -E setup.ilm.enabled=false -E setup.template.enabled=false
root       230  3.1  1.3 1614728 113952 ?      Sl   12:19   0:31 /usr/share/elastic-agent/data/install/metricbeat-8.0.0-SNAPSHOT-linux-x86_64/metricbeat -E setup.ilm.enabled=false -E setup.template.enabled=f
root       252 46.3  3.9 1696260 319308 ?      Sl   12:19   7:42 /usr/share/elastic-agent/data/install/filebeat-8.0.0-SNAPSHOT-linux-x86_64/filebeat -E setup.ilm.enabled=false -E setup.template.enabled=false
root       277  0.2  1.0 1319352 86252 ?       Sl   12:19   0:02 /usr/share/elastic-agent/data/install/metricbeat-8.0.0-SNAPSHOT-linux-x86_64/metricbeat -E setup.ilm.enabled=false -E setup.template.enabled=f
root       694  0.0  0.0  51764  3524 pts/1    R+   12:36   0:00 ps aux
```

**Comment by ruflin** [comment] 2020-05-11 08:18
@ph @michalpristas If the debug logging indeed is the problem we should probably switch back to info logging by default but have a config option to enable it.

**Comment by michalpristas** [comment] 2020-05-11 09:02
i will verify both options and make the change if necessary

**Comment by michalpristas** [comment] 2020-05-12 10:25
do you use default config and default docker image or some snapshot one. is kibana running and you see agent there?
i have troubles reproducing it it's running few minutes now and still this
<img width="604" alt="image" src="https://user-images.githubusercontent.com/1522652/81673279-afbbcd00-944b-11ea-981f-56df477b9b7d.png">

**Comment by mtojek** [comment] 2020-05-12 10:45
I used the standard testing environment from: https://github.com/elastic/integrations/tree/master/testing/environments

and enabled the "system" integration.

**Comment by michalpristas** [comment] 2020-05-18 10:25
i'm going to close this as i still cannot reproduce high cpu load, not when running manually not when using integration testing environment.
<img width="238" alt="image" src="https://user-images.githubusercontent.com/1522652/82202702-9e1e6d80-9902-11ea-8ec4-4c4ab4527caf.png">

**Comment by mtojek** [comment] 2020-05-18 10:50
@michalpristas I wanted to reverify this issue, but unfortunately it failed enrollment: https://github.com/elastic/beats/issues/18612

**Comment by mtojek** [comment] 2020-05-20 07:41
It's higher CPU load on my end that you observed, but I think I found the issue. It's correlated with filebeat system logs and dumped events:

```
[root@676f69c3d247 elastic-agent]# ls -lh data/logs/default/
total 79M
-rw------- 1 root root 6.0M May 20 07:37 filebeat
-rw------- 1 root root  10M May 20 07:36 filebeat-2020-05-20-07-51
-rw------- 1 root root  10M May 20 07:36 filebeat-2020-05-20-07-52
-rw------- 1 root root 9.7M May 20 07:36 filebeat-2020-05-20-07-53
-rw------- 1 root root 9.8M May 20 07:36 filebeat-2020-05-20-07-54
-rw------- 1 root root  10M May 20 07:36 filebeat-2020-05-20-07-55
-rw------- 1 root root  10M May 20 07:37 filebeat-2020-05-20-07-56
-rw------- 1 root root  10M May 20 07:37 filebeat-2020-05-20-07-57
-rw------- 1 root root 275K May 20 07:36 metricbeat
-rw------- 1 root root  410 May 20 07:31 metricbeat-2020-05-20-07-1
-rw------- 1 root root 3.0M May 20 07:36 metricbeat-2020-05-20-07-2
```

Is it possible to add a debug flag to switch off logging events to be published? It would be great to enable it in runtime, maybe using GRPC?

**Comment by michalpristas** [comment] 2020-05-20 09:37
verified and is indeed related to log level defaulting to trace.
going to change log level here to info (this seems ok)

**Closed** 2020-05-25 14:36 UTC
Labels: Ingest Management:alpha1, Team:Ingest Management, bug
