### ISSUE TITLE
does autodiscover support reload?

### ISSUE THREAD

**Issue by ascendlin** [elastic/beats#29984] opened 2022-01-25 06:48 UTC
autodiscover config
```yaml
filebeat.autodiscover:
  providers:
    - type: docker
      labels.dedot: true
      templates:
        - condition:
            contains:
              docker.container.name: kibana
          config:
            - type: docker
              containers.ids:
                - "${data.docker.container.id}"
output.console:
  pretty: true

processors:
- add_host_metadata: ~
- add_docker_metadata: ~
```
when i changed the condition “docker.container.name” to "demo1"
```yaml
docker.container.name: demo1
```
filebeat didn't reload

**Comment by ChrsMark** [comment] 2022-01-25 11:07
Hi @ascendlin! How are you deploying Filebeat on k8s? Did you use the Daemonset manifests from [https://www.elastic.co/guide/en/beats/filebeat/current/running-on-kubernetes.html](https://www.elastic.co/guide/en/beats/filebeat/current/running-on-kubernetes.html)? In that case how do you update the Filebeat's config? I would expect that updating the config means updating the configmap accordingly and in that case the Daemonset needs to be restarted also so as to get the new configuration. Let us know if that helps.

**Comment by ChrsMark** [comment] 2022-02-03 09:59
I'm gonna close this one since it looks more like a question and not a confirmed bug. You can use [https://discuss.elastic.co/tag/filebeat](https://discuss.elastic.co/tag/filebeat) in the future for questions. Thank's!

**Closed by ChrsMark** 2022-02-03 09:59 UTC
Labels: Team:Integrations
