### ISSUE TITLE
[7.13.0-SNAPSHOT] Elastic-Agent: unable to find enrollment token named "Default" in policy "Default policy"

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#24310] opened 2021-03-03 09:16 UTC
Today we spotted an issue while running Elastic Agent:

```
Attaching to elastic-package-stack_elastic-agent_1
[36melastic-agent_1              |[0m Performing setup of Fleet in Kibana
[36melastic-agent_1              |[0m Error: unable to find enrollment token named "Default" in policy "Default policy"
```

Link: https://beats-ci.elastic.co/job/Ingest-manager/job/elastic-package/job/PR-269/3/artifact/build/elastic-stack-dump/stack/logs/elastic-agent.log

The issue will fail all master builds for elastic/integrations and elastic/elastic-package.

Steps to reproduce:

```
elastic-package stack update -v
elastic-package stack up -v -d
```

For reference:
https://github.com/elastic/elastic-package/pull/269

EDIT:

Keep in mind that we had to push a workaround for the agent's image. You can find Docker Compose definitions here: https://github.com/elastic/elastic-package/blob/c8b00a93596e157c7eafb8b0163440cf88ced59f/internal/install/static_snapshot_yml.go

**Comment by ph** [comment] 2021-03-03 13:37
This look like a fleet issue, more than a beats issue.

@nchaulet did we broke something in 7.13?

**Comment by blakerouse** [comment] 2021-03-03 13:42
@ph I am looking into this. I merged #24220, that refactors how the container is started. I think Kibana might have change how it names enrollment tokens. Trying to verify what the issue is, if that was changed I was un-aware.

**Comment by ph** [comment] 2021-03-03 13:45
@blakerouse OK, I've sent it back to the right board. thanks for looking into it, I would have though that the refactoring in Kibana could have cause this issue so feel free to send it back to fleet.

**Comment by jalvz** [comment] 2021-03-03 13:45
FWIW I can reproduce the issue with `docker run  -it --env FLEET_ENROLL=1 --env FLEET_INSECURE=1 --env FLEET_SETUP=1 --env KIBANA_FLEET_HOST="http://kibana:5601" --env FLEET_URL="http://kibana:5601" --rm docker.elastic.co/beats/elastic-agent:8.0.0-SNAPSHOT.

Do not only I need to pass the token name including the id, but the actual api key too. This works: `docker run -it --env FLEET_ENROLL=1 --env FLEET_INSECURE=1 --env FLEET_SETUP=1 --env KIBANA_FLEET_HOST="http://kibana:5601" --env FLEET_URL="http://kibana:5601"  --env FLEET_TOKEN_NAME="Default (c20805f6-6fba-4e9d-9333-b0e4eb749204)" --env FLEET_ENROLLMENT_TOKEN="TUdTRDlIY0JqMUJMeW5jM0VhMDk6anVLVUdGZmtUVXVZYm9rcWxsVVd1dw==" --rm docker.elastic.co/beats/elastic-agent:8.0.0-SNAPSHOT"`

**Comment by nchaulet** [comment] 2021-03-03 14:05
We did not merge the refactoring to fleet server yet in Kibana for 7.13.0

**Comment by mtojek** [comment] 2021-03-03 15:34
I understand that the fix from Blake will bring back the original behavior: 

>docker run -it --env FLEET_ENROLL=1 --env FLEET_INSECURE=1 --env FLEET_SETUP=1 --env KIBANA_FLEET_HOST="http://kibana:5601" --env FLEET_URL="http://kibana:5601" --rm docker.elastic.co/beats/elastic-agent:8.0.0-SNAPSHOT

... so there is no need to define `FLEET_ENROLLMENT_TOKEN` and `FLEET_TOKEN_NAME`.

**Comment by mtojek** [comment] 2021-03-03 16:02
Let me write update on the issue:

I'm trying to make the Integrations green again. I got some guidance from @blakerouse to consider switching to fleet server: https://github.com/elastic/elastic-package/pull/272 , which doesn't work in 7.13.0 (probably due to the above issue?)

Actually there are more incompatible things:
1. There is another policy, not the `Default` one. This will break our logic for system tests.
2. Agent's healthcheck doesn't work anymore: https://github.com/elastic/elastic-package/blob/master/internal/install/static_snapshot_yml.go#L85 . With fleet server, we're not able to detect when a policy has been assigned. I'm looking for ideas here.

I'm looking for some guidance on how should we proceed here. We tried with 8.0.0-SNAPSHOT and 7.13.0-SNAPSHOT, and currently both releases are failing.

**Comment by ruflin** [comment] 2021-03-04 09:56
@blakerouse @michalpristas Please help here. It is really important that before we make breaking changes we get the teams on board to not break CI and test environments!

**Comment by jsoriano** [comment] 2021-03-04 10:04
> @blakerouse @michalpristas Please help here. It is really important that before we make breaking changes we get the teams on board to not break CI and test environments!

Could we make CI jobs to depend on pinned versions of its dependencies so this kind of breaking changes are not introduced by mistake?

**Comment by mtojek** [comment] 2021-03-04 10:07
Yes, @jsoriano . I'm working on this here: https://github.com/elastic/elastic-package/issues/271

**Comment by jsoriano** [comment] 2021-03-04 10:07
> Yes, @jsoriano . I'm working on this here: [elastic/elastic-package#271](https://github.com/elastic/elastic-package/issues/271)

Great thanks!

**Comment by mtojek** [comment] 2021-03-04 10:10
Just a small update:

With recent temporary fixes https://github.com/elastic/elastic-package/pull/274 and https://github.com/elastic/integrations/pull/760  we unblocked Integrations and Elastic Package developers. Unfortunately such fixes have a side effect - they work only for 7.13.0-SNAPSHOT.

We'll have a proper solution once https://github.com/elastic/elastic-package/issues/271 is ready.

**Comment by ph** [comment] 2021-03-04 12:55
I see an open PR created by @blakerouse linked in this issue from yesterday https://github.com/elastic/beats/pull/24319 this has not been reviewed or tested, @mtojek or @michalpristas  have you look if it fixes this issue?

**Comment by mtojek** [comment] 2021-03-04 15:51
Let me know if we need more data, logs, etc. from us.

**Comment by mtojek** [comment] 2021-03-05 08:29
Unfortunately I have to reopen the issue as the problem still persists. It might be related to not releasing next snapshots, so I prefer to keep it open until the problem can be confirmed to be solved.

**Comment by mtojek** [comment] 2021-03-08 09:45
It seems that we moved forward with fixes for Agent. It fails now with: 

```
Attaching to elastic-package-stack_elastic-agent_1
[36melastic-agent_1              |[0m Performing setup of Fleet in Kibana
[36melastic-agent_1              |[0m The Elastic Agent is currently in BETA and should not be used in production
[36melastic-agent_1              |[0m 
[36melastic-agent_1              |[0m Error: Error: connection to Kibana is insecure, strongly recommended to use a secure connection (override with --insecure)
[36melastic-agent_1              |[0m Error: enrollment failed: exit status 1
```

Source: https://beats-ci.elastic.co/job/Ingest-manager/job/elastic-package/job/PR-273/7/artifact/build/elastic-stack-dump/stack/logs/elastic-agent.log

Is it something that has been fixed recently?

**Comment by ph** [comment] 2021-03-09 19:16
@mtojek Looking at the comments and the reference this is not an issue anymore?

**Closed by ph** 2021-03-09 19:16 UTC
Labels: Team:Agent
