### ISSUE TITLE
Metricbeat-7.16.2 does not support billing api version 2019-10-01

### ISSUE THREAD

**Issue by adhiraj-g** [elastic/beats#29928] opened 2022-01-20 13:51 UTC
I had upgraded to Elasticsearch version 7.16-2.
I am now using metricbeat version 7.16.2. Still its showing that the billing api is not supported. Are we using API-version: 2019-10-01 in this version or below?

`2022-01-05T07:02:52.470-0500 ERROR module/wrapper.go:259 Error fetching data for metricset azure.billing: error retrieving usage information: Retrieving usage details failed in client: consumption.UsageDetailsClient#List: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="400" Message="Subscription scope usage is not supported for current api version. Please use api version after 2019-10-01
`
I tried testing on Azure to confirm whether the subscription type i'm using is supported with the consumption API. It worked fine there.

As checked on the elastic search forum - [Link](https://discuss.elastic.co/t/metricbeat-7-16-2-does-not-support-billing-api-version-2019-10-01/293582) this seems like a bug. Hence raising an issue.

**Comment by adhiraj-g** [comment] 2022-03-27 16:25
Hi There,
Any updates on when the fix might be available?

**Comment by tommyers-elastic** [comment] 2022-06-15 14:29
thank you for raising this! 

I believe this issue is a duplicate of #20758 - please track progress over there :)

**Closed by tommyers-elastic** 2022-06-15 14:29 UTC
Labels: bug, Team:Integrations
