### ISSUE TITLE
Topbeat (v1.2.2) Performance Problem

### ISSUE THREAD

**Issue by githubmui** [elastic/beats#1539] opened 2016-05-01 11:10 UTC
Filtering with any process filter except ".*" leads to the documented performance impact on my windows 7 system.

![performance with process filter](https://cloud.githubusercontent.com/assets/17704200/14941470/6e3d4160-0f9d-11e6-805b-3c247fcbc74c.PNG)

- Version: v1.2.2
- Operating System: Windows 7 SP1
- Steps to Reproduce: Use following config file ...

[topbeat-yml.txt](https://github.com/elastic/beats/files/244075/topbeat-yml.txt)

**Comment by tsg** [comment] 2016-05-01 21:05
Seems like a duplicate of #1460, thanks for the extra details.

**Closed by tsg** 2016-05-01 21:05 UTC
