### ISSUE TITLE
Metricbeat Prometheus module can't fetch over 200K event in one shot

### ISSUE THREAD

**Issue by jehutywong** [elastic/beats#11912] opened 2019-04-24 01:33 UTC
config:
metricbeat.modules:
- module: prometheus
  period: 10s
  hosts: ["&lt;prometheus_url&gt;"]
  metrics_path: '/federate'
  query:
    'match[]': '{__name__!=""}'
  namespace: example

response:
"error": {
"message": "Unable to decode response from prometheus endpoint"
}

For confirmed bugs, please report:
- Version: Metricbeat-7.0.0
- Operating System: CentOS 7 x86_64
- Discuss Forum URL: https://discuss.elastic.co/t/metricbeat-prometheus-module-not-support-match-query/177571
- Seen also in https://github.com/elastic/beats/issues/14513 (Metricbeat 7.4.2, Ubuntu and Windows)
- Steps to Reproduce: 
When a query in a Prometheus directive returns over roughly 200k events, this error comes out.

**Comment by odacremolbap** [comment] 2019-06-20 12:58
I wasn't able to reproduce, any hint on how to replicate the scenario?

**Comment by jehutywong** [comment] 2019-06-21 03:01
Well my config is as simple as following. How many events did your Prometheus server return? @odacremolbap 

`metricbeat.modules:
- module: prometheus
  period: 10s
  hosts: ["&lt;prometheus_url&gt;"]
  metrics_path: '/federate'
  query:
    'match[]': '{__name__!=""}'
  namespace: example`

**Comment by yxyx520** [comment] 2019-07-18 12:13
The reason of your problem is not "Metricbeat Prometheus module can't fetch over 200K event in one shot",please check your prometheus_url is correct.You can use this command and have a test
`curl -v  -G --data-urlencode 'match[]={name!=""}' http://prometheus_url/federate`

**Comment by jehutywong** [comment] 2019-07-19 03:11
Well Prometheus API works well with the query
`curl -s -G --data-urlencode 'match[]={site=~"n.*"}' http://127.0.0.1:9090/federate | wc -l
535615
`
But the same query put into metricbeat, i will have the error above

**Comment by evandroasjr** [comment] 2020-01-03 08:16
Hi all,
I have this same issue. Any news?

Cheers,
Evandro

**Comment by jsoriano** [comment] 2020-01-30 17:12
Since 7.5.0, metricbeat logs more information when this error happens (https://github.com/elastic/beats/pull/13749), could someone with this problem share the error message on 7.5 or greater?

**Comment by christian-morin** [comment] 2020-02-21 14:32
I believe I'm seeing the same behavior in a Java Quarkus MicroProfile enabled app (as #14513 referenced here). Running metricbeat 7.6.1 I'm getting the following error:

`unable to decode response from prometheus endpoint: decoding of metric family failed: text format parsing error in line 1: expected float as value, got "'t"`

The prometheus metrics retrieved from my /metrics endpoint validated correctly using Prometheus promtool but somehow fails when trying to decode the response by metricbeat prometheus collector.

I can't understand where it's getting 't from as it's nowhere in the response. Would be great to be able to debug log what data it's actually trying to decode, but even setting debug logging I'm not seeing any information regarding what it's trying to decode? (or even which metric value) only the error above, which is hard to understand where it's coming from.

**Comment by jsoriano** [comment] 2020-02-24 09:46
@christian-morin It is possible that for some reason Metricbeat is receiving a different response, if it is an error https://github.com/elastic/beats/pull/15712 will help to investigate it, this change will be included in 7.6.1. In the meantime you could try to run a custom build of the 7.6 branch.

**Comment by christian-morin** [comment] 2020-03-19 15:44
@jsoriano ran this with 7.6.1 and noticed a new (and correct) error-description "unexpected status code 406 from server", which made me realise that the request from metricbeat is sent without an Accept header which creates this behavior for some prometheus-implementations which require this header to be set. Should I open a new issue for this?

**Comment by jsoriano** [comment] 2020-03-19 16:22
@christian-morin thanks for the update! Does [the workaround](https://github.com/elastic/beats/issues/16870#issuecomment-598734082) mentioned in #16870 work for you?

**Comment by christian-morin** [comment] 2020-03-20 08:28
@jsoriano yes, adding the Accept header in the Prometheus module config as
```
headers: 
  accept: "text/plain"
```
Made it start working!

**Comment by jsoriano** [comment] 2020-03-20 09:26
Ok, I am going to close this issue as since 7.5 (#13749) it is easier to diagnose what is happening on these cases, and we can continue with specific issues.
For the problem with accept headers we have the more specific #16835.
If someone is having a different problem, with a different error message, please update at least to 7.5.2 and open a new issue with the logged error.

Thanks all!

**Closed by jsoriano** 2020-03-20 09:26 UTC
Labels: Metricbeat, Team:Integrations, [zube]: Investigate, module

**Comment by ArvindhVenkatraman** [comment] 2020-08-24 19:12
i have the same problem. When the run it as curl could see the events but getting the below error in the module.error.message
unable to decode response from prometheus endpoint: unexpected status code 403 from server. not sure why it is giving me 403 error because it is not forbidden but for some reason it is unable to decode the response. i tried filtering on the match to a simple set but still wont work. Any suggestion ?

**Comment by infa-vsakati** [comment] 2020-11-12 03:50
> i have the same problem. When the run it as curl could see the events but getting the below error in the module.error.message
> unable to decode response from prometheus endpoint: unexpected status code 403 from server. not sure why it is giving me 403 error because it is not forbidden but for some reason it is unable to decode the response. i tried filtering on the match to a simple set but still wont work. Any suggestion ?

did u got solution

**Comment by liu-xiao-guo** [comment] 2022-11-29 06:30
I am following the tutorial at https://www.elastic.co/guide/en/observability/8.5/monitor-java-app.html#_what_youll_learn_3, and now I am having the error like:

`{"log.level":"error","@timestamp":"2022-11-29T14:29:59.700+0800","log.origin":{"file.name":"module/wrapper.go","file.line":256},"message":"Error fetching data for metricset prometheus.collector: unable to decode response from prometheus endpoint: unexpected status code 500 from server","service.name":"metricbeat","ecs.version":"1.6.0"}`

I do not know what caused the problem.
