### ISSUE TITLE
Connecting error publishing events to Logstash

### ISSUE THREAD

**Issue by politrons** [elastic/beats#934] opened 2016-02-05 17:03 UTC
I´m having similar issue when I try to connect to my logstash

Logstash version 2.0.0
Filebeat 1.0.1

Here the error

INFO Connecting error publishing events (retrying): dial tcp 192.168.50.5:14560: getsockopt: connection refused
This is my logstash configuration
```
input {
  beats {
    codec => json
    port => 14560
  }
}
output {
  elasticsearch {hosts=> localhost}
  stdout {codec = > rubydebug}
}
```
Here my filebeat configuration
```
   logstash:
    # The Logstash hosts
    hosts: ["{{ 192.168.50.5:14560 }}","{{ 192.168.50.15:14560 }}"]
```
I install the filebeat logstash plugin as I read it

  `./plugin install logstash-input-beats`
I´m completely run out of ideas, and I would love to use this framework, but it´s seems not responding at all. 
Any ideas would be great.

Regards.

**Comment by ruflin** [comment] 2016-02-07 19:07
Is that a duplicate of https://github.com/elastic/beats/issues/875#issuecomment-180434312 ?

**Comment by politrons** [comment] 2016-02-07 19:11
Not it's not. That question was done my me, and somebody ask me to do it again in another forum section. The first question and responses are not the same issue that I have right now

**Comment by ruflin** [comment] 2016-02-07 19:22
@politrons I think you are referring to the post by @urso : https://github.com/elastic/beats/issues/875#issuecomment-180439865 As far as I can see he meant to open an forum post on discuss here (https://discuss.elastic.co/c/beats) instead of a Github issue?

**Closed** 2016-03-09 00:22 UTC
Labels: Filebeat, question
