### ISSUE TITLE
[http.go] Add new field (user) when parsing HTTP request

### ISSUE THREAD

**Issue by ldvc** [elastic/beats#44] opened 2014-06-25 13:57 UTC
##### Enhancement
Hi there! First of all, thanks for this easy-to-use soft! When using Kerberos auth, HTTP request contains a specific field which looks like `DOEJOHN@EXAMPLE.NET` in order to transport user accessing webapp. Will it be possible to parse (and push to ElasticSearch) this field in order to make report based on it ?

###### Access log example
```
192.168.1.100 - DOEJOHN@EXAMPLE.NET [25/Jun/2014:13:49:04 +0200] "GET /myapp/ HTTP/1.1" 200 10419 "-" "Mozilla/5.0 (Windows NT 6.1; rv:30.0) Gecko/20100101 Firefox/30.0"
```
Thanks.

**Comment by monicasarbu** [comment] 2016-06-14 12:28
Closing it as the issue is too old.

**Closed by monicasarbu** 2016-06-14 12:28 UTC
Labels: enhancement, Packetbeat
