### ISSUE TITLE
Filebeat 8.3.2 (build 2022-07-06) keep sending already indexed logs

### ISSUE THREAD

**Issue by MADxHAWK** [elastic/beats#32401] opened 2022-07-19 12:42 UTC
``Problem seems to still exist.
Im sending cisco logfiles to logstash using filebeat 8.3.2 built 2022-07-06 on Ubuntu 20.04
Logfiles are send to logstash over and over again.

Elasticsearch showed me a log for a switch with a single line over 400 times after just a few hours. 

System A: 
V-host (4 Cores @ 2.2 GHz with 8GB RAM) running Ubuntu 20.04 with syslog-ng (receiving logs from cisco devices) and Filebeat (sending it to the ELK-Stack on System B.

System B: 
v-Host (8 Cores @2.6GHz with 32GB RAM) running Ubuntu 20.04 with ELK-Stack 8.x
Systemload is permanently over 80% and i have a constant datastream of about 3-4mbit/s from Filebeat to ELK-Stack since filebeat keeps sending all data over and over again. 

Receiving logs from Cisco Devices (Switches / ASA) by syslog-ng on System A. 
syslog-ng creates a new log every day at 00:00 UTC with the following Folder structure

/var/log/remotelogs/switches
+ 10.0.0.1/ 
   + 10.0.0.1-2022.06.01.log
   + [...]
   + 10.0.0.1-2022.07.19.log
+ 10.0.0.2/
   + 10.0.0.2-2022.06.01.log
   + [...]
   + 10.0.0.2-2022.07.19.log
+ [...]

my filebeat config:

```
config:
    modules:
      path: /etc/filebeat/modules.d/*.yml
      reload:
        enabled: false
  inputs:
  - enabled: true
    id: cisco-switch
    paths:
    - /var/log/remotelogs/switches/*/*.log
    tags:
    - cisco-switch
    type: filestream
  - enabled: true
    id: cisco-asa
    paths:
    - /var/log/remotelogs/ASA/*/*.log
    tags:
    - cisco-asa
    type: filestream
logging:
  files:
    keepfiles: 5
    name: filebeat
    path: /var/log/filebeat
    permissions: 48
  level: info
  to_files: true
output:
  logstash:
    hosts:
    - xx.xx.xx.103:5044
path:
  config: /etc/filebeat
  data: /var/lib/filebeat
  home: /usr/share/filebeat
  logs: /var/log/filebeat
processors:
- add_host_metadata:
    when:
      not:
        contains:
          tags: forwarded
- add_cloud_metadata: null
- add_docker_metadata: null
- add_kubernetes_metadata: null
setup:
  kibana: null
  template:
    settings:
      index:
        number_of_shards: 1

```

i have one logfile containing only 1 line

`Aug 5 21:45:42 xxx.xxx.60.9 snmpv3 USM user, persisting snmpEngineBoots. Please Wait...`

This logentry was created befor the clock was syncronised, thats while the date is Aug. 05.

after just 2 hours, i had over 500 entries of this line in elasticsearch of this single line
![elastic](https://user-images.githubusercontent.com/8193408/179749760-eac0ed14-f786-4f68-b7f9-2e9d2c92b027.png)

Same happend with all other logfiles. After just 1 weekend the indices took about 600GB of diskspace while the total size of all logfiles are just about 150 MB.
So filebeat keept sendeing all logfiles from 200+ cisco devices over an over again and i have every logfile line multiple times.

My Logstash config to receive logs from filebeat on the loghost. 
Input
```
input {
  beats {
    port => 5044
  }
} 
```

Cisco switch
```
filter {
	if "cisco-switch" in [tags] and "pre-processed" not in [tags] {
		mutate {
			add_tag => [ "pre-processed", "Switch", "Cisco IOS/NXOS" ]
		}
		
		grok {
			patterns_dir => ["/etc/logstash/patterns/*"]
			match => [
				"message", "%{CISCOTIMESTAMP:received} %{SYSLOGHOST:device} %{CISCOTIMESTAMPTZ1:logtime}: %%{DATA:facility}-%{INT:severity_level}-%{CISCO_REASON:mnemonic}: %{GREEDYDATA:log_message}",
				"message", "%{CISCOTIMESTAMP:received} %{SYSLOGHOST:device} %{CISCOTIMESTAMPTZ2:logtime}: %%{DATA:facility}-%{INT:severity_level}-%{CISCO_REASON:mnemonic}: %{GREEDYDATA:log_message}",
				"message", "%{CISCOTIMESTAMP:received} %{SYSLOGHOST:device} %{TZ:logtime}: %%{DATA:facility}-%{INT:severity_level}-%{CISCO_REASON:mnemonic}: %{GREEDYDATA:log_message}",
				"message", "%{CISCOTIMESTAMP:received} %{SYSLOGHOST:device} %{CISCOTIMESTAMPTZ2:logtime}: %{DATA:facility}: %{GREEDYDATA:log_message}",
				"message", "%{CISCOTIMESTAMP:logtime} %{SYSLOGHOST:device} %%{DATA:facility}-%{INT:severity_level}-%{CISCO_REASON:mnemonic}: %{GREEDYDATA:log_message}",
				"message", "%{CISCOTIMESTAMP:logtime} %{SYSLOGHOST:device} %{GREEDYDATA:log_message}"
			]
		}
		
		syslog_pri { }
		
		date {
			match => [
				"logtime",
 
				# IOS
				"MMM  d YYYY HH:mm:ss.SSS ZZZ",
				"MMM  d YYYY HH:mm:ss ZZZ",
				"MMM  d YYYY HH:mm:ss.SSS",
				"MMM dd YYYY HH:mm:ss.SSS ZZZ",
				"MMM dd YYYY HH:mm:ss ZZZ",
				"MMM dd YYYY HH:mm:ss.SSS",
				 
				# Nexus
				"YYYY MMM  d HH:mm:ss.SSS ZZZ",
				"YYYY MMM  d HH:mm:ss ZZZ",
				"YYYY MMM  d HH:mm:ss.SSS",
				"YYYY MMM dd HH:mm:ss.SSS ZZZ",
				"YYYY MMM dd HH:mm:ss ZZZ",
				"YYYY MMM dd HH:mm:ss.SSS",
				
				# Logdate without year as timestamp
				"MMM dd HH:mm:ss",
				"MMM  d HH:mm:ss",
				 
				# Hail marry
				"ISO8601"
			]
			target => "@timestamp"
		}	
	
	}
} 
```

Cisco ASA
```
filter {
	if "cisco-asa" in [tags] and "pre-processed" not in [tags] {
		mutate {
			add_tag => [ "pre-processed", "ASA" ]
		}
		
		grok {
			patterns_dir => ["/etc/logstash/patterns/*"]
			match => [
				"message", "%{CISCOTIMESTAMP:logtime} %{SYSLOGHOST:device} %%{DATA:facility}-%{INT:severity_level-}-%{CISCO_REASON:mnemonic}: %{GREEDYDATA:log_message}"
			]
		}
		
		syslog_pri { }
		
		grok {
				patterns_dir => ["/etc/logstash/patterns/*"]
				match => [
					"log_message", "%{CISCOFW106001}",
					"log_message", "%{CISCOFW106006_106007_106010}",
					"log_message", "%{CISCOFW106014}",
					"log_message", "%{CISCOFW106015}",
					"log_message", "%{CISCOFW106021}",
					"log_message", "%{CISCOFW106023}",
					"log_message", "%{CISCOFW106100}",
					"log_message", "%{CISCOFW110002}",
					"log_message", "%{CISCOFW302010}",
					"log_message", "%{CISCOFW302013_302014_302015_302016}",
					"log_message", "%{CISCOFW302020_302021}",
					"log_message", "%{CISCOFW305011}",
					"log_message", "%{CISCOFW313001_313004_313008}",
					"log_message", "%{CISCOFW313005}",
					"log_message", "%{CISCOFW402117}",
					"log_message", "%{CISCOFW402119}",
					"log_message", "%{CISCOFW419001}",
					"log_message", "%{CISCOFW419002}",
					"log_message", "%{CISCOFW500004}",
					"log_message", "%{CISCOFW602303_602304}",
					"log_message", "%{CISCOFW710001_710002_710003_710005_710006}",
					"log_message", "%{CISCOFW713172}",
					"log_message", "%{CISCOFW733100}",
					"log_message", "%{WORD:action} %{WORD:protocol} %{CISCO_REASON:reason} from %{DATA:src_interface}:%{IP:src_ip}/%{INT:src_port} to %{DATA:dst_interface}:%{IP:dst_ip}/%{INT:dst_port}; %{GREEDYDATA:dnssec_validation}",
					"log_message", "%{CISCO_ACTION:action} %{WORD:protocol} %{CISCO_REASON:reason}.*(%{IP:src_ip}).*%{IP:dst_ip} on interface %{GREEDYDATA:interface}",
					"log_message", "Connection limit exceeded %{INT:inuse_connections}/%{INT:connection_limit} for input packet from %{IP:src_ip}/%{INT:src_port} to %{IP:dst_ip}/%{INT:dst_port} on interface %{GREEDYDATA:interface}",
					"log_message", "TCP Intercept %{DATA:threat_detection} to %{IP:ext_nat_ip}/%{INT:ext_nat_port}.*(%{IP:int_nat_ip}/%{INT:int_nat_port}).*Average rate of %{INT:syn_avg_rate} SYNs/sec exceeded the threshold of %{INT:syn_threshold}.#%{INT}",
					"log_message", "Embryonic connection limit exceeded %{INT:econns}/%{INT:limit} for %{WORD:direction} packet from %{IP:src_ip}/%{INT:src_port} to %{IP:dst_ip}/%{INT:dst_port} on interface %{GREEDYDATA:interface}"
				]
			}
	
		date {
			match => [
				"logtime",
 
				# IOS
				"MMM dd HH:mm:ss",
				"MMM  d HH:mm:ss",
				"MMM  d YYYY HH:mm:ss.SSS ZZZ",
				"MMM  d YYYY HH:mm:ss ZZZ",
				"MMM  d YYYY HH:mm:ss.SSS",
				"MMM dd YYYY HH:mm:ss.SSS ZZZ",
				"MMM dd YYYY HH:mm:ss ZZZ",
				"MMM dd YYYY HH:mm:ss.SSS",
				 
				# Nexus
				"YYYY MMM  d HH:mm:ss.SSS ZZZ",
				"YYYY MMM  d HH:mm:ss ZZZ",
				"YYYY MMM  d HH:mm:ss.SSS",
				"YYYY MMM dd HH:mm:ss.SSS ZZZ",
				"YYYY MMM dd HH:mm:ss ZZZ",
				"YYYY MMM dd HH:mm:ss.SSS",
				 
				# Hail marry
				"ISO8601"
			]
			target => "@timestamp"
		}	
	
	}
}

```

Output
```
output {
	if "cisco-switch" in [tags] {
		if "_grokparsefailure" in [tags] {
			file {
				path => "/var/log/remotelogs/grokfail/grokfail-logparse.log"
			}
		}
		else {
			elasticsearch {
				hosts => ["https://localhost:9200"]
				index => "cisco-switch-%{+yyyy.MM.dd}"
				user => "elastic"
				password => "*********"
				ssl => true
				ssl_certificate_verification => false
			}
		}
	}
	
	if "cisco-asa" in [tags] {
		elasticsearch {
			hosts => ["https://localhost:9200"]
			index => "cisco-asa-%{+yyyy.MM.dd}"
			user => "elastic"
			password => "*********"
			ssl => true
			ssl_certificate_verification => false
		}
	}
	 
}

```

**Comment by cmacknz** [comment] 2022-07-20 14:19
@MADxHAWK are there filebeat debug logs you can provide?

**Comment by MADxHAWK** [comment] 2022-07-21 11:26
@cmacknz 
not at the moment cause im not in the office again befor Monday Jul 25th.
I will restart filebeat / logstash and see if i can post some debuglogs then. 
Problem is  when i enable debug logging the logfile will grow quite fast to 10MB and will be rotated aprox. every 2 minutes.

**Comment by MADxHAWK** [comment] 2022-07-22 09:28
@cmacknz 

Ok had to go to the office today and started filebeat for a few seconds to get a fresh logfile, (see attachment). 
[filebeat-20220722.log](https://github.com/elastic/beats/files/9166483/filebeat-20220722.log)

I hope it helps. 
Remark: I had to replace the first 2 octets of the ip adresses by xxx and rename the file from .ndjson to .log to attach it

**Comment by cmacknz** [comment] 2022-07-22 18:20
The logs are full of errors indicating there are too many open files, right from when filebeat starts.

```
log.level":"info","@timestamp":"2022-07-22T09:17:13.217Z","log.origin":{"file.name":"cfgfile/reload.go","file.line":164},"message":"Config reloader started","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"info","@timestamp":"2022-07-22T09:17:13.218Z","log.origin":{"file.name":"cfgfile/reload.go","file.line":224},"message":"Loading of config files completed.","service.name":"filebeat","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-07-22T09:17:14.956Z","log.logger":"input.filestream","log.origin":{"file.name":"filestream/input.go","file.line":140},"message":"File could not be opened for reading: failed opening /var/log/remotelogs/switches/xxx.xxx.102.5/xxx.xxx.102.5-2022.07.03.log: open /var/log/remotelogs/switches/xxx.xxx.102.5/xxx.xxx.102.5-2022.07.03.log: too many open files","service.name":"filebeat","id":"cisco-switch","source_file":"filestream::cisco-switch::native::10878996-2050","path":"/var/log/remotelogs/switches/xxx.xxx.102.5/xxx.xxx.102.5-2022.07.03.log","state-id":"native::10878996-2050","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-07-22T09:17:14.956Z","log.logger":"input.filestream","log.origin":{"file.name":"filestream/input.go","file.line":140},"message":"File could not be opened for reading: failed opening /var/log/remotelogs/switches/xxx.xxx.31.5/xxx.xxx.31.5-2022.07.09.log: open /var/log/remotelogs/switches/xxx.xxx.31.5/xxx.xxx.31.5-2022.07.09.log: too many open files","service.name":"filebeat","id":"cisco-switch","source_file":"filestream::cisco-switch::native::10748855-2050","path":"/var/log/remotelogs/switches/xxx.xxx.31.5/xxx.xxx.31.5-2022.07.09.log","state-id":"native::10748855-2050","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-07-22T09:17:14.956Z","log.logger":"input.filestream","log.origin":{"file.name":"filestream/input.go","file.line":140},"message":"File could not be opened for reading: failed opening /var/log/remotelogs/switches/xxx.xxx.79.11/xxx.xxx.79.11-2022.06.28.log: open /var/log/remotelogs/switches/xxx.xxx.79.11/xxx.xxx.79.11-2022.06.28.log: too many open files","service.name":"filebeat","id":"cisco-switch","source_file":"filestream::cisco-switch::native::10748653-2050","path":"/var/log/remotelogs/switches/xxx.xxx.79.11/xxx.xxx.79.11-2022.06.28.log","state-id":"native::10748653-2050","ecs.version":"1.6.0"}
```

This is later followed by errors indicating the registry could not be updated. An educated guess for the reason is that it couldn't open the files because a new file handled couldn't be created due to many being open at once:

```
{"log.level":"error","@timestamp":"2022-07-22T09:18:47.738Z","log.logger":"input","log.origin":{"file.name":"input-logfile/publish.go","file.line":145},"message":"Failed to update state in the registry for 'filestream::cisco-switch::native::10879095-2050'","service.name":"filebeat","input_type":"filestream","ecs.version":"1.6.0"}
{"log.level":"error","@timestamp":"2022-07-22T09:18:47.738Z","log.logger":"input","log.origin":{"file.name":"input-logfile/publish.go","file.line":145},"message":"Failed to update state in the registry for 'filestream::cisco-switch::native::10748849-2050'","service.name":"filebeat","input_type":"filestream","ecs.version":"1.6.0"}
```

The registry failing to update will definitely cause data duplication. I am not convinced this is a problem with filebeat yet, it could be that there are legitimately too many open files (perhaps the log rotation policy for the Cisco devices needs to be improved) or the limit for the number of files that can be opened on the system needs to be increased.

We have some metrics about file handles that are reported in the logs:

```
        "handles": {
          "limit": {
            "hard": 524288,
            "soft": 1024
          },
          "open": 20
        },
        "info": {
          "ephemeral_id": "1e626fcb-06b9-4ec9-8f17-b41815c0f161",
          "uptime": {
            "ms": 121509
          },
          "version": "8.3.2"
        },
        "memstats": {
          "gc_next": 81653320,
          "memory_alloc": 40586808,
          "memory_sys": 8912896,
          "memory_total": 7722200680,
          "rss": 155713536
        },
        "runtime": {
          "goroutines": 57
        }
      },
      "filebeat": {
        "events": {
          "added": 131084,
          "done": 131084
        },
        "harvester": {
          "open_files": 0,
          "running": 0
        }
      },
```

The soft or per process limit on open files is still the default of 1024, you can try increasing that and see if it helps. Curiously filebeat reports no open files from harvesters but that could simply be that it tried and failed to open them at this moment in time.

**Comment by MADxHAWK** [comment] 2022-07-26 12:18
Hello @cmacknz 

well at the moment it seems to run. I have increased the open file limit. 

The problem occured after i wanted to re readin the indices and i have about 400 machines sending logfiles to the logserver and have to store those logs for 90 days. so in a worst case scenario i would have to reindex about 36.000 logfiles. 
When i ran into this problem i tried to re index about 40 days of logfiles from about 200 machines (about 8000 logfiles +/- a few 100) 

So maybe there is a way that filebeat not trying to read all files at once it it harvests a folder structure with lots of files. 
this might take longer but maybe would prevent running in such a problem.

**Comment by cmacknz** [comment] 2022-07-26 12:59
Filestream supports the same [harvester_limit](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html#filebeat-input-log-harvester-limit) config option that the log input does to help with this situation. Apparently this is not in the input documentation though, which I will make a note to fix.

I'm going to close this as it isn't a Filebeat bug and I think there's a work around for your use case in the configuration options. If you want to follow up feel free to continue asking questions on https://discuss.elastic.co/c/elastic-stack/beats/, we try to use the issue tracker only for confirmed bugs.

**Closed by cmacknz** 2022-07-26 12:59 UTC
Labels: bug, Team:Elastic-Agent-Data-Plane

**Comment by MADxHAWK** [comment] 2022-07-27 06:59
@cmacknz 

thank you. 

i have increased the file limit now. 
i also copied all recent logfiles to another location and started filebeat with an empty folder structure. 
Now it seems like filebeatreads every line only once. 

The problem occured as i had to delete the indices in elasticsearch and wanted to read them in again. 
about

**Comment by MADxHAWK** [comment] 2022-08-03 07:57
@cmacknz Im sorry but the problem popped up again and this time its not the filelimit. 
I had no problems for aprox. 7-8 days, untill today. 
What happend seems to be that the log.json exceeded 10mb  (under /var/lib/filebeat/registry/filebeat/) and was overwriten with a new one. At least thats what happening right now after filebeat started again to re-read all logfiles over and over again. 
Fielbeat keeps deleting the log.json when it exceeds 10MB and creates a new on. The xxxxxxx.json keeps rotating too.

i have 400+ Cisco devices that sending logs to the syslogserver and wich are rotated daily. 
I have to keep the Logs for 90 Days so i have 400+ folders each with 91 logfiles at max. 
I can compress files after each day so they wont be recognised by filebeat as files to read in anymore, but that will leave me at least with 400+ logfiles per day. 
If  Filebeat looses its track everytime the registry exceeded 10 mb this will happend quite often.

**Comment by cmacknz** [comment] 2022-08-03 15:21
We have developers assigned to watch the discuss forum, please move the discussion there and someone will help you. You can reference this issue, and if there is a confirmed bug we can reopen it or create a new one.
