### ISSUE TITLE
Output with MaxRetries set to -1 stops receiving events after some number of failures

### ISSUE THREAD

**Issue by jseely** [elastic/beats#6865] opened 2018-04-13 20:43 UTC
I'm working on a custom output for Azure Event Hubs (using the `github.com/Azure/azure-event-hubs-go` client).

In my implementation it doesn't use the `transport.Client` struct as the client is able to renegotiate broken network connections on its own. However when I simulate a broken network connection using `tcpkill` it appears that after the pipeline receives too many errors back from my `outputs.Group` it stops calling `Publish(batch publisher.Batch) error` on the client. In my testing the group was created using `return outputs.Success(1, -1, client)`, so from what I can tell it should retry infinitely.

If anyone has any ideas why it stops sending my output batches I'd really appreciate the help!

For confirmed bugs, please report:
- Version: fork of `origin/master`
- Operating System: Ubuntu 16.04.4 LTS
- Steps to Reproduce: Have output return errors for a few seconds with Retries set to -1 on the Group and the pipeline will stop sending batches to the output.

**Comment by urso** [comment] 2018-04-16 11:58
I wouldn't treat this as a bug, as it's most likely some missing signaling. Without seeing the code I can't really tell what the issue is. You have to call `(publisher.Batch).Retry` to signal the publisher pipeline the batch needs to be retried. Once the batch has been published you have to call `(publisher.Batch).ACK`. These signals tell the queue to free space or adjust the batch TTL counter. Don't hard-code `Retry` to `-1`. Normally it's a setting + some beats always enable infinite retry, no matter the settings. The `error` return from your output does not affect the batch signaling, as a subset of events might be published or not. Internally all signaling and processing is asynchronous.
The error return is used by the publisher pipeline to call Close and Connect on your client.

We mostly use github for bugs and enhancement requests. For developer discussions we also have discuss: https://discuss.elastic.co/c/beats/libbeat
On discuss, some more people might join in as well.

**Comment by jseely** [comment] 2018-04-16 17:26
Thanks @urso. I've opened this https://discuss.elastic.co/t/custom-output-stops-receiving-batches-after-errors/128235 topic and added my `Publish(...)` code if you have a chance to take a look.

**Comment by urso** [comment] 2018-04-16 17:44
Will have a look. Closing this one. Thank you!

**Closed by urso** 2018-04-16 17:44 UTC
