### ISSUE TITLE
Filebeat package path for yum installation is broken

### ISSUE THREAD

**Issue by sourav3690** [elastic/beats#12190] opened 2019-05-15 16:17 UTC
Getting a NOT FOUND error when trying to install Filebeat on my RHEL server using the steps mentioned here: https://www.elastic.co/guide/en/beats/filebeat/current/setup-repositories.html.

Getting NOT FOUND error when trying to access the url (https://artifacts.elastic.co/packages/7.x/yum OR https://artifacts.elastic.co/packages/6.x/yum) directly on a browser or by curl.

Has the package url changed or is it down for some reason?

Please suggest alternate ways to download and install Filebeat on my RHEL server. 

Thanks! 
For confirmed bugs, please report:
- Version: Elastic/Filebeat version 6.x and 7.x
- Operating System: RHEL 6
- Discuss Forum URL:
- Steps to Reproduce:

**Comment by ph** [comment] 2019-05-23 01:28
@mikemadden42 Can you take a look?

**Comment by mikemadden42** [comment] 2019-05-23 01:54
Sure @ph I'll take a look at this issue.

**Comment by mikemadden42** [comment] 2019-05-23 02:29
The following worked fine to install the latest filebeat on a CentOS docker container.  The process should be similar for a RHEL box.

```bash
[root@f1c05ed2a349 ~]# rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch

[root@f1c05ed2a349 ~]# cat > /etc/yum.repos.d/elastic.repo
[elastic-7.x]
name=Elastic repository for 7.x packages
baseurl=https://artifacts.elastic.co/packages/7.x/yum
gpgcheck=1
gpgkey=https://artifacts.elastic.co/GPG-KEY-elasticsearch
enabled=1
autorefresh=1
type=rpm-md

[root@f1c05ed2a349 ~]# yum info filebeat
Loaded plugins: fastestmirror, ovl
Determining fastest mirrors
 * base: mirror.mobap.edu
 * extras: mirror.mobap.edu
 * updates: mirror.mobap.edu
base                                                                                                                                              | 3.6 kB  00:00:00
elastic-7.x                                                                                                                                       | 1.3 kB  00:00:00
extras                                                                                                                                            | 3.4 kB  00:00:00
updates                                                                                                                                           | 3.4 kB  00:00:00
(1/5): base/7/x86_64/group_gz                                                                                                                     | 166 kB  00:00:00
(2/5): extras/7/x86_64/primary_db                                                                                                                 | 201 kB  00:00:00
(3/5): elastic-7.x/primary                                                                                                                        |  19 kB  00:00:00
(4/5): updates/7/x86_64/primary_db                                                                                                                | 5.0 MB  00:00:00
(5/5): base/7/x86_64/primary_db                                                                                                                   | 6.0 MB  00:00:02
elastic-7.x                                                                                                                                                        51/51
Available Packages
Name        : filebeat
Arch        : i686
Version     : 7.1.0
Release     : 1
Size        : 12 M
Repo        : elastic-7.x
Summary     : Filebeat sends log files to Logstash or directly to Elasticsearch.
URL         : https://www.elastic.co/products/beats/filebeat
License     : Elastic-License
Description : Filebeat sends log files to Logstash or directly to Elasticsearch.

Name        : filebeat
Arch        : x86_64
Version     : 7.1.0
Release     : 1
Size        : 13 M
Repo        : elastic-7.x
Summary     : Filebeat sends log files to Logstash or directly to Elasticsearch.
URL         : https://www.elastic.co/products/beats/filebeat
License     : Elastic-License
Description : Filebeat sends log files to Logstash or directly to Elasticsearch.
```

```bash
[root@f1c05ed2a349 ~]# yum install -y filebeat
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile
 * base: mirror.mobap.edu
 * extras: mirror.mobap.edu
 * updates: mirror.mobap.edu
Resolving Dependencies
--> Running transaction check
---> Package filebeat.x86_64 0:7.1.0-1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

=========================================================================================================================================================================
 Package                                 Arch                                  Version                                  Repository                                  Size
=========================================================================================================================================================================
Installing:
 filebeat                                x86_64                                7.1.0-1                                  elastic-7.x                                 13 M

Transaction Summary
=========================================================================================================================================================================
Install  1 Package

Total download size: 13 M
Installed size: 42 M
Downloading packages:
filebeat-7.1.0-x86_64.rpm                                                                                                                         |  13 MB  00:00:02
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : filebeat-7.1.0-1.x86_64                                                                                                                               1/1
  Verifying  : filebeat-7.1.0-1.x86_64                                                                                                                               1/1

Installed:
  filebeat.x86_64 0:7.1.0-1

Complete!

[root@f1c05ed2a349 ~]# rpm -q filebeat
filebeat-7.1.0-1.x86_64
```

I do not believe the yum repository is indexable from a web browser or curl.  I believe this is by design, but I can check with the team that maintains the repo.

I get the following error if I use curl.

```bash
[root@f1c05ed2a349 ~]# curl https://artifacts.elastic.co/packages/7.x/yum

<html>
  <head></head>
  <body>
    <h1>Not Found</h1>
  </body>
</html>
```

**Comment by sourav3690** [comment] 2019-05-23 12:37
I am not sure, however I am still getting an error. I was trying for elastic 6.x.
I did however, install filebeat using the rpm package manager successfully.

**Comment by sourav3690** [comment] 2019-05-23 15:15
I am getting the following error on `sudo yum install filebeat`

`
Setting up Install Process
https://artifacts.elastic.co/packages/6.x/yum/repodata/repomd.xml: [Errno 14] PYCURL ERROR 22 - "HTTP response code said error"
Trying other mirror.
Error: Cannot retrieve repository metadata (repomd.xml) for repository: elastic-6.x. Please verify its path and try again
`

**Comment by mikemadden42** [comment] 2019-05-23 15:44
Can you include how the yum repo is defined?  For example:

```bash
$ cat /etc/yum.repos.d/elastic.repo
```

Can you download the `repomd.xml` file with curl?

```bash
[root@071521fa133d ~]# curl https://artifacts.elastic.co/packages/6.x/yum/repodata/repomd.xml
<?xml version="1.0" encoding="UTF-8"?>
<repomd xmlns="http://linux.duke.edu/metadata/repo" xmlns:rpm="http://linux.duke.edu/metadata/rpm">
 <revision>1558361691</revision>
<data type="filelists">
  <checksum type="sha256">22e63c4a157756f840d28f8c8df494eb89f12c0ee56d89dae01d71f742eebe51</checksum>
  <open-checksum type="sha256">e7e6ae060715b70bafd4bd4f29cb5346cf7690b558b4da4500e12117c095ecf9</open-checksum>
  <location href="repodata/filelists.xml.gz"/>
  <timestamp>1558361771</timestamp>
  <size>12414922</size>
  <open-size>219168239</open-size>
</data>
<data type="other">
  <checksum type="sha256">ad98d32fe3d8a4cd4f51b60aefacc11df86b197ede7cfea904756b2f796517f1</checksum>
  <open-checksum type="sha256">e098a44b6e33c6957cbe77c467dea8e7682220a812fb3e39e057f3d741afc0dc</open-checksum>
  <location href="repodata/other.xml.gz"/>
  <timestamp>1558361771</timestamp>
  <size>21892</size>
  <open-size>84676</open-size>
</data>
<data type="primary">
  <checksum type="sha256">ef186a1ce0681fd472e502e97444cf0fe84b566d595b3bae7362bd44e86c17c9</checksum>
  <open-checksum type="sha256">21012e7a2452d18dd6396ce35e64f9ed97c22c320eae5111e26d747421a4badb</open-checksum>
  <location href="repodata/primary.xml.gz"/>
  <timestamp>1558361771</timestamp>
  <size>189862</size>
  <open-size>1933000</open-size>
</data>
</repomd>
```

**Comment by mikemadden42** [comment] 2019-05-23 15:59
The following command could be useful to find other versions of filebeat.  I have limited the output to the last 20 results, but this would like all 6.x versions of filebeat in the yum repo.

```bash
[root@071521fa133d ~]# yum list available filebeat --showduplicates | tail -20
filebeat.i686                         6.5.2-1                        elastic-6.x
filebeat.x86_64                       6.5.2-1                        elastic-6.x
filebeat.i686                         6.5.3-1                        elastic-6.x
filebeat.x86_64                       6.5.3-1                        elastic-6.x
filebeat.i686                         6.5.4-1                        elastic-6.x
filebeat.x86_64                       6.5.4-1                        elastic-6.x
filebeat.i686                         6.6.0-1                        elastic-6.x
filebeat.x86_64                       6.6.0-1                        elastic-6.x
filebeat.i686                         6.6.1-1                        elastic-6.x
filebeat.x86_64                       6.6.1-1                        elastic-6.x
filebeat.i686                         6.6.2-1                        elastic-6.x
filebeat.x86_64                       6.6.2-1                        elastic-6.x
filebeat.i686                         6.7.0-1                        elastic-6.x
filebeat.x86_64                       6.7.0-1                        elastic-6.x
filebeat.i686                         6.7.1-1                        elastic-6.x
filebeat.x86_64                       6.7.1-1                        elastic-6.x
filebeat.i686                         6.7.2-1                        elastic-6.x
filebeat.x86_64                       6.7.2-1                        elastic-6.x
filebeat.i686                         6.8.0-1                        elastic-6.x
filebeat.x86_64                       6.8.0-1                        elastic-6.x
```

**Comment by sourav3690** [comment] 2019-05-27 11:33
> Can you include how the yum repo is defined? For example:
> 
> ```shell
> $ cat /etc/yum.repos.d/elastic.repo
> ```
> 
> Can you download the `repomd.xml` file with curl?
> 
> ```shell
> [root@071521fa133d ~]# curl https://artifacts.elastic.co/packages/6.x/yum/repodata/repomd.xml
> <?xml version="1.0" encoding="UTF-8"?>
> <repomd xmlns="http://linux.duke.edu/metadata/repo" xmlns:rpm="http://linux.duke.edu/metadata/rpm">
>  <revision>1558361691</revision>
> <data type="filelists">
>   <checksum type="sha256">22e63c4a157756f840d28f8c8df494eb89f12c0ee56d89dae01d71f742eebe51</checksum>
>   <open-checksum type="sha256">e7e6ae060715b70bafd4bd4f29cb5346cf7690b558b4da4500e12117c095ecf9</open-checksum>
>   <location href="repodata/filelists.xml.gz"/>
>   <timestamp>1558361771</timestamp>
>   <size>12414922</size>
>   <open-size>219168239</open-size>
> </data>
> <data type="other">
>   <checksum type="sha256">ad98d32fe3d8a4cd4f51b60aefacc11df86b197ede7cfea904756b2f796517f1</checksum>
>   <open-checksum type="sha256">e098a44b6e33c6957cbe77c467dea8e7682220a812fb3e39e057f3d741afc0dc</open-checksum>
>   <location href="repodata/other.xml.gz"/>
>   <timestamp>1558361771</timestamp>
>   <size>21892</size>
>   <open-size>84676</open-size>
> </data>
> <data type="primary">
>   <checksum type="sha256">ef186a1ce0681fd472e502e97444cf0fe84b566d595b3bae7362bd44e86c17c9</checksum>
>   <open-checksum type="sha256">21012e7a2452d18dd6396ce35e64f9ed97c22c320eae5111e26d747421a4badb</open-checksum>
>   <location href="repodata/primary.xml.gz"/>
>   <timestamp>1558361771</timestamp>
>   <size>189862</size>
>   <open-size>1933000</open-size>
> </data>
> </repomd>
> ```

curl https://artifacts.elastic.co/packages/6.x/yum/repodata/repomd.xml
curl: (7) Failed to connect to 2a04:4e42:2c::734: Network is unreachable

**Comment by dedemorton** [comment] 2019-10-09 23:02
Is this issue still a problem? @mikemadden42 Is there a documentation change required here? If not, please apply a different label so we can get this in the correct work queue. Thanks!

**Comment by mikemadden42** [comment] 2019-10-10 14:02
@sourav3690 It looks like you may not be able to reach `artifacts.elastic.co` from your host.  Can you try the following command to download the latest RPM for 6.8?

> curl -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-6.8.3-x86_64.rpm

@dedemorton I do not believe there is a documentation issue.  I'll change the label to `Filebeat`.

**Comment by Jasstkn** [comment] 2019-12-06 09:10
Any news? I still can't download yum package for filebeat-oss 6.8

**Comment by mikemadden42** [comment] 2019-12-06 14:32
@Jasstkn Can you try directly downloading the RPM?

```bash
$ curl -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-oss-6.8.5-x86_64.rpm
```

The following [page](https://www.elastic.co/guide/en/beats/filebeat/6.8/setup-repositories.html
) references this path for the YUM repo.

`https://artifacts.elastic.co/packages/6.x/yum`

Could you please try this updated URL?

**Comment by Jasstkn** [comment] 2019-12-06 14:59
@mikemadden42 Yes, url was correct, but I missed the right version: 6.8.5 works =) thank you!

**Comment by mikemadden42** [comment] 2019-12-06 15:27
@Jasstkn I'm glad that version `6.8.5` worked.  I'll close this issue.

**Closed by mikemadden42** 2019-12-06 15:27 UTC
Labels: :Packaging, Filebeat
