### ISSUE TITLE
Unable to install lower version agent on 7.13 kibana BC3 Build.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#25523] opened 2021-05-04 11:36 UTC
**Kibana version:**
7.13 BC3 Kibana Cloud QA environment 

**Host OS and Browser version:**
Any[windows/linux/Mac], All

**Preconditions**
1.  7.13 BC3 Kibana Cloud QA environment should be available.
```
BUILD 40647
COMMIT ac09c73a4a7998c770b50d39177c22036ae14375
Artifact page: https://staging.elastic.co/7.13.0-100107e6/summary-7.13.0.html
```
2.  **Few policies should be available on cloud.**
3.  **_7.12.1 agent artifact should be download and extracted at endpoint._**

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. RDP to Endpoint.
3. Now, attempt to install a lower version agent using installation command from Add Agent flyout. 
4. Observe, could not decode raw respose error shows up.

**Actual Result:**
Unable to install 7.12.1 version agent on 7.13 kibana BC3 Build.

**Screenshots:** 
![image](https://user-images.githubusercontent.com/72375798/116997800-e2b13d80-acfa-11eb-90ef-dc5552e74f50.png)

**Comment by dikshachauhan-qasource** [comment] 2021-05-04 11:37
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment] 2021-05-04 11:43
Reviewed & assigned to @EricDavisX

**Comment by blakerouse** [comment] 2021-05-04 11:59
This is expected behavior. A 7.12 Elastic Agent cannot communicate with a 7.13 Kibana, because the entire API that was used to communicate with Kibana was removed from Kibana in 7.13.

For 7.12 to 7.13 this needs to be removed from the test plan. But for 7.13 to 7.14 it should be added back in.

**Closed by blakerouse** 2021-05-04 11:59 UTC
Labels: Team:Agent, bug, impact:high

**Comment by dikshachauhan-qasource** [comment] 2021-05-04 12:06
Hi @blakerouse 

We have few testcases under managed policy with agents having lower version. So we are blocked to verify the functionlity that managed hosts are not upgraded for now and  as per your feedback putting them on hold to be verified in next release.

Thanks for confirming the expected behavior.
