### ISSUE TITLE
Scalability Feature Request: Filebeat refresh Logstash worker connections

### ISSUE THREAD

**Issue by fedwmt** [elastic/beats#1747] opened 2016-05-26 18:40 UTC
We're using Filebeat 1.2.3 with logstash output.  Our logstash host (config value) is actually a load balancer (or DNS) so that we can (in theory) dynamically scale up/down the # of logstash servers without changing the filebeat config.

However, since Filebeat has persistent TCP connections to logstash servers (or in this case, the load balancer or DNS), we must currently restart the Filebeat agent (across the cluster) in order for connections to be properly balanced across the logstash server pool. 

We believe it would be useful to have a feature in Filebeat (for the logstash output, and perhaps other outputs) wherein it could be configured to hold worker connections (to logstash) for up to "N" minutes, then reset the connection.  This would allow the load-balancer (or DNS) to properly re-distribute the connections within the logstash server pool.

A "workaround" would be to periodically restart the Filebeat agent (e.g. via cron), but that's not ideal.

Thanks!

**Comment by geebee** [comment] 2016-06-22 15:09
This looks like a duplicate of #661?

**Closed** 2020-08-08 06:30 UTC
Labels: Stalled, enhancement, libbeat, needs_team
