### ISSUE TITLE
ignoring external input configuration in take_over: true mode

### ISSUE THREAD

**Issue by fixed77** [elastic/beats#40600] opened 2024-08-23 12:24 UTC
filebeat 8.15.0
there is a working filebit with the configuration:

filebeat.yml:
```
#=========================== Filebeat inputs =============================
filebeat.config:
  inputs:
    enabled: true
    path: inputs.d/*.yml
    reload.enabled: false
    reload.period: 60s
    clean_removed: false
    close_removed: false
    clean_renamed: false
    close_renamed: false
    close_timeout: 1h
```

inputs.d/nginx.yml
```
- type: log
  enabled: true
  paths:
    - /var/log/nginx/access.log
```

let's try switching to filestream. change inputs.d/nginx.yml to:
```
- type: filestream
  id: fs-nginx-accesslog
  take_over: true
  enabled: true
  paths:
    - /var/log/nginx/access.log
```
and restart filebeat.
data is duplicated and there is no mention of take_over in the logs.

if all input files move to the main filebeat.yml config, then everything goes well

**Comment by cmacknz** [comment] 2024-09-17 18:39
Duplicate of https://github.com/elastic/beats/issues/36378

**Closed by cmacknz** 2024-09-17 18:39 UTC
Labels: Team:Elastic-Agent-Data-Plane, >bug
