### ISSUE TITLE
[Metricbeat] Kafka Module Fails if no Topics

### ISSUE THREAD

**Issue by gingerwizard** [elastic/beats#7194] opened 2018-05-29 12:24 UTC
Version: 6.2.4
OS: K8 running on GCP

The kafka module appears to fail if no topics are present.  Further analysis is required but an unexpected response causes the following error:

```
2018-04-16T13:33:30.899Z	INFO	kafka/log.go:36	Connected to broker at [[172.17.0.12:9092]] (unregistered)

2018-04-16T13:33:30.904Z	DEBUG	[kafka]	kafka/broker.go:348	Try to match broker to: 172.17.0.12:9092
2018-04-16T13:33:30.904Z	DEBUG	[kafka]	kafka/broker.go:109	found matching broker 172.17.0.12:9092 with id 1
2018-04-16T13:33:30.905Z	INFO	kafka/log.go:36	Closed connection to broker [[172.17.0.12:9092]]

2018-04-16T13:33:39.863Z	INFO	kafka/log.go:36	Failed to connect to broker [[ dial tcp: missing address]]: %!s(MISSING)

2018-04-16T13:33:39.864Z	INFO	kafka/log.go:36	Failed to connect to broker [[ dial tcp: missing address]]: %!s(MISSING)
``` 
Config

```
- module: kafka
                  hosts: "${data.host}:${data.port}"
                  period: 5s
                  metricsets: ["partition","consumergroup"]
```
With no topics, kafka does not appear to return a broker address. Pcaps attached.
[kafka-with-topics.pcap.txt](https://github.com/elastic/beats/files/2048145/kafka-with-topics.pcap.txt)
[kafka-no-topics.pcap.txt](https://github.com/elastic/beats/files/2048146/kafka-no-topics.pcap.txt)

**Comment by jsoriano** [comment] 2018-06-08 12:11
Hi @gingerwizard,
I think the problems you were having with kafka in k8s were also caused by #7193, it should be already fixed in master.
Thanks for investigating and reporting these issues!

**Closed by jsoriano** 2018-06-08 12:11 UTC
Labels: Metricbeat, bug
