### ISSUE TITLE
Logs Data for "elastic_agent" dataset not generated by Agent

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#26518] opened 2021-06-28 10:04 UTC
**Kibana version:** 7.14.0 Snapshot Kibana self-managed environment

**Host OS and Browser version:** All, All

**Build details:**
```
Build: 42089
Commit: 67a71c75d2da40e49fba2620f488c9b4ce2467d2
Artifact Links: 
https://snapshots.elastic.co/7.14.0-15b00b37/downloads/elasticsearch/elasticsearch-7.14.0-SNAPSHOT-windows-x86_64.zip
https://snapshots.elastic.co/7.14.0-15b00b37/downloads/kibana/kibana-7.14.0-SNAPSHOT-windows-x86_64.zip
https://snapshots.elastic.co/7.14.0-15b00b37/downloads/beats/elastic-agent/elastic-agent-7.14.0-SNAPSHOT-windows-x86_64.zip
```

**Preconditions:**
1. 7.14.0 Snapshot Kibana self-managed environment should be available.
2. Elastic Agent must be installed with Default Fleet Server Policy having Fleet Server integration.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Data Streams tab and observe no logs type data for "elastic_agent" dataset.

**Expected Result:**
Logs data for "elastic_agent" dataset should be generated under Data Streams tab. 

**Logs:**
[logs.zip](https://github.com/elastic/beats/files/6725310/logs.zip)

**Screenshot:**
![4](https://user-images.githubusercontent.com/77374876/123618406-cd055380-d825-11eb-8310-34dcbbeab9b0.JPG)

**Comment by amolnater-qasource** [comment] 2021-06-28 10:04
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment] 2021-06-28 11:22
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment] 2021-06-28 14:37
@amolnater-qasource can you attach the policy the Agent was on?  I don't want to make assumptions, please.  It may be the expected result - but maybe not, the policy will help inform.  Thank you.

**Comment by EricDavisX** [comment] 2021-06-28 20:24
I think I have another scenario impacted by the cause of this issue:  deploy an Agent and go to the Fleet 'logs' tab for the Agent and no logs are shown (because elastic_agent dataset is pre-selected, but no logs exist and it cannot then be unselected!).  If you select other datasets and then also select a different time frame (to make the data pull in anew) then it will show some logs - very scary at first.  The Fleet UI is acting up too, but that is follow up separately.

**Comment by EricDavisX** [comment] 2021-06-28 20:52
The above may be the exact cause of this, too - it has additional logs if helpful.
I found this challenging to triage due to a Kibana Fleet side bug, fyi - https://github.com/elastic/kibana/issues/103563 if you're using the UI as you work through this.

**Comment by amolnater-qasource** [comment] 2021-06-29 07:13
Hi @EricDavisX 
>Can you attach the policy the Agent was on? I don't want to make assumptions, please. It may be the expected result - but maybe not, the policy will help inform.

Please find Default Fleet Server Policy attached below:
[elastic-agent.zip](https://github.com/elastic/beats/files/6731252/elastic-agent.zip)

Further, we have revalidated your observations and also found it reproducible on cloud environments.

Build details:
```
Build: 42091
Commit: fe3ea8ed1fc80caa3acd805d24a1e9ea882aa30f
Artifact Link: https://snapshots.elastic.co/7.14.0-b3f1839d/downloads/beats/elastic-agent/elastic-agent-7.14.0-SNAPSHOT-windows-x86_64.zip
```

Please let us know if anything else is required from our end.
Thanks
QAS

**Comment by michalpristas** [comment] 2021-07-01 09:38
did something changed fleet/permissions side?
i'm looking at this locally
we havent changed much recently but what i'm looking at is that agent generates config with correct path and settings, this config is then picked up by monitoring filebeat which processes files and sends events.
dataset is not populated though

when i change dataset from `elastic_agent` to `elastic_agent` and index from `logs-elastic_agent-default` to `logs-elastic_agent.elastic_agent-default` i see events in discovery view, agent logs tab is not populated though

<img width="1341" alt="obrázok" src="https://user-images.githubusercontent.com/1522652/124101578-ca8e3e00-da5f-11eb-95a3-46633acd8e43.png">

when i keep dataset to `elastic_agent` so filtering works inside `Logs` tab in `Agent detail page` and keep `index` modified to `logs-elastic_agent.elastic_agent-default` no events are propagated as in the first place which lets me with an assumption that index permissions were changed. 

cc @ruflin @blakerouse

**Comment by ruflin** [comment] 2021-07-01 11:04
@afgomez Can you chime in here? My guess is that this is related to the permissions in Kibana. It might be that we miss something in the package itself?

**Comment by afgomez** [comment] 2021-07-06 10:05
The permissions generated for the agent are as follows:

```yaml
output_permissions:
  default:
    _elastic_agent_checks:
      cluster:
        - monitor
      indices:
        - names:
            - logs-elastic_agent.*-default
            - metrics-elastic_agent.*-default
          privileges:
            - auto_configure
            - create_doc
```

My guess is that the `.` after `logs-elastic_agent.` should go away. I can open a PR for it

**Comment by michalpristas** [comment] 2021-07-06 10:07
yeah this seems incorrect, please let me know when you have a PR, this will also need to be be backported to 7.14

**Closed** 2021-07-06 13:33 UTC
Labels: Team:Agent, bug, impact:critical

**Comment by michalpristas** [comment] 2021-07-06 13:38
@amolnater-qasource please retest when https://github.com/elastic/kibana/pull/104447 goes in

**Comment by amolnater-qasource** [comment] 2021-07-07 09:15
Hi @michalpristas 
Thanks, we will revalidate this once build with latest merges will be available.

**Comment by amolnater-qasource** [comment] 2021-07-08 07:01
Hi @EricDavisX 
We have revalidated this issue on 7.14.0 Snapshot and found it **fixed**.
- "elastic_agent" dataset are generated for Agent under Data Streams tab and Logs tab

Build details:
```
Build: 42366
Commit: 22dee04008b9936be37225b97a6456e750d559a7
Artifact Link: https://snapshots.elastic.co/7.14.0-ef1f955b/downloads/beats/elastic-agent/elastic-agent-7.14.0-SNAPSHOT-windows-x86_64.zip
```

**Screenshot:**
![11](https://user-images.githubusercontent.com/77374876/124876160-56b3de80-dfe7-11eb-841d-a71a61ef8667.JPG)

Hence we are closing this out.
cc: @michalpristas 
Thanks
QAS
