### ISSUE TITLE
[Agent] Agent starts throwing Docker log error every second (seemingly after Endpoint is started)

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#24610] opened 2021-03-17 18:33 UTC
I had a 7.12 BC4 Agent installed on M1 ARM mac Mini and it is working as expected. At some point it starts logging the below line as an error every second and I'm not 100% sure what triggered it.  Does anyone know what this line relates (besides general Docker usage) which I am not using in this instance.

[agent-docker-events-repeated-every-second.txt](https://github.com/elastic/beats/files/6158788/agent-docker-events-repeated-every-second.txt)

This is using 7.12 BC4 Cloud deploy of stack and 7.12 BC4 macOS artifact to hit the team M1 ARM mac mini for testing.  nothing else seems bad - but this will add the logs for sure, would be nice to avoid.

In reviewing the logs, the error starts sometime shortly afte rEndpoint is turned on in the policy, but perhaps that is just coincidental.

I tried turning off Endpoint in policy and the error logging didn't go away, so perhaps that informs that it isn't related to Endpoint.

**Comment by EricDavisX** [comment] 2021-03-17 20:36
issue came from testing tasks in: https://github.com/elastic/beats/issues/21855

**Comment by EricDavisX** [comment] 2021-05-03 17:38
@dikshachauhan-qasource can you comment on this when you next test macOS ARM 1 on PH's machine please?

**Comment by dikshachauhan-qasource** [comment] 2021-05-04 09:01
Hi @EricDavisX 

We have attempted to install an agent today on mac mini arm 64 machine, however was getting connection timed out error.

![image](https://user-images.githubusercontent.com/72375798/116981520-3c0e7200-ace5-11eb-8bf5-2bc895b92eb4.png)

Could you please check if machine is powered on at our end. After that we can validate above reported issue and confirm on same.

Thanks
QAS

**Comment by michalpristas** [comment] 2021-05-05 07:33
this is probably comming from dynamic inputs. 
we start docker watcher at the start and check for failure, if we encounter error to connect we skip docker watcher but if connection was ok we proceed with setting up watcher. 
this watcher is then generating these event most probably because docker was stopped? 

can you confirm docker was not running at the start of the agent

**Comment by ph** [comment] 2021-05-05 18:24
Seems the macmini is OOO, let me check that.

**Comment by dikshachauhan-qasource** [comment] 2021-05-12 11:34
Hi @EricDavisX 

We have validated this ticket today on cloud-qa build and found it **not reproducible**. Build details are follows:
```
Kibana version: 7.13 BC4
BUILD 40749
COMMIT 5a6bad454ffe263aafed54cbd3f764253694bf37
Artifact link: https://staging.elastic.co/7.13.0-5c4bc719/summary-7.13.0.html
```

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/117968512-e3be1c80-b343-11eb-9023-b6c1fffbe3f6.png)

Please let me know if anything else is required.

Thanks
QAS

**Comment by ph** [comment] 2021-05-12 12:36
Closing this from last comment.

**Closed** 2021-05-12 12:35 UTC
Labels: Team:Agent
