### ISSUE TITLE
Deprecation logs for Beats

### ISSUE THREAD

**Issue by andresrc** [elastic/beats#21591] opened 2020-10-06 18:08 UTC
Elastic Stack products will start to ship deprecation logs to a specific index based on the new indexing strategy. 

We should analyse how to leverage this functionality from beats:
* Directly or via stack monitoring?
* A single stream per beat, one stream for all the beats?

Coordinate with https://github.com/elastic/beats/issues/21336

**Comment by ph** [comment] 2020-10-06 18:46
duplicate of #21592 ?

**Closed by ph** 2020-10-06 18:46 UTC
Labels: Team:Services

**Comment by andresrc** [comment] 2020-10-06 19:41
mmm, I got an error but it seems it was created twice
