### ISSUE TITLE
[Elastic Agent] Agent datastreams are conflicting with Filebeat setup

### ISSUE THREAD

**Issue by mostlyjason** [elastic/beats#19369] opened 2020-06-24 16:22 UTC
While trying to set up filebeat in my 8.0 snapshot cluster and I got this error message. Is it possible filebeat modules are conflicting with agent?

```
jason@jason-VB-Development:~/filebeat-8.0.0-SNAPSHOT-linux-x86_64$ ./filebeat setup
Overwriting ILM policy is disabled. Set `setup.ilm.overwrite:true` for enabling.
Exiting: failed to check for alias 'filebeat-8.0.0': (status=400) {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The provided expression [logs-agent-default] matches a data stream, specify the corresponding concrete indices instead."}],"type":"illegal_argument_exception","reason":"The provided expression [logs-agent-default] matches a data stream, specify the corresponding concrete indices instead."},"status":400}: 400 Bad Request: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The provided expression [logs-agent-default] matches a data stream, specify the corresponding concrete indices instead."}],"type":"illegal_argument_exception","reason":"The provided expression [logs-agent-default] matches a data stream, specify the corresponding concrete indices instead."},"status":400}
```

For confirmed bugs, please report:
- Version: 8.0 snapshot
- Operating System: Ubuntu
- Steps to Reproduce: 
  1. Install Elastic Agent on host, enroll into fleet and run it
  2. Install filebeat 
  3. ./filebeat modules enable system
  4. ./filebeat setup

@EricDavisX is it worth having a test case to make sure that Elastic Agent is compatible with Filebeat running on the same cluster? I imagine a large % of customers use Beats.

**Comment by ruflin** [comment] 2020-06-25 09:51
@michalpristas What I see above in the error comes probably from the agent / Filebeat run through the Agent. Is Agent somehow interferring with other filebeat binaries?

**Comment by ph** [comment] 2020-06-25 19:08
I am confused by this.

@mostlyjason Could you share the YML configuration that you are using for filebeat?

**Comment by mostlyjason** [comment] 2020-06-25 20:01
I'm just using the default filebeat.yml with the cloud.id and and cloud.auth pasted in.  Seems to be reproducable since I tried it with a fresh 8.0 cluster on staging, and a fresh directory for filebeat and elastic agent.

**Comment by michalpristas** [comment] 2020-06-26 08:50
@mostlyjason i'm confused by this as well. are you running agent + filebeat (independent of filebeat included in agent) on the same machine and then try to configure the standalone one?

**Comment by ph** [comment] 2020-06-26 12:52
````
Exiting: failed to check for alias 'filebeat-8.0.0': (status=400) {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The provided expression [logs-agent-default] matches a data stream, specify the corresponding concrete indices instead."}],"type":"illegal_argument_exception","reason":"The provided expression [logs-agent-default] matches a data stream, specify the corresponding concrete indices instead."},"status":400}: 400 Bad Request: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The provided expression [logs-agent-default] matches a data stream, specify the corresponding concrete indices instead."}],"type":"illegal_argument_exception","reason":"The provided expression [logs-agent-default] matches a data stream, specify the corresponding concrete indices instead."},"status":400}
```

So, taking a step back and looking more deeply in the error messages.

1. **Overwriting ILM policy is disabled:** this mean that there is a matching ILM policy on the remote cluster. 
2.  **failed to check for alias 'filebeat-8.0.0**: Filebeat is indeed running into ILM and check that the writing alias filebeat-8.0.0 exists.
3. **logs-agent-default** This is weird, because this new indexing strategy only concern Agent, Filebeat have no knowledge of that concept at all.

I do have a theory, there is a conflict between the ILM policy in ingest manager and the one shipped with Filebeat, what point me to this is the datastream error `logs-agent-default`. 

 I am not sure if this is an error with Agent / Filebeat but instead with how we deal with packages, @michalpristas Can you try to reproduce the above use case?

**Comment by mostlyjason** [comment] 2020-06-26 14:12
Thanks @ph thats a helpful breakdown. @michalpristas yes what you said is correct

**Comment by ph** [comment] 2020-06-26 14:56
@michalpristas Lets try to reproduce on our hand, but I suspect the problem isn't on the agent and the Filebeat side but in EPM.

**Comment by jsoriano** [comment] 2020-07-06 16:50
I have found this issue with Metricbeat too:
```
2020-07-06T18:23:26.628+0200	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(elasticsearch(http://127.0.0.1:9200)): Connection marked as failed because the onConnect callback failed: failed to check for alias 'metricbeat-8.0.0': (status=400) {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The provided expression [logs-agent-default] matches a data stream, specify the corresponding concrete indices instead."}],"type":"illegal_argument_exception","reason":"The provided expression [logs-agent-default] matches a data stream, specify the corresponding concrete indices instead."},"status":400}: 400 Bad Request: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The provided expression [logs-agent-default] matches a data stream, specify the corresponding concrete indices instead."}],"type":"illegal_argument_exception","reason":"The provided expression [logs-agent-default] matches a data stream, specify the corresponding concrete indices instead."},"status":400}
```

Once this error appears Metricbeat stops ingesting, so it could affect working deployments where giving a try to the Agent.

Steps to reproduce:
* Have metribeat running.
* Start ingesting with an agent in the same cluster.
* Restart original metricbeat.

Then original metricbeat cannot ingest anymore. To reproduce this it is not enough with adding a configuration, an agent needs to ingest data.

I can reproduce it with this metricbeat configuration:
```
metricbeat.modules:
- module: zookeeper
  metricsets: [mntr, server, connection]
  hosts:
  - localhost:2181

output.elasticsearch:
  hosts: [127.0.0.1:9200]
  username: elastic
  password: changeme
```
And elastic agent on standalone mode.

**Comment by ph** [comment] 2020-07-06 19:02
@jsoriano I am going to reproduce it thanks for the config.

**Comment by ph** [comment] 2020-07-08 13:30
@jsoriano The error that you see:

```
2020-07-06T18:23:26.628+0200	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(elasticsearch(http://127.0.0.1:9200)): Connection marked as failed because the onConnect callback failed: failed to check for alias 'metricbeat-8.0.0': (status=400) {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The provided expression [logs-agent-default] matches a data stream, specify the corresponding concrete indices instead."}],"type":"illegal_argument_exception","reason":"The provided expression [logs-agent-default] matches a data stream, specify the corresponding concrete indices instead."},"status":400}: 400 Bad Request: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The provided expression [logs-agent-default] matches a data stream, specify the corresponding concrete indices instead."}],"type":"illegal_argument_exception","reason":"The provided expression [logs-agent-default] matches a data stream, specify the corresponding concrete indices instead."},"status":400}
```
This is in the metricbeat log?

**Comment by jsoriano** [comment] 2020-07-08 13:34
Yes, this is in the Metricbeat log.

**Comment by ph** [comment] 2020-07-08 13:37
@jsoriano Just to clarify the steps.

In your reproducable case, did you ever run kibana / ingest manager?

**Comment by jsoriano** [comment] 2020-07-08 14:25
Yes, I run Kibana and ES with the 8.0.0-SNAPSHOTs, and Metricbeat and Agent built from master. Not sure though if I opened the ingest manager UI, I think I didn't do it on my last try with the posted configurations, but I could try again to confirm.

Are you having problems to reproduce this?

**Comment by ph** [comment] 2020-07-14 15:55
Checking with @blakerouse we aren't sure how this is possible yet.

**Comment by michalpristas** [comment] 2020-07-15 08:22
trying to repro filebeat issue from both masters i had no issues 
<img width="606" alt="image" src="https://user-images.githubusercontent.com/1522652/87521703-0086b680-c685-11ea-82f9-58fb5d68a6e2.png">

i will try metricbeat as described above

**Comment by michalpristas** [comment] 2020-07-15 09:35
@jsoriano do you have logs from metricbeat logs from both original metricbeat and one running by agent (in `data/logs/default/metrcibeat`) available.
Not using zookeeper but kibana module but i'm ingesting still

@ph were you able to repro?

**Comment by michalpristas** [comment] 2020-07-15 13:28
assigning me as i'm playing with it

**Comment by ph** [comment] 2020-07-15 13:38
I've haven't been able to reproduce it, looking at the error its maybe a package that we install via EPM. :(

**Comment by jsoriano** [comment] 2020-07-28 10:53
An update of this, I have tried to reproduce it again with master and with 7.x, good news is that with 7.x this issue doesn't happen to me. So maybe this is caused by some breaking change in Beats/ES/Kibana for 8.x and we are good with 7.x, but we should be careful in case we backport what is causing this.

To reproduce this I am using Elasticsearch and Kibana from the scenario in https://github.com/elastic/integrations/tree/master/testing/environments. I don't open Kibana or install any package on any moment.

For master:
* I run the scenario as is in the integrations repository, that starts the stack using 8.0 snapshots.
* I run metricbeat built from master branch.
* I run elastic-agent built from master branch (with `mage package`) and with the reference config file included in the tar.gz.
* After running elastic agent, if I restart metricbeat it cannot ingest anymore, with this error:
```
2020-07-28T11:07:49.883+0200	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(elasticsearch(http://127.0.0.1:9200)): Connection marked as failed because the onConnect callback failed: failed to check for alias 'metricbeat-8.0.0': (status=400) {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The provided expression [logs-elastic.agent-default] matches a data stream, specify the corresponding concrete indices instead."}],"type":"illegal_argument_exception","reason":"The provided expression [logs-elastic.agent-default] matches a data stream, specify the corresponding concrete indices instead."},"status":400}: 400 Bad Request: {"error":{"root_cause":[{"type":"illegal_argument_exception","reason":"The provided expression [logs-elastic.agent-default] matches a data stream, specify the corresponding concrete indices instead."}],"type":"illegal_argument_exception","reason":"The provided expression [logs-elastic.agent-default] matches a data stream, specify the corresponding concrete indices instead."},"status":400}
```

Note: running `PLATFORMS=linux/amd64 mage package` fails for me with current master with the following error, but tar.gz seems to be correctly generated:
```
COPY failed: stat /var/lib/docker/tmp/docker-builder878593990/beat: no such file or directory
...
Error: failed building elastic-agent type=docker for platform=linux/amd64: failed to build docker: running "docker build -t docker.elastic.co/beats/elastic-agent:8.0.0 build/package/elastic-agent/elastic-agent-linux-amd64.docker/docker-build" failed with exit code 1
```

For 7.x:
* I run the scenario as in the integrations repository, but replacing the versions with `7.9.0-SNAPSHOT`.
* I run metricbeat built from 7.x branch.
* I run elastic-agent built from 7.x branch (with `mage package`) and with the reference config file included in the tar.gz.
* Metricbeat has no problem ingesting even after restarting it.

**Comment by michalpristas** [comment] 2020-07-28 12:10
not sure what changed but today i'm hitting some race on ^^^ `beat` build dir. sometimes it gets build completely sometimes partially and sometimes not at all before proceeding to composing docker image.

**Comment by michalpristas** [comment] 2020-07-28 13:05
@jsoriano try latest master for build issue, should be ok now

**Comment by jsoriano** [comment] 2020-07-28 13:34
> @jsoriano try latest master for build issue, should be ok now

It builds now, yes, thanks!

**Comment by ph** [comment] 2020-07-28 13:48
Can we close this?

**Comment by jsoriano** [comment] 2020-07-28 14:03
> Can we close this?

This issue still happens with master, are we ok with this?

It doesn't seem to affect 7.9/beta1, so in any case I think we can remove the `Ingest Management:beta1` label.

**Comment by ruflin** [comment] 2020-07-28 14:36
If it still happens in master, we should keep it open and continue investigating. I would really like to understand why it happens so we can figure out if 7.x is also effected.

**Comment by ph** [comment] 2020-07-28 14:40
Let's keep it open.

I am worried, are we missing a commit in 7.9?

**Comment by jsoriano** [comment] 2020-08-04 13:39
I can confirm that I cannot reproduce this issue anymore with latest 8.0 snapshots. And I agree that elastic/kibana#69061 looks like the same issue. So let's close this one. Thanks for the investigation!

**Closed by jsoriano** 2020-08-04 13:39 UTC
Labels: Ingest Management:beta1, Team:Ingest Management, bug
