### ISSUE TITLE
Fleet: policy aren't assigned to agents (flaky) 

### ISSUE THREAD

**Issue by mtojek** [elastic/beats#27299] opened 2021-08-03 12:08 UTC
Hi Team,

today we discovered problems with assigning policy to an agent, which causes problems with flaky integration tests:

Network Traffic:

https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-1434/8/pipeline/
https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/branches/PR-1434/runs/8/nodes/397/steps/5255/log/?start=0

Kubernetes:

https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/branches/PR-1434/runs/6/nodes/378/steps/5463/log/?start=0
https://beats-ci.elastic.co/blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/integrations/branches/PR-1434/runs/2/nodes/378/steps/5968/log/?start=0

Sample logs (elastic-package waits indefinitely for policy getting assigned):

```
[2021-08-03T09:00:48.187Z] 2021/08/03 09:00:47 DEBUG POST http://127.0.0.1:5601/api/fleet/agent_policies
[2021-08-03T09:00:51.489Z] 2021/08/03 09:00:51 DEBUG adding package data stream to test policy...
[2021-08-03T09:00:51.489Z] 2021/08/03 09:00:51 DEBUG POST http://127.0.0.1:5601/api/fleet/package_policies
[2021-08-03T09:00:54.791Z] 2021/08/03 09:00:54 DEBUG deleting old data in data stream...
[2021-08-03T09:00:54.792Z] 2021/08/03 09:00:54 DEBUG found 0 hits in logs-network_traffic.http-ep data stream
[2021-08-03T09:00:54.792Z] 2021/08/03 09:00:54 DEBUG GET http://127.0.0.1:5601/api/fleet/agent_policies/4b55f5d0-f439-11eb-998a-a3b987ac23b7
[2021-08-03T09:00:54.792Z] 2021/08/03 09:00:54 DEBUG assigning package data stream to agent...
[2021-08-03T09:00:54.792Z] 2021/08/03 09:00:54 DEBUG PUT http://127.0.0.1:5601/api/fleet/agents/02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8/reassign
[2021-08-03T09:00:56.177Z] 2021/08/03 09:00:56 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8
[2021-08-03T09:00:56.177Z] 2021/08/03 09:00:56 DEBUG Wait until the policy (ID: 4b55f5d0-f439-11eb-998a-a3b987ac23b7, revision: 2) is assigned to the agent (ID: 02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8)...
[2021-08-03T09:00:58.092Z] 2021/08/03 09:00:58 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8
[2021-08-03T09:00:58.369Z] 2021/08/03 09:00:58 DEBUG Wait until the policy (ID: 4b55f5d0-f439-11eb-998a-a3b987ac23b7, revision: 2) is assigned to the agent (ID: 02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8)...
[2021-08-03T09:01:00.288Z] 2021/08/03 09:01:00 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8
[2021-08-03T09:01:00.288Z] 2021/08/03 09:01:00 DEBUG Wait until the policy (ID: 4b55f5d0-f439-11eb-998a-a3b987ac23b7, revision: 2) is assigned to the agent (ID: 02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8)...
[2021-08-03T09:01:02.208Z] 2021/08/03 09:01:02 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8
[2021-08-03T09:01:02.208Z] 2021/08/03 09:01:02 DEBUG Wait until the policy (ID: 4b55f5d0-f439-11eb-998a-a3b987ac23b7, revision: 2) is assigned to the agent (ID: 02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8)...
[2021-08-03T09:01:04.752Z] 2021/08/03 09:01:04 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8
[2021-08-03T09:01:04.752Z] 2021/08/03 09:01:04 DEBUG Policy revision assigned to the agent (ID: 02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8)...
[2021-08-03T09:01:04.752Z] 2021/08/03 09:01:04 DEBUG checking for expected data in data stream...
[2021-08-03T09:01:04.752Z] 2021/08/03 09:01:04 DEBUG found 1 hits in logs-network_traffic.http-ep data stream
[2021-08-03T09:01:04.752Z] 2021/08/03 09:01:04 DEBUG reassigning original policy back to agent...
[2021-08-03T09:01:04.752Z] 2021/08/03 09:01:04 DEBUG PUT http://127.0.0.1:5601/api/fleet/agents/02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8/reassign
[2021-08-03T09:01:06.138Z] 2021/08/03 09:01:06 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8
[2021-08-03T09:01:06.474Z] 2021/08/03 09:01:06 DEBUG Wait until the policy (ID: 345eaa90-f437-11eb-998a-a3b987ac23b7, revision: 1) is assigned to the agent (ID: 02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8)...
[2021-08-03T09:01:08.388Z] 2021/08/03 09:01:08 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8
[2021-08-03T09:01:08.388Z] 2021/08/03 09:01:08 DEBUG Wait until the policy (ID: 345eaa90-f437-11eb-998a-a3b987ac23b7, revision: 1) is assigned to the agent (ID: 02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8)...
[2021-08-03T09:01:10.302Z] 2021/08/03 09:01:10 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8
[2021-08-03T09:01:10.302Z] 2021/08/03 09:01:10 DEBUG Wait until the policy (ID: 345eaa90-f437-11eb-998a-a3b987ac23b7, revision: 1) is assigned to the agent (ID: 02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8)...
[2021-08-03T09:01:12.217Z] 2021/08/03 09:01:12 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8
[2021-08-03T09:01:12.217Z] 2021/08/03 09:01:12 DEBUG Wait until the policy (ID: 345eaa90-f437-11eb-998a-a3b987ac23b7, revision: 1) is assigned to the agent (ID: 02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8)...
[2021-08-03T09:01:14.761Z] 2021/08/03 09:01:14 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8
[2021-08-03T09:01:14.762Z] 2021/08/03 09:01:14 DEBUG Wait until the policy (ID: 345eaa90-f437-11eb-998a-a3b987ac23b7, revision: 1) is assigned to the agent (ID: 02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8)...
[2021-08-03T09:01:16.678Z] 2021/08/03 09:01:16 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8
[2021-08-03T09:01:16.678Z] 2021/08/03 09:01:16 DEBUG Wait until the policy (ID: 345eaa90-f437-11eb-998a-a3b987ac23b7, revision: 1) is assigned to the agent (ID: 02c2aaa9-3a9a-4ea8-bf8b-c96dc691b0f8)...
```

Observations:
1. Both integrations, Kubernetes and Network Traffic, are pretty big, have lots of data streams which means lots of tests running. I suspect it's just more probably to cause flakiness there.

**Comment by EricDavisX** [comment] 2021-08-10 17:47
I can comment from the testing side.  It has been the intention to improve the e2e-tests (which are run as part of Beats/Agent CI for each PR) and so should catch issues before merging; but time has not allowed us to get the depth we desire, yet.  

Also, this one seems dependent on 'larger' http transaction sizes, note the tests have basic policy assignment covered.  If we can confirm any details on what is needed to see the bug it would help write a test:
- is it only payloads larger than 1024 bytes?  
- is this something we'd be able to cover in unit tests on Fleet Server (or Beats) repo or do we need the infrastructure and support from the e2e-testing framework to achieve it?

**Comment by ruflin** [comment] 2021-08-10 17:52
If my understanding is correct, it is not about an exact size that it happens. As the defer was called in the wrong place there was only a certain amount of time for the reader to read the body. This also explains the flakyness and it not occuring always in the same place.

I'm not too surprised we didn't catch it with the e2e tests as it is a bit unpredictable. This likely fits more into a load testing environment. Integrations tests uncovered it because of a large amount of changes and larger policies.

**Comment by scunningham** [comment] 2021-08-10 17:53
This is largely a timing issue.  Effectively the agent is incorrectly aborting the HTTP transaction before all the data has arrived.  While it can happen with smaller payloads, a larger payload exacerbates the issue because 1) there are more packets 2) there is extra latency in compressing the payload.  The transaction will complete if all the data is delivered in the window before which the transaction is closed.  Any delay in data delivery will evoke the bug.

In theory you can repro this with a policy containing a ton of integrations as that would be a large payload.

**Comment by EricDavisX** [comment] 2021-08-10 18:31
Thanks Ruflin and Sean.  I will leave the larger 'scale testing' discussion aside, but this is indeed a form of scale problem.  And it seems it is one that can be assessed by the test team (and explicitly automated, even in the e2e-testing framework) if we can identify (more explicitly) how many integrations will trigger it?  Alternatively we can identify the minimum number of integrations we want to say we support as part of a single Agent policy.  Is that number 25, 50, 100, or even more?

**Comment by mtojek** [comment] 2021-08-10 19:21
> I'm not too surprised we didn't catch it with the e2e tests as it is a bit unpredictable. This likely fits more into a load testing environment. Integrations tests uncovered it because of a large amount of changes and larger policies.

I would agree that it should be covered with load testing if it wasn't a single policy (with one integration) triggering this. But I like the idea of a load test that @scunningham mentioned - push as many integrations as possible and meet the limit.

>  And it seems it is one that can be assessed by the test team (and explicitly automated, even in the e2e-testing framework) if we can identify (more explicitly) how many integrations will trigger it? 

To answer this question you can look at latest failed master builds:
https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/master/670/

+kubernetes
+network_traffic

**Comment by ruflin** [comment] 2021-08-11 11:29
PR to get this fixed is open here: https://github.com/elastic/beats/pull/27297

**Comment by EricDavisX** [comment] 2021-08-12 15:54
I see the above PR was backported to 7.14.X - I'm surprised this impacted 7.14 and we didn't know it earlier.  I had thought it was a beyond-7.14 change, but I may have been thinking about a different urgent bug.  If we can figure out how we missed it (collectively) it may be worth a mini postmortem type follow up.

**Comment by scunningham** [comment] 2021-08-12 16:20
The change was added late to address a memory leak that was considered a
blocker.

**Comment by jsoriano** [comment] 2021-08-17 16:58
> PR to get this fixed is open here: #27297

Is this issue fixed?

I see something like this consistently affecting some integrations, see https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/PR-1537/2/pipeline/422 for example. I could also reproduce this locally with the tomcat integration. Not sure if this is still the same issue.

`elastic-package test` fails with:
```
Error: error running package system tests: could not complete test run: could not assign policy to agent: error occurred while waiting for the policy to be assigned to all agents: timeout: policy hasn't been assigned in time
```

Not sure if related, in `elastic-agent` logs I see messages like this one:
```
Could not communicate with fleet-server Checking API will retry, error: fail to decode checkin response: unexpected EOF
```

**Comment by ruflin** [comment] 2021-08-18 07:34
This should have been fixed BUT we had the first successful build since the fix for 7.15.0-SNAPSHOT only yesterday. Could you pull the most recent images and check if you still see it?

**Comment by jsoriano** [comment] 2021-08-18 09:35
> This should have been fixed BUT we had the first successful build since the fix for 7.15.0-SNAPSHOT only yesterday. Could you pull the most recent images and check if you still see it?

Right, integrations builds are back to green with these new snapshots :+1:

**Comment by ruflin** [comment] 2021-08-18 09:47
Great to hear but please keep an eye on it ;-)

**Comment by camazza** [comment] 2021-08-19 09:47
When can we expect an official release containing this fix? 
This has affected our deployment very seriously, we use elastic-agents to collect logs and half of them are offline (or running on old policies) due to this.

**Comment by EricDavisX** [comment] 2021-08-19 13:28
we had some good discussion on how this could be caught in 'soak' test from the Agent side in e2e-testing repo. Ticket logged to track:  https://github.com/elastic/e2e-testing/issues/1468

@camazza the fixes are merged and backported to 7.14.x and 7.15 lines, I can't speak to when they will be available, but the .x patch release are intended to be fairly quickly released (a matter of weeks between them?)

**Comment by blakerouse** [comment] 2021-08-25 13:44
Being that this is fixed, and an issue was filed for the soak testing, I am going to closing this.

**Comment by mtojek** [comment] 2022-05-04 13:30
Folks, this issue hasn't been fixed yet.

Here is a sample from our CI using 7.17.0 (network_traffic):

```
[2022-05-04T10:20:41.696Z] 2022/05/04 10:20:41 DEBUG Agent data: {"id":"dfbc47ed-37ad-4b5c-9b80-40fa4c364a89","policy_id":"2016d7cc-135e-5583-9758-3ba01f5a06e5","local_metadata":{"host":{"name":"docker-fleet-agent"}}}
[2022-05-04T10:20:41.696Z] 2022/05/04 10:20:41 DEBUG Wait until the policy (ID: 2016d7cc-135e-5583-9758-3ba01f5a06e5, revision: 1) is assigned to the agent (ID: dfbc47ed-37ad-4b5c-9b80-40fa4c364a89)...
[2022-05-04T10:20:43.604Z] 2022/05/04 10:20:43 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/dfbc47ed-37ad-4b5c-9b80-40fa4c364a89
[2022-05-04T10:20:43.604Z] 2022/05/04 10:20:43 DEBUG Agent data: {"id":"dfbc47ed-37ad-4b5c-9b80-40fa4c364a89","policy_id":"2016d7cc-135e-5583-9758-3ba01f5a06e5","local_metadata":{"host":{"name":"docker-fleet-agent"}}}
[2022-05-04T10:20:43.604Z] 2022/05/04 10:20:43 DEBUG Wait until the policy (ID: 2016d7cc-135e-5583-9758-3ba01f5a06e5, revision: 1) is assigned to the agent (ID: dfbc47ed-37ad-4b5c-9b80-40fa4c364a89)...
[2022-05-04T10:20:45.507Z] 2022/05/04 10:20:45 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/dfbc47ed-37ad-4b5c-9b80-40fa4c364a89
[2022-05-04T10:20:45.507Z] 2022/05/04 10:20:45 DEBUG Agent data: {"id":"dfbc47ed-37ad-4b5c-9b80-40fa4c364a89","policy_id":"2016d7cc-135e-5583-9758-3ba01f5a06e5","local_metadata":{"host":{"name":"docker-fleet-agent"}}}
[2022-05-04T10:20:45.507Z] 2022/05/04 10:20:45 DEBUG Wait until the policy (ID: 2016d7cc-135e-5583-9758-3ba01f5a06e5, revision: 1) is assigned to the agent (ID: dfbc47ed-37ad-4b5c-9b80-40fa4c364a89)...
[2022-05-04T10:20:47.412Z] 2022/05/04 10:20:47 DEBUG GET http://127.0.0.1:5601/api/fleet/agents/dfbc47ed-37ad-4b5c-9b80-40fa4c364a89
[2022-05-04T10:20:47.412Z] 2022/05/04 10:20:47 DEBUG Agent data: {"id":"dfbc47ed-37ad-4b5c-9b80-40fa4c364a89","policy_id":"2016d7cc-135e-5583-9758-3ba01f5a06e5","local_metadata":{"host":{"name":"docker-fleet-agent"}}}
[2022-05-04T10:20:47.412Z] 2022/05/04 10:20:47 DEBUG Wait until the policy (ID: 2016d7cc-135e-5583-9758-3ba01f5a06e5, revision: 1) is assigned to the agent (ID: dfbc47ed-37ad-4b5c-9b80-40fa4c364a89)...
[2022-05-04T10:20:49.316Z] Error: error running package system tests: could not complete test run: could not assign policy to agent: error occurred while waiting for the policy to be assigned to all agents: timeout: policy hasn't been assigned in time
```

[job](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fintegrations/detail/main/570/pipeline)

Let me know what do you need for debugging.

**Comment by mtojek** [comment] 2022-05-04 13:31
@jlind23 I guess that this should land in the agent's queue "to investigate".

**Closed** 2023-11-01 11:55 UTC
Labels: Stalled, Team:Elastic-Agent-Control-Plane
