### ISSUE TITLE
[Functionbeat] Allow to automatically subscribe to new cloudwatch/sqs/kinesis trigger.

### ISSUE THREAD

**Issue by ph** [elastic/beats#10756] opened 2019-02-14 13:48 UTC
**The description below is relevent for SQS, Kinesis and cloudwatch log group.**

The current workflow of Functionbeat requires you to know beforehand the name of the cloudwatch log group, you cannot register a wildcard. This cause problem when you have a really large number of log groups or you are creating them and removing dynamically. 

We should add an `autodiscover` mode to Functionbeat that will allow you to listen from events coming from your AWS infrastructure to automatically subscribe new log group to your Functionbeat lambda.

**Comment by ph** [comment] 2019-02-18 14:00
@kvch This is really an interesting feature that might interest you, I am not sure of the implementation yet, I presume that the permissions will be hardest part here.

**Comment by tfendt** [comment] 2019-02-21 02:48
+1 on this. Please allow a wild card options for log_group_name. We have 1000+ log groups in one environment. They get added automatically (and removed) when a new serverless service is created and deployed which in our dev environment happens frequently.

**Comment by spectorar** [comment] 2019-04-18 22:24
+1 to the wildcard solution. One thing I dislike about AWS's Cloudwatch -> Elasticsearch Service feature is that it has to be configured per log group. As others have said, there could be a lot of log groups. Allowing wildcards/prefixes in the config for FunctionBeat would greatly simplify this.

**Comment by phillpafford** [comment] 2019-06-06 16:30
+1 for wildcard

**Comment by jasonslater2000** [comment] 2019-07-22 17:59
+1 on this as well, without wildcard/autodiscover, configuration would be untenable

**Comment by jderose9** [comment] 2019-08-12 15:56
I'm struggling to see how functionbeat can be useful at scale without this feature.

**Comment by johnnydimas** [comment] 2019-11-13 20:39
This is a must-have!

**Comment by alphachai** [comment] 2019-12-11 19:24
We were planning to use functionbeat, but without this option, I'm not sure how it's even possible at scale.

**Comment by cluggas** [comment] 2020-04-16 14:01
Rather than wildcard the log groups, would you consider removing the need for the `triggers` section in the `functionbeat.yml` file entirely? 

AWS treats the Log Group Subscription and the Subscription Target as different resources, and only couples them in one direction allowing Subscriptions to scale up independently of Targets. By requiring the `triggers` list in `functionbeat.yml` the coupling goes in the other direction from Target to Subscription, which makes for an inflexible and unscalable architecture.

Could `triggers` be made optional? I realise it is required if you are using the Manager to deploy the Log Group Subscriptions. But anyone using this at scale probably won't be using Manager.

**Comment by kvch** [comment] 2020-04-22 15:27
@cluggas You raise a valid point. Could you please open a separate issue for your request?

**Comment by kaykhancheckpoint** [comment] 2020-08-07 08:27
Did anything come of this? has anyone found an alternative solution to deal with auto discovering cloud watch log groups?

**Comment by greendad** [comment] 2020-08-07 09:21
@kaykhancheckpoint One way would be standardising all the log groups that I am interested in with the same prefix in name and I am injecting the log groups dynamically into functionbeat configuration when deploying it. So when a new log group is added, I would just trigger the functionbeat deployment again(through a trigger) automatically. I am not sure if it exactly fits your use case. I haven't implemented the trigger yet FYI.

**Comment by swiftmas** [comment] 2020-09-09 23:37
We  have been looking at a solution that would be functional with @cluggas suggestion. 

If Functionbeat did not require a triggers list and instead dealt with any triggers assigned to the lambda you could create hooks in your service deployments which attach their log groups to functionbeat. Permissions are the only thing in the configuration that can take a wild card so they can be grouped by naming convention.

**Comment by Nighthawk14** [comment] 2021-03-25 14:50
We've encountered the same issue as do not use the functionbeat manager and we would prefer to have the `triggers` object as optional because all our log groups subscriptions are managed via our IaC tool (Terraform).

As a workaround we've changed the log group subscriptions to point to Kinesis (Log Group Subscription > Kinesis Data Stream > Functionbeat Lambda). The `triggers` object is still mandatory but at least it is reduced to a single line (the Kinesis stream ARN) and the lambda trigger from Kinesis can be managed via Terraform.

**Comment by Pidz-b** [comment] 2021-03-30 10:42
Any progress, we'd love to use this beat in our microservice architecture, but the way it works currently is very hour intensive...

**Comment by malachantrio** [comment] 2021-04-16 09:44
Without this feature functionbeat is so unwieldy. Its kinda crazy it was designed so that you have to explicitly name every function and log group you want to ship in one monolithic config file.

For us this basically means that every new service has a lengthy back and forth between devs and the platform team trying to get the config right on both ends so that functionbeat actually ships the logs

**Comment by malachantrio** [comment] 2021-04-16 09:47
>  Has anyone found an alternative solution to deal with auto discovering cloud watch log groups,. whilst we wait for an official solution ?

Unfortunately not, it seems that while you can fool the serverless deploy into wildcarding the invoke permissions on the functionbeat lambda itself, functionbeat still seems to double check a log event (that AWS has already allowed through to the functionbeat lambda) comes from a source that is explicitly mentioned in the functionbeat config yml file. We thought we had it cracked and we could get apps to self register, but it's looking like actually functionbeat has foiled us yet again :(

**Comment by tehmaspc** [comment] 2021-05-28 16:04
@Nighthawk14 

> We've encountered the same issue as do not use the functionbeat manager and we would prefer to have the `triggers` object as optional because all our log groups subscriptions are managed via our IaC tool (Terraform).
> 
> As a workaround we've changed the log group subscriptions to point to Kinesis (Log Group Subscription > Kinesis Data Stream > Functionbeat Lambda). The `triggers` object is still mandatory but at least it is reduced to a single line (the Kinesis stream ARN) and the lambda trigger from Kinesis can be managed via Terraform.

This is the model I want to enhance my Fnb deployment model to since we've used this before w/ other tools (e.g. CW Logs->Kinesis (via Subscription filter)->AWS ES)

But how are you doing it w/ Fnb to then ensure that CW Logs that can represent diff services send their data to Kinesis which Fnb monitors and then ensure that Fnb sends to ES into the proper index? Are you doing any ETL'ing w/i Fnb, using Ingest Pipelines on the ES side? Curious as to your approach. Thanks!

**Comment by Nighthawk14** [comment] 2021-06-08 08:47
@tehmaspc  We don't do any specifig ETL on the data and we don't have any Ingest pipeline on the ES side. 
The only thing we have is in `functionbeat.yml` configuration file  we add this:
```
processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
```
  Which will add the log-stream name into your ES document giving you the exact service (assuming each of your services write CW log in a separate log-stream inside the same log-group).
So in ES we get the log-group value being the name of our service, and the log-stream value being the ID of the specific service instance.

**Comment by kumarnarendra701** [comment] 2021-08-03 19:06
Any progress on auto-discover or add multiple log-group?

**Comment by BaronWhite** [comment] 2021-08-25 15:28
+1

**Comment by eyearian-oak9** [comment] 2021-10-07 17:12
+1

**Comment by shaundclements** [comment] 2022-03-31 05:49
would it be possible to pass in an override of the functionbeat.yml file i.e.
when performing the export function include an array of identified lambdas as a parameter
-E "functionbeat.provider.aws.functions.triggers=...

**Comment by KeyanatGiggso** [comment] 2022-04-29 02:05
> elastic-serverless-forwarder
Hey @ravikesarwani, Got the Blog, Want to know about the Logstash Compatibility and the custom processors like in the other beats, Can you brief about it ?

**Comment by kaykhan** [comment] 2022-08-23 15:53
I saw this issue a while back and continued with just manually adding lambda function triggers manually. But occured recently.
when you start to list a lot of lambda function 40+

```
The final policy size (20576) is bigger than the limit (20480). (Service: AWSLambdaInternal; Status Code: 400; Error Code: PolicyLengthExceededException; Request ID: 4815dab8-f579-439b-977a-dd71810d168a; Proxy: null)
```

**Comment by tehmaspc** [comment] 2022-08-23 16:36
> I saw this issue a while back and continued with just manually adding lambda function triggers manually. But we ran into an issue recently which seems inevitable. when you start to list a lot of lambda function 40+ you will come across this error
> 
> ```
> The final policy size (20576) is bigger than the limit (20480). (Service: AWSLambdaInternal; Status Code: 400; Error Code: PolicyLengthExceededException; Request ID: 4815dab8-f579-439b-977a-dd71810d168a; Proxy: null)
> ```
> 
> The functionbeat lambda function creates a bunch of permissions one for each lambda you declare and is then blockd by the maximum policy size that aws has a hard limit on.
> 
> Ultimately it means now we can't log any new lambda functions.

Yes - you will hit this limit if you have too many triggers within each Lambda (or Functionbeat) configuration.
What I ultimately did is define some logical grouping of Functionbeats and documented the limits or number of triggers we put into any individual Functionbeat - that way we can group as many triggers into a single FnB but try not to have too many FnBs to reduce management and IP address exhaustion (since all our Functionbeats deliver data to an onprem Elasticsearch cluster).

**Comment by kaykhan** [comment] 2022-08-23 16:39
@tehmaspc Yes, so you are deploying multiple functionbeat cloudwatgch lambda functions. it's one solution, but it is not elegant.

**Comment by kaykhan** [comment] 2022-08-23 16:55
@tehmaspc Im curious if you have thought about using kinesis stream instead. For each lambda function you declare it produces a log group and in a the log group you can set a log subscription and point to a kinesis data stream.

**Comment by tehmaspc** [comment] 2022-08-27 21:56
Hey @kaykhan - I haven't used Kinesis Stream w/ Filebeat but prior to going the Filebeat route we were successfully using Kinesis Firehose to collect data from all the AWS CW Log Groups we were interested in and sending that log data to the data sinks that Kinesis Firehose supported. At that time we were using AWS' ES service (now OpenSearch) and it worked great. Our business simply wanted to move log data in-house. If you can go the AWS CW Log Group->Firehose->{Splunk, OpenSearch, etc} route I'd recommend it - it works well. The only complication is figuring out how to properly store the data to your sink - e.g. - if you send it from Firehose to OpenSearch - you may not want all your data coming from CW Logs to all go into one index - so you need to figure out how to split out the data - either upstream via more Firehose infra or downstream at the OpenSearch layer across multiple index families/etc.

In addition, when we used Firehose to deliver all this data to our AWS ES infrastructure - we set up the subscription filter per log group via Terraform to the proper environment specific Kinesis Firehose stream during application stack deployment (within our deployment pipelines).

HTH!

Cheers,
Tehmasp

**Comment by ravikesarwani** [comment] 2022-08-29 00:13
@KeyanatGiggso Sorry I missed the earlier question from you.
[Elastic Serverless Forwarder ](https://github.com/elastic/elastic-serverless-forwarder/blob/main/docs/README-AWS.md)supports both Elastic cloud and self-managed Elastic deployments.
Logstash output is not supported as of right now, but it's in the roadmap.
Common pre-processing functions like [Include/Exclude filters](https://github.com/elastic/elastic-serverless-forwarder/blob/main/docs/README-AWS.md#defining-includeexclude-filters), [tags](https://github.com/elastic/elastic-serverless-forwarder/blob/main/docs/README-AWS.md#using-tags), [json content discovery](https://github.com/elastic/elastic-serverless-forwarder/blob/main/docs/README-AWS.md#json-content-discovery), and [multiline processing](https://github.com/elastic/elastic-serverless-forwarder/blob/main/docs/README-AWS.md#manage-multiline-messages) are already supported by Elastic Serverless forwarder. Other custom transformation tasks can be implemented using Elasticsearch [ingest pipelines](https://www.elastic.co/guide/en/elasticsearch/reference/current/ingest.html).

Like to understand your use case in details so that we can help you utilize Elastic serverless forwarder.

**Comment by Barhuumi** [comment] 2022-09-05 21:55
The auto subscription can be handled by yourself pretty easily. I'd also recommend Kinesis or SQS as your integration point rather than going direct to the lambda as it provides better for control for the number of concurrent lambdas we spin up.

You can consume an event from Cloudtrail every time a new cloudwatch log group is created, and have your event handler set a subscription filter pointing to your stream. (I guess you could so the same if you opt for the lambda route and set your lambda as the target in the subscription filter).
 
 The below blog post shares the concept and has examples.
 
 https://theburningmonk.com/2017/08/centralised-logging-for-aws-lambda/
 https://theburningmonk.com/2018/07/centralised-logging-for-aws-lambda-revised-2018/

**Comment by Barhuumi** [comment] 2022-09-06 08:26
You can auto discover and subscribe newly created log groups easily enough. You can consume a Cloudtrail event upon a new log group being created, and invoke a lambda that will set a subscription filter on the new log group to your target (lambda/kinesis/sqs).

This blog shared that concept and documents the steps:
https://theburningmonk.com/2017/08/centralised-logging-for-aws-lambda/
https://theburningmonk.com/2018/07/centralised-logging-for-aws-lambda-revised-2018/

**Closed** 2024-03-04 09:46 UTC
Labels: enhancement, Functionbeat, Team:Integrations, [zube]: Investigate, Stalled
