### ISSUE TITLE
Recursive file paths in Auditbeat

### ISSUE THREAD

**Issue by xlammertink** [elastic/beats#5266] opened 2017-09-28 19:20 UTC
Hi everyone,

I was testing out Auditbeats and I have to say that I really like the product. However, there is one major feature that I'm missing: recursive file paths.

I would like to use Auditbeat to track all file changes on a directory, and that includes the changes in sub-directories as well. I definitively think that I'm not the only one, so I would like to have this feature implemented.

The way I see it it would work like this:
- One could set the file.paths.include parameters to monitor a path including its sub-directories
- And to exlude certain subdirectories one could set the file.paths.exclude parameter

I have placed a discussion here already: https://discuss.elastic.co/t/recursive-file-paths/101155.

**Comment by jakommo** [comment] 2017-12-11 10:42
I think this issue is a duplicate of https://github.com/elastic/beats/issues/5421. You opened this first but https://github.com/elastic/beats/issues/5421 has more details. 
Are you ok with closing this and sticking to https://github.com/elastic/beats/issues/5421 ?

**Closed** 2017-12-13 16:37 UTC
Labels: Auditbeat, enhancement
