### ISSUE TITLE
[Metricbeat] Elasticsearch Module settings should document TLS / SSL support

### ISSUE THREAD

**Issue by pickypg** [elastic/beats#5827] opened 2017-12-06 17:22 UTC
The Elasticsearch Metricbeat module supports TLS / SSL, you can apparently specifiy the same settings as the Elasticsearch output (but under the module's configuration).

From @andrewkroh:

> Pretty much any of the modules that are HTTP based all share the same code and all support the same SSL options.

We should probably make a common set of TLS / SSL options that documentation can inherit / insert into their pages so that we don't have to repeat this everywhere.

**Comment by exekias** [comment] 2017-12-07 12:21
I think this is a duplicate of https://github.com/elastic/beats/issues/4268?

**Closed** 2017-12-11 23:04 UTC
Labels: docs, Metricbeat
