### ISSUE TITLE
Elastic Agent is enrolled successfully, then stopped - when enrolled again and started it throws repeated error

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#18625] opened 2020-05-18 21:46 UTC
seeing an odd error in Agent logs:
ERROR	fleet_gateway.go:163	failed to dispatch actions, error: acknowledge 506

- Version:  7.8 BC2
- Operating System: Centos7 
- Discuss Forum URL: n/a - since its a new alpha feature I didn't run it thru discuss forum
- Steps to Reproduce: 
- set up 7.8 ES / Kibana / Ingest with required xpack start up keys.
- deploy the agent on host with Fleet and default config / datasources as:
./elastic-agent enroll https://8b1de8db819f4d14a62539b65b539e6b.us-central1.gcp.foundit.no:443 MFkwVEdYSUJpc3BtMEwxcGh4dTY6dS1tRExVQU9ReVNkQnd4V21sYzlwQQ==

- see Agent generally work in Kibana, it says enrolled, is 'online'
- set up a different config, with new datasource change Agent to this new config, seems to work
- then unenroll Agent from the UI.  This seems to work, but I'm unclear on expectations... the Agent continues to run, and starts throwing a connection error, so the Kibana side work seems correctly revoking.
- so I stop the process, to avoid error messages and memory / cpu processing.
- when I decide to run it again I re-enroll it, with the original string (the only one I got from the UI, and the 'up' arrow to re-use it made side, because I unenrolled from UI.
- when I run it again it seems to work but throws errors in console.  
- and a ps -ef | grep agent
... reveals not 1 pair (metric + filebeat) but 2 pairs running / trying which may be the problem.

initial log snippet:
2020-05-18T19:08:12Z DEBUG  fleet_gateway.go:166    FleetGateway is sleeping, next update in 30s
2020-05-18T19:08:45Z DEBUG  fleet_gateway.go:146    FleetGateway calling Checkin API
2020-05-18T19:08:45Z DEBUG  client.go:170   Request method: POST, path: /api/ingest_manager/fleet/agents/9105b785-a4ae-4084-8e3c-16ce71995ad0/checkin
{"action":"checkin","success":true,"actions":[{"agent_id":"9105b785-a4ae-4084-8e3c-16ce71995ad0","type":"CONFIG_CHANGE","data":{"config":{"id":"80293790-96c5-11ea-b1f8-bb8f587997c0","outputs":{"default":{"type":"elasticsearch","hosts":...

full repeated error log is attached
[error-log-from-host-from-agent.txt](https://github.com/elastic/beats/files/4646990/error-log-from-host-from-agent.txt)

ps -ef | grep agent reveals:
[root@mainqa-atlcolo-10-0-7-247 ~]# ps -ef | grep agent
root      5078 62168 50 21:43 pts/0    00:00:08 ./elastic-agent run
root      5089  5078  0 21:43 pts/0    00:00:00 /home/endgame/elastic-agent-7.8.0-linux-x86_64/data/install/filebeat-7.8.0-linux-x86_64/filebeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.mode=x-pack-fleet -E management.enabled=true -E logging.level=debug -E logging.level=debug -E http.enabled=true -E http.host=unix:///tmp/elastic-agen/default/filebeat/filebeat.sock -E logging.files.path=/home/endgame/elastic-agent-7.8.0-linux-x86_64/data/logs/default -E logging.files.name=filebeat -E logging.files.keepfiles=7 -E logging.files.permission=0644 -E logging.files.interval=1h -E path.data=/home/endgame/elastic-agent-7.8.0-linux-x86_64/data/run/default/filebeat--7.8.0
root      5115  5078  7 21:43 pts/0    00:00:00 /home/endgame/elastic-agent-7.8.0-linux-x86_64/data/install/metricbeat-7.8.0-linux-x86_64/metricbeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.mode=x-pack-fleet -E management.enabled=true -E logging.level=debug -E logging.level=debug -E http.enabled=true -E http.host=unix:///tmp/elastic-agent/default/metricbeat/metricbeat.sock -E logging.files.path=/home/endgame/elastic-agent-7.8.0-linux-x86_64/data/logs/default -E logging.files.name=metricbeat -E logging.files.keepfiles=7 -E logging.files.permission=0644 -E logging.files.interval=1h -E path.data=/home/endgame/elastic-agent-7.8.0-linux-x86_64/data/run/default/metricbeat--7.8.0
root      5139  5078 34 21:43 pts/0    00:00:02 /home/endgame/elastic-agent-7.8.0-linux-x86_64/data/install/filebeat-7.8.0-linux-x86_64/filebeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.mode=x-pack-fleet -E management.enabled=true -E logging.level=debug -E logging.level=debug -E http.enabled=true -E http.host=unix:///tmp/elastic-agen/default/filebeat/filebeat.sock -E logging.files.path=/home/endgame/elastic-agent-7.8.0-linux-x86_64/data/logs/default -E logging.files.name=filebeat -E logging.files.keepfiles=7 -E logging.files.permission=0644 -E logging.files.interval=1h -E path.data=/home/endgame/elastic-agent-7.8.0-linux-x86_64/data/run/default/filebeat--7.8.0--3664363137303562373336393634363536333631373233613734373237353635356465336230633434323938666331633134396166626634633839393666623932343237616534316534363439623933346361343935393931623738353262383535
root      5168  5078  8 21:44 pts/0    00:00:00 /home/endgame/elastic-agent-7.8.0-linux-x86_64/data/install/metricbeat-7.8.0-linux-x86_64/metricbeat -E setup.ilm.enabled=false -E setup.template.enabled=false -E management.mode=x-pack-fleet -E management.enabled=true -E logging.level=debug -E logging.level=debug -E http.enabled=true -E http.host=unix:///tmp/elastic-agent/default/metricbeat/metricbeat.sock -E logging.files.path=/home/endgame/elastic-agent-7.8.0-linux-x86_64/data/logs/default -E logging.files.name=metricbeat -E logging.files.keepfiles=7 -E logging.files.permission=0644 -E logging.files.interval=1h -E path.data=/home/endgame/elastic-agent-7.8.0-linux-x86_64/data/run/default/metricbeat--7.8.0--3664363137303562373336393634363536333631373233613734373237353635356465336230633434323938666331633134396166626634633839393666623932343237616534316534363439623933346361343935393931623738353262383535
root      5187 63530  0 21:44 pts/1    00:00:00 grep --color=auto agent

**Comment by ph** [comment] 2020-05-19 12:23
@michalpristas Could you take a look?

**Comment by michalpristas** [comment] 2020-05-19 12:26
@EricDavisX jsut a sanity check, did you run agent before enrolling it? 
like enroll, run, enroll, run?

**Comment by michalpristas** [comment] 2020-05-19 12:57
duplicate of https://github.com/elastic/beats/issues/17389

**Closed by michalpristas** 2020-05-19 12:57 UTC
Labels: Team:Ingest Management, bug
