### ISSUE TITLE
packetbeat-devices

### ISSUE THREAD

**Issue by internaute** [elastic/beats#2179] opened 2016-08-05 12:44 UTC
Hello everyone

Could you help me please 

when I enter this commant 
**packetbeat -devices**   I get the following lines:

 runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x717409]

goroutine 1 [running]:
github.com/elastic/beats/vendor/github.com/tsg/gopacket/pcap.sockaddr_to_IP(0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/elastic/beats/vendor/github.com/tsg/gopacket/pcap/pcap.go:557 +0x49
github.com/elastic/beats/vendor/github.com/tsg/gopacket/pcap.findalladdresses(0x244b6e0, 0xc82126fce0, 0x0, 0x1)
	/go/src/github.com/elastic/beats/vendor/github.com/tsg/gopacket/pcap/pcap.go:543 +0xe1
github.com/elastic/beats/vendor/github.com/tsg/gopacket/pcap.FindAllDevs(0xc820126120, 0x5, 0x5, 0x0, 0x0)
	/go/src/github.com/elastic/beats/vendor/github.com/tsg/gopacket/pcap/pcap.go:529 +0x35d
github.com/elastic/beats/packetbeat/sniffer.ListDeviceNames(0xc820000301, 0x0, 0x0, 0x0, 0x0, 0x0)
	/go/src/github.com/elastic/beats/packetbeat/sniffer/sniffer.go:74 +0x75
github.com/elastic/beats/packetbeat/beat.(*Packetbeat).HandleFlags(0xc8200fa480, 0xc820106280)
	/go/src/github.com/elastic/beats/packetbeat/beat/packetbeat.go:100 +0x79
github.com/elastic/beats/libbeat/beat.(*Beat).CommandLineSetup(0xc820106280)
	/go/src/github.com/elastic/beats/libbeat/beat/beat.go:111 +0x3d4
github.com/elastic/beats/libbeat/beat.Run(0xab0b60, 0xa, 0xa84d68, 0x5, 0x7fb284d38450, 0xc8200fa480, 0x7fb284d38368)
	/go/src/github.com/elastic/beats/libbeat/beat/beat.go:72 +0x12f
main.main()
	/go/src/github.com/elastic/beats/packetbeat/main.go:15 +0xe1

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1696 +0x1

goroutine 5 [syscall]:
os/signal.loop()
	/usr/local/go/src/os/signal/signal_unix.go:22 +0x18
created by os/signal.init.1
	/usr/local/go/src/os/signal/signal_unix.go:28

**Comment by ruflin** [comment] 2016-08-08 08:38
Which packetbeat version are you using? What is your OS?

**Comment by internaute** [comment] 2016-08-08 09:01
Hello
this is the version that i am using
packetbeat version 1.2.3 (amd64)


2016-08-08 10:38 GMT+02:00 Nicolas Ruflin <notifications@github.com>:

**Comment by ruflin** [comment] 2016-08-08 10:46
* What is your operating system?
* Where are you running it? Inside a virtual environment? Containers?

**Comment by internaute** [comment] 2016-08-08 11:01
it is running on debian8 it is my host (the iodine client side ) not a
guest machine

2016-08-08 12:46 GMT+02:00 Nicolas Ruflin <notifications@github.com>:

**Comment by ruflin** [comment] 2016-08-08 12:54
So far I couldn't reproduce this. How did you install packetbeat?

**Comment by internaute** [comment] 2016-08-08 13:19
I have just followed the steps mention in this link:
https://www.elastic.co/guide/en/beats/packetbeat/current/packetbeat-installation.html

2016-08-08 14:54 GMT+02:00 Nicolas Ruflin <notifications@github.com>:

**Comment by andrewkroh** [comment] 2016-08-08 22:43
This is a duplicate of #346 so I'm closing this issue. 

The workaround is to specify the device by name rather than by number in your Packetbeat configuration file. You can list the devices with `ifconfig -a` to get their names.

**Closed by andrewkroh** 2016-08-08 22:43 UTC
Labels: needs details, Packetbeat
