### ISSUE TITLE
[Rhel 7.3][Fleet]: Linux .tar.gz and .rpm Agents not sending data on rhel 7.3

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#27132] opened 2021-07-29 12:52 UTC
**Description:**
We have attempted to validate agent installation over rhel 7.3 with .rpm and .tar.gz artifacts on 7.14.0 BC-5 Kibana Cloud environment.

**Reference ticket:**
https://github.com/elastic/beats/issues/27116
As per this issue, we have installed the agent using --insecure.

**Build Details:**
```
Build: 42722
Commit: fb2c86acb9cabd7e3eee7b91b38bdde3d3eda9b6
Artifact Link: https://staging.elastic.co/7.14.0-20ebeb16/summary-7.14.0.html  
```

**Observations:**
- No agent logs under Agent Logs tab.
- No Data under data streams tab.
- Endpoint not visible under Endpoints tab.

**.tar.gz agent Logs:**
[logs.zip](https://github.com/elastic/beats/files/6900565/logs.zip)

**Endpoint Logs:**
[endpoint-000000.zip](https://github.com/elastic/beats/files/6900578/endpoint-000000.zip)

**Screenshot:**
Logs tab:
![7](https://user-images.githubusercontent.com/77374876/127492510-5891bd7d-0916-45e6-a2ad-d69e58ff67dd.JPG)

Data Streams tab:
![6](https://user-images.githubusercontent.com/77374876/127492414-fd65ccf1-28ec-44a5-86ef-8fdbfceba89a.JPG)

Endpoints tab:
![8](https://user-images.githubusercontent.com/77374876/127493234-65285359-545d-4a45-8abf-5128beccf875.JPG)

**Comment by amolnater-qasource** [comment] 2021-07-29 12:52
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment] 2021-07-29 12:55
Reviewed & Assigned to @EricDavisX

**Comment by michalpristas** [comment] 2021-07-29 12:57
`{"log.level":"error","@timestamp":"2021-07-29T08:39:09.195-0400","log.logger":"publisher_pipeline_output","log.origin":{"file.name":"pipeline/output.go","file.line":154},"message":"Failed to connect to backoff(elasticsearch(https://eae9a99ad36e4c8d9bc36c02f47f64f8.us-central1.gcp.foundit.no:443)): Get \"https://eae9a99ad36e4c8d9bc36c02f47f64f8.us-central1.gcp.foundit.no:443\": x509: certificate signed by unknown authority","service.name":"filebeat","event.dataset":"filebeat_monitor-json.log","ecs.version":"1.6.0"}`

seems like duplicate of https://github.com/elastic/beats/issues/27116

looks like OS issue not the issue of the agent. 
are trusted cert authorities up to date?

**Comment by EricDavisX** [comment] 2021-07-29 22:05
I tested on Debian 10 with the DEB installer and had no issues installing Agent or Endpoint and getting all expected logs.  I also tested on RHEL 8 (I thought it was a v7 os but it wasn't!) with the tar.gz installer as well as the RPM and both worked fine as well.  Let's close this as 7.3 specific and track it in the earlier logged ticket noted, 27116

**Closed by EricDavisX** 2021-07-29 22:05 UTC
Labels: Team:Agent, bug, impact:high
