### ISSUE TITLE
Metricbeat doesn't resolve all IPs to hostname, like heartbeat does.

### ISSUE THREAD

**Issue by vchan2002** [elastic/beats#6108] opened 2018-01-19 00:29 UTC
In heartbeat, there's is an option of `mode:all` that allowed hosts that are load balanced by any means to be resolved and have its health checked.

It appears that, on metricbeat, that is not an option... even though I added that option, it does not do anything... Is that intentional?  

My use case is that, if am getting metrics from a elasticsearch cluster (3 nodes) or a set of logstash clusters (2 nodes) that's being derived by a consul service, the consul service returns multiple IPs when it is looked up.  However, it appears that metricbeat gets the 1st IP it looks up and sticks with it in terms of returning its metrics..

**Comment by ruflin** [comment] 2018-01-22 01:35
If you have 3 nodes cluster or elasticsearch it is recommended to install metricbeat on each of the 3 machines. Like this you get local information about each node and don't need to specify 3 ip addresses.

Perhaps I miss something in your use case. Could you share your Metricbeat config?

**Comment by vchan2002** [comment] 2018-01-25 19:56
The use case I have is that, rather than trying to install metricbeat in all of the instances of different apps (elasticsearch, logstash, rabbitmq, {BTW, some of which I ran as containers also}) where I want stats, I am running metricbeat in a container that uses consul's service discovery to discover my services and get stats over the wire.


- module: elasticsearch
  metricsets: ["node", "node_stats"]
  period: 10s
  mode: all
  hosts: ["monitorstats-es5.service.consul:9200"]

- module: logstash
  metricsets: ["node", "node_stats"]
  period: 10s
  mode: all
  hosts: ["dockersyslogger.service.consul:9600"]

I believe that is a legit use case for metricbeat to gather stats that way, don't you think?

**Comment by ruflin** [comment] 2018-01-26 02:32
Having metricbeat in it's own docker container is definitive a legit use case. For this case I recommend to use our autodiscover feature.

In your above config do you put only 1 url to fetch ES data in metricbeat and then consul does some magic (sorry, not familiar with consul). Can you share some more details on how the above is working as it seems to fetch stats from only 1 host.

**Comment by vchan2002** [comment] 2018-01-26 04:22
Given how heartbeat is able to do a lookup of all the IP addresses behind a DNS address and do a check on each one of them, I expected that to work in a similar manner in metricbeat, aka, being able to lookup all of the IPs that the DNS address resolves to.  As I mentioned above, it does not.  

What seems to be odd is that, I also have a rabbitmq monitor on this same docker container, but as I look at the rabbitmq stats in elasticsearch, it has a field called rabbitmq.node.name that shows that it is hitting both hosts....  However, no such field exists for elasticsearch node stats or logstash node stats.... again.. is that by design?

**Comment by ruflin** [comment] 2018-01-28 02:40
At the moment we have a 1-1 mapping in Metricbeat, means only 1 metricset is started for each host. With the DNS lookup you mention the number of hosts behind the DNS can change over time. A similar logic applies for example to docker or kubernetes where container come and go. Instead of trying to build this lookup logic in each metricset we start  Autodiscovery. Autodisovery allows to build different mechanism to have such lookup mechanism and start metricsets based on some criterias. Have a look here: https://www.elastic.co/guide/en/beats/metricbeat/current/configuration-autodiscover.html `consul` or more generic `dns` could be an other autodiscovery provider.

As rabbitmq uses an almost identical implementation to the elasticsearch module I would be surprised if it actually hits both hosts at the same time. I assume what happens is that the DNS once returns one host and the next time an other. So you get data from both hosts over time, just not every x seconds. 

So it's by design that the above should not work. Can you double check if it actually works in RabbitMQ?

As you already run on docker, could you use the docker autodisovery instead of consul?

@exekias See above for an indirect request of DNS / Consul auto discovery provider.

**Comment by kapowkimc** [comment] 2018-02-08 15:44
I completely understand what the OP is seeking here. As a newbie in metricbeats running a docker swarm mode cluster I ended up exactly here.

In docker swarm mode, service discovery is done very elegantly through dns. If I have three container instances of a service, then running a dns request on the service name returns a list of three A records pointing me to those services inside the overlay network. (shuffling the order with each request to facilitate round robin LB of requests) These containers can be running on any of the nodes in the swarm. Potentially all three containers on the same node.

I would have thought too, that configuring the service name in the metricbeats module conf would automatically resolve to the ips of the containers running this service and start the data collection from each of them. No matter how many was running. 

I looked at your auto discovery. Is this working for docker swarm mode? Meaning it only starts collecting from containers started on the same host as metrickbeats is running, even though container events are published from the entire cluster?

**Comment by exekias** [comment] 2018-02-08 15:50
Hi @kapowkimc, it should work in Swarm, the deployment model requires you to deploy a Metricbeat container per node in the cluster. It will be in charge of monitoring the containers in its host. Consider giving it a try as I think it covers your use case.

**Comment by atmosx** [comment] 2019-03-28 08:45
@exekias no it doesn't. If you chose to use `host` network mode there's no way to bind other networks, so you'll either have to use a second metricbeat instance to monitor endpoints (e.g. Prometheus exporters) that are accessible through swarm network only or find a way to expose those endpoints to the host node. Note that due to docker's limitation you can't bind both `host` and an overlay network.

Now, say that you want to monitor a container exposing metrics in swarm. If you use `hints.autodiscovery` you'll also have to issue to specific IP address for each task. Each swarm service consists of one or more tasks. Each service has a virtual IP which will redirect connections to the tasks in RR fashion. However, through DNS swarm returns the IP addresses of each task. You'll want to monitor each task separately. If you monitor through the virtual IP, then you'll be hitting a different endpoint each time. Prometheus solves this through CNAME resolution. Metricbeat apparently doesn't. Even if it did though, I'm afraid that, given the modus operandi of metricbeat (one instance on each node) you'll end having each metricbeat node collecting data for the same endpoints, hence you'll have to resort in some sort of data deduplication.

Metricbeat doesn't play well in swarm. Even the solution of having one metricbeat per node and a single instance to collect metric from exporters inside the swarm cluster, is problematic as you'd to manually update the configuration to include the task IP addresses.

**Comment by atmosx** [comment] 2019-03-28 08:52
> I looked at your auto discovery. Is this working for docker swarm mode? Meaning it only starts collecting from containers started on the same host as metrickbeats is running, even though container events are published from the entire cluster?

Metricbeat will only collect data from the local node.

**Closed** 2020-08-07 20:30 UTC
Labels: Metricbeat, Stack monitoring, Stalled, Team:Integrations, [zube]: Backlog, discuss
