### ISSUE TITLE
Fleet Server agent stuck in updating state on triggering unenrollment from Kibana UI

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/beats#26101] opened 2021-06-02 07:09 UTC
**Description:**
Fleet Server agent when installed with any policy having Fleet Server integration stuck in updating state on triggering unenrollment from Kibana UI.

**Kibana version:** 7.13.1 BC-2 Kibana cloud environment

**Host OS and Browser version:** Windows 10 x64, All

**Build Details:**
```
 Artifact link used: https://snapshots.elastic.co/7.13.0-7457d36a/downloads/beats/elastic-agent/elastic-agent-7.13.0-SNAPSHOT-windows-x86_64.zip
 Build: 40903
 Commit: 9b177ae95979d96cf172517a3c6e469bbbda07ed
```

**Preconditions:**
1. 7.13.0 BC-2 Kibana cloud environment should be available.
2. Windows 10 x64 Fleet Server agent must be installed with any policy having Fleet Server Integration on 7.13.1 BC-2. 

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Agents tab and unenroll Fleet Server agent.
3. Observe Fleet Server agent stuck in updating state.

**Expected Result:**
Fleet server agent should get uninstalled on triggering unenrollment from Kibana UI.

**Logs:**
[logs.zip](https://github.com/elastic/beats/files/6582640/logs.zip)

**Note:**
- This issue is reported in lieu of https://github.com/elastic/beats/issues/25561 

**Screenshot:**
![2](https://user-images.githubusercontent.com/77374876/120438571-2bfab880-c39f-11eb-9ffc-e72c29afc25a.JPG)

**Comment by amolnater-qasource** [comment] 2021-06-02 07:09
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment] 2021-06-02 07:44
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment] 2021-06-02 18:05
I think this is a dupe, need to search for the ticket...

**Comment by amolnater-qasource** [comment] 2021-06-03 05:22
Hi @EricDavisX 
We have created this ticket in lieu of https://github.com/elastic/beats/issues/25561 for better discussion.

Thanks

**Comment by amolnater-qasource** [comment] 2021-06-03 09:09
Further, while testing on self-managed 7.14.0 Snapshot we have found this issue **reproducible**. 
Fleet Server agent having Fleet Server integration stuck in updating state on triggering unenrollment from Kibana UI.

Thanks

**Comment by EricDavisX** [comment] 2021-06-07 22:32
@hbharding @ph @mostlyjason hi - did we want to work on the UX for this for self-managed usage?  It would apply to any cloud-stacks where users spin up their own Fleet Servers as well.  

Just passing along the issue.  Something to think on.  I'm removing the 'high' impact label as until we know more, I suppose this won't be seen as much.  But it is an open question as to what state the host processes are in when a user attempts it.

**Comment by amolnater-qasource** [comment] 2021-06-14 10:53
Hi @mostlyjason 
We have waited for more than 10 minutes after triggering unenrollment from Kibana UI.
- Agent installed with Fleet Server integration stuck in updating state.

> I think it should eventually go offline?

- We have checked this earlier it never goes to offline state, it remains UPDATING through out the day.

>What happens when you force unenroll?

Agent stuck in UPDATING state immediately goes to INACTIVE state.

**Screenshot:**
![6](https://user-images.githubusercontent.com/77374876/121881253-a676f100-cd2c-11eb-9882-075b1fa05b13.JPG)

Please let us know if anything else is required from our end.
Thanks
QAS

**Comment by mostlyjason** [comment] 2021-06-16 16:50
@ph @jen-huang this looks like a bug but I'm not sure whether its on the fleet side or elastic agent side. I'd expect the agent to be unenrolled gracefully and then transition to the inactive state. 

Its not super urgent because there is a workaround to force unenroll the agent. Perhaps its something to keep in our queue to clean up?

**Comment by amolnater-qasource** [comment] 2021-06-23 11:30
Hi @mostlyjason 
We have reproduced this issue on 7.14.0 Snapshot with different steps.
- Uninstalled elastic-agent (installed with default policy having System and endpoint security) with .\elastic-agent uninstall command.
- Agent went offline from Kibana UI and then we triggered Unenroll agent from Kibana UI.
- We observed that agent is stuck in "Updating" state.

**Screenshot:**
![6](https://user-images.githubusercontent.com/77374876/123087752-84732200-d442-11eb-9803-72fdf9df5a30.JPG)

**Build details:**
```
Build: 41896
Commit: e26582638988179d134e77e59b66ed8f982ab064
Artifact link: https://snapshots.elastic.co/7.14.0-df0371f0/downloads/beats/elastic-agent/elastic-agent-7.14.0-SNAPSHOT-windows-x86_64.zip
```

Thanks
QAS

**Comment by blakerouse** [comment] 2021-06-23 13:42
@amolnater-qasource That is expected behavior. If you uninstall the Elastic Agent from the host it does not unenroll from Kibana. Then when you trigger the Unenroll (not Force Unenroll) Kibana triggers and action for the Elastic Agent to unenroll, but at this point your Elastic Agent is already uninstalled and not running so it will never receive the action.

If you perform uninstall then want to unenroll it must be a Force Unenroll.

**Comment by amolnater-qasource** [comment] 2021-06-24 06:22
Hi @blakerouse 
Thank you for the feedback on observations shared at https://github.com/elastic/beats/issues/26101#issuecomment-866758507 
>If you perform uninstall then want to unenroll it must be a Force Unenroll.

Yes we are able to unenroll uninstalled elastic-agent with Force Unenroll.

Thanks
QAS

**Comment by EricDavisX** [comment] 2021-06-24 21:25
Just confirming, since the above was with different steps it is a different issue and not the same as what is reported here.  If the original steps are still a problem it can be considered as clean up work

**Comment by amolnater-qasource** [comment] 2021-06-28 07:32
Hi @EricDavisX 
Yes, this issue is still **reproducible**.
- Fleet Server agent is stuck in updating state on triggering unenrollment from Kibana UI.

**Build details:**
```
Build: 42089
Commit: 67a71c75d2da40e49fba2620f488c9b4ce2467d2
Artifact Link: https://snapshots.elastic.co/7.14.0-15b00b37/downloads/beats/elastic-agent/elastic-agent-7.14.0-SNAPSHOT-windows-x86_64.zip
```

Thanks
QAS

**Comment by amolnater-qasource** [comment] 2021-06-29 07:13
Hi @mostlyjason 
>can you test this by unenrolling (without force unenroll) from the fleet UI without uninstalling the agent first?

Yes, we are able to unenroll the agent if we don't uninstall first.
However the original issue this is reported for, is still reproducible and we have shared our latest observations at https://github.com/elastic/beats/issues/26101#issuecomment-869438243

- Fleet Server agent installed with Fleet Server integration gets stuck in Updating state on triggering unenrollment.

Please let us know if anything else is required from our end.
Thanks
QAS

**Comment by mostlyjason** [comment] 2021-07-06 13:14
Ok this sounds like the expected behavior, as Blake mentioned. I think we can close this one. Let me know if I'm overlooking anything.

**Comment by mostlyjason** [comment] 2021-07-08 13:18
I had a chat with Amol on Slack and clarified that there are two separate scenarios described in this thread. The first is the original reported issue that the agent remains stuck even when it is not uninstalled first. This is still broken so I'm reopening the issue. 

The second scenario is that it gets stuck in updating when we uninstall the agent on the host first. This is the expected behavior so we can ignore this scenario.

**Comment by amolnater-qasource** [comment] 2021-07-12 07:04
Thanks  @mostlyjason for re-opening this issue. Yes, Scenario1 is is still reproducible on 7.14.0 Snapshot.

Please let us know if anything is required from our side.

**Build details:**
```
Build: 42479
Commit: 7f950fbe0d37a576158ad19f5c7c8244628d67e6
Artifact Link: https://snapshots.elastic.co/7.14.0-9b23ec55/downloads/beats/elastic-agent/elastic-agent-7.14.0-SNAPSHOT-windows-x86_64.zip
```

**Screenshot:**
![2](https://user-images.githubusercontent.com/77374876/125242389-3d25d600-e30a-11eb-826a-db4f29415c92.JPG)

Thanks

**Comment by blakerouse** [comment] 2021-07-12 12:11
@mostlyjason @amolnater-qasource Both are expected behavior. My comment in https://github.com/elastic/beats/issues/26101#issuecomment-866847441 matches your scenario 1, what you're seeing is expected behavior.

Unless the Elastic Agent your are talking about is not running Fleet Server? Then that is an issue. But based on the title of this issue and the comments this issue has always been about an Elastic Agent running a Fleet Server and unenrolling.

**Comment by mostlyjason** [comment] 2021-07-12 12:40
> That is expected behavior. If you uninstall the Elastic Agent from the host it does not unenroll from Kibana. Then when you trigger the Unenroll (not Force Unenroll) Kibana triggers and action for the Elastic Agent to unenroll, but at this point your Elastic Agent is already uninstalled and not running so it will never receive the action.

Just to make sure we both have the same understanding, your comment quoted above seems to talk about uninstalling the Elastic Agent and then unenrolling it from Kibana. This is what I called "the second scenario."

The first scenario is that the user unenrolls from Kibana without uninstalling it first. How does your comment address this scenario? In this case, it also looks to be stuck in the updating state. Are you saying that is expected?

@amolnater-qasource I believe Blake and I are assuming that in your latest screenshot showing Default policy is stuck in updating, that the policy contains a Fleet server integration. Is that correct?

**Comment by blakerouse** [comment] 2021-07-12 13:02
@mostlyjason I am speaking about both scenarios. Scenario 1 is not supported. You cannot unenroll an Elastic Agent with a Fleet Server bootstrapped on it. That is because the Elastic Agent can only communicate with its Fleet Server and unenroll stops all sub-processes (including Fleet Server) so Elastic Agent cannot ack the unenroll so it stays in Updating always and does not complete unenrollment.

**Comment by mostlyjason** [comment] 2021-07-12 19:47
@blakerouse thanks for explanation! I'm concerned about the UX though because users do not understand how it works under the covers. From a user perspective, it seems unexpected that it would be stuck in updating state. @nimarezainia what is your perspective? Do you see this as a UX issue?

**Comment by EricDavisX** [comment] 2021-07-19 17:53
@nimarezainia @mostlyjason can you cite if you'd think this is more of an Enhancement then (to prevent any Agent running Fleet Server Integration from being unenrolled)?  we can log a new ticket if you prefer, might be cleaner and we can close this out, then, too.  @amolnater-qasource can follow through.  I removed the 7.14 label fyi

**Comment by ruflin** [comment] 2021-08-05 10:11
As @EricDavisX mentioned we should have a follow up issue to figure out how we improve the UX around this. @mostlyjason Can you take care of this? Closing this issue.

**Closed by ruflin** 2021-08-05 10:11 UTC
Labels: Team:Agent, bug

**Comment by EricDavisX** [comment] 2021-08-09 19:03
I've logged this to Kibana repo as: https://github.com/elastic/kibana/issues/107955
