### ISSUE TITLE
'Error fetching agents; external error occurred' pop up coming inconsistently on Agents Tab

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#23756] opened 2021-01-29 13:03 UTC
**Build Details:**
Version : 7.11 BC5 on cloud
BUILD 37827
COMMIT d801a7bb08e17368584d00fbd97a5d0006285b51

Agent Artifact Link: https://staging.elastic.co/7.11.0-903dc0b6/downloads/beats/elastic-agent/elastic-agent-7.11.0-windows-x86_64.zip

**Steps to Reproduce**
- Go to Fleet 'Agents' list.
- Observed that inconsistently error "Error Fetching Agents" is thrown on Agent Tab

**Screenshot:**
![bug_29jan](https://user-images.githubusercontent.com/72375798/106278253-6bce5980-6260-11eb-94a4-977366b752de.png)

**Comment by dikshachauhan-qasource** [comment] 2021-01-29 13:04
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment] 2021-01-29 13:28
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment] 2021-01-29 17:07
@ph should we at least review if we can see this and look at error logs?
@dikshachauhan-qasource can you try to reproduce on local setup instead of cloud, for same build?
we would like to have the Kibana logs if possible.  If we can reproduce it on cloud here, we can try to get the logs.  I believe this was cloud 'prod' elastic as the test team was having issues with 'staging' yesterday and so was not using it, fyi.

**Comment by ph** [comment] 2021-01-29 17:25
@nchaulet I've moved it into the investigation,  I see the item as marked as high. But I am not totally sure, I would have expected that kind of behavior show up for some time.

**Comment by EricDavisX** [comment] 2021-01-29 18:39
I fully acknowledge the repro scenario isn't known - there must be something more on the setup / environment side that contributes.  It isn't seen on all BC5 builds, and isn't consistent when it is.

**Comment by nchaulet** [comment] 2021-01-29 18:54
@EricDavisX It's possible to have the cloud instance id in this case, it will help to investigate the logs and what is the error behind

**Comment by nchaulet** [comment] 2021-01-29 19:24
Investigation still in progress, but dumping a little what I found for now so the errors is not really frequent 60 errors out of 50k during the last 7 days 

<img width="1675" alt="Screen Shot 2021-01-29 at 2 10 07 PM" src="https://user-images.githubusercontent.com/1336873/106318065-411ed980-623d-11eb-801b-b82a7f87ccb1.png">
<img width="1680" alt="Screen Shot 2021-01-29 at 2 10 22 PM" src="https://user-images.githubusercontent.com/1336873/106318067-411ed980-623d-11eb-92e2-0c42e6e436f9.png">

but each time we saw this error close in the log from the 500
<img width="821" alt="Screen Shot 2021-01-29 at 2 20 21 PM" src="https://user-images.githubusercontent.com/1336873/106318276-aecb0580-623d-11eb-85f5-7f20481f53a4.png">

**Comment by ph** [comment] 2021-01-29 19:27
@nchaulet is that the cloud proxy layer?

**Comment by nchaulet** [comment] 2021-01-29 19:30
No I think the error is coming from Kibana.

**Comment by amolnater-qasource** [comment] 2021-02-01 13:31
Hi @EricDavisX 
As per https://github.com/elastic/beats/issues/23756#issuecomment-769930390 we have re-validated this on 7.11.0 Kibana cloud environment. Build details are as follows:

```
Artifact link used: https://staging.elastic.co/7.11.0-903dc0b6/downloads/beats/elastic-agent/elastic-agent-7.11.0-windows-x86_64.zip
Build: 37827
Commit: d801a7bb08e17368584d00fbd97a5d0006285b51
```
**Observations:**
- This issue is still reproduceable on Kibana cloud environment.
- "Error fetching agents" error is occurred due to inactivity for 5-10 minutes.

**Environment details:**
```
Cloud id: elastic-security-deployment:dXMtY2VudHJhbDEuZ2NwLmZvdW5kaXQubm8kZTQ3ZWZlOThmZWY3NGRmZDhiMDk3MmMwODNmOTRmMjYkNTJiNzI0NmVmNWI2NGI2Mzk2YjNhNDI2OTU1ZTMyMDA=
Cloud url: https://52b7246ef5b64b6396b3a426955e3200.us-central1.gcp.foundit.no:9243/
Username/password: elastic | 9Pf0UUL5PJXKLClFofC1a01H
```
Screenshots:
![SocketHangup cloud](https://user-images.githubusercontent.com/77374876/106465011-6cb0f680-64bf-11eb-91f0-ef53febc20cc.png)

Further, we have found that this issue is not occurring on stack deployment.
```
Machine IP: 10.0.5.222
```

Please let us know if anything else is required.

Thanks
QAS

**Comment by EricDavisX** [comment] 2021-02-03 00:25
@amolnater-qasource hi - can you elaborate on what you want to convey in the comment 'not occurring on the stack deployment'?  To me 'the stack' means the Elasticsearch / Logstash / Kibana and cloud components.  Thank you.

**Comment by amolnater-qasource** [comment] 2021-02-03 05:14
Hi @EricDavisX 
Here am referring to on-prem environment.

Thanks
QAS

**Comment by EricDavisX** [comment] 2021-02-03 22:26
Thank you @amolnater-qasource .  In Elastic teams, 'the stack' is always the stack, whether it is self-managed or in cloud.  self-managed can mean several things (including ECE) but is sometimes interchanged with 'on-prem' tho they are not exactly the same.  Happy to pass on some nuances, thank you for the clarification.

I can concur, I am not seeing this or other 503 / socket-timeout issues in the other self-managed cluster I am testing on, so it seems somehow specific to or just significantly more prevalent in cloud usage.

**Comment by amolnater-qasource** [comment] 2021-02-04 09:08
Hi @EricDavisX 
Thanks for the enhanced information.
Yes Eric, as per our observation you concluded correct. We have observed it most specific to cloud environments only. Further we have not found this issue occurring on self managed stack.

Thanks 
QAS

**Comment by EricDavisX** [comment] 2021-02-04 20:37
This issue is potentially fixed by elastic/kibana#90066 - With a 7.11 circa bc6 snapshot, I still see the 503 / socket-hangup error in the logs, but Agent seemed ok.  I did not see any 'Error fetching agents' pop up.

So, it seems this is fixed and the overall experience is improved, though not totally fixed.  Let us test with BC6 and close this out (hopefully)

**Comment by amolnater-qasource** [comment] 2021-02-05 11:11
Hi @EricDavisX 
We have revalidated this issue on 7.11 BC-6 Kibana Cloud Environment and found it as **Fixed**.

Build details: 
```
Artifact link: https://staging.elastic.co/7.11.0-af4ff60e/downloads/beats/elastic-agent/elastic-agent-7.11.0-windows-x86_64.zip
Build: 37890
Commit: 80030db683333591cf7de76bc6780c96e8b733a2
```
**Observations:**
- No 'Error fetching agents' pop up appears under Fleet tab.
 Hence, closing this issue.

**Screenshot:**
![6](https://user-images.githubusercontent.com/77374876/107022208-1c8da900-67cb-11eb-9d54-1509c115abc3.JPG)

Please let us know if anything else is required.

Thanks 
QAS

**Comment by dikshachauhan-qasource** [comment] 2021-02-08 11:51
Hi @EricDavisX 

Today while performing regression on 7.11 BC7 Kibana Cloud build, we are observing continuous 'Error fetching agents' pop-ups on Fleet>Agents UI.

**Build details:**
```
BUILD 37897
COMMIT 3f71ce7177a41e067ddb1e670ec4ace5f6d4f5fe
Artifact link:  https://staging.elastic.co/7.11.0-1f38d552/summary-7.11.0.html
```

**Observations:**
- Pop-ups are getting displayed on newly created Kibana cloud environment without any agent installed.
- Further, pop-ups are still coming even after agent is installed.
- Pop up showing different error messages each time like: internal error, socket hang up error and error messages like shown below in screenshot.

**Screenshot:**
![image](https://user-images.githubusercontent.com/72375798/107192078-299cd900-6a13-11eb-8cf9-3248b9f9c09a.png)



Hence, we are re-opening this issue.

Thanks
QAS

**Comment by EricDavisX** [comment] 2021-02-24 22:39
I have not seen this on recent 7.12 snapshot or BC (BC2) testing.

**Comment by amolnater-qasource** [comment] 2021-02-25 11:00
Hi @EricDavisX 
We have revalidated this issue on 7.12.0 BC-2 Kibana cloud environment.

**Observations:**
- "Error fetching agents" pop ups under Agents tab.
- Observed `"socket hang up" [error]` logs under agent Logs tab.

**Screenshots:**
![socket](https://user-images.githubusercontent.com/77374876/109142948-7a3b6280-7785-11eb-93b9-826a76829c48.png)

**Build details:**
```
Build: 39000
Commit: 4f65a5a1268fa78f1af9117d12312e1cee433376
```
Thanks 
QAS

**Comment by EricDavisX** [comment] 2021-02-25 16:25
Thanks so much Amol.  I'm glad to know it is still evidenced.  It makes me think... @michalpristas @nchaulet  I wonder if it could relate to performance and ability of the Agent host to talk out to the internet (Kibana or ES).  Meaning: maybe only slower or more taxed host machines would show this off, somewhat akin to the way the problems seen in deploying Agent are showing in:  
https://github.com/elastic/beats/issues/24180#issuecomment-785915614

**Comment by EricDavisX** [comment] 2021-02-25 17:08
I just reproduced a variation on this and in researching it am realizing there are different bugs that all manifest with the same high level error 'error fetching agents' in a pop up.  @amolnater-qasource can we make sure we have distinct issues for each of the problems?  

I see...
- 'an internal server error' originally in the description, I don't see that anymore, do you?
- 'socket hang-up' which we had hoped we had a fix that would help, if not fully alleviate it?
-  and most recently in your post above: 'invalid GET /Agents response'

Let's do a new ticket for that, and possibly close this out if we aren't seeing the "original" 2.  New ticket in the kibana repo please (since it seems unrelated to Agent at this point).

The error I see is this:  The key is empty and needs to be wrapped by a saved object type like fleet-agents: Bad Request

And I only see it when I pass in a bad kql to the Agents search bar.  so it is different. new issue is:
https://github.com/elastic/kibana/issues/92853

Back to this issue... I think we should close it out for 7.12 if we aren't seeing the same bugs anymore.  We can give it some time to see if it comes up during other regression tests.

**Comment by amolnater-qasource** [comment] 2021-02-26 08:14
Hi @EricDavisX 
As per your feedback, we will report a separate ticket for the same if it comes up during other regression tests.

Thanks
QAS

**Closed** 2021-03-01 20:52 UTC
Labels: 7.12 candidate, Team:Fleet, Team:Ingest Management, bug, impact:high
