### ISSUE TITLE
Filebeat is reporting an 'input' problem, unsure what the cause or impact is, error: "Can only start an input when all related states are finished"

### ISSUE THREAD

**Issue by EricDavisX** [elastic/beats#21933] opened 2020-10-16 19:26 UTC
This is with the 7.10 BC2 build that was re-signed by Infra to help us continue testing.

Using a 7.11 snapshot kibana and the *just released this morning 0.8.0 package of System Integration package.

I don't know if it will be a Beats problem, or a package problem or on Agent side?  The error is being reported by Filebeat, in this case, so that may be where we start reviewing?

It is a Centos 8 system and I installed the .tar.gz Agent package with the 'install' command and had no problems for a few mins.  I quickly installed a new integration policy to install 'Endpoint' and oddly enough the timing on that is exactly when I see the filebeat problem, but it surely can't be related?  Seems unlikely, but I wanted to mention.

error:
`
Application: filebeat--7.10.0[63a20f1b-ef58-437d-88a1-ee23bc3c4df2]: State changed to DEGRADED: 1 error: 2 errors: Error creating runner from config: Can only start an input when all related states are finished: {Id: native::25889930-64768, Finished: false, Fileinfo: &{secure-20200918 19330 384 {216275053 63736048098 0x64cea60} {64768 25889930 1 33152 0 0 0 0 19330 4096 40 {1602865587 930190261} {1600451298 216275053} {1600454102 163846939} [0 0 0]}}, Source: /var/log/secure-20200918, Offset: 19330, Timestamp: 2020-10-16 14:30:17.029617771 -0400 EDT m=+10.908029060, TTL: -1ns, Type: log, Meta: map[], FileStateOS: 25889930-64768}; Error creating runner from config: Can only start an input when all related states are finished: {Id: native::25683066-64768, Finished: false, Fileinfo: &{messages 1594 384 {418471648 63738469797 0x64cea60} {64768 25683066 1 33152 0 0 0 0 1594 4096 8 {1602872666 482622152} {1602872997 418471648} {1602872997 418471648} [0 0 0]}}, Source: /var/log/messages, Offset: 1594, Timestamp: 2020-10-16 14:30:17.029617771 -0400 EDT m=+10.908029060, TTL: -1ns, Type: log, Meta: map[], FileStateOS: 25683066-64768}`

This screen shot shows the Activity log progression:
<img width="1153" alt="Screen Shot 2020-10-16 at 2 39 48 PM" src="https://user-images.githubusercontent.com/12970373/96300234-33618300-0fc3-11eb-84ea-a665f343bcf1.png">

full Agent log:
[input-error-agent.log](https://github.com/elastic/beats/files/5393889/input-error-agent.log)

more host details: mainqa-atlcolo-10-0-7-165, and I can offer up / help with access as needed to the vm which is behind the Endgame VPN

**Comment by EricDavisX** [comment] 2020-10-16 19:26
between Blake and Alex K we weren't sure who should look at it first.  @ph @ruflin thoughts?

**Comment by ruflin** [comment] 2020-10-19 08:15
This error is normally happening on the Filebeat site if reading from a file cannot be finished, for example because Elasticsearch is not available anymore. I see two log files in the state:

* `/var/log/secure-20200918`
* `/var/log/messages`

My first question is: Why part of the policy tails these two files? Could you share the full policy yaml Fleet creates or the Elastic Agent has?

The second question is on what we should do, if an input does not stop so we can't deploy the new policy. @blakerouse ?

**Comment by ph** [comment] 2020-10-21 15:47
Would like @urso opinion here.

**Comment by urso** [comment] 2020-10-28 12:23
We would need to see the whole configuration. You get this error if 2 inputs are configured to read the same file.

On first sight it looks like it is a duplicate of https://github.com/elastic/beats/issues/22054. In case we have 2 integrations configured that read the same file we need to have different IDs. With different IDs filebeat can the state for each integration independently.

**Comment by jlind23** [comment] 2022-03-31 08:34
Backlog grooming: Closing for now.

**Closed by jlind23** 2022-03-31 08:34 UTC
Labels: Team:Services
