### ISSUE TITLE
[metricbeat ][failed to capure disk util running as service on Windows]

### ISSUE THREAD

**Issue by pedrosk** [elastic/beats#12854] opened 2019-07-10 18:54 UTC
For confirmed bugs, please report:
- Version: metricbeat 6.8.1
- Operating System:  Server 2008 R2.
- Discuss Forum URL:
- Steps to Reproduce: 
On the windows OS is Server 2008 R2. a metricbeat 6.8.1 will not show disk space used (would be green and 0% used) when run as service. However, when run as admin metricbeat would show disk space.

<b><i>Running as admin:</i> </b>
![image](https://user-images.githubusercontent.com/16103646/60996424-2f53a980-a31a-11e9-8fc8-b2a41d4f3aab.png)

<br><b><i><hr></I><br>
Running as service:
![image](https://user-images.githubusercontent.com/16103646/60996269-e69bf080-a319-11e9-9991-309a94a51c18.png)

**Comment by kaiyan-sheng** [comment] 2019-07-15 17:26
I think this is the same as https://github.com/elastic/beats/issues/12435

**Comment by exekias** [comment] 2019-07-16 08:27
agreed, closing as a duplicate of #12435, where some solution has been discussed already

**Closed** 2019-07-16 08:28 UTC
Labels: Metricbeat
