### ISSUE TITLE
elastic-agent install 'interactive' command is unable to enroll the agent into Fleet

### ISSUE THREAD

**Issue by rahulgupta-qasource** [elastic/beats#21244] opened 2020-09-23 12:06 UTC
**Kibana version:**
Kibana: 8.0.0-SNAPSHOT

**Elasticsearch version:**
Elasticsearch: 8.0.0-SNAPSHOT

**Host OS and Browser version:**
Windows 10 , All

**Original install method (e.g. download page, yum, from source, etc.):**
From 8.0.0-SNAPSHOT on staging cloud environment https://staging.found.no/

**Description**
elastic-agent install command is unable to enroll the agent into Fleet

**Preconditions**
1. 8.0.0-SNAPSHOT Kibana cloud environment should be available.

**Steps to Reproduce**
1. Open the 8.0.0-SNAPSHOT Kibana cloud environment in browser.
2. Download the 8.0.0 agent from artifact link(https://console.cloud.google.com/storage/browser/beats-ci-artifacts/pull-requests/pr-21206/elastic-agent?pageState=(%22StorageObjectListTable%22:(%22f%22:%22%255B%255D%22))&prefix=&forceOnObjectsSortingFiltering=false)
3. RDP to the endpoint and place the agent.
4. Unarchive the agent
5. Open powershell as admin and run the command for interactive mode:
./elastic-agent install
6. Observe that installation is successful bit agent is unable to enroll into fleet.

**Test data**
N/A

**Impacted Test case id**
N/A

**Actual Result**
[Ingest Management]: elastic-agent install command is unable to enroll the agent into Fleet

**Expected Result**
[Ingest Management]: elastic-agent install command should be able to enroll the agent into Fleet

**What's working**
 - Issue is also occurring for mac and linux

**What's not working**
 - N/A

**Screenshot**
![windows_interactive_fail](https://user-images.githubusercontent.com/59917944/94010277-55e8ed80-fdc3-11ea-9031-d7d2c873688f.jpg)

**Logs**
N/A

**Comment by rahulgupta-qasource** [comment] 2020-09-23 12:08
@muskangulati-qasource Please review the bug

**Comment by muskangulati-qasource** [comment] 2020-09-23 12:32
Reviewed & assigned to @EricDavisX .

**Comment by EricDavisX** [comment] 2020-09-23 14:10
confirmed on Windows (as seen here) and macOS (by Eric, screenshots sent to Blake)

**Comment by EricDavisX** [comment] 2020-09-23 17:43
note, the usage above is actually a 'negative' test which is passing, because it uses the enrollment token uuid instead of the token itself, the 'secret' which is the string that ends with the == in the UI.

<img width="449" alt="Screen Shot 2020-09-23 at 1 42 55 PM" src="https://user-images.githubusercontent.com/12970373/94049245-b87dc180-fda2-11ea-84b8-8c1dac6d65b5.png">

So I can close this out as not an issue.  But, I'll say that when I used the secret it still failed.  Blake is fixing it so we can re-test soon.

**Closed by EricDavisX** 2020-09-23 17:43 UTC
Labels: Team:Ingest Management, bug, impact:high
