### ISSUE TITLE
[Ingest Manager]: Agent goes to unhealthy state on Agents tab UI when using default namespace in Agent policy.

### ISSUE THREAD

**Issue by dikshachauhan-qasource** [elastic/beats#23332] opened 2020-12-31 07:09 UTC
**Kibana version:**
7.11 BC Kibana Cloud environment 

**Elasticsearch version:**
7.11 BC Kibana Cloud environment 

**Host OS and Browser version:**
Windows 10, All

**Original install method (e.g. download page, yum, from source, etc.):**
7.11 BC Kibana Cloud environment  

[Ingest Manager]: Agent goes to unhealthy state on Agents tab UI when using default namespace in Agent policy.

**Preconditions**
1.  7.11 BC Kibana Cloud environment  should be available.
```
BUILD 37399
COMMIT f3abc08ac648f8b302733c5c22a39048314a027c
Artifact link: https://staging.elastic.co/7.11.0-710164a0/downloads/beats/elastic-agent/elastic-agent-7.11.0-windows-x86_64.zip
```
2. Default policy having system integration should exist.[No change in namespace].

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. Go to Fleet>Agents. Click on 'Create user and enable central management' button.
3. RDP to endpoint. Run installation command using default policy.
4. Navigate back to Fleet UI.
5. Go to Agents Tab.
6. Wait for few seconds and observe, agent goes to unhealthy state.

Logs:
```
[elastic_agent][error] Could not communicate with Checking API will retry, error: Status code: 503, Kibana returned an error: Service Unavailable, message: socket hang up
```

**Reference ticket Id:**
N/A

**Actual Result**
Agent goes to unhealthy state on Agents tab UI when using default namespace in Agent policy.

Screenshot:
![7 11_defaultnamespaceAgent](https://user-images.githubusercontent.com/72375798/103399016-25081980-4b65-11eb-956a-bc08fb99ca9a.jpg)

**Expected Result**
Agent should remain in healthy state on Agents tab UI when using default namespace in Agent policy.

**What's working**
- Data streaming starts
- Agent logs generated

**What's not working**
Agent goes to unhealthy state on Agents tab UI when using default namespace in Agent policy[having System and endpoint integration with namespace default].

Error at logs:
```
[elastic_agent][error] Could not communicate with Checking API will retry, error: Status code: 503, Kibana returned an error: Service Unavailable, message: socket hang up
[elastic_agent][info] 2020-12-31T01:44:51-05:00: type: 'STATE': sub_type: 'RUNNING' message: Application: endpoint-security--7.11.0[b40634a0-4b29-11eb-ba59-659cbe501564]: State changed to DEGRADED: Missed last check-in
```
- Same behavior has been observed for MAC agents. Please refer below screenshot.
![Mac_observation](https://user-images.githubusercontent.com/72375798/103398969-ef633080-4b64-11eb-9dd0-cdd8c968c501.jpg)

**Comment by manishgupta-qasource** [comment] 2020-12-31 07:14
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment] 2021-01-04 19:03
The Fleet Server setup changes that caused other bugs are not backported to 7.11 so this will be a different problem we should review.  @ph I pinged @nchaulet via slack - but we may need Agent side help.

**Comment by nchaulet** [comment] 2021-01-04 19:06
I think it's correct to have the agent as `unhealthy` here as an error occured looking at the log

**Comment by EricDavisX** [comment] 2021-01-04 19:07
ah, thanks Nicolas!  @nchaulet I acknowledge the state may be correct, but do we know what causes the underlying problem?  We can update or spawn a new issue if better - just don't want to lose track of the main problem.

**Comment by nchaulet** [comment] 2021-01-04 19:15
Looking at the log I think there is differents issue:
* the endpoint integretion returning a `degraded` status
* some 503 when calling the checkin API but I guess this one should be resolved after the agent checkin cc @michalpristas

**Comment by ph** [comment] 2021-01-04 19:30
**Actions:**

- @EricDavisX can confirm that the packaging is OK on macOS and it's not missing the `*.sha512`
- I agree with @nchaulet investigation, that from the provided log the **unhealthy** state should be the current state.
- After talking with @EricDavisX I believe this is something more problematic here either a packaging on some OS, or a problem with the integration with Endpoint.
- @dikshachauhan-qasource After talking with @EricDavisX we thinking having a call to understand what is going on would be the best way to move forward and do live debug. @EricDavisX will schedule a call with @michalpristas and myself.

**Comment by ph** [comment] 2021-01-04 19:33
What worried me is  _unhealthy_  state are possible, the problem is when an Agent is never able to recover from that case.

**Comment by EricDavisX** [comment] 2021-01-05 01:11
The macOS 7.11 BC1 package is currently showing as ok in my test on cloud Prod of 7.11.  I have it installed ok against my personal mac.

**Comment by EricDavisX** [comment] 2021-01-07 19:39
we have the 503 socket hangup issue logged separately as https://github.com/elastic/kibana/issues/86742

and the 'unhealthy' agent issue is logged as https://github.com/elastic/beats/issues/23402 

so - we can close this to avoid duplicate work in favor of the more concise issue.  Thank you for helping to keep it on our radar @dikshachauhan-qasource this has been a rough few weeks, I appreciate you!

**Closed by EricDavisX** 2021-01-07 19:39 UTC
Labels: Team:Ingest Management, blocker, bug, impact:critical
