### ISSUE TITLE
Add documentation for HTTP Basic Auth in Metricbeat Modules

### ISSUE THREAD

**Issue by xeraa** [elastic/beats#4457] opened 2017-06-06 08:21 UTC
For example in the JMX module basic auth is supported with `username` and `password`, but it's not included in the documentation or examples:

```
- module: jolokia
  metricsets: ["jmx"]
  hosts: ["localhost:8080"]
  username: admin
  password: secret
  namespace: "metrics"
  jmx.mappings:
    ...
```

**Comment by exekias** [comment] 2017-10-24 20:34
This is a duplicate of https://github.com/elastic/beats/issues/4268

**Closed by exekias** 2017-10-24 20:34 UTC
Labels: docs, good first issue, Hacktoberfest, Metricbeat
